Repository saleor/saleor, pull requests merged in 2018-07, with the labels that each got.

#2348 Fix wrong payment display in dashboard
  saleor/dashboard/order/views.py
  saleor/order/models.py
Labels: bug, dashboard

#2360 Use the venv module that comes with Python
  Dockerfile
Labels: technical debt

#2359 Attributes mutations
  saleor/graphql/api.py
  saleor/graphql/product/mutations/__init__.py
  saleor/graphql/product/mutations/attributes.py
  saleor/graphql/product/mutations/products.py
  tests/api/test_attributes.py
  tests/conftest.py
Labels: api

#2361 Add Django 2.1 to the test matrix
  .travis.yml
  tox.ini
Labels: technical debt

#2371 Use unprefixed binary path on CircleCI
  .circleci/config.yml
Labels: technical debt

#2372 Add SEO input fields
  saleor/graphql/api.py
  saleor/graphql/core/types.py
  saleor/graphql/core/utils.py
  saleor/graphql/page/mutations.py
  saleor/graphql/product/mutations/products.py
  tests/api/test_core.py
Labels: api

#2327 Order mutations
  saleor/dashboard/order/views.py
  saleor/graphql/account/mutations.py
  saleor/graphql/api.py
  saleor/graphql/core/mutations.py
  saleor/graphql/order/mutations/__init__.py
  saleor/graphql/order/mutations/draft_orders.py
  saleor/graphql/order/mutations/fulfillments.py
  saleor/graphql/order/mutations/orders.py
  saleor/graphql/order/types.py
  saleor/graphql/product/mutations/products.py
  saleor/order/migrations/0048_auto_20180629_1055.py
  saleor/order/models.py
  saleor/shipping/migrations/0009_auto_20180629_1055.py
  tests/api/test_fulfillment.py
  tests/api/test_order.py
  tests/conftest.py
Labels: api

#2373 Add missing input type descriptions
  saleor/graphql/page/mutations.py
  saleor/graphql/product/mutations/products.py
Labels: api, documentation

#2383 Add Chinese (Taiwan) to the language list
  saleor/settings.py
Labels: i18n

#2387 Remove dynamic class names from snapshots
  package-lock.json
  package.json
  saleor/static/dashboard-next/storybook/Stories.test.ts
  saleor/static/dashboard-next/storybook/__snapshots__/Stories.test.ts.snap
Labels: react, technical debt

#2385 GraphQL doc
  docs/architecture.rst
  docs/architecture/graphql.rst
Labels: api, documentation

#2388 Drop redux
  package-lock.json
  package.json
  saleor/static/dashboard-next/index.tsx
Labels: react

#2406 Have docker-compose use correct paths
  docker-compose.yml
Labels: technical debt

#2412 Allow AWS_LOCATION to be set, fix STATIC_URL
  Dockerfile
  saleor/settings.py
Labels: technical debt

#2413 Pass AWS_LOCATION to docker build
  .circleci/config.yml
Labels: technical debt

#2391 Convert snake_case field names to camelCase
  saleor/graphql/core/mutations.py
  saleor/graphql/core/utils.py
  tests/api/test_core.py
Labels: api, bug

#2397 Set variant name in mutation
  saleor/core/utils/random_data.py
  saleor/dashboard/product/forms.py
  saleor/graphql/product/mutations/products.py
  saleor/product/utils/attributes.py
  tests/api/test_product.py
  tests/api/test_variant.py
  tests/dashboard/test_product.py
  tests/test_product_attributes.py
Labels: api, bug

#2438 Change application theme
  saleor/static/dashboard-next/attributes/components/AttributeDetailsPage/AttributeDetailsPage.tsx
  saleor/static/dashboard-next/attributes/components/AttributeListPage/AttributeListPage.tsx
  saleor/static/dashboard-next/attributes/components/AttributeValueList/AttributeValueList.tsx
  saleor/static/dashboard-next/attributes/index.ts
  saleor/static/dashboard-next/categories/components/CategoryDetailsPage/CategoryDetailsPage.tsx
  saleor/static/dashboard-next/categories/components/CategoryList/CategoryList.tsx
  saleor/static/dashboard-next/categories/components/CategoryProducts/CategoryProducts.tsx
  saleor/static/dashboard-next/categories/components/CategoryProperties/CategoryProperties.tsx
  saleor/static/dashboard-next/collections/components/CollectionDetailsPage/CollectionDetailsPage.tsx
  saleor/static/dashboard-next/collections/components/CollectionListPage/CollectionListPage.tsx
  saleor/static/dashboard-next/collections/components/CollectionProducts/CollectionProducts.tsx
  saleor/static/dashboard-next/collections/components/CollectionProperties/CollectionProperties.tsx
  saleor/static/dashboard-next/components/CardTitle/CardTitle.tsx
  saleor/static/dashboard-next/components/CardTitle/index.ts
  saleor/static/dashboard-next/components/ControlledCheckbox.tsx
  saleor/static/dashboard-next/components/ControlledSwitch.tsx
  saleor/static/dashboard-next/components/ExtendedPageHeader/ExtendedPageHeader.tsx
  saleor/static/dashboard-next/components/FormSpacer.tsx
  saleor/static/dashboard-next/components/Money/Money.tsx
  saleor/static/dashboard-next/components/PageHeader/PageHeader.tsx
  saleor/static/dashboard-next/components/PriceField/PriceField.tsx
  saleor/static/dashboard-next/components/RichTextEditor.tsx
  saleor/static/dashboard-next/components/SaveButtonBar/SaveButtonBar.tsx
  saleor/static/dashboard-next/components/SeoForm/SeoForm.tsx
  saleor/static/dashboard-next/components/SingleSelectField/SingleSelectField.tsx
  saleor/static/dashboard-next/components/StatusLabel/StatusLabel.tsx
  saleor/static/dashboard-next/components/TableCellAvatar/TableCellAvatar.tsx
  saleor/static/dashboard-next/components/TableCellAvatar/index.ts
  saleor/static/dashboard-next/customers/components/CustomerAddress/CustomerAddress.tsx
  saleor/static/dashboard-next/customers/components/CustomerDetails/CustomerDetails.tsx
  saleor/static/dashboard-next/customers/components/CustomerListPage/CustomerListPage.tsx
  saleor/static/dashboard-next/orders/components/OrderCustomer/OrderCustomer.tsx
  saleor/static/dashboard-next/orders/components/OrderDetailsPage/OrderDetailsPage.tsx
  saleor/static/dashboard-next/orders/components/OrderFulfillment/OrderFulfillment.tsx
  saleor/static/dashboard-next/orders/components/OrderListPage/OrderListPage.tsx
  saleor/static/dashboard-next/orders/components/OrderProducts/OrderProducts.tsx
  saleor/static/dashboard-next/orders/components/OrderSummary/OrderSummary.tsx
  saleor/static/dashboard-next/pages/components/PageDetailsPage/PageDetailsPage.tsx
  saleor/static/dashboard-next/productTypes/components/ProductTypeDetailsPage/ProductTypeDetailsPage.tsx
  saleor/static/dashboard-next/productTypes/components/ProductTypeListPage/ProductTypeListPage.tsx
  saleor/static/dashboard-next/productTypes/components/ProductTypeProperties/ProductTypeProperties.tsx
  saleor/static/dashboard-next/storybook/__snapshots__/Stories.test.ts.snap
  saleor/static/dashboard-next/storybook/stories/components/Money.tsx
  saleor/static/dashboard-next/storybook/stories/components/SaveButtonBar.tsx
  saleor/static/dashboard-next/storybook/stories/vouchers/VoucherDetailsPage.tsx
  saleor/static/dashboard-next/theme.ts
  saleor/static/dashboard-next/vouchers/components/VoucherDetailsPage/VoucherDetailsPage.tsx
  saleor/static/dashboard-next/vouchers/components/VoucherListPage/VoucherListPage.tsx
  saleor/static/dashboard-next/vouchers/components/VoucherProperties/VoucherProperties.tsx
Labels: react

#2447 Make possible to add addresses to the user in dashboard
  saleor/account/models.py
  saleor/graphql/account/mutations.py
  saleor/graphql/account/types.py
  saleor/graphql/order/mutations/draft_orders.py
  saleor/graphql/order/mutations/orders.py
  tests/api/test_account.py
  tests/api/utils.py
Labels: api

#2484 Sync i18n data
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/djangojs.mo
  locale/en/LC_MESSAGES/djangojs.po
  locale/sk/LC_MESSAGES/djangojs.mo
  locale/sk/LC_MESSAGES/djangojs.po
  saleor/dashboard/locale/en/LC_MESSAGES/django.mo
  saleor/dashboard/locale/en/LC_MESSAGES/django.po
Labels: i18n

#2487 Site settings endpoints
  saleor/graphql/account/types.py
  saleor/graphql/api.py
  saleor/graphql/core/fields.py
  saleor/graphql/core/mutations.py
  saleor/graphql/core/resolvers.py
  saleor/graphql/core/types.py
  saleor/graphql/core/types/__init__.py
  saleor/graphql/core/types/common.py
  saleor/graphql/core/types/money.py
  saleor/graphql/core/types/shop.py
  saleor/graphql/discount/mutations.py
  saleor/graphql/discount/types.py
  saleor/graphql/menu/types.py
  saleor/graphql/order/mutations/draft_orders.py
  saleor/graphql/order/mutations/fulfillments.py
  saleor/graphql/order/mutations/orders.py
  saleor/graphql/order/types.py
  saleor/graphql/page/mutations.py
  saleor/graphql/page/types.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/types.py
  saleor/graphql/shipping/mutations.py
  saleor/graphql/shipping/types.py
  saleor/graphql/utils.py
  tests/api/test_core.py
Labels: api
