Repository saleor/saleor, pull requests merged in 2018-03, with the labels that each got.

#1842 Improve contenerization
  saleor/static/dashboard/js/components/app/category/details/categoryList.js
  saleor/static/dashboard/js/components/app/category/details/details.js
  saleor/static/dashboard/js/components/app/category/form/base.js
  saleor/static/dashboard/js/components/app/category/form/categoryCreateForm.js
  saleor/static/dashboard/js/components/app/category/form/categoryUpdateForm.js
  saleor/static/dashboard/js/components/app/components/cards/descriptionCard.js
  saleor/static/dashboard/js/components/app/components/cards/filterCard.js
  saleor/static/dashboard/js/components/app/components/cards/listCard.js
  saleor/static/dashboard/js/components/app/components/modals.js
  saleor/static/dashboard/js/components/app/components/table.js
  saleor/static/dashboard/js/components/app/i18n.js
  saleor/static/dashboard/js/components/app/index.js
  saleor/static/dashboard/js/components/app/theme.js
Labels: dashboard, frontend, react

#1844 Add blockquote style
  saleor/static/scss/layouts/_product-page.scss
Labels: frontend, storefront

#1866 Use Python 3.6 on CircleCI
  circle.yml
Labels: technical debt

#1870 Disable automatic chunk splitting
  templates/base.html
  templates/dashboard/base.html
  templates/dashboard/styleguide/index.html
  webpack.config.js
Labels: performance

#1874 Use django-filters for sorting in API
  saleor/graphql/product/filters.py
  saleor/graphql/product/types.py
Labels: api

#1852 Fix code import style
  saleor/account/backends/facebook.py
  saleor/account/backends/google.py
  saleor/account/forms.py
  saleor/account/views.py
  saleor/checkout/core.py
  saleor/core/utils/random_data.py
  saleor/dashboard/customer/filters.py
  saleor/dashboard/customer/views.py
  saleor/dashboard/graphql/api.py
  saleor/dashboard/graphql/mutations.py
  saleor/dashboard/staff/views.py
  saleor/dashboard/widgets.py
  saleor/discount/utils.py
  saleor/graphql/api.py
  saleor/order/views.py
  saleor/search/backends/postgresql_dashboard.py
  tests/test_discounts.py
Labels: technical debt

#1880 Improve pages UI
  docs/architecture.rst
  templates/dashboard/base.html
  templates/dashboard/page/detail.html
  templates/dashboard/page/form.html
  templates/dashboard/page/modal_delete.html
  templates/page/details.html
Labels: frontend

#1881 Rich-text editor improvements
  saleor/dashboard/product/forms.py
  saleor/settings.py
  saleor/static/dashboard/images/editor/align_center.svg
  saleor/static/dashboard/images/editor/align_justify.svg
  saleor/static/dashboard/images/editor/align_left.svg
  saleor/static/dashboard/images/editor/align_right.svg
  saleor/static/dashboard/images/editor/format_clear.svg
  saleor/static/dashboard/images/editor/insert_link.svg
  saleor/static/dashboard/images/editor/insert_photo.svg
  saleor/static/dashboard/images/editor/quote.svg
  saleor/static/dashboard/js/components/editor.js
  saleor/static/dashboard/scss/components/_rich-text-editor.scss
Labels: dashboard, frontend

#1871 Add Collections Sitemap
  docs/integrations/seo.rst
  saleor/core/sitemaps.py
Labels: seo

#1893 Make order.total not nullable
  saleor/order/migrations/0039_auto_20180312_1203.py
  saleor/order/models.py
Labels: technical debt

#1906 Remove nedless dependency on importing prices.Money in order migration
  saleor/order/migrations/0039_auto_20180312_1203.py
  saleor/order/models.py
Labels: technical debt

#1911 Update translation files
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/djangojs.mo
  locale/en/LC_MESSAGES/djangojs.po
  saleor/dashboard/locale/en/LC_MESSAGES/django.mo
  saleor/dashboard/locale/en/LC_MESSAGES/django.po
Labels: i18n

#1892 Fix ReleasePaymentForm, add tests for ManagePaymentForms
  saleor/dashboard/order/forms.py
  templates/dashboard/order/modal/release.html
  tests/conftest.py
  tests/dashboard/test_order.py
Labels: dashboard

#1924 Add product filter widget
  saleor/static/dashboard-next/js/__tests__/components/__snapshots__/CategoryDetails.test.tsx.snap
  saleor/static/dashboard-next/js/__tests__/components/__snapshots__/FilterCard.test.tsx.snap
  saleor/static/dashboard-next/js/category/components/ProductFilters.tsx
  saleor/static/dashboard-next/js/category/views/details.tsx
  saleor/static/dashboard-next/js/components/Page.tsx
  saleor/static/dashboard-next/js/components/cards/FilterCard.tsx
Labels: react

#1905 [WiP]Add graphql API for page app
  saleor/dashboard/graphql/api.py
  saleor/dashboard/graphql/mutations.py
  saleor/dashboard/graphql/page/__init__.py
  saleor/dashboard/graphql/page/mutations.py
  saleor/dashboard/graphql/page/types.py
  saleor/dashboard/graphql/product/mutations.py
  saleor/graphql/api.py
  saleor/graphql/page/__init__.py
  saleor/graphql/page/types.py
  tests/conftest.py
  tests/dashboard/test_graphql.py
  tests/test_graphql.py
Labels: api

#1948 Remove absolute positioning
  saleor/static/dashboard/scss/components/_global.scss
Labels: frontend

#1899 SEO friendly description for products.
  saleor/core/utils/random_data.py
  saleor/core/utils/text.py
  saleor/dashboard/product/forms.py
  saleor/product/migrations/0053_product_seo_description.py
  saleor/product/migrations/0054_merge_20180320_1108.py
  saleor/product/models.py
  templates/dashboard/product/form.html
  templates/product/details.html
  tests/dashboard/test_product.py
  tests/test_core.py
Labels: seo

#1951 Add pages
  .gitignore
  package.json
  saleor/dashboard/graphql/api.py
  saleor/static/dashboard-next/js/AppRoot.tsx
  saleor/static/dashboard-next/js/category/components/CategoryList.tsx
  saleor/static/dashboard-next/js/category/mutations.ts
  saleor/static/dashboard-next/js/category/queries.ts
  saleor/static/dashboard-next/js/components/ControlledCheckbox.tsx
  saleor/static/dashboard-next/js/components/RichTextEditor.tsx
  saleor/static/dashboard-next/js/gql-types.ts
  saleor/static/dashboard-next/js/index.tsx
  saleor/static/dashboard-next/js/page/components/PageBaseForm.tsx
  saleor/static/dashboard-next/js/page/components/PageDeleteDialog.tsx
  saleor/static/dashboard-next/js/page/components/PageFilters.tsx
  saleor/static/dashboard-next/js/page/components/PageListComponent.tsx
  saleor/static/dashboard-next/js/page/index.tsx
  saleor/static/dashboard-next/js/page/mutations.ts
  saleor/static/dashboard-next/js/page/queries.ts
  saleor/static/dashboard-next/js/page/views/PageCreateForm.tsx
  saleor/static/dashboard-next/js/page/views/PageList.tsx
  saleor/static/dashboard-next/js/page/views/PageUpdateForm.tsx
  saleor/static/dashboard-next/js/schema.json
Labels: react

#1975 Fix typo in template
  templates/dashboard/page/list.html
Labels: dashboard, frontend

#1978 Move form logic to a typed Form component
  saleor/static/dashboard-next/category/components/BaseForm.tsx
  saleor/static/dashboard-next/category/components/CategoryDeleteDialog.tsx
  saleor/static/dashboard-next/category/views/CategoryCreateForm.tsx
  saleor/static/dashboard-next/category/views/CategoryUpdateForm.tsx
  saleor/static/dashboard-next/components/Form/Form.tsx
  saleor/static/dashboard-next/components/Form/FormActions.tsx
  saleor/static/dashboard-next/components/Form/index.ts
  saleor/static/dashboard-next/components/PageHeader.tsx
  saleor/static/dashboard-next/page/views/PageCreateForm.tsx
  saleor/static/dashboard-next/page/views/PageUpdateForm.tsx
Labels: api, dashboard, react

#1980 Rewrite page forms
  saleor/static/dashboard-next/page/components/PageBaseForm.tsx
  saleor/static/dashboard-next/page/index.tsx
  saleor/static/dashboard-next/page/views/PageCreateForm.tsx
  saleor/static/dashboard-next/page/views/PageUpdateForm.tsx
Labels: react

#1976 Improve form error handling
  saleor/static/dashboard-next/components/RichTextEditor.tsx
  saleor/static/dashboard-next/page/components/PageBaseForm.tsx
Labels: react

#1973 Allow to create attribute values from product form
  saleor/dashboard/product/forms.py
  saleor/dashboard/product/views.py
  saleor/data_feeds/google_merchant.py
  saleor/product/models.py
  saleor/static/dashboard/js/components/selects.js
  templates/dashboard/product/form.html
  templates/dashboard/product/product_variant/form.html
  tests/dashboard/test_product.py
  tests/test_product.py
Labels: dashboard

#1988 Fix menu tests and generating random menus
  saleor/core/utils/random_data.py
  tests/conftest.py
  tests/dashboard/test_menu.py
Labels: bug

#1945 Implement product API for dashboard
  saleor/dashboard/graphql/api.py
  saleor/dashboard/graphql/mutations.py
  saleor/dashboard/graphql/product/filters.py
  saleor/dashboard/graphql/product/forms.py
  saleor/dashboard/graphql/product/mutations.py
  saleor/dashboard/graphql/utils.py
  saleor/dashboard/product/forms.py
  saleor/graphql/api.py
  saleor/graphql/product/types.py
  saleor/product/migrations/0056_auto_20180330_0321.py
  saleor/product/models.py
  tests/conftest.py
  tests/dashboard/test_graphql.py
  tests/test_graphql.py
Labels: api, dashboard, in progress

#2002 GraphQL fields description
  saleor/dashboard/graphql/api.py
  saleor/dashboard/graphql/core/__init__.py
  saleor/dashboard/graphql/core/mutations.py
  saleor/dashboard/graphql/page/mutations.py
  saleor/dashboard/graphql/product/mutations.py
  saleor/dashboard/graphql/product/types.py
  saleor/graphql/api.py
  saleor/graphql/core/types.py
  saleor/graphql/page/types.py
  saleor/graphql/product/types.py
  tests/dashboard/test_graphql.py
  tests/test_graphql.py
Labels: api

#2008 Sync translations with Transifex
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/djangojs.mo
  locale/en/LC_MESSAGES/djangojs.po
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  locale/pl/LC_MESSAGES/django.mo
  locale/pl/LC_MESSAGES/django.po
  locale/pl/LC_MESSAGES/djangojs.mo
  locale/pl/LC_MESSAGES/djangojs.po
  saleor/dashboard/locale/en/LC_MESSAGES/django.mo
  saleor/dashboard/locale/en/LC_MESSAGES/django.po
  saleor/dashboard/locale/pl/LC_MESSAGES/django.mo
  saleor/dashboard/locale/pl/LC_MESSAGES/django.po
Labels: i18n
