Repository saleor/saleor, pull requests merged in 2018-12, with the labels that each got.

#3393 Upgrade React, Apollo, Webpack and Babel
  apollo.config.js
  package-lock.json
  package.json
  saleor/static/dashboard-next/collections/containers/ProductSearch.tsx
  saleor/static/dashboard-next/components/MenuToggle.tsx
  saleor/static/dashboard-next/components/Navigator.tsx
  saleor/static/dashboard-next/components/Paginator.tsx
  saleor/static/dashboard-next/components/Toggle.tsx
  saleor/static/dashboard-next/mutations.tsx
  saleor/static/dashboard-next/orders/containers/OrderVariantSearch.tsx
  saleor/static/dashboard-next/orders/containers/UserSearch.tsx
  saleor/static/dashboard-next/products/containers/ProductImagesReorder.tsx
  saleor/static/dashboard-next/queries.tsx
  saleor/static/dashboard-next/storybook/config.js
  tslint.json
  webpack.config.js
Labels: react, technical debt

#3380 Fix calls to ngettext_lazy
  saleor/dashboard/order/forms.py
  saleor/dashboard/order/views.py
  saleor/dashboard/product/views.py
  saleor/graphql/order/mutations/fulfillments.py
  saleor/order/__init__.py
Labels: bug

#3101 Add first and last name in user
  CHANGELOG.md
  saleor/account/forms.py
  saleor/account/migrations/0024_auto_20181011_0737.py
  saleor/account/models.py
  saleor/account/utils.py
  saleor/account/views.py
  saleor/core/utils/random_data.py
  saleor/dashboard/customer/filters.py
  saleor/dashboard/customer/forms.py
  saleor/dashboard/order/filters.py
  saleor/dashboard/staff/filters.py
  saleor/dashboard/staff/forms.py
  saleor/graphql/account/mutations.py
  saleor/graphql/account/resolvers.py
  saleor/graphql/schema.graphql
  saleor/search/backends/elasticsearch_dashboard.py
  saleor/search/backends/postgresql_dashboard.py
  saleor/search/backends/test_elasticsearch_dashboard.py
  saleor/search/documents.py
  saleor/static/dashboard-next/types/globalTypes.ts
  templates/account/details.html
  templates/dashboard/customer/detail.html
  templates/dashboard/customer/list.html
  templates/dashboard/order/detail.html
  templates/dashboard/staff/list.html
  tests/api/test_account.py
  tests/cassettes/test_dashboard_search_orders_by_user.yaml
  tests/cassettes/test_dashboard_search_orders_by_user_email.yaml
  tests/cassettes/test_dashboard_search_orders_by_user_name.yaml
  tests/cassettes/test_dashboard_search_orders_by_user_name_without_address.yaml
  tests/cassettes/test_dashboard_search_user_by_email.yaml
  tests/cassettes/test_dashboard_search_user_name.yaml
  tests/cassettes/test_dashboard_search_user_name_without_address.yaml
  tests/conftest.py
  tests/dashboard/test_customer.py
  tests/dashboard/test_staff.py
  tests/test_account.py
  tests/test_elasticsearch.py
  tests/test_postgresql_search.py
Labels: blocker

#3445 Update roadmap content
  src/components/Roadmap/Roadmap.jsx
Labels: frontend

#3497 Resolve to None when empty ID was passed
  CHANGELOG.md
  saleor/graphql/core/mutations.py
  saleor/static/dashboard-next/types/globalTypes.ts
  tests/api/test_base_mutation.py
Labels: api
