Repository saleor/saleor, pull requests merged in 2018-10, with the labels that each got.

#3104 Update react-dom
  package-lock.json
  package.json
Labels: frontend, react, technical debt

#3150 Separate parent variable from category input
  saleor/graphql/product/mutations/products.py
  saleor/graphql/schema.graphql
  saleor/static/dashboard-next/categories/mutations.ts
  saleor/static/dashboard-next/categories/types/CategoryCreate.ts
  saleor/static/dashboard-next/categories/types/CategoryUpdate.ts
  saleor/static/dashboard-next/categories/views/CategoryCreate.tsx
  saleor/static/dashboard-next/types/globalTypes.ts
  tests/api/test_category.py
  tests/api/test_core.py
Labels: api

#2983 Optimize queries in API
  Pipfile
  requirements.txt
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/types.py
  saleor/graphql/api.py
  saleor/graphql/core/fields.py
  saleor/graphql/discount/resolvers.py
  saleor/graphql/discount/types.py
  saleor/graphql/menu/resolvers.py
  saleor/graphql/menu/types.py
  saleor/graphql/order/resolvers.py
  saleor/graphql/order/types.py
  saleor/graphql/page/resolvers.py
  saleor/graphql/page/types.py
  saleor/graphql/product/fields.py
  saleor/graphql/product/filters.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/resolvers.py
  saleor/graphql/shipping/types.py
  saleor/graphql/shop/types.py
  saleor/graphql/utils.py
  saleor/order/models.py
  saleor/product/models.py
  saleor/static/dashboard-next/categories/types/CategoryCreate.ts
  saleor/static/dashboard-next/categories/types/CategoryUpdate.ts
  saleor/static/dashboard-next/collections/mutations.ts
  saleor/static/dashboard-next/collections/types/CreateCollection.ts
  saleor/static/dashboard-next/orders/types/OrderCancel.ts
  saleor/static/dashboard-next/orders/types/OrderCapture.ts
  saleor/static/dashboard-next/orders/types/OrderCreateFulfillment.ts
  saleor/static/dashboard-next/orders/types/OrderDetails.ts
  saleor/static/dashboard-next/orders/types/OrderDetailsFragment.ts
  saleor/static/dashboard-next/orders/types/OrderDraftCancel.ts
  saleor/static/dashboard-next/orders/types/OrderDraftFinalize.ts
  saleor/static/dashboard-next/orders/types/OrderDraftUpdate.ts
  saleor/static/dashboard-next/orders/types/OrderFulfillmentCancel.ts
  saleor/static/dashboard-next/orders/types/OrderFulfillmentUpdateTracking.ts
  saleor/static/dashboard-next/orders/types/OrderLineAdd.ts
  saleor/static/dashboard-next/orders/types/OrderLineDelete.ts
  saleor/static/dashboard-next/orders/types/OrderLineUpdate.ts
  saleor/static/dashboard-next/orders/types/OrderMarkAsPaid.ts
  saleor/static/dashboard-next/orders/types/OrderRefund.ts
  saleor/static/dashboard-next/orders/types/OrderRelease.ts
  saleor/static/dashboard-next/types/globalTypes.ts
  tests/api/test_attributes.py
  tests/api/test_graphql.py
  tests/api/test_product.py
  tests/conftest.py
Labels: in progress

#3176 Add customers section
  saleor/graphql/account/resolvers.py
  saleor/graphql/product/resolvers.py
  saleor/static/dashboard-next/AppRoot.tsx
  saleor/static/dashboard-next/components/AddressEdit/AddressEdit.tsx
  saleor/static/dashboard-next/components/AddressFormatter/AddressFormatter.tsx
  saleor/static/dashboard-next/components/CardTitle/CardTitle.tsx
  saleor/static/dashboard-next/customers/components/CustomerAddress/CustomerAddress.tsx
  saleor/static/dashboard-next/customers/components/CustomerAddress/index.ts
  saleor/static/dashboard-next/customers/components/CustomerAddresses/CustomerAddresses.tsx
  saleor/static/dashboard-next/customers/components/CustomerAddresses/index.ts
  saleor/static/dashboard-next/customers/components/CustomerCreateAddress/CustomerCreateAddress.tsx
  saleor/static/dashboard-next/customers/components/CustomerCreateAddress/index.ts
  saleor/static/dashboard-next/customers/components/CustomerCreateDetails/CustomerCreateDetails.tsx
  saleor/static/dashboard-next/customers/components/CustomerCreateDetails/index.ts
  saleor/static/dashboard-next/customers/components/CustomerCreateNote/CustomerCreateNote.tsx
  saleor/static/dashboard-next/customers/components/CustomerCreateNote/index.ts
  saleor/static/dashboard-next/customers/components/CustomerCreatePage/CustomerCreatePage.tsx
  saleor/static/dashboard-next/customers/components/CustomerCreatePage/index.ts
  saleor/static/dashboard-next/customers/components/CustomerDetails/CustomerDetails.tsx
  saleor/static/dashboard-next/customers/components/CustomerDetailsPage/CustomerDetailsPage.tsx
  saleor/static/dashboard-next/customers/components/CustomerEditPage/CustomerEditPage.tsx
  saleor/static/dashboard-next/customers/components/CustomerEditPage/index.ts
  saleor/static/dashboard-next/customers/components/CustomerList/CustomerList.tsx
  saleor/static/dashboard-next/customers/components/CustomerList/index.ts
  saleor/static/dashboard-next/customers/components/CustomerListPage/CustomerListPage.tsx
  saleor/static/dashboard-next/customers/components/CustomerOrders/CustomerOrders.tsx
  saleor/static/dashboard-next/customers/components/CustomerStats/CustomerStats.tsx
  saleor/static/dashboard-next/customers/components/CustomerStats/index.ts
  saleor/static/dashboard-next/customers/fixtures.ts
  saleor/static/dashboard-next/customers/index.tsx
  saleor/static/dashboard-next/customers/mutations.ts
  saleor/static/dashboard-next/customers/queries.ts
  saleor/static/dashboard-next/customers/types.ts
  saleor/static/dashboard-next/customers/types/CreateCustomer.ts
  saleor/static/dashboard-next/customers/types/CustomerCreateData.ts
  saleor/static/dashboard-next/customers/types/CustomerDetails.ts
  saleor/static/dashboard-next/customers/types/CustomerDetailsFragment.ts
  saleor/static/dashboard-next/customers/types/CustomerFragment.ts
  saleor/static/dashboard-next/customers/types/ListCustomers.ts
  saleor/static/dashboard-next/customers/types/RemoveCustomer.ts
  saleor/static/dashboard-next/customers/types/UpdateCustomer.ts
  saleor/static/dashboard-next/customers/urls.ts
  saleor/static/dashboard-next/customers/views/CustomerCreate.tsx
  saleor/static/dashboard-next/customers/views/CustomerDetails.tsx
  saleor/static/dashboard-next/customers/views/CustomerList.tsx
  saleor/static/dashboard-next/index.tsx
  saleor/static/dashboard-next/orders/components/OrderAddressEditDialog/OrderAddressEditDialog.tsx
  saleor/static/dashboard-next/orders/components/OrderDetailsPage/OrderDetailsPage.tsx
  saleor/static/dashboard-next/orders/components/OrderDraftPage/OrderDraftPage.tsx
  saleor/static/dashboard-next/storybook/__snapshots__/Stories.test.ts.snap
  saleor/static/dashboard-next/storybook/config.js
  saleor/static/dashboard-next/storybook/stories/collections/CollectionDetailsPage.tsx
  saleor/static/dashboard-next/storybook/stories/customers/CustomerAddress.tsx
  saleor/static/dashboard-next/storybook/stories/customers/CustomerCreatePage.tsx
  saleor/static/dashboard-next/storybook/stories/customers/CustomerDetails.tsx
  saleor/static/dashboard-next/storybook/stories/customers/CustomerDetailsPage.tsx
  saleor/static/dashboard-next/storybook/stories/customers/CustomerEditPage.tsx
  saleor/static/dashboard-next/storybook/stories/customers/CustomerListPage.tsx
  saleor/static/dashboard-next/storybook/stories/customers/CustomerOrders.tsx
  saleor/static/dashboard-next/types/globalTypes.ts
Labels: in progress

#3198 Use Elasticsearch 6.x
  Dockerfile
  Pipfile
  Pipfile.lock
  docker-compose.yml
  requirements.txt
  saleor/search/backends/test_elasticsearch_storefront.py
  tests/cassettes/test_dashboard_search_orders_by_user.yaml
  tests/cassettes/test_dashboard_search_user_by_email.yaml
  tests/cassettes/test_dashboard_search_user_name.yaml
  tests/cassettes/test_dashboard_search_with_empty_results.yaml
  tests/cassettes/test_dashboard_search_with_product_result.yaml
  tests/cassettes/test_new_search_doesnt_show_unpublished.yaml
  tests/cassettes/test_new_search_with_empty_results.yaml
  tests/cassettes/test_new_search_with_result.yaml
  tests/settings.py
Labels: technical debt

#3206 Fix the Pipenv lock file
  Pipfile.lock
Labels: technical debt

#3210 Make order line sorting stable
  saleor/graphql/order/types.py
  saleor/order/models.py
  tests/api/test_order.py
Labels: technical debt

#3213 Prevent tests from modifying real settings
  tests/api/test_shop.py
  tests/dashboard/test_order.py
  tests/dashboard/test_product.py
  tests/test_core.py
  tests/test_emails.py
  tests/test_order.py
  tests/test_product.py
  tests/test_sitemap.py
Labels: technical debt
