Repository saleor/saleor, pull requests merged in 2018-11, with the labels that each got.

#3265 Add paginator component
  saleor/static/dashboard-next/categories/index.tsx
  saleor/static/dashboard-next/categories/views/CategoryDetails/index.tsx
  saleor/static/dashboard-next/collections/index.tsx
  saleor/static/dashboard-next/collections/views/CollectionDetails.tsx
  saleor/static/dashboard-next/collections/views/CollectionList.tsx
  saleor/static/dashboard-next/components/Paginator.tsx
  saleor/static/dashboard-next/customers/index.tsx
  saleor/static/dashboard-next/customers/views/CustomerList.tsx
  saleor/static/dashboard-next/misc.ts
  saleor/static/dashboard-next/orders/index.tsx
  saleor/static/dashboard-next/orders/views/OrderList.tsx
  saleor/static/dashboard-next/pages/index.tsx
  saleor/static/dashboard-next/pages/views/PageList.tsx
  saleor/static/dashboard-next/productTypes/index.tsx
  saleor/static/dashboard-next/productTypes/views/ProductTypeList.tsx
  saleor/static/dashboard-next/products/index.tsx
  saleor/static/dashboard-next/products/views/ProductList.tsx
  saleor/static/dashboard-next/staff/index.tsx
  saleor/static/dashboard-next/staff/views/StaffList.tsx
Labels: blocker

#3279 Add window titles
  package-lock.json
  package.json
  saleor/static/dashboard-next/categories/index.tsx
  saleor/static/dashboard-next/categories/views/CategoryCreate.tsx
  saleor/static/dashboard-next/categories/views/CategoryDetails/index.tsx
  saleor/static/dashboard-next/collections/index.tsx
  saleor/static/dashboard-next/collections/views/CollectionCreate.tsx
  saleor/static/dashboard-next/collections/views/CollectionDetails.tsx
  saleor/static/dashboard-next/components/Shop/index.tsx
  saleor/static/dashboard-next/components/Shop/query.ts
  saleor/static/dashboard-next/components/Shop/types/ShopInfo.ts
  saleor/static/dashboard-next/components/WindowTitle/index.tsx
  saleor/static/dashboard-next/configuration/index.tsx
  saleor/static/dashboard-next/customers/index.tsx
  saleor/static/dashboard-next/customers/views/CustomerCreate.tsx
  saleor/static/dashboard-next/customers/views/CustomerDetails.tsx
  saleor/static/dashboard-next/index.tsx
  saleor/static/dashboard-next/orders/index.tsx
  saleor/static/dashboard-next/orders/types/OrderDetails.ts
  saleor/static/dashboard-next/orders/views/OrderDetails.tsx
  saleor/static/dashboard-next/pages/index.tsx
  saleor/static/dashboard-next/pages/views/PageCreate.tsx
  saleor/static/dashboard-next/pages/views/PageDetails.tsx
  saleor/static/dashboard-next/productTypes/index.tsx
  saleor/static/dashboard-next/productTypes/views/ProductTypeCreate.tsx
  saleor/static/dashboard-next/productTypes/views/ProductTypeUpdate/index.tsx
  saleor/static/dashboard-next/products/index.tsx
  saleor/static/dashboard-next/products/views/ProductCreate.tsx
  saleor/static/dashboard-next/products/views/ProductUpdate.tsx
  saleor/static/dashboard-next/products/views/ProductVariant.tsx
  saleor/static/dashboard-next/products/views/ProductVariantCreate.tsx
  saleor/static/dashboard-next/siteSettings/views/index.tsx
  saleor/static/dashboard-next/staff/index.tsx
  saleor/static/dashboard-next/staff/views/StaffDetails.tsx
Labels: blocker

#3290 Make Webpack rebuilds fast
  saleor/static/dashboard-next/storybook/webpack.config.js
  webpack.config.js
Labels: technical debt

#3309 Ensure that all queries are built on top of TypedQuery
  saleor/static/dashboard-next/pages/queries.ts
  saleor/static/dashboard-next/pages/views/PageDetails.tsx
  saleor/static/dashboard-next/pages/views/PageList.tsx
  saleor/static/dashboard-next/products/queries.ts
  saleor/static/dashboard-next/products/views/ProductCreate.tsx
  saleor/static/dashboard-next/products/views/ProductImage/index.tsx
  saleor/static/dashboard-next/products/views/ProductList.tsx
  saleor/static/dashboard-next/products/views/ProductUpdate/index.tsx
  saleor/static/dashboard-next/products/views/ProductVariant/index.tsx
  saleor/static/dashboard-next/products/views/ProductVariantCreate.tsx
Labels: blocker

#3263 Replace Graphene view with a custom one
  saleor/graphql/core/mutations.py
  saleor/graphql/core/types/__init__.py
  saleor/graphql/core/types/upload.py
  saleor/graphql/file_upload/views.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/views.py
  saleor/settings.py
  saleor/urls.py
  templates/graphql/playground.html
  tests/api/conftest.py
  tests/api/test_account.py
  tests/api/test_view.py
Labels: help wanted, in progress

#3322 Sync translations with Transifex
  .tx/config
  locale/ar/LC_MESSAGES/django.po
  locale/ar/LC_MESSAGES/djangojs.po
  locale/bn/LC_MESSAGES/django.po
  locale/da/LC_MESSAGES/django.po
  locale/da/LC_MESSAGES/djangojs.po
  locale/mn/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/djangojs.po
  saleor/dashboard/locale/ar/LC_MESSAGES/django.po
  saleor/dashboard/locale/bn/LC_MESSAGES/django.po
  saleor/dashboard/locale/da/LC_MESSAGES/django.po
  saleor/dashboard/locale/mn/LC_MESSAGES/django.po
  saleor/dashboard/locale/sv/LC_MESSAGES/django.po
  saleor/settings.py
Labels: i18n

#3339 Remove test warnings
  saleor/menu/models.py
  saleor/settings.py
  tests/test_product_tags.py
Labels: technical debt
