Repository saleor/saleor, pull requests merged in 2020-03, with the labels that each got.

#5328 Upgrade to Django 3.0
  .travis.yml
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/checkout/context_processors.py
  saleor/demo/views.py
  saleor/graphql/core/fields.py
  saleor/graphql/core/types/filter_input.py
  saleor/graphql/middleware.py
  saleor/graphql/views.py
  saleor/settings.py
  tests/api/test_account.py
  tests/api/test_middleware.py
  tests/test_cart.py
  tox.ini
Labels: technical debt

#5392 Fix migration 0112 for products
  saleor/product/migrations/0112_auto_20200129_0050.py
Labels: bug

#5414 Add filter by ids to warehouses query
  CHANGELOG.md
  saleor/graphql/schema.graphql
  saleor/graphql/warehouse/filters.py
  tests/api/pagination/test_warehouse.py
  tests/api/test_warehouse.py
Labels: graphql

#5357 Force django to load the wsgi on startup
  CHANGELOG.md
  saleor/wsgi/__init__.py
Labels: devops
