Repository saleor/saleor, pull requests merged in 2020-12, with the labels that each got.

#6593 Feature: push the hash alongside of branch in master
  .github/workflows/publish-containers.rst
  .github/workflows/publish-containers.yml
  Dockerfile
Labels: devops

#6600 Fix remove channel without orders
  saleor/channel/error_codes.py
  saleor/graphql/channel/dataloaders.py
  saleor/graphql/channel/mutations.py
  saleor/graphql/channel/tests/test_channel_delete_mutations.py
  saleor/graphql/channel/tests/test_channel_queries.py
  saleor/graphql/channel/types.py
  saleor/graphql/schema.graphql
Labels: mulitchannel

#6602 CheckoutComplete performance
  saleor/checkout/checkout_cleaner.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/graphql/checkout/tests/benchmark/conftest.py
  saleor/graphql/checkout/tests/test_checkout_complete.py
  saleor/graphql/order/tests/test_order.py
  saleor/payment/gateway.py
  saleor/payment/tests/test_payment.py
  saleor/tests/fixtures.py
Labels: in progress, performance

#6568 Introduce file attributes
  CHANGELOG.md
  saleor/attribute/__init__.py
  saleor/attribute/migrations/0003_auto_20201113_1149.py
  saleor/attribute/models.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/products_data/utils.py
  saleor/csv/utils/__init__.py
  saleor/csv/utils/products_data.py
  saleor/graphql/attribute/descriptions.py
  saleor/graphql/attribute/mutations.py
  saleor/graphql/attribute/tests/mutations/test_attribute_create.py
  saleor/graphql/attribute/tests/mutations/test_attribute_update.py
  saleor/graphql/attribute/tests/queries/test_attribute_query.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/types.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/core/mutations.py
  saleor/graphql/core/tests/test_file_upload.py
  saleor/graphql/core/types/__init__.py
  saleor/graphql/core/types/common.py
  saleor/graphql/page/mutations/pages.py
  saleor/graphql/page/tests/test_page.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/enums.py
  saleor/graphql/product/mutations/attributes.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_utils.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/product/tests/test_variant_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/product/utils.py
  saleor/graphql/schema.graphql
  saleor/product/tasks.py
  saleor/product/tests/test_generate_and_set_variant_name.py
  saleor/product/tests/test_generate_name_for_variant.py
  saleor/product/tests/test_get_variant_selection_attributes.py
  saleor/product/utils/variants.py
  saleor/tests/fixtures.py
Labels: feature branch, test deployment

#6599 Return Products
  saleor/graphql/order/mutations/fulfillments.py
  saleor/graphql/order/schema.py
  saleor/graphql/order/tests/test_fulfillment.py
  saleor/graphql/order/tests/test_fulfillment_refund_products.py
  saleor/graphql/order/tests/test_fulfillment_return_products.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
  saleor/order/__init__.py
  saleor/order/actions.py
  saleor/order/error_codes.py
  saleor/order/events.py
  saleor/order/migrations/0094_auto_20201216_1505.py
  saleor/order/tests/test_order_actions.py
  saleor/order/tests/test_order_actions_create_fulfillments_for_returned_products.py
  saleor/order/tests/test_order_actions_refund_products.py
  saleor/tests/fixtures.py
Labels: test deployment

#6552 Performance: Checkout
  saleor/account/utils.py
  saleor/checkout/__init__.py
  saleor/checkout/base_calculations.py
  saleor/checkout/calculations.py
  saleor/checkout/checkout_cleaner.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_cart.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/utils.py
  saleor/core/utils/random_data.py
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils.py
  saleor/graphql/account/dataloaders.py
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/benchmark/conftest.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/tests/test_checkout_complete.py
  saleor/graphql/checkout/tests/test_checkout_digital.py
  saleor/graphql/checkout/tests/test_checkout_promo_codes.py
  saleor/graphql/checkout/types.py
  saleor/graphql/order/tests/test_fulfillment.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/test_payment.py
  saleor/graphql/product/dataloaders/__init__.py
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_variant.py
  saleor/order/models.py
  saleor/order/tests/test_order.py
  saleor/order/tests/test_order_actions.py
  saleor/order/utils.py
  saleor/payment/gateway.py
  saleor/payment/gateways/adyen/tests/conftest.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/utils/common.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/tests/test_payment.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/tests/test_manager.py
  saleor/plugins/vatlayer/plugin.py
  saleor/plugins/vatlayer/tests/test_vatlayer.py
  saleor/product/models.py
  saleor/product/tests/test_product.py
  saleor/shipping/models.py
  saleor/tests/fixtures.py
  saleor/warehouse/availability.py
  saleor/warehouse/tests/test_stock_availability.py
  saleor/webhook/serializers.py
Labels: 3.0, feature branch

#6436 Drop deprecated quantity fields
  CHANGELOG.md
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/benchmark/test_homepage.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/graphql/product/tests/deprecated/test_variant_availability.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_variant_pricing.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/warehouse/availability.py
  saleor/warehouse/tests/test_stock_availability.py
Labels: blocked

#6633 Add filter through channels in orders query
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/schema.graphql
Labels: mulitchannel
