Repository saleor/saleor, pull requests merged in 2020-10, with the labels that each got.

#6157 Filtering and sorting in multichannel
  saleor/checkout/utils.py
  saleor/core/tests/test_core.py
  saleor/csv/tests/export/test_export.py
  saleor/discount/models.py
  saleor/discount/tests/test_discounts.py
  saleor/graphql/account/sorters.py
  saleor/graphql/channel/filters.py
  saleor/graphql/channel/sorters.py
  saleor/graphql/core/types/__init__.py
  saleor/graphql/core/types/sort_input.py
  saleor/graphql/discount/filters.py
  saleor/graphql/discount/sorters.py
  saleor/graphql/discount/tests/test_discount.py
  saleor/graphql/discount/tests/test_pagination.py
  saleor/graphql/discount/tests/test_sale_sorting_with_channels.py
  saleor/graphql/discount/tests/test_voucher_sorting_with_channels.py
  saleor/graphql/menu/sorters.py
  saleor/graphql/order/sorters.py
  saleor/graphql/product/filters.py
  saleor/graphql/product/sorters.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_product_filtering_and_sorting_with_channels.py
  saleor/graphql/product/tests/test_product_pagination.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/utils.py
  saleor/graphql/utils/sorting.py
Labels: mulitchanel

#6174 Extend ProductVariantChannelListing with cost_price field
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/products_data/test_prepare_headers.py
  saleor/csv/tests/export/products_data/utils.py
  saleor/csv/utils/__init__.py
  saleor/csv/utils/product_headers.py
  saleor/csv/utils/products_data.py
  saleor/graphql/core/tests/test_core.py
  saleor/graphql/csv/enums.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_product_channel_listing_update.py
  saleor/graphql/product/tests/test_product_discounted_price.py
  saleor/graphql/product/tests/test_product_sorting_attributes.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/product/tests/test_variant_channel_listing_update.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/product/migrations/0130_migrate_cost_price_to_channel_listing.py
  saleor/product/models.py
  saleor/product/tests/test_product.py
  saleor/product/tests/test_product_attributes.py
  saleor/product/utils/costs.py
  saleor/tests/fixtures.py
  saleor/webhook/serializers.py
Labels: mulitchanel

#6221 Fix shipping method resolver in order type
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/types.py
Labels: mulitchanel

#6224 Add filtering by Product IDs to `products` query
  CHANGELOG.md
  saleor/graphql/product/filters.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/schema.graphql
Labels: graphql

#6212 Move available for purchase and visible in listings to product channel listing
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_prepare_headers.py
  saleor/csv/tests/export/products_data/utils.py
  saleor/csv/utils/__init__.py
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/core/tests/test_graphql.py
  saleor/graphql/core/types/__init__.py
  saleor/graphql/core/types/filter_input.py
  saleor/graphql/csv/enums.py
  saleor/graphql/meta/tests/test_meta_queries.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/utils.py
  saleor/graphql/product/filters.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/benchmark/test_category.py
  saleor/graphql/product/tests/benchmark/test_collection.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/test_attribute_filtering_with_channels.py
  saleor/graphql/product/tests/test_attribute_pagination.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_product_channel_listing_update.py
  saleor/graphql/product/tests/test_product_set_availability_for_purchase.py
  saleor/graphql/product/tests/test_product_sorting_attributes.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/mutations/channels.py
  saleor/product/migrations/0133_auto_20201006_0635.py
  saleor/product/models.py
  saleor/tests/fixtures.py
Labels: in progress, mulitchanel

#6238 Fill up publication_date + sort by publication_date
  saleor/graphql/page/mutations.py
  saleor/graphql/page/tests/test_page.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/sorters.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_product_sorting.py
  saleor/graphql/schema.graphql
  saleor/page/migrations/0013_update_publication_date.py
  saleor/product/migrations/0128_update_publication_date.py
  saleor/static/populatedb_data.json
Labels: 3.0

#6243 Drop bulk publish on product and collections
  saleor/graphql/order/sorters.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/tests/test_pagination.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/schema.graphql
Labels: mulitchanel

#6239 Add attribute type field to attribute
  saleor/graphql/product/descriptions.py
  saleor/graphql/product/enums.py
  saleor/graphql/product/mutations/attributes.py
  saleor/graphql/product/tests/test_attribute_pagination.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_product_sorting_attributes.py
  saleor/graphql/product/types/attributes.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/product/__init__.py
  saleor/product/migrations/0128_attribute_type.py
  saleor/product/models.py
  saleor/tests/fixtures.py
Labels: page types

#6241 Allow to filter attributes by type
  saleor/graphql/product/filters.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: page types

#6254 Update populate db
  saleor/core/management/commands/populatedb.py
  saleor/core/tests/test_core.py
  saleor/core/utils/random_data.py
  saleor/static/populatedb_data.json
Labels: mulitchannel

#6255 Mulitchannel fixes.
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/discount/mutations.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/tests/test_product_channel_listing_update.py
  saleor/graphql/product/tests/test_variant_channel_listing_update.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/mutations/channels.py
  saleor/graphql/shipping/types.py
Labels: mulitchannel

#6253 Generate page attributes in populatedb
  saleor/static/populatedb_data.json
Labels: page types

#6257 Fix populatedb
  saleor/core/management/commands/populatedb.py
  saleor/core/utils/random_data.py
  saleor/static/populatedb_data.json
Labels: mulitchannel

#6252 Fix price error field name in mutation responses
  saleor/graphql/core/mutations.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/shipping/mutations.py
  saleor/graphql/shipping/tests/test_shipping_method.py
Labels: bug

#6268 Fix products query on category type
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/types/products.py
Labels: mulitchannel

#6259 update visible product and variants
  saleor/graphql/product/tests/test_attribute_filtering_with_channels.py
  saleor/graphql/product/tests/test_attribute_pagination.py
  saleor/product/models.py
  saleor/product/tests/test_product_availability.py
  saleor/tests/fixtures.py
Labels: mulitchannel

#6213 move collections to channel listing
  saleor/core/management/commands/populatedb.py
  saleor/core/utils/random_data.py
  saleor/graphql/channel/dataloaders.py
  saleor/graphql/channel/mutations.py
  saleor/graphql/core/enums.py
  saleor/graphql/core/tests/test_view.py
  saleor/graphql/core/types/common.py
  saleor/graphql/discount/types.py
  saleor/graphql/menu/mutations.py
  saleor/graphql/menu/resolvers.py
  saleor/graphql/menu/schema.py
  saleor/graphql/menu/tests/deprecated/__init__.py
  saleor/graphql/menu/tests/deprecated/test_menu.py
  saleor/graphql/menu/tests/test_menu.py
  saleor/graphql/menu/types.py
  saleor/graphql/meta/mutations.py
  saleor/graphql/meta/tests/test_meta_mutations.py
  saleor/graphql/meta/tests/test_meta_queries.py
  saleor/graphql/product/dataloaders/__init__.py
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/filters.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/sorters.py
  saleor/graphql/product/tests/benchmark/conftest.py
  saleor/graphql/product/tests/benchmark/test_collection.py
  saleor/graphql/product/tests/benchmark/test_homepage.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_collection_channel_listing_update.py
  saleor/graphql/product/tests/test_collection_filtering_and_sorting_with_channels.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_product_pagination.py
  saleor/graphql/product/tests/test_product_sorting.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/types.py
  saleor/graphql/shop/mutations.py
  saleor/graphql/shop/schema.py
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
  saleor/graphql/translations/mutations.py
  saleor/graphql/translations/resolvers.py
  saleor/graphql/translations/schema.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/graphql/translations/types.py
  saleor/menu/models.py
  saleor/menu/tests/test_menu.py
  saleor/product/error_codes.py
  saleor/product/migrations/0135_collection_channellisting.py
  saleor/product/models.py
  saleor/site/migrations/0026_remove_sitesettings_homepage_collection.py
  saleor/site/models.py
  saleor/static/populatedb_data.json
  saleor/tests/fixtures.py
Labels: mulitchannel

#6272 Fix order with non default currency
  saleor/graphql/order/tests/test_order.py
  saleor/order/models.py
  saleor/tests/fixtures.py
Labels: mulitchannel

#6269 Add attributes validation while creating/updating a product's variant
  CHANGELOG.md
  saleor/graphql/core/tests/test_core.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/tests/test_product_minimal_variant_price.py
  saleor/graphql/product/tests/test_variant.py
Labels: core

#6273 Add mutations to create and update page type
  saleor/graphql/core/types/common.py
  saleor/graphql/page/mutations.py
  saleor/graphql/page/schema.py
  saleor/graphql/page/tests/test_page_type_create.py
  saleor/graphql/page/tests/test_page_type_update.py
  saleor/graphql/schema.graphql
  saleor/page/error_codes.py
Labels: page types

#6288 Add page types query
  saleor/graphql/page/filters.py
  saleor/graphql/page/resolvers.py
  saleor/graphql/page/schema.py
  saleor/graphql/page/sorters.py
  saleor/graphql/page/tests/benchmark/test_page_type.py
  saleor/graphql/page/tests/test_page_types_sorting_and_filtering.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: page types

#6293 Update AttributeCreate mutation permissions
  saleor/graphql/product/mutations/attributes.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/schema.graphql
Labels: page types

#6291 Add channel param to homepage queries from dashboard
  saleor/graphql/order/resolvers.py
  saleor/graphql/order/schema.py
  saleor/graphql/order/tests/deprecated/__init__.py
  saleor/graphql/order/tests/deprecated/test_order.py
  saleor/graphql/order/tests/test_homepage.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/order/utils.py
  saleor/product/utils/__init__.py
  saleor/tests/fixtures.py
Labels: mulitchannel

#6283 Drop currency from shipping_method
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/types.py
  saleor/graphql/shipping/types.py
  saleor/shipping/migrations/0023_remove_shippingmethod_currency.py
  saleor/shipping/models.py
  saleor/shipping/tests/test_shipping.py
  saleor/tests/fixtures.py
Labels: mulitchannel

#6298 Add configuration field to enable the native 3d secure support
  saleor/graphql/checkout/tests/test_checkout_complete.py
  saleor/payment/gateway.py
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/test_utils.py
  saleor/payment/gateways/adyen/utils.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: test deployment

#6307 Add page to page type relation
  saleor/graphql/page/dataloaders.py
  saleor/graphql/page/mutations.py
  saleor/graphql/page/tests/test_page.py
  saleor/graphql/page/types.py
  saleor/graphql/schema.graphql
  saleor/page/migrations/0015_pagetype.py
  saleor/page/models.py
  saleor/tests/fixtures.py
Labels: page types

#6313 Add cost_price validation in ProductVariantBulkCreate
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/tests/test_variant.py
Labels: mulitchannel

#6304 Extend attribute assignment mutations to handle page attributes
  saleor/graphql/page/mutations/__init__.py
  saleor/graphql/page/mutations/attributes.py
  saleor/graphql/page/mutations/pages.py
  saleor/graphql/page/schema.py
  saleor/graphql/page/tests/test_attributes.py
  saleor/graphql/product/mutations/attributes.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/schema.graphql
  saleor/page/error_codes.py
Labels: page types

#6312 Add delete page types mutations
  saleor/graphql/page/bulk_mutations.py
  saleor/graphql/page/mutations/pages.py
  saleor/graphql/page/schema.py
  saleor/graphql/page/tests/test_page_bulk_delete.py
  saleor/graphql/page/tests/test_page_type_delete.py
  saleor/graphql/page/tests/test_page_types_bulk_delete.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: page types

#6308 Drop default currency
  saleor/checkout/migrations/0021_django_price_2.py
  saleor/checkout/migrations/0032_auto_20201022_0818.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/core/middleware.py
  saleor/core/taxes.py
  saleor/core/utils/__init__.py
  saleor/discount/__init__.py
  saleor/discount/migrations/0002_voucher.py
  saleor/discount/migrations/0003_auto_20160207_0534.py
  saleor/discount/migrations/0004_auto_20170206_0407.py
  saleor/discount/migrations/0007_auto_20180108_0814.py
  saleor/discount/migrations/0017_django_price_2.py
  saleor/discount/migrations/0022_auto_20200916_1123.py
  saleor/discount/migrations/0024_auto_20201022_0818.py
  saleor/discount/migrations/0025_auto_20201023_0834.py
  saleor/discount/models.py
  saleor/giftcard/migrations/0002_auto_20190814_0413.py
  saleor/giftcard/models.py
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/tests/test_checkout_complete.py
  saleor/graphql/checkout/types.py
  saleor/graphql/core/validators.py
  saleor/graphql/order/mutations/draft_orders.py
  saleor/graphql/order/mutations/orders.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_product_channel_listing_update.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/schema.graphql
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
  saleor/order/migrations/0072_django_price_2.py
  saleor/order/migrations/0091_auto_20201022_0818.py
  saleor/order/models.py
  saleor/payment/gateways/dummy/plugin.py
  saleor/payment/gateways/dummy_credit_card/plugin.py
  saleor/payment/gateways/utils.py
  saleor/payment/migrations/0002_transfer_payment_to_payment_method.py
  saleor/payment/models.py
  saleor/payment/tests/test_gateways_utils.py
  saleor/payment/tests/test_payment.py
  saleor/payment/utils.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/tests/test_manager.py
  saleor/product/migrations/0106_django_prices_2.py
  saleor/product/migrations/0135_collection_channellisting.py
  saleor/product/utils/costs.py
  saleor/settings.py
  saleor/shipping/migrations/0017_django_price_2.py
  saleor/shipping/migrations/0024_auto_20201022_0818.py
  saleor/shipping/models.py
  saleor/shipping/tests/test_shipping.py
  saleor/tests/fixtures.py
Labels: in progress, mulitchannel

#6314 Add attribute error
  saleor/graphql/core/enums.py
  saleor/graphql/core/types/common.py
  saleor/graphql/product/mutations/attributes.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/schema.graphql
  saleor/product/error_codes.py
Labels: page types

#6322 Optimize product queries in multichannel
  saleor/discount/utils.py
  saleor/graphql/channel/dataloaders.py
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/types/products.py
  saleor/product/tests/test_product_availability.py
  saleor/product/utils/availability.py
Labels: in progress, mulitchannel

#6337 Optimize product variant queries
  saleor/graphql/product/tests/test_variant_pricing.py
  saleor/graphql/product/types/products.py
  saleor/product/utils/availability.py
Labels: mulitchannel

#6336 Fix order_updated not triggering on mutation orderupdate
  saleor/graphql/order/mutations/orders.py
  saleor/graphql/order/tests/test_order.py
Labels: bug

#6334 Optimize product channel listing queries
  saleor/graphql/channel/dataloaders.py
  saleor/graphql/discount/tests/test_voucher_channel_listing.py
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/types/channels.py
Labels: mulitchannel

#6338 Allow associating attribute values with pages
  saleor/graphql/page/dataloaders.py
  saleor/graphql/page/mutations/pages.py
  saleor/graphql/page/tests/test_page.py
  saleor/graphql/page/types.py
  saleor/graphql/product/dataloaders/attributes.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/tests/test_utils.py
  saleor/graphql/product/utils.py
  saleor/graphql/schema.graphql
  saleor/product/utils/attributes.py
  saleor/tests/fixtures.py
Labels: page types

#6321 Add pageTypeReorderAttributes mutation
  saleor/graphql/page/mutations/attributes.py
  saleor/graphql/page/schema.py
  saleor/graphql/page/tests/test_page_type_reorder_attributes.py
  saleor/graphql/product/mutations/attributes.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/schema.graphql
Labels: page types

#6346 Fix empty name and description in updatePlugin mutation response
  saleor/graphql/plugins/tests/test_plugins.py
  saleor/plugins/manager.py
Labels: bug

#6349 Fix margin resolver on varaint channel listing
  saleor/graphql/product/tests/test_variant_channel_listing_update.py
  saleor/graphql/product/types/channels.py
  saleor/product/tests/test_product.py
  saleor/product/utils/costs.py
Labels: mulitchannel

#6352 Fix missing available for purchase date in populate
  saleor/static/populatedb_data.json
Labels: mulitchannel

#6356 Update populatedb with page type
  saleor/core/management/commands/populatedb.py
  saleor/core/tests/test_core.py
  saleor/core/utils/random_data.py
  saleor/graphql/page/tests/test_page_type_reorder_attributes.py
  saleor/static/populatedb_data.json
Labels: page types

#6324 Add validation for order update related mutations
  saleor/graphql/order/mutations/draft_orders.py
  saleor/graphql/order/mutations/orders.py
  saleor/graphql/order/tests/test_order.py
Labels: bug

#6358 Drop 'money_spent' filter from customers query
  saleor/graphql/account/filters.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/schema.graphql
Labels: mulitchannel

#6359 Optimize checkout queries
  saleor/graphql/checkout/types.py
  saleor/graphql/shipping/dataloaders.py
Labels: mulitchannel
