Repository saleor/saleor, pull requests merged in 2020-01, with the labels that each got.

#5109 Remove hashes from requirements files
  requirements.txt
  requirements_dev.txt
Labels: blocker

#5175 Fix for necessity of requires_confirmation field on AccountRegister
  saleor/graphql/account/mutations/account.py
  saleor/graphql/schema.graphql
Labels: bug

#5176 Add permission groups
  CHANGELOG.md
  saleor/account/error_codes.py
  saleor/core/management/commands/populatedb.py
  saleor/core/utils/random_data.py
  saleor/graphql/account/filters.py
  saleor/graphql/account/mutations/permission_group.py
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/schema.py
  saleor/graphql/account/sorters.py
  saleor/graphql/account/types.py
  saleor/graphql/schema.graphql
  saleor/settings.py
  tests/api/test_account_permission_group.py
  tests/conftest.py
Labels: graphql
