Repository saleor/saleor, pull requests merged in 2021-04, with the labels that each got.

#7079 Benchmark tests for order address resolvers
  conftest.py
  saleor/graphql/order/tests/benchmark/fixtures.py
  saleor/graphql/order/tests/benchmark/test_order.py
Labels: performance

#7083 Orders query address fields performance improvements
  CHANGELOG.md
  saleor/graphql/order/types.py
Labels: performance

#7082 Make quantity field on StockInput required
  CHANGELOG.md
  saleor/graphql/product/mutations/products.py
  saleor/graphql/schema.graphql
Labels: approved-breaking-change

#6829 Unconfirmed order line manipulation
  CHANGELOG.md
  saleor/attribute/tests/test_utils.py
  saleor/graphql/account/tests/test_account_permission_group.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/checkout/tests/test_checkout_complete.py
  saleor/graphql/invoice/mutations.py
  saleor/graphql/invoice/tests/test_invoice_create.py
  saleor/graphql/invoice/tests/test_invoice_request.py
  saleor/graphql/order/mutations/discount_order.py
  saleor/graphql/order/mutations/draft_orders.py
  saleor/graphql/order/mutations/orders.py
  saleor/graphql/order/schema.py
  saleor/graphql/order/tests/test_discount_order.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/page/tests/test_page_type_update.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/schema.graphql
  saleor/order/__init__.py
  saleor/order/events.py
  saleor/order/migrations/0103_auto_20210401_1105.py
  saleor/order/models.py
  saleor/order/tests/test_notifications.py
  saleor/order/tests/test_order.py
  saleor/order/tests/test_order_actions.py
  saleor/order/tests/test_order_utils.py
  saleor/order/utils.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/plugin.py
  saleor/tests/fixtures.py
  saleor/warehouse/management.py
  saleor/warehouse/tests/test_stock_management.py
Labels: approved-breaking-change, test deployment

#7059 Rich text attribute input
  CHANGELOG.md
  saleor/attribute/__init__.py
  saleor/attribute/migrations/0008_auto_20210407_0632.py
  saleor/attribute/models/base.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/products_data/utils.py
  saleor/csv/utils/__init__.py
  saleor/csv/utils/products_data.py
  saleor/graphql/attribute/descriptions.py
  saleor/graphql/attribute/mutations.py
  saleor/graphql/attribute/types.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/schema.graphql
  saleor/graphql/translations/mutations.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/graphql/translations/types.py
  saleor/tests/fixtures.py
Labels: approved-breaking-change

#7091 Orders user userEmail performance
  CHANGELOG.md
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/types.py
Labels: performance

#7131 Fix failing export when exporting attribute without values
  CHANGELOG.md
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/utils/products_data.py
  saleor/graphql/csv/enums.py
  saleor/graphql/schema.graphql
Labels: approved-breaking-change

#7120 Order events performance
  CHANGELOG.md
  saleor/graphql/order/dataloaders.py
  saleor/graphql/order/types.py
  saleor/graphql/warehouse/dataloaders.py
Labels: performance

#7125 Order payment status performance
  CHANGELOG.md
  saleor/graphql/order/dataloaders.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/types.py
  saleor/order/models.py
Labels: performance

#7116 Add description to shipping method
  CHANGELOG.md
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/mutations/shippings.py
  saleor/graphql/shipping/tests/test_shipping_method.py
  saleor/graphql/shipping/types.py
  saleor/graphql/translations/mutations.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/graphql/translations/types.py
  saleor/shipping/migrations/0030_auto_20210415_1001.py
  saleor/shipping/models.py
Labels: approved-breaking-change, blocked, test deployment

#7159 Switch graphene opentracing middleware to tracing decorator
  CHANGELOG.md
  saleor/core/tracing.py
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/types.py
  saleor/graphql/app/resolvers.py
  saleor/graphql/app/types.py
  saleor/graphql/attribute/resolvers.py
  saleor/graphql/attribute/schema.py
  saleor/graphql/attribute/types.py
  saleor/graphql/channel/resolvers.py
  saleor/graphql/channel/schema.py
  saleor/graphql/channel/types.py
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/checkout/types.py
  saleor/graphql/core/schema.py
  saleor/graphql/core/types/common.py
  saleor/graphql/core/types/money.py
  saleor/graphql/csv/schema.py
  saleor/graphql/csv/types.py
  saleor/graphql/discount/resolvers.py
  saleor/graphql/discount/schema.py
  saleor/graphql/discount/types.py
  saleor/graphql/giftcard/resolvers.py
  saleor/graphql/giftcard/schema.py
  saleor/graphql/giftcard/types.py
  saleor/graphql/menu/resolvers.py
  saleor/graphql/menu/types.py
  saleor/graphql/middleware.py
  saleor/graphql/order/resolvers.py
  saleor/graphql/order/schema.py
  saleor/graphql/order/types.py
  saleor/graphql/page/resolvers.py
  saleor/graphql/page/types.py
  saleor/graphql/payment/resolvers.py
  saleor/graphql/payment/types.py
  saleor/graphql/plugins/resolvers.py
  saleor/graphql/plugins/schema.py
  saleor/graphql/plugins/types.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/digital_contents.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/schema.py
  saleor/graphql/shipping/types.py
  saleor/graphql/shop/resolvers.py
  saleor/graphql/shop/types.py
  saleor/graphql/translations/resolvers.py
  saleor/graphql/translations/schema.py
  saleor/graphql/translations/types.py
  saleor/graphql/warehouse/schema.py
  saleor/graphql/warehouse/types.py
  saleor/graphql/webhook/resolvers.py
  saleor/graphql/webhook/schema.py
  saleor/graphql/webhook/types.py
  saleor/graphql/wishlist/resolvers.py
  saleor/settings.py
Labels: performance, tracing

#7195 Fix core sorting on related fields
  CHANGELOG.md
  saleor/graphql/core/connection.py
  saleor/graphql/order/tests/test_order.py
Labels: bug

#7169 Order fulfillments performance
  saleor/graphql/order/dataloaders.py
  saleor/graphql/order/types.py
Labels: performance

#7166 Order total captured performance
  saleor/graphql/order/dataloaders.py
  saleor/graphql/order/types.py
  saleor/order/models.py
  saleor/payment/dataloaders.py
  saleor/payment/model_helpers.py
  saleor/payment/models.py
Labels: performance

#7205 Feature/rebuild sort and filter for plugins per channel
  saleor/graphql/plugins/filters.py
  saleor/graphql/plugins/resolvers.py
  saleor/graphql/plugins/sorters.py
  saleor/graphql/plugins/tests/queries/test_plugins.py
  saleor/plugins/tests/sample_plugins.py
Labels: test deployment

#7170 Order total authorized performance
  CHANGELOG.md
  saleor/graphql/order/types.py
  saleor/order/models.py
  saleor/payment/model_helpers.py
Labels: performance

#7175 Order actions performance
  CHANGELOG.md
  saleor/graphql/order/types.py
  saleor/order/models.py
Labels: performance

#7207 Fix export with empty assignment values
  CHANGELOG.md
  saleor/attribute/migrations/0009_auto_20210421_0552.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/products_data/test_prepare_headers.py
  saleor/csv/tests/export/products_data/utils.py
  saleor/csv/utils/product_headers.py
  saleor/csv/utils/products_data.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/csv/enums.py
  saleor/graphql/page/tests/test_page.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/schema.graphql
Labels: approved-breaking-change, test deployment

#7214 Fix export with empty assignment values
  CHANGELOG.md
  saleor/attribute/migrations/0009_auto_20210421_0552.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/products_data/test_prepare_headers.py
  saleor/csv/tests/export/products_data/utils.py
  saleor/csv/utils/product_headers.py
  saleor/csv/utils/products_data.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/csv/enums.py
  saleor/graphql/page/tests/test_page.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/schema.graphql
Labels: approved-breaking-change

#7174 Order subtotal performance
  CHANGELOG.md
  saleor/graphql/order/types.py
  saleor/order/models.py
  saleor/payment/model_helpers.py
Labels: performance

#7206 Fix variants dataloader with default channel
  CHANGELOG.md
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/tests/test_product.py
Labels: bug

#7224 Order line thumbnail performance
  CHANGELOG.md
  saleor/graphql/order/types.py
  saleor/graphql/product/dataloaders/__init__.py
  saleor/graphql/product/dataloaders/products.py
  saleor/product/models.py
Labels: performance

#7220 Feature/rebuild plugin filters to handle channels
  CHANGELOG.md
  saleor/graphql/plugins/enums.py
  saleor/graphql/plugins/filters.py
  saleor/graphql/plugins/mutations.py
  saleor/graphql/plugins/resolvers.py
  saleor/graphql/plugins/tests/queries/test_plugins.py
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/graphql/schema.graphql
  saleor/plugins/tests/sample_plugins.py
Labels: test deployment

#6790 Introduce numeric attributes
  CHANGELOG.md
  saleor/attribute/__init__.py
  saleor/attribute/migrations/0010_auto_20210412_0736.py
  saleor/attribute/models/base.py
  saleor/core/tests/test_weight.py
  saleor/core/units.py
  saleor/core/weight.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/products_data/utils.py
  saleor/csv/utils/__init__.py
  saleor/csv/utils/products_data.py
  saleor/graphql/api.py
  saleor/graphql/attribute/descriptions.py
  saleor/graphql/attribute/mutations.py
  saleor/graphql/attribute/tests/mutations/test_attribute_create.py
  saleor/graphql/attribute/tests/mutations/test_attribute_update.py
  saleor/graphql/attribute/tests/queries/test_attribute_query.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/types.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/core/enums.py
  saleor/graphql/page/mutations/pages.py
  saleor/graphql/product/filters.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/tests/test_shipping_zones_query.py
  saleor/order/models.py
  saleor/product/models.py
  saleor/product/tests/test_get_variant_selection_attributes.py
  saleor/shipping/models.py
  saleor/site/migrations/0029_auto_20210120_0934.py
  saleor/site/models.py
  saleor/static/populatedb_data.json
  saleor/tests/fixtures.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: attributes, feature branch
