Repository saleor/saleor, pull requests merged in 2021-02, with the labels that each got.

#6832 Fix page content_json field to return JSON
  CHANGELOG.md
  saleor/graphql/page/tests/test_page.py
  saleor/graphql/page/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/translations/types.py
Labels: approved-breaking-change

#6821 Add ability to store category attributes
  saleor/attribute/migrations/0007_auto_20210129_1130.py
  saleor/attribute/models/__init__.py
  saleor/attribute/models/category.py
  saleor/core/error_codes.py
  saleor/graphql/core/types/common.py
  saleor/graphql/schema.graphql
  saleor/graphql/shop/mutations.py
  saleor/graphql/shop/schema.py
  saleor/graphql/shop/tests/benchmark/test_category_settings.py
  saleor/graphql/shop/tests/test_category_settings_update.py
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
  saleor/tests/fixtures.py
Labels: attributes

#6841 Add support for multiline in Plugin configuration
  saleor/graphql/schema.graphql
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/base_plugin.py
  saleor/plugins/user_email/plugin.py
Labels: test deployment

#6839 Allow sorting category attributes
  saleor/graphql/product/dataloaders/attributes.py
  saleor/graphql/schema.graphql
  saleor/graphql/shop/mutations.py
  saleor/graphql/shop/schema.py
  saleor/graphql/shop/tests/benchmark/test_category_settings.py
  saleor/graphql/shop/tests/test_category_settings_reorder_attributes.py
  saleor/graphql/shop/tests/test_category_settings_update.py
  saleor/graphql/shop/types.py
Labels: approved-breaking-change, attributes

#6869 Add example category attributes
  saleor/core/utils/random_data.py
  saleor/static/populatedb_data.json
Labels: attributes

#6870 Add example collection attribute
  saleor/core/utils/random_data.py
  saleor/static/populatedb_data.json
Labels: attributes

#6784 Drop country middleware
  .isort.cfg
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/core/middleware.py
  saleor/core/tests/test_core.py
  saleor/core/utils/__init__.py
  saleor/core/utils/random_data.py
  saleor/graphql/checkout/mutations.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_product_channel_listings_queries.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/product/tests/test_variant_pricing.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/shop/tests/benchmark/test_homepage.py
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
  saleor/graphql/tests/test_utils.py
  saleor/graphql/utils/__init__.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/graphql/warehouse/tests/test_stock.py
  saleor/product/utils/availability.py
  saleor/settings.py
  saleor/tests/settings.py
  saleor/warehouse/availability.py
  saleor/warehouse/tests/test_stock_availability.py
Labels: approved-breaking-change, blocked

#6875 Fix CI
  .github/workflows/pytest.yml
Labels: in progress

#6664 Feature: add inclusion type to ZIP code rules
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/order/mutations/orders.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/dataloaders.py
  saleor/graphql/shipping/enums.py
  saleor/graphql/shipping/mutations/shippings.py
  saleor/graphql/shipping/schema.py
  saleor/graphql/shipping/tests/test_shipping_method.py
  saleor/graphql/shipping/types.py
  saleor/shipping/__init__.py
  saleor/shipping/migrations/0027_auto_20210120_2201.py
  saleor/shipping/models.py
  saleor/shipping/postal_codes.py
  saleor/shipping/tests/test_postal_codes.py
  saleor/shipping/tests/test_zip_codes.py
  saleor/shipping/zip_codes.py
  saleor/tests/fixtures.py
Labels: approved-breaking-change, test deployment

#6927 Fix shop query postal codes filtering
  saleor/graphql/shop/resolvers.py
  saleor/graphql/shop/tests/test_shop.py
Labels: bug

#6923 Fix logic to calculate prices with proper tax calculation
  saleor/graphql/order/mutations/discount_order.py
  saleor/graphql/order/mutations/draft_orders.py
  saleor/graphql/order/mutations/orders.py
  saleor/graphql/order/tests/test_discount_order.py
  saleor/graphql/order/types.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
Labels: test deployment
