Repository saleor/saleor, pull requests merged in 2021-07, with the labels that each got.

#7587 Bump requirements
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#7574 User type performance
  CHANGELOG.md
  saleor/graphql/account/dataloaders.py
  saleor/graphql/account/types.py
  saleor/graphql/giftcard/dataloaders.py
  saleor/graphql/order/dataloaders.py
Labels: performance

#7604 Checkout lines add fix
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/test_checkout_lines.py
Labels: bug, core

#7616 Bump requirements
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
  tox.ini
Labels: test deployment

#7623 Drop top-level checkoutLine query with related resolver
  CHANGELOG.md
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/schema.graphql
Labels: approved-breaking-change

#7648 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#7559 Improve account search results by using ILIKE instead of TrigramSimilarity.
  saleor/account/migrations/0053_auto_20210719_1048.py
  saleor/account/models.py
  saleor/core/__init__.py
  saleor/core/app.py
  saleor/core/db/filters.py
  saleor/graphql/account/filters.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/account/tests/test_pagination.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/sorters.py
  saleor/graphql/product/tests/test_product.py
Labels: in progress

#7653 [SALEOR-3965] Extend Sale & Voucher to include Metadata
  saleor/discount/migrations/0027_auto_20210719_2155.py
  saleor/discount/models.py
  saleor/graphql/discount/filters.py
  saleor/graphql/discount/types.py
  saleor/graphql/meta/mutations.py
  saleor/graphql/meta/permissions.py
  saleor/graphql/meta/resolvers.py
  saleor/graphql/meta/tests/test_meta_mutations.py
  saleor/graphql/meta/tests/test_meta_queries.py
  saleor/graphql/schema.graphql
Labels: test deployment

#7692 Update dependencies
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#7696 Update GiftCardCreate mutation
  saleor/core/utils/promo_code.py
  saleor/core/utils/validators.py
  saleor/giftcard/__init__.py
  saleor/giftcard/events.py
  saleor/giftcard/migrations/0005_auto_20210719_1116.py
  saleor/graphql/core/types/common.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/giftcard/tests/benchmark/test_gift_card_mutations.py
  saleor/graphql/giftcard/tests/deprecated/test_gift_card_mutations.py
  saleor/graphql/giftcard/tests/deprecated/test_gift_card_query.py
  saleor/graphql/giftcard/tests/mutations/__init__.py
  saleor/graphql/giftcard/tests/mutations/test_gift_card_create.py
  saleor/graphql/giftcard/tests/test_gift_card.py
  saleor/graphql/giftcard/types.py
  saleor/graphql/schema.graphql
Labels: approved-breaking-change

#7709 Extend install app logic to handle extensions
  saleor/app/installation_utils.py
  saleor/app/manifest_validations.py
  saleor/app/tasks.py
  saleor/app/tests/test_installation_utils.py
  saleor/graphql/app/tests/mutations/test_app_fetch_manifest.py
  saleor/tests/fixtures.py
Labels: test deployment

#7500 [SALEOR-3088] Date & DateTime attributes
  CHANGELOG.md
  saleor/attribute/__init__.py
  saleor/attribute/migrations/0014_auto_20210619_1836.py
  saleor/attribute/models/base.py
  saleor/core/utils/random_data.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/products_data/utils.py
  saleor/csv/tests/export/test_export.py
  saleor/csv/utils/__init__.py
  saleor/csv/utils/export.py
  saleor/csv/utils/products_data.py
  saleor/graphql/attribute/descriptions.py
  saleor/graphql/attribute/types.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/page/tests/test_page.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/filters.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/schema.graphql
  saleor/product/tests/test_product.py
  saleor/static/populatedb_data.json
  saleor/tests/fixtures.py
  saleor/webhook/serializers.py
  saleor/webhook/tests/test_webhook_serializers.py
Labels: test deployment
