Repository saleor/saleor, pull requests merged in 2021-09, with the labels that each got.

#7992 Change hidden products access permissions
  saleor/core/permissions.py
  saleor/graphql/attribute/tests/queries/test_attribute_filter.py
  saleor/graphql/product/tests/benchmark/test_variant_stocks.py
  saleor/graphql/product/tests/test_product.py
  saleor/product/models.py
  saleor/product/tests/test_product_availability.py
Labels: 3.0

#8002 Use exact permission to determine if user has access to resources 3.0
  saleor/account/tests/test_account.py
  saleor/account/utils.py
  saleor/attribute/models/base.py
  saleor/core/models.py
  saleor/graphql/attribute/filters.py
  saleor/graphql/attribute/tests/queries/test_attribute_filter.py
  saleor/graphql/attribute/tests/queries/test_attribute_query.py
  saleor/graphql/menu/types.py
  saleor/graphql/order/types.py
  saleor/graphql/page/tests/test_page.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/product/types/products.py
  saleor/page/models.py
  saleor/product/models.py
Labels: 3.0

#8004 Add workaround for incorrect tax calculation recieved from Avatax for 3.0
  saleor/plugins/avatax/plugin.py
Labels: 3.0

#8015 Fix language codes in 3.0
  saleor/account/migrations/0055_alter_user_language_code.py
  saleor/account/migrations/0056_merge_20210903_0640.py
  saleor/checkout/migrations/0036_alter_checkout_language_code.py
  saleor/core/languages.py
  saleor/order/migrations/0115_alter_order_language_code.py
Labels: 3.0

#8017 Fix checkout lines update can create line with 0 quantity
  saleor/checkout/migrations/0037_remove_empty_lines.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/tests/test_checkout_lines.py
Labels: 3.0

#8018 Fix language codes in 3.1
  saleor/account/migrations/0055_alter_user_language_code.py
  saleor/account/migrations/0056_merge_20210903_0640.py
  saleor/checkout/migrations/0036_alter_checkout_language_code.py
  saleor/checkout/migrations/0037_merge_20210903_1013.py
  saleor/core/languages.py
  saleor/order/migrations/0115_alter_order_language_code.py
  saleor/order/migrations/0117_merge_20210903_1013.py
Labels: 3.1, reviewed

#8008 Add workaround for incorrect tax calculation recieved from Avatax for 3.1
  saleor/plugins/avatax/plugin.py
Labels: 3.1

#8021 Fix the example query displayed in Playground in 3.1
  templates/graphql/playground.html
Labels: bug

#8020 Fix the example query displayed in Playground
  templates/graphql/playground.html
Labels: bug

#8019 Block CheckoutLinesUpdate for creating empty lines in 3.1
  saleor/checkout/migrations/0037_remove_empty_lines.py
  saleor/checkout/migrations/0038_merge_20210903_1048.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/tests/test_checkout_lines.py
Labels: 3.1, reviewed

#8033 Fix performance issue
  saleor/attribute/migrations/0016_auto_20210827_0938.py
  saleor/attribute/models/base.py
  saleor/graphql/attribute/filters.py
Labels: 3.1, reviewed

#8036 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#8040 Fix checking existing lines quantity 3.1
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/test_checkout_lines.py
  saleor/warehouse/availability.py
Labels: 3.1, reviewed

#8026 Refactor permission decorators
  saleor/core/permissions.py
  saleor/graphql/decorators.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/tests/test_decorators.py
Labels: 3.0

#7964 Fix attributes values filter performance issue
  saleor/attribute/migrations/0016_auto_20210827_0938.py
  saleor/attribute/models/base.py
  saleor/graphql/attribute/filters.py
Labels: 3.0

#8058 Optimize product filtering by attribute
  saleor/graphql/product/filters.py
Labels: 3.1

#8079 Bump dependencies
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#8065 Fix inccorect handling of last response object 3.0
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/tests/test_plugin.py
Labels: 3.0

#8078 Optimize product filtering by attribute in 3.0
  saleor/graphql/product/filters.py
Labels: 3.0, reviewed

#8066 Fix inccorect handling of last response object
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/tests/test_plugin.py
Labels: reviewed

#8084 Fix adyen do not assume that checkout exists for additional action 3.0
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_additional_actions.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.0

#8085 Fix adyen do not assume that checkout exists for additional action
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_additional_actions.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: reviewed

#8053 Fix bug with handling orders containing deleted variants
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: test deployment, 3.0

#8089 Fix bug with handling orders containing deleted variants in 3.1
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.1, reviewed

#8083 Fix passing replace flag to check_stock_quantity_bulk
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/test_checkout_lines.py
  saleor/warehouse/availability.py
Labels: 3.0

#8091 Fix passing replace flag to check_stock_quantity_bulk
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/test_checkout_lines.py
  saleor/warehouse/availability.py
Labels: 3.1, reviewed

#7261 Introduce swatch attributes
  CHANGELOG.md
  saleor/attribute/__init__.py
  saleor/attribute/migrations/0017_auto_20210811_0701.py
  saleor/attribute/models/base.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/products_data/utils.py
  saleor/csv/utils/__init__.py
  saleor/csv/utils/products_data.py
  saleor/graphql/attribute/descriptions.py
  saleor/graphql/attribute/mutations.py
  saleor/graphql/attribute/tests/mutations/test_attribute_create.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_create.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_update.py
  saleor/graphql/attribute/tests/queries/test_attribute_query.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/schema.graphql
  saleor/product/tests/test_get_variant_selection_attributes.py
  saleor/tests/fixtures.py
Labels: test deployment, 3.1

#8076 Possibility to pass metadata in checkoutPaymentCreate
  CHANGELOG.md
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/checkout/mutations.py
  saleor/graphql/meta/mutations.py
  saleor/graphql/meta/permissions.py
  saleor/graphql/meta/resolvers.py
  saleor/graphql/meta/tests/conftest.py
  saleor/graphql/meta/tests/test_meta_mutations.py
  saleor/graphql/meta/tests/test_meta_queries.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/test_payment.py
  saleor/graphql/payment/types.py
  saleor/graphql/payment/utils.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/fixtures.py
  saleor/payment/__init__.py
  saleor/payment/gateways/stripe/consts.py
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/stripe_api.py
  saleor/payment/gateways/stripe/tests/test_plugin.py
  saleor/payment/gateways/stripe/tests/test_plugin_deprecated.py
  saleor/payment/gateways/stripe/tests/test_stripe_api.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/payment/interface.py
  saleor/payment/migrations/0030_auto_20210908_1346.py
  saleor/payment/models.py
  saleor/payment/tests/test_payment.py
  saleor/payment/utils.py
  saleor/plugins/webhook/tests/test_payment_webhook.py
  saleor/tests/fixtures.py
Labels: test deployment

#8110 Fix missing transaction id in Braintree
  CHANGELOG.md
  saleor/payment/gateways/braintree/__init__.py
  saleor/payment/gateways/braintree/tests/test_braintree.py
Labels: 3.0

#8113 Fix missing transaction id in Braintree in 3.1
  saleor/payment/gateways/braintree/__init__.py
  saleor/payment/gateways/braintree/tests/test_braintree.py
Labels: 3.1, reviewed

#8107 Backport GraphQL Federations fix to 3.0
  CHANGELOG.md
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/account/types.py
  saleor/graphql/api.py
  saleor/graphql/app/tests/queries/test_app.py
  saleor/graphql/app/types.py
  saleor/graphql/channel/types.py
  saleor/graphql/core/federation.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
Labels: 3.0

#8141 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#8093 Capture user agent when tracing
  saleor/graphql/views.py
Labels: 3.0

#8094 Capture user agent when tracing in 3.1
  saleor/graphql/views.py
Labels: 3.1

#8098 Fix call handler with incorrect function arguments
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.0

#8139 Increase webhook sync timeout to 20
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_payment_webhook.py
  saleor/settings.py
Labels: 3.0

#8105 Change PluginsManager to call methods only on active plugins
  saleor/plugins/manager.py
  saleor/plugins/tests/fixtures.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/tests/test_manager.py
Labels: 3.0

#8109 Saleor 2831/3.1/pluginsmanager call action only active plugin
  saleor/plugins/manager.py
  saleor/plugins/tests/fixtures.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/tests/test_manager.py
Labels: reviewed

#8111 Add order status verification to DraftOrderDelete mutation
  saleor/graphql/order/mutations/draft_orders.py
  saleor/graphql/order/tests/test_order.py
Labels: 3.0

#8138 add order status verification to DraftOrderDelete mutation in 3.1
  saleor/graphql/order/mutations/draft_orders.py
  saleor/graphql/order/tests/test_order.py
Labels: 3.1, reviewed

#8142 Fix account address update as anonymous user in 3.0
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/test_account.py
Labels: 3.0, reviewed

#8156 Saleor 4422/3.1/increase timeout for sync webhooks
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_payment_webhook.py
  saleor/settings.py
Labels: 3.1

#8126 Add allow_stock_to_be_exceeded flag in OrderFulfill mutation
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/order/mutations/fulfillments.py
  saleor/graphql/order/tests/test_fulfillment.py
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/schema.graphql
  saleor/graphql/warehouse/dataloaders.py
  saleor/order/actions.py
  saleor/order/tests/test_fulfillments_actions.py
  saleor/warehouse/management.py
  saleor/warehouse/migrations/0015_alter_stock_quantity.py
  saleor/warehouse/models.py
Labels: 3.0

#8155 Saleor 4421/3.1/extend orderfulfill mutation by new flag to allow stock exceeded
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/order/mutations/fulfillments.py
  saleor/graphql/order/tests/test_fulfillment.py
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/schema.graphql
  saleor/graphql/warehouse/dataloaders.py
  saleor/order/actions.py
  saleor/order/tests/test_fulfillments_actions.py
  saleor/warehouse/management.py
  saleor/warehouse/migrations/0015_alter_stock_quantity.py
  saleor/warehouse/migrations/0016_merge_20210921_1036.py
  saleor/warehouse/models.py
Labels: 3.1, reviewed

#8201 Bump dependencies
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#8102 Improve draft orders and orders webhooks
  CHANGELOG.md
  saleor/graphql/invoice/tests/test_invoice_delete.py
  saleor/graphql/invoice/tests/test_invoice_request.py
  saleor/graphql/invoice/tests/test_invoice_request_delete.py
  saleor/graphql/order/mutations/draft_orders.py
  saleor/graphql/order/mutations/orders.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/schema.graphql
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/event_types.py
  saleor/webhook/tests/test_webhook_sample_payloads.py
Labels: 3.0

#8200 Improve draft orders webhooks in 3.1
  CHANGELOG.md
  saleor/graphql/invoice/tests/test_invoice_delete.py
  saleor/graphql/invoice/tests/test_invoice_request.py
  saleor/graphql/invoice/tests/test_invoice_request_delete.py
  saleor/graphql/order/mutations/draft_orders.py
  saleor/graphql/order/mutations/orders.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/schema.graphql
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/event_types.py
  saleor/webhook/tests/test_webhook_sample_payloads.py
Labels: 3.1, reviewed

#8174 Remove unnecessary database lock on discount during checkout complete mutation
  CHANGELOG.md
  saleor/checkout/complete_checkout.py
  saleor/checkout/utils.py
  saleor/discount/utils.py
  saleor/graphql/checkout/tests/test_checkout_complete.py
Labels: 3.0

#8182 Unnecessary database lock in checkout complete mutation in 3.1
  saleor/checkout/complete_checkout.py
  saleor/checkout/utils.py
  saleor/discount/utils.py
  saleor/graphql/checkout/tests/test_checkout_complete.py
Labels: 3.1, reviewed

#8163 Add ID list for order filtering
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/schema.graphql
Labels: 3.0

#8178 Add ID list for order filtering
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/schema.graphql
Labels: 3.1, reviewed

#8208 Mute confusing PermissionDenied logs
  saleor/graphql/tests/fixtures.py
Labels: reviewed

#8211 Fix/backport product cursor fix
  CHANGELOG.md
  saleor/graphql/core/connection.py
  saleor/graphql/product/sorters.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/utils/sorting.py
Labels: reviewed

#8209 Handle SameSite cookie attribute in jwt refresh token middleware
  saleor/core/middleware.py
  saleor/core/tests/test_middleware.py
Labels: 3.0

#8170 Too many fields from payment object are accessible for customer in ordertype
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/tests/utils.py
  saleor/graphql/payment/tests/deprecated/test_checkout_payment_create.py
  saleor/graphql/payment/tests/test_payment.py
  saleor/graphql/payment/types.py
  saleor/tests/fixtures.py
Labels: 3.0

#8179 Mark X- headers as deprecated. Add headers without prefix
  CHANGELOG.md
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/tests/cassettes/test_creates_app_from_manifest.yaml
  saleor/app/tests/cassettes/test_creates_app_from_manifest_activate_app.yaml
  saleor/app/tests/cassettes/test_creates_app_from_manifest_app_has_all_required_permissions.yaml
  saleor/app/tests/cassettes/test_install_app_task.yaml
  saleor/app/tests/test_app_commands.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/cassettes/test_trigger_webhooks_with_http.yaml
  saleor/plugins/webhook/tests/cassettes/test_trigger_webhooks_with_http_and_secret_key.yaml
  saleor/plugins/webhook/tests/test_webhook_protocols.py
Labels: 3.0

#8225 Too many fields from payment object
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/tests/utils.py
  saleor/graphql/payment/tests/deprecated/test_checkout_payment_create.py
  saleor/graphql/payment/tests/test_payment.py
  saleor/graphql/payment/types.py
  saleor/tests/fixtures.py
Labels: 3.1, reviewed

#8205 Mark X- headers as deprecated. Add headers without prefix
  CHANGELOG.md
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/tests/cassettes/test_creates_app_from_manifest.yaml
  saleor/app/tests/cassettes/test_creates_app_from_manifest_activate_app.yaml
  saleor/app/tests/cassettes/test_creates_app_from_manifest_app_has_all_required_permissions.yaml
  saleor/app/tests/cassettes/test_install_app_task.yaml
  saleor/app/tests/test_app_commands.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/cassettes/test_trigger_webhooks_with_http.yaml
  saleor/plugins/webhook/tests/cassettes/test_trigger_webhooks_with_http_and_secret_key.yaml
  saleor/plugins/webhook/tests/test_webhook_protocols.py
Labels: 3.1

#8175 Fix Insufficient stock error in checkoutLinesUpdate with 0 quantity.
  saleor/graphql/checkout/tests/test_checkout_lines.py
  saleor/warehouse/availability.py
Labels: 3.0

#8203 Query fingerprint in span info
  saleor/graphql/tests/test_tracing.py
  saleor/graphql/utils/__init__.py
  saleor/graphql/views.py
Labels: test deployment, 3.1

#8232 Fix Insufficient stock error in checkoutLinesUpdate with 0 quantity.
  saleor/graphql/checkout/tests/test_checkout_lines.py
  saleor/warehouse/availability.py
Labels: 3.1, reviewed

#8064 Make sale per variant
  CHANGELOG.md
  saleor/core/utils/random_data.py
  saleor/discount/__init__.py
  saleor/discount/migrations/0030_discount_variants.py
  saleor/discount/models.py
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils.py
  saleor/graphql/checkout/tests/test_checkout_promo_codes.py
  saleor/graphql/discount/dataloaders.py
  saleor/graphql/discount/mutations.py
  saleor/graphql/discount/tests/benchmark/test_sales.py
  saleor/graphql/discount/tests/benchmark/test_vouchers.py
  saleor/graphql/discount/tests/test_discount.py
  saleor/graphql/discount/types.py
  saleor/graphql/product/tests/test_product_discounted_price.py
  saleor/graphql/schema.graphql
  saleor/product/models.py
  saleor/product/tasks.py
  saleor/product/utils/availability.py
  saleor/product/utils/variant_prices.py
  saleor/tests/fixtures.py
Labels: test deployment, 3.1

#8240 Unify GraphQL span naming across tracers
  saleor/graphql/tests/test_tracing.py
  saleor/graphql/views.py
Labels: tracing, 3.1

#8241 Unify GraphQl span naming across tracers
  saleor/graphql/tests/test_tracing.py
  saleor/graphql/views.py
Labels: tracing, 3.0, reviewed

#8157 Sales webhooks
  CHANGELOG.md
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils.py
  saleor/graphql/discount/mutations.py
  saleor/graphql/discount/tests/test_discount.py
  saleor/graphql/schema.graphql
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/tests/test_manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/tests/fixtures.py
  saleor/webhook/event_types.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.1

#8243 Make sentry settings configurable
  saleor/core/app.py
  saleor/demo/settings.py
  saleor/settings.py
Labels: 3.0

#8245 Make sentry settings configurable
  saleor/core/app.py
  saleor/demo/settings.py
  saleor/settings.py
Labels: 3.1, reviewed

#7633 Support empty SKUs for products variants
  CHANGELOG.md
  saleor/checkout/complete_checkout.py
  saleor/core/analytics.py
  saleor/core/tests/test_analytics.py
  saleor/core/utils/random_data.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/test_export.py
  saleor/csv/utils/__init__.py
  saleor/csv/utils/products_data.py
  saleor/graphql/attribute/tests/queries/test_attribute_filtering_with_channels.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/tests/test_checkout_complete.py
  saleor/graphql/core/validators.py
  saleor/graphql/csv/enums.py
  saleor/graphql/order/tests/test_fulfillment.py
  saleor/graphql/order/tests/test_fulfillment_refund_products.py
  saleor/graphql/order/tests/test_fulfillment_return_products.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/types.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_product_filtering_and_sorting_with_channels.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/product/tests/test_variant_query.py
  saleor/graphql/product/tests/test_variant_with_filtering.py
  saleor/graphql/product/utils.py
  saleor/graphql/schema.graphql
  saleor/order/migrations/0120_orderline_optional_sku.py
  saleor/order/models.py
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/order/tests/test_order.py
  saleor/order/tests/test_order_actions.py
  saleor/order/tests/test_order_actions_create_fulfillments_for_returned_products.py
  saleor/order/utils.py
  saleor/payment/gateways/adyen/tests/utils/test_common.py
  saleor/payment/gateways/adyen/utils/common.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/cassettes/test_calculate_checkout_line_without_sku_total[False-24.39-30.00-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_calculate_checkout_line_without_sku_total[False-30.00-36.90-False].yaml
  saleor/plugins/avatax/tests/cassettes/test_calculate_checkout_line_without_sku_total[True-12.20-15.00-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_calculate_checkout_line_without_sku_total[True-15.00-18.45-False].yaml
  saleor/plugins/avatax/tests/cassettes/test_calculate_order_line_total.yaml
  saleor/plugins/avatax/tests/cassettes/test_calculate_order_line_without_sku_total.yaml
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/product/migrations/0149_alter_productvariant_sku.py
  saleor/product/models.py
  saleor/product/tests/test_generate_and_set_variant_name.py
  saleor/product/utils/variants.py
  saleor/seo/schema/email.py
  saleor/seo/tests/test_seo_schema.py
  saleor/tests/fixtures.py
  saleor/webhook/payloads.py
  saleor/webhook/serializers.py
  saleor/webhook/tests/test_webhook_payloads.py
  templates/invoices/invoice_products_table.html
Labels: test deployment, approved-breaking-change, 3.1
