Repository saleor/saleor, pull requests merged in 2021-08, with the labels that each got.

#7752 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#7776 Bump to 3.0.0 b.8
  CHANGELOG.md
  saleor/checkout/fetch.py
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/tests/test_checkout_promo_codes.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_product_channel_listings_queries.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/product/tests/test_variant_pricing.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
  saleor/graphql/tests/test_utils.py
  saleor/graphql/utils/__init__.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/graphql/warehouse/tests/test_dataloaders.py
  saleor/graphql/warehouse/tests/test_stock.py
  saleor/product/utils/availability.py
  saleor/tests/fixtures.py
  saleor/warehouse/availability.py
  saleor/warehouse/models.py
  saleor/warehouse/tests/test_warehouse.py
  saleor/webhook/payloads.py
Labels: test deployment

#7798 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#7808 Bump to 3.0.0 b.9
  CHANGELOG.md
  CONTRIBUTING.md
  poetry.lock
  requirements.txt
  requirements_dev.txt
  saleor/attribute/models/base.py
  saleor/core/utils/translations.py
  saleor/graphql/translations/types.py
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/stripe_api.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/tests/fixtures.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: test deployment

#7809 Temporarily revert major version upgrade of weasyprint
  poetry.lock
  pyproject.toml
Labels: bug

#7810 Bump to 3.0.0-b.10
  poetry.lock
  pyproject.toml
Labels: test deployment

#7824 Fix fulfillment cancel when warehouse provided
  saleor/graphql/order/mutations/fulfillments.py
  saleor/graphql/order/tests/test_fulfillment.py
Labels: test deployment

#7843 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#7845 Bump to 3.0.0-b.11
  CHANGELOG.md
  poetry.lock
  requirements.txt
  requirements_dev.txt
  saleor/attribute/models/base.py
  saleor/graphql/core/types/filter_input.py
  saleor/graphql/core/types/sort_input.py
  saleor/graphql/discount/resolvers.py
  saleor/graphql/discount/schema.py
  saleor/graphql/discount/tests/deprecated/test_discount.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/translations/mutations.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: test deployment

#7681 Gift cards CRUD
  conftest.py
  saleor/core/__init__.py
  saleor/core/utils/promo_code.py
  saleor/core/utils/random_data.py
  saleor/core/utils/validators.py
  saleor/discount/migrations/0028_alter_voucher_code.py
  saleor/discount/models.py
  saleor/giftcard/__init__.py
  saleor/giftcard/events.py
  saleor/giftcard/migrations/0005_auto_20210719_1116.py
  saleor/giftcard/migrations/0006_auto_20210719_1117.py
  saleor/giftcard/migrations/0007_auto_20210719_1311.py
  saleor/giftcard/models.py
  saleor/graphql/account/tests/benchmark/fixtures.py
  saleor/graphql/checkout/tests/test_checkout_promo_codes.py
  saleor/graphql/core/enums.py
  saleor/graphql/core/types/common.py
  saleor/graphql/giftcard/dataloaders.py
  saleor/graphql/giftcard/enums.py
  saleor/graphql/giftcard/filters.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/giftcard/schema.py
  saleor/graphql/giftcard/tests/benchmark/__init__.py
  saleor/graphql/giftcard/tests/benchmark/fixtures.py
  saleor/graphql/giftcard/tests/benchmark/test_gift_card_mutations.py
  saleor/graphql/giftcard/tests/benchmark/test_gift_card_queries.py
  saleor/graphql/giftcard/tests/deprecated/__init__.py
  saleor/graphql/giftcard/tests/deprecated/test_gift_card_mutations.py
  saleor/graphql/giftcard/tests/deprecated/test_gift_card_query.py
  saleor/graphql/giftcard/tests/mutations/__init__.py
  saleor/graphql/giftcard/tests/mutations/test_gift_card_activate.py
  saleor/graphql/giftcard/tests/mutations/test_gift_card_create.py
  saleor/graphql/giftcard/tests/mutations/test_gift_card_deactivate.py
  saleor/graphql/giftcard/tests/mutations/test_gift_card_delete.py
  saleor/graphql/giftcard/tests/mutations/test_gift_card_update.py
  saleor/graphql/giftcard/tests/queries/__init__.py
  saleor/graphql/giftcard/tests/queries/test_gift_card.py
  saleor/graphql/giftcard/tests/queries/test_gift_cards.py
  saleor/graphql/giftcard/tests/test_gift_card.py
  saleor/graphql/giftcard/types.py
  saleor/graphql/meta/permissions.py
  saleor/graphql/meta/resolvers.py
  saleor/graphql/meta/tests/test_meta_mutations.py
  saleor/graphql/meta/tests/test_meta_queries.py
  saleor/graphql/schema.graphql
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
  saleor/tests/fixtures.py
Labels: test deployment, approved-breaking-change, feature branch

#7871 Fix send invoice logic and linked unit tests
  saleor/graphql/invoice/tests/test_send_invoice_notification.py
  saleor/invoice/notifications.py
Labels: 3.0, Reviewed

#7872 Fix send invoice logic and linked unit tests
  saleor/graphql/invoice/tests/test_send_invoice_notification.py
  saleor/invoice/notifications.py
Labels: 3.1, Reviewed

#7869 Update weasyprint to v53.0
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#7873 Optimize available quantity loader in 3.1
  CHANGELOG.md
  saleor/graphql/product/types/products.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/warehouse/models.py
Labels: 3.1, Reviewed

#7881 Email plugin does not choose proper channel configuration
  saleor/plugins/admin_email/notify_events.py
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tasks.py
  saleor/plugins/admin_email/tests/test_notify_events.py
  saleor/plugins/admin_email/tests/test_plugin.py
  saleor/plugins/admin_email/tests/test_tasks.py
  saleor/plugins/email_common.py
  saleor/plugins/user_email/notify_events.py
  saleor/plugins/user_email/plugin.py
  saleor/plugins/user_email/tasks.py
  saleor/plugins/user_email/tests/test_notify_events.py
  saleor/plugins/user_email/tests/test_plugin.py
  saleor/plugins/user_email/tests/test_tasks.py
Labels: 3.0, Reviewed

#7876 Email plugin does not choose proper channel configuration
  saleor/plugins/admin_email/notify_events.py
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tasks.py
  saleor/plugins/admin_email/tests/test_notify_events.py
  saleor/plugins/admin_email/tests/test_plugin.py
  saleor/plugins/admin_email/tests/test_tasks.py
  saleor/plugins/email_common.py
  saleor/plugins/user_email/notify_events.py
  saleor/plugins/user_email/plugin.py
  saleor/plugins/user_email/tasks.py
  saleor/plugins/user_email/tests/test_notify_events.py
  saleor/plugins/user_email/tests/test_plugin.py
  saleor/plugins/user_email/tests/test_tasks.py
Labels: 3.0

#7886 Fix for failing voucher recalculation
  saleor/checkout/utils.py
Labels: test deployment, 3.1

#7888 Fix failing voucher recalculation for 3.0
  saleor/checkout/utils.py
Labels: 3.0

#7890 Email plugin does not choose proper channel configuration
  saleor/plugins/admin_email/notify_events.py
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tasks.py
  saleor/plugins/admin_email/tests/test_notify_events.py
  saleor/plugins/admin_email/tests/test_plugin.py
  saleor/plugins/admin_email/tests/test_tasks.py
  saleor/plugins/email_common.py
  saleor/plugins/user_email/notify_events.py
  saleor/plugins/user_email/plugin.py
  saleor/plugins/user_email/tasks.py
  saleor/plugins/user_email/tests/test_notify_events.py
  saleor/plugins/user_email/tests/test_plugin.py
  saleor/plugins/user_email/tests/test_tasks.py
Labels: reviewed

#7701 Feature/extending dashboard with apps
  CHANGELOG.md
  saleor/app/installation_utils.py
  saleor/app/manifest_validations.py
  saleor/app/migrations/0005_appextension.py
  saleor/app/models.py
  saleor/app/tasks.py
  saleor/app/tests/test_installation_utils.py
  saleor/app/tests/test_manifest_validation.py
  saleor/app/types.py
  saleor/core/jwt.py
  saleor/core/tests/test_jwt.py
  saleor/graphql/app/dataloaders.py
  saleor/graphql/app/enums.py
  saleor/graphql/app/filters.py
  saleor/graphql/app/mutations.py
  saleor/graphql/app/resolvers.py
  saleor/graphql/app/schema.py
  saleor/graphql/app/tests/benchmarks/__init__.py
  saleor/graphql/app/tests/benchmarks/test_app_extensions.py
  saleor/graphql/app/tests/mutations/test_app_fetch_manifest.py
  saleor/graphql/app/tests/queries/test_app.py
  saleor/graphql/app/tests/queries/test_app_extension.py
  saleor/graphql/app/tests/queries/test_app_extensions.py
  saleor/graphql/app/tests/queries/test_apps.py
  saleor/graphql/app/types.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: test deployment, 3.1

#7893 Fix failing address checks in Adyen 3.0
  saleor/payment/gateways/adyen/tests/utils/test_common.py
  saleor/payment/gateways/adyen/utils/common.py
Labels: 3.0

#7675 Fulfillment confirmation
  CHANGELOG.md
  saleor/graphql/order/dataloaders.py
  saleor/graphql/order/mutations/fulfillments.py
  saleor/graphql/order/schema.py
  saleor/graphql/order/tests/test_fulfillment.py
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/shop/mutations.py
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
  saleor/graphql/webhook/enums.py
  saleor/graphql/webhook/tests/test_webhook.py
  saleor/order/__init__.py
  saleor/order/actions.py
  saleor/order/error_codes.py
  saleor/order/events.py
  saleor/order/migrations/0114_auto_20210722_1146.py
  saleor/order/tests/test_fulfullments_actions.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/site/migrations/0030_auto_20210722_1141.py
  saleor/site/models.py
  saleor/tests/fixtures.py
  saleor/webhook/event_types.py
Labels: test deployment, feature branch, 3.1

#7885 Configure delete empty allocations as periodic task
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/settings.py
  saleor/warehouse/tasks.py
Labels: 3.0

#7912 Configure delete empty allocations as periodic task in 3.1
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/settings.py
  saleor/warehouse/tasks.py
Labels: 3.1, reviewed

#7920 Add missing usage of new auth header for apps
  saleor/core/auth.py
  saleor/core/auth_backend.py
  saleor/core/jwt.py
  saleor/graphql/core/tests/test_middleware.py
  saleor/graphql/middleware.py
Labels: test deployment

#7923 Add usage of new auth header for apps for 3.0
  saleor/core/auth.py
  saleor/core/auth_backend.py
  saleor/core/jwt.py
  saleor/graphql/core/tests/test_middleware.py
  saleor/graphql/middleware.py
Labels: 3.0, reviewed

#7907 Add default country to channel
  saleor/channel/migrations/0002_channel_default_country.py
  saleor/channel/migrations/0003_alter_channel_default_country.py
  saleor/channel/models.py
  saleor/graphql/channel/mutations.py
  saleor/graphql/channel/tests/fixtures.py
  saleor/graphql/channel/tests/test_channel_create_mutations.py
  saleor/graphql/channel/tests/test_channel_queries.py
  saleor/graphql/channel/tests/test_channel_update_mutations.py
  saleor/graphql/channel/types.py
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_product_channel_listings_queries.py
  saleor/graphql/product/tests/test_variant_pricing.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/warehouse/dataloaders.py
  saleor/graphql/warehouse/tests/test_dataloaders.py
  saleor/warehouse/models.py
  saleor/warehouse/tests/test_warehouse.py
Labels: test deployment, approved-breaking-change

#7590 Product variant channel listing webhooks (stocks)
  CHANGELOG.md
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/order/mutations/draft_orders.py
  saleor/graphql/order/mutations/orders.py
  saleor/graphql/order/tests/benchmark/test_fulfillment_refund_and_return_products.py
  saleor/graphql/order/tests/test_fulfillment.py
  saleor/graphql/order/tests/test_fulfillment_refund_products.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/tests/benchmark/test_variant_stocks.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/utils.py
  saleor/graphql/schema.graphql
  saleor/graphql/warehouse/mutations.py
  saleor/graphql/warehouse/tests/test_warehouse.py
  saleor/order/actions.py
  saleor/order/tests/test_fulfullments_actions.py
  saleor/order/tests/test_order.py
  saleor/order/tests/test_order_actions.py
  saleor/order/tests/test_order_utils.py
  saleor/order/utils.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/tests/fixtures.py
  saleor/warehouse/availability.py
  saleor/warehouse/management.py
  saleor/warehouse/models.py
  saleor/warehouse/tests/test_stock_management.py
  saleor/webhook/event_types.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.1

#7925 Add default country to channel
  saleor/channel/migrations/0002_channel_default_country.py
  saleor/channel/migrations/0003_alter_channel_default_country.py
  saleor/channel/models.py
  saleor/graphql/channel/mutations.py
  saleor/graphql/channel/tests/fixtures.py
  saleor/graphql/channel/tests/test_channel_create_mutations.py
  saleor/graphql/channel/tests/test_channel_queries.py
  saleor/graphql/channel/tests/test_channel_update_mutations.py
  saleor/graphql/channel/types.py
  saleor/graphql/checkout/mutations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_product_channel_listings_queries.py
  saleor/graphql/product/tests/test_variant_pricing.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/warehouse/dataloaders.py
  saleor/graphql/warehouse/tests/test_dataloaders.py
  saleor/warehouse/models.py
  saleor/warehouse/tests/test_warehouse.py
Labels: test deployment, approved-breaking-change, reviewed

#7976 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#7959 Reduce number of spans generated by PluginManager in 3.1
  saleor/plugins/manager.py
  saleor/plugins/vatlayer/plugin.py
  saleor/product/utils/availability.py
Labels: 3.1, reviewed

#7957 Reduce number of spans in plugin manager
  saleor/plugins/manager.py
  saleor/plugins/vatlayer/plugin.py
  saleor/product/utils/availability.py
Labels: 3.0

#7938 Fix fulfillments refund with waiting for approval state
  saleor/graphql/order/mutations/fulfillments.py
  saleor/graphql/order/tests/test_fulfillment_refund_products.py
Labels: test deployment

#7821 SALEOR-4122: ExternalNotificationTrigger mutation
  CHANGELOG.md
  saleor/account/notifications.py
  saleor/core/notification/__init__.py
  saleor/core/notification/mutation_handler.py
  saleor/core/notification/utils.py
  saleor/core/notification/validation.py
  saleor/core/tests/test_notification.py
  saleor/csv/notifications.py
  saleor/csv/tests/test_notifications.py
  saleor/graphql/api.py
  saleor/graphql/core/enums.py
  saleor/graphql/core/types/common.py
  saleor/graphql/core/utils/error_codes.py
  saleor/graphql/notifications/__init__.py
  saleor/graphql/notifications/error_codes.py
  saleor/graphql/notifications/mutations/__init__.py
  saleor/graphql/notifications/mutations/external_notification_trigger.py
  saleor/graphql/notifications/schema.py
  saleor/graphql/notifications/tests/__init__.py
  saleor/graphql/notifications/tests/conftest.py
  saleor/graphql/notifications/tests/test_external_notification_dispatch.py
  saleor/graphql/notifications/tests/test_external_notification_query.py
  saleor/graphql/schema.graphql
  saleor/invoice/notifications.py
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/manager.py
  saleor/plugins/sendgrid/plugin.py
  saleor/plugins/sendgrid/tasks.py
  saleor/plugins/sendgrid/tests/conftest.py
  saleor/plugins/sendgrid/tests/test_plugin.py
  saleor/plugins/user_email/plugin.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: 3.1

#7982 Fix `CheckoutByTokenLoader` for not exisitng tokens
  saleor/graphql/checkout/dataloaders.py
Labels: 3.0

#7983 Fix `CheckoutByTokenLoader` for not exisiting tokens
  saleor/graphql/checkout/dataloaders.py
Labels: 3.1, reviewed
