Repository saleor/saleor, pull requests merged in 2022-08, with the labels that each got.

#10261 Fix ORM crash when generating hundreds of search vector in SQL
  CHANGELOG.md
  saleor/account/search.py
  saleor/checkout/complete_checkout.py
  saleor/core/postgres.py
  saleor/core/search_tasks.py
  saleor/core/tests/test_postgresql_search.py
  saleor/core/utils/random_data.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/order_update.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/tests/test_pagination.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/tests/test_product.py
  saleor/order/search.py
  saleor/plugins/anonymize/plugin.py
  saleor/product/search.py
  saleor/tests/fixtures.py
Labels: bug

#10279 Limit the maximum number of search vectors to generate per index
  CHANGELOG.md
  saleor/checkout/complete_checkout.py
  saleor/core/postgres.py
  saleor/core/search_tasks.py
  saleor/core/tests/test_postgresql_search.py
  saleor/core/utils/random_data.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/order_update.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/tests/test_pagination.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/tests/test_product.py
  saleor/order/search.py
  saleor/plugins/anonymize/plugin.py
  saleor/product/search.py
  saleor/settings.py
  saleor/tests/fixtures.py
Labels: bug

#10282 Fix ORM crash when generating hundreds of search vector in SQL
  CHANGELOG.md
  saleor/account/search.py
  saleor/checkout/complete_checkout.py
  saleor/core/postgres.py
  saleor/core/search_tasks.py
  saleor/core/tests/test_postgresql_search.py
  saleor/core/utils/random_data.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/order_update.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/tests/test_pagination.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/tests/test_product.py
  saleor/order/search.py
  saleor/plugins/anonymize/plugin.py
  saleor/product/search.py
  saleor/tests/fixtures.py
Labels: bug

#10280 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
  saleor/core/utils/editorjs.py
Labels: test deployment, :robot: bot

#10284 Limit the maximum number of search vectors to generate per index
  CHANGELOG.md
  saleor/checkout/complete_checkout.py
  saleor/core/postgres.py
  saleor/core/search_tasks.py
  saleor/core/tests/test_postgresql_search.py
  saleor/core/utils/random_data.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/order_update.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/tests/test_pagination.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/tests/test_product.py
  saleor/order/search.py
  saleor/plugins/anonymize/plugin.py
  saleor/product/search.py
  saleor/settings.py
  saleor/tests/fixtures.py
Labels: bug

#10296 Fix thumbnail deletion signal
  saleor/account/signals.py
  saleor/core/tests/test_tasks.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_digital_content.py
  saleor/product/signals.py
  saleor/product/tests/test_product.py
  saleor/thumbnail/signals.py
Labels: bug

#10298 Fix variant quantity available for no channel and country code in 3.5
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/product/types/products.py
Labels: test deployment

#10297 Fix variant quantity available for no channel and country code
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/product/types/products.py
Labels: test deployment

#10303 Upgrade django to 3.2.15
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, security

#10304 Upgrade django to 3.2.15
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, security

#10305 Upgrade django to 3.2.15
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, security

#10307 Upgrade django to 3.2.15
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, security

#10308 Upgrade django to 3.2.15
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, security

#10095 Multiple copies of a single variant in the same Checkout/Order
  CHANGELOG.md
  saleor/checkout/fetch.py
  saleor/checkout/utils.py
  saleor/core/management/commands/populatedb.py
  saleor/core/utils/random_data.py
  saleor/graphql/checkout/mutations/checkout_create.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/checkout_lines_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
  saleor/graphql/checkout/tests/mutations/test_utils.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/order_line_delete.py
  saleor/graphql/order/mutations/order_lines_create.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/utils.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/schema.graphql
  saleor/order/actions.py
  saleor/order/events.py
  saleor/order/tests/test_notifications.py
  saleor/order/tests/test_order.py
  saleor/order/tests/test_order_utils.py
  saleor/order/utils.py
  saleor/tests/fixtures.py
Labels: feature branch, rfc

#10326 Fix wrong expression count in flat concatenation warnings
  saleor/core/postgres.py
Labels: bug

#10331 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#10358 Fix quantity available for stocks with cc warehouses
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/product/types/products.py
  saleor/graphql/warehouse/dataloaders.py
Labels: reviewed

#10343 Fix quantity available for stocks with cc warehouses
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/product/types/products.py
  saleor/graphql/warehouse/dataloaders.py
Labels: reviewed

#10367 Allow adding an item to the cart when there is a stock only in cc warehouse for 3.6
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/checkout_lines_update.py
  saleor/graphql/checkout/mutations/checkout_shipping_address_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
  saleor/graphql/product/tests/test_product.py
  saleor/warehouse/availability.py
  saleor/warehouse/models.py
Labels: reviewed

#10368 Allow adding an item to the cart when there is a stock only in cc warehouse
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/checkout_lines_update.py
  saleor/graphql/checkout/mutations/checkout_shipping_address_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
  saleor/graphql/product/tests/test_product.py
  saleor/warehouse/availability.py
  saleor/warehouse/models.py
Labels: reviewed

#10369 Optimize update_products_discounted_prices_of_catalogues_task
  saleor/product/utils/variant_prices.py
Labels: performance

#10371 optimize update products discounted prices of catalogues task
  saleor/product/utils/variant_prices.py
Labels: performance

#10365 Fix the variant quantityAvailable for negative stocks
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/warehouse/dataloaders.py
Labels: reviewed

#10366 Fix the variant quantityAvailable for negative stocks
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/warehouse/dataloaders.py
Labels: reviewed

#10384 Fix thumbnail url crash for id of not existsing instance
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/views.py
Labels: reviewed

#10381 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#10393 Fix assigning tax code to object meta 3.2
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/vatlayer/plugin.py
  saleor/plugins/vatlayer/tests/test_vatlayer.py
Labels: reviewed

#10394 Fix assigning tax code to object meta 3.3
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/vatlayer/plugin.py
  saleor/plugins/vatlayer/tests/test_vatlayer.py
Labels: reviewed

#10395 Fix assigning tax code to object meta 3.4
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/vatlayer/plugin.py
  saleor/plugins/vatlayer/tests/test_vatlayer.py
Labels: reviewed

#10396 Fix assigning tax code to object meta 3.5
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/vatlayer/plugin.py
  saleor/plugins/vatlayer/tests/test_vatlayer.py
Labels: reviewed

#10397 Fix assigning tax code to object meta 3.6
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/vatlayer/plugin.py
  saleor/plugins/vatlayer/tests/test_vatlayer.py
Labels: reviewed

#10398 Fix assigning tax code to object meta
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/vatlayer/plugin.py
  saleor/plugins/vatlayer/tests/test_vatlayer.py
Labels: reviewed

#10436 Mark webhook secretKey as deprecated
  saleor/graphql/schema.graphql
  saleor/graphql/webhook/mutations.py
  saleor/graphql/webhook/types.py
Labels: technical debt

#10454 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#10474 Fix search update migrations
  saleor/product/migrations/0157_update_product_search_document.py
  saleor/product/migrations/0165_update_product_search_document.py
  saleor/product/migrations/0171_product_search_index_dirty.py
Labels: bug

#10475 Fix search update migrations
  saleor/product/migrations/0157_update_product_search_document.py
  saleor/product/migrations/0165_update_product_search_document.py
  saleor/product/migrations/0171_product_search_index_dirty.py
Labels: bug

#10476 Fix search update migrations
  saleor/product/migrations/0157_update_product_search_document.py
  saleor/product/migrations/0165_update_product_search_document.py
  saleor/product/migrations/0171_product_search_index_dirty.py
Labels: bug

#10472 Fix search update migrations
  saleor/product/migrations/0157_update_product_search_document.py
  saleor/product/migrations/0165_update_product_search_document.py
  saleor/product/migrations/0171_product_search_index_dirty.py
Labels: bug

#10485 Fix typo in search vectors
  saleor/core/search_tasks.py
Labels: bug

#10486 Fix typo in search vectors
  saleor/core/search_tasks.py
Labels: bug

#10416 [RFC] Sorting warehouses within channel
  CHANGELOG.md
  saleor/channel/__init__.py
  saleor/channel/migrations/0005_channel_allocation_strategy.py
  saleor/channel/models.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/utils.py
  saleor/graphql/channel/enums.py
  saleor/graphql/channel/mutations.py
  saleor/graphql/channel/schema.py
  saleor/graphql/channel/tests/fixtures.py
  saleor/graphql/channel/tests/test_channel_create_mutations.py
  saleor/graphql/channel/tests/test_channel_queries.py
  saleor/graphql/channel/tests/test_channel_reorder_warehouses.py
  saleor/graphql/channel/tests/test_channel_update_mutations.py
  saleor/graphql/channel/types.py
  saleor/graphql/checkout/mutations/checkout_create.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/order_line_update.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/warehouse/dataloaders.py
  saleor/order/tests/test_order.py
  saleor/order/tests/test_order_utils.py
  saleor/order/utils.py
  saleor/warehouse/management.py
  saleor/warehouse/migrations/0032_alter_channel_warehouse.py
  saleor/warehouse/models.py
  saleor/warehouse/reservations.py
  saleor/warehouse/tests/test_stock_management.py
  saleor/warehouse/tests/test_stock_reservations_management.py
Labels: test deployment, rfc

#10507 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#10497 Add default country rate
  saleor/graphql/schema.graphql
  saleor/graphql/tax/mutations/tax_country_configuration_update.py
  saleor/graphql/tax/tests/mutations/test_tax_country_configuration_update.py
  saleor/graphql/tax/types.py
  saleor/product/migrations/0172_merge_20220718_1354.py
  saleor/product/migrations/0174_merge_20220809_1020.py
  saleor/product/migrations/0176_auto_20220826_0947.py
  saleor/product/migrations/0176_merge_20220817_1253.py
  saleor/shipping/migrations/0032_shippingmethod_tax_class.py
  saleor/tax/error_codes.py
  saleor/tax/migrations/0001_initial.py
  saleor/tax/models.py
Labels: approved-breaking-change

#10518 Upgrade Saleor to Django version 4.0
  .github/workflows/pytest.yml
  .github/workflows/test-migrations-compatibility.yml
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/account/migrations/0046_user_jwt_token_key.py
  saleor/account/models.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/core/auth.py
  saleor/core/exceptions.py
  saleor/core/models.py
  saleor/discount/utils.py
  saleor/graphql/account/mutations/authentication.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/mutations/test_token_create.py
  saleor/graphql/account/tests/mutations/test_token_refresh.py
  saleor/graphql/account/tests/mutations/test_tokens_deactivate_all.py
  saleor/graphql/account/utils.py
  saleor/graphql/attribute/mutations.py
  saleor/graphql/context.py
  saleor/graphql/core/__init__.py
  saleor/graphql/core/context.py
  saleor/graphql/core/dataloaders.py
  saleor/graphql/core/mutations.py
  saleor/graphql/core/tests/test_core_reordering.py
  saleor/graphql/meta/mutations.py
  saleor/graphql/page/mutations/pages.py
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/mutations/digital_contents.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/sorters.py
  saleor/graphql/shipping/utils.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/menu/models.py
  saleor/order/actions.py
  saleor/order/events.py
  saleor/payment/interface.py
  saleor/payment/utils.py
  saleor/plugins/anonymize/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/utils.py
  saleor/product/models.py
  saleor/product/utils/__init__.py
  saleor/product/utils/variants.py
  saleor/urls.py
  saleor/warehouse/management.py
  saleor/warehouse/reservations.py
  saleor/webhook/observability/tests/test_utils.py
Labels: technical debt
