Repository saleor/saleor, pull requests merged in 2022-07, with the labels that each got.

#10076 Unquote secret access when calling sqs
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
Labels: bug

#10097 Unquote secret access when calling sqs
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
Labels: bug

#10043 Improve click & collect and stock allocation
  CHANGELOG.md
  conftest.py
  saleor/checkout/fetch.py
  saleor/checkout/utils.py
  saleor/core/utils/random_data.py
  saleor/giftcard/utils.py
  saleor/graphql/channel/dataloaders.py
  saleor/graphql/channel/mutations.py
  saleor/graphql/channel/tests/benchmark/__init__.py
  saleor/graphql/channel/tests/benchmark/fixtures.py
  saleor/graphql/channel/tests/benchmark/test_channel.py
  saleor/graphql/channel/tests/test_channel_create_mutations.py
  saleor/graphql/channel/tests/test_channel_delete_mutations.py
  saleor/graphql/channel/tests/test_channel_update_mutations.py
  saleor/graphql/channel/types.py
  saleor/graphql/channel/utils.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
  saleor/graphql/core/types/common.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/types.py
  saleor/graphql/product/filters.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/mutations/shippings.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_create.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_update.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/graphql/warehouse/filters.py
  saleor/graphql/warehouse/tests/test_stock.py
  saleor/graphql/warehouse/tests/test_warehouse.py
  saleor/order/actions.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
  saleor/tests/fixtures.py
  saleor/warehouse/availability.py
  saleor/warehouse/management.py
  saleor/warehouse/migrations/0029_warehouse_channels.py
  saleor/warehouse/migrations/0030_add_channels_to_warehouses.py
  saleor/warehouse/models.py
  saleor/warehouse/tests/test_stock.py
  saleor/warehouse/tests/test_stock_management.py
  saleor/warehouse/tests/test_stock_reservations_management.py
  saleor/warehouse/tests/test_warehouse.py
  saleor/webhook/payloads.py
Labels: test deployment

#10118 Fix product media reordering
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/tests/test_product.py
Labels: test deployment

#10135 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#10102 Possibility to skip validation for checkout addresses billing part
  saleor/graphql/checkout/mutations/checkout_billing_address_update.py
  saleor/graphql/checkout/mutations/checkout_complete.py
  saleor/graphql/checkout/mutations/checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_billing_address_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/schema.graphql
Labels: test deployment

#10116 Make API not strip query params from redirect url
  saleor/core/tests/test_url.py
  saleor/core/utils/url.py
Labels: test deployment

#10178 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#10163 Add support for the CUSTOMER_* app mount points
  CHANGELOG.md
  saleor/app/migrations/0016_alter_appextension_mount.py
  saleor/app/types.py
  saleor/graphql/schema.graphql
Labels: test deployment

#10185 Fix inconsistent beat scheduling and compatibility with db scheduler
  CHANGELOG.md
  saleor/core/schedules.py
  saleor/schedulers/__init__.py
  saleor/schedulers/customschedule.py
  saleor/schedulers/migrations/0001_initial.py
  saleor/schedulers/migrations/__init__.py
  saleor/schedulers/models.py
  saleor/schedulers/schedulers.py
  saleor/settings.py
Labels: bug

#10196 Fix inconsistent beat scheduling and compatibility with db scheduler
  CHANGELOG.md
  saleor/core/schedules.py
  saleor/schedulers/__init__.py
  saleor/schedulers/customschedule.py
  saleor/schedulers/migrations/0001_initial.py
  saleor/schedulers/migrations/__init__.py
  saleor/schedulers/models.py
  saleor/schedulers/schedulers.py
  saleor/settings.py
Labels: bug

#10218 Fix stock validation and allocation for order with local collection point
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/conftest.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/tests/fixtures.py
  saleor/warehouse/availability.py
  saleor/warehouse/management.py
  saleor/warehouse/models.py
Labels: test deployment

#10225 Fix stock allocation for order with global collection point
  CHANGELOG.md
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/warehouse/management.py
Labels: test deployment

#10226 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#10227 Fix returning GraphQL IDs in the SALE_TOGGLE webhook
  saleor/discount/tasks.py
  saleor/discount/tests/test_tasks.py
  saleor/graphql/discount/mutations/utils.py
Labels: test deployment

#10232 Fix stock validation and allocation for order with local collection point for 3.5
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/conftest.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/tests/fixtures.py
  saleor/warehouse/availability.py
  saleor/warehouse/management.py
  saleor/warehouse/models.py
Labels: reviewed

#10234 Fix returning GraphQL IDs in the SALE_TOGGLE webhook for 3.5
  saleor/discount/tasks.py
  saleor/discount/tests/test_tasks.py
  saleor/graphql/discount/mutations/utils.py
Labels: reviewed

#10233 Fix stock allocation for order with global collection point for 3.5
  CHANGELOG.md
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/warehouse/management.py
Labels: reviewed

#10199 Optimize filtering attributes by dates
  saleor/graphql/product/filters.py
  saleor/graphql/product/tests/test_product.py
  saleor/product/tests/test_product.py
Labels: performance

#10111 Display only shippable countries for a channel
  saleor/graphql/channel/resolvers.py
  saleor/graphql/channel/schema.py
  saleor/graphql/channel/tests/test_channel_queries.py
  saleor/graphql/channel/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/dataloaders.py
  saleor/graphql/shipping/types.py
Labels: test deployment

#10253 Use custom search vector in order search
  saleor/account/search.py
  saleor/core/postgres.py
  saleor/order/search.py
  saleor/product/search.py
Labels: reviewed
