Repository saleor/saleor, pull requests merged in 2022-11, with the labels that each got.

#11118 Bump cryptography to 38.0.3: use OpenSSL 3.0.7
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.1

#11119 Bump cryptography to 38.0.3: use OpenSSL 3.0.7
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.2

#11120 Bump cryptography to 38.0.3: use OpenSSL 3.0.7
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.3

#11121 Bump cryptography to 38.0.3: use OpenSSL 3.0.7
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.4

#11122 Bump cryptography to 38.0.3: use OpenSSL 3.0.7
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.5

#11123 Bump cryptography to 38.0.3: use OpenSSL 3.0.7
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.6

#11124 Bump cryptography to 38.0.3: use OpenSSL 3.0.7
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.7

#11125 Bump cryptography to 38.0.3: use OpenSSL 3.0.7
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.8

#11126 Bump cryptography to 38.0.3: use OpenSSL 3.0.7
  CHANGELOG.md
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, main

#11106 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#11102 Fix generate_payment_payload function when refund data is provided
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: main

#11127 Bump dependencies for origin/SALEOR-6391-simple-taxes
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies

#11128 Various small fixes
  .editorconfig
  .isort.cfg
  .vscode/settings.json
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/core/utils/__init__.py
  saleor/core/utils/random_data.py
  saleor/graphql/core/tests/test_core.py
  saleor/graphql/core/utils/__init__.py
  saleor/graphql/core/validators/query_cost.py
  setup.cfg
Labels: technical debt

#11153 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#11139 Prevent multiple `checkoutPaymentCreate` calls and creating an order for inactive payment
  saleor/checkout/complete_checkout.py
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/tests/test_checkout_complete.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_payment_create.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: 3.1

#11164 Replace synchronous load_site with promise
  saleor/graphql/checkout/mutations/checkout_complete.py
  saleor/graphql/checkout/mutations/checkout_create.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/checkout_lines_update.py
  saleor/graphql/checkout/mutations/checkout_shipping_address_update.py
  saleor/graphql/checkout/types.py
  saleor/graphql/menu/mutations.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/fulfillment_approve.py
  saleor/graphql/order/mutations/order_capture.py
  saleor/graphql/order/mutations/order_confirm.py
  saleor/graphql/order/mutations/order_fulfill.py
  saleor/graphql/order/mutations/order_line_discount_remove.py
  saleor/graphql/order/mutations/order_line_discount_update.py
  saleor/graphql/order/mutations/order_lines_create.py
  saleor/graphql/order/types.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shop/mutations.py
  saleor/graphql/shop/schema.py
  saleor/graphql/shop/types.py
  saleor/graphql/site/dataloaders.py
  saleor/graphql/translations/mutations.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/graphql/warehouse/types.py
Labels: 3.8

#11028 Add `attribute` field to `AttributeValueTranslatableContent` type
  CHANGELOG.md
  saleor/graphql/core/descriptions.py
  saleor/graphql/schema.graphql
  saleor/graphql/translations/tests/test_translations.py
  saleor/graphql/translations/types.py
Labels: test deployment

#11168 Remove stock rows from lock during checkoutComplete
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/graphql/checkout/mutations/checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/settings.py
Labels: 3.7

#11169 Remove stock rows from lock during checkoutComplete
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/graphql/checkout/mutations/checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/settings.py
Labels: 3.8

#11171 Prevent multiple `checkoutPaymentCreate` calls and creating an order for inactive payment
  saleor/checkout/complete_checkout.py
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/tests/test_checkout_complete.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: 3.4

#11174 Prevent multiple `checkoutPaymentCreate` calls and creating an order for inactive payment
  saleor/checkout/complete_checkout.py
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: 3.5

#11176 Prevent multiple `checkoutPaymentCreate` calls and creating an order for inactive payment
  saleor/checkout/complete_checkout.py
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: 3.6

#11177 Prevent multiple `checkoutPaymentCreate` calls and creating an order for inactive payment
  saleor/checkout/complete_checkout.py
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: 3.7

#11180 Prevent multiple `checkoutPaymentCreate` calls and creating an order for inactive payment
  saleor/checkout/complete_checkout.py
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: 3.8

#11175 Optimize memory usage of delete_expired_checkouts task
  saleor/checkout/tasks.py
Labels: performance

#11194 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#11201 Update image validation
  saleor/graphql/core/tests/test_core.py
  saleor/graphql/core/utils/__init__.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_product.py
  saleor/product/tests/utils.py
  saleor/thumbnail/__init__.py
Labels: 3.6

#11200 Update image validation
  saleor/graphql/core/tests/test_core.py
  saleor/graphql/core/utils/__init__.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_product.py
  saleor/product/tests/utils.py
  saleor/thumbnail/__init__.py
Labels: 3.7

#11199 Update image validation
  saleor/graphql/core/tests/test_core.py
  saleor/graphql/core/utils/__init__.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_product.py
  saleor/product/tests/utils.py
  saleor/thumbnail/__init__.py
Labels: 3.8

#11198 Add changelog checker to github workflows
  .github/workflows/changelog-check.yml
Labels: skip changelog

#11215 Optimize memory usage of delete_expired_checkouts task
  saleor/checkout/tasks.py
Labels: performance, 3.2

#11216 Optimize memory usage of delete_expired_checkouts task
  saleor/checkout/tasks.py
Labels: performance, 3.1

#11214 Optimize memory usage of delete_expired_checkouts task
  saleor/checkout/tasks.py
Labels: performance, 3.3

#11213 Optimize memory usage of delete_expired_checkouts task
  saleor/checkout/tasks.py
Labels: performance, 3.4

#11211 Optimize memory usage of delete_expired_checkouts task
  saleor/checkout/tasks.py
Labels: performance, 3.6

#11210 Optimize memory usage of delete_expired_checkouts task
  saleor/checkout/tasks.py
Labels: performance, 3.7

#11209 Optimize memory usage of delete_expired_checkouts task
  saleor/checkout/tasks.py
Labels: performance, 3.8

#11217 Optimize order image payload generation
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
Labels: 3.8

#11218 Optimize order image payload generation
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
Labels: 3.7

#11220 Optimize order image payload generation
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
Labels: skip changelog

#11221 Remove maxminddb
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: technical debt

#11222 Move the test file to the tests directory
  saleor/graphql/tests/test_middleware.py
Labels: technical debt

#11232 Optimize high IOPS on attributeValueUpdate
  saleor/graphql/attribute/mutations/attribute_value_update.py
Labels: performance

#11234 Optimize disk IOPS on attribute value update
  saleor/graphql/attribute/mutations.py
  saleor/graphql/attribute/utils.py
Labels: performance, 3.8

#11235 Optimize disk IOPS on attribute value update
  saleor/graphql/attribute/mutations.py
  saleor/graphql/attribute/utils.py
Labels: performance, 3.7

#11236 Optimize disk IOPS on attribute value update
  saleor/graphql/attribute/mutations.py
  saleor/graphql/attribute/utils.py
Labels: performance, 3.6

#11237 Optimize disk IOPS on attribute value update
  saleor/graphql/attribute/mutations.py
  saleor/graphql/attribute/utils.py
Labels: performance, 3.5

#11238 Optimize disk IOPS on attribute value update
  saleor/graphql/attribute/mutations.py
  saleor/graphql/attribute/utils.py
Labels: performance, 3.4

#11244 Reverte api changes for `checkoutLinesAdd.lines` and `PageFilterInput.ids`
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/core/types/filter_input.py
  saleor/graphql/schema.graphql
Labels: 3.5

#11240 Fix duplicated stock when calculate available quantity
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/warehouse/dataloaders.py
Labels: 3.6

#11241 Fix duplicated stock when calculate available quantity
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/warehouse/dataloaders.py
Labels: 3.7

#11242 Fix duplicated stock when calculate available quantity
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/warehouse/dataloaders.py
Labels: 3.8

#11243 Fix duplicated stock when calculate available quantity
  saleor/graphql/product/tests/test_variant_availability.py
  saleor/graphql/warehouse/dataloaders.py
Labels: skip changelog

#11253 Revert api changes for `checkoutLinesAdd.lines` and `PageFilterInput.ids`
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/core/types/filter_input.py
  saleor/graphql/schema.graphql
Labels: 3.4

#11254 Revert api changes for `checkoutLinesAdd.lines` and `PageFilterInput.ids`
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/core/types/filter_input.py
  saleor/graphql/schema.graphql
Labels: 3.3

#11255 Revert api changes for `checkoutLinesAdd.lines` and `PageFilterInput.ids`
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/core/types/filter_input.py
  saleor/graphql/schema.graphql
Labels: 3.2

#11262 Add exif image validation
  saleor/graphql/account/mutations/staff.py
  saleor/graphql/attribute/mutations.py
  saleor/graphql/core/tests/test_core.py
  saleor/graphql/core/tests/test_file_upload.py
  saleor/graphql/core/tests/test_file_validation.py
  saleor/graphql/core/tests/test_validators.py
  saleor/graphql/core/utils/__init__.py
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/core/validators/file.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/menu/mutations.py
  saleor/graphql/order/mutations/order_add_note.py
  saleor/graphql/page/mutations/pages.py
  saleor/graphql/product/mutations/product_type_create.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/warehouse/mutations.py
  saleor/product/tests/utils.py
Labels: 3.8

#11271 Add exif image validation
  saleor/graphql/account/mutations/staff.py
  saleor/graphql/attribute/mutations.py
  saleor/graphql/core/tests/test_core.py
  saleor/graphql/core/tests/test_file_upload.py
  saleor/graphql/core/tests/test_file_validation.py
  saleor/graphql/core/tests/test_validators.py
  saleor/graphql/core/utils/__init__.py
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/core/validators/file.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/menu/mutations.py
  saleor/graphql/order/mutations/order_add_note.py
  saleor/graphql/page/mutations/pages.py
  saleor/graphql/product/mutations/product_type_create.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/warehouse/mutations.py
  saleor/product/tests/utils.py
Labels: 3.7

#11272 Add exif image validation
  saleor/graphql/account/mutations/staff.py
  saleor/graphql/attribute/mutations.py
  saleor/graphql/core/tests/test_core.py
  saleor/graphql/core/tests/test_file_upload.py
  saleor/graphql/core/tests/test_file_validation.py
  saleor/graphql/core/tests/test_validators.py
  saleor/graphql/core/utils/__init__.py
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/core/validators/file.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/menu/mutations.py
  saleor/graphql/order/mutations/order_add_note.py
  saleor/graphql/page/mutations/pages.py
  saleor/graphql/product/mutations/product_type_create.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/warehouse/mutations.py
  saleor/product/tests/utils.py
Labels: 3.6

#11279 Fix error code for `collectionCreate` mutation
  saleor/graphql/product/mutations/products.py
Labels: 3.8

#11280 Fix error code for `collectionCreate` mutation
  saleor/graphql/product/mutations/products.py
Labels: 3.7

#11281 Fix error code for `collectionCreate` mutation
  saleor/graphql/product/mutations/products.py
Labels: 3.6

#11278 Fix plugin configuration
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/plugins/base_plugin.py
  saleor/tax/migrations/0002_add_default_tax_configs.py
Labels: skip changelog

#11259 Split product types and mutations
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/mutations/__init__.py
  saleor/graphql/product/mutations/category/__init__.py
  saleor/graphql/product/mutations/category/category_create.py
  saleor/graphql/product/mutations/category/category_delete.py
  saleor/graphql/product/mutations/category/category_update.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/mutations/collection/__init__.py
  saleor/graphql/product/mutations/collection/collection_add_products.py
  saleor/graphql/product/mutations/collection/collection_create.py
  saleor/graphql/product/mutations/collection/collection_delete.py
  saleor/graphql/product/mutations/collection/collection_remove_products.py
  saleor/graphql/product/mutations/collection/collection_reorder_products.py
  saleor/graphql/product/mutations/collection/collection_update.py
  saleor/graphql/product/mutations/product/__init__.py
  saleor/graphql/product/mutations/product/product_create.py
  saleor/graphql/product/mutations/product/product_delete.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/graphql/product/mutations/product/product_media_delete.py
  saleor/graphql/product/mutations/product/product_media_reorder.py
  saleor/graphql/product/mutations/product/product_media_update.py
  saleor/graphql/product/mutations/product/product_update.py
  saleor/graphql/product/mutations/product_type/__init__.py
  saleor/graphql/product/mutations/product_type/product_type_create.py
  saleor/graphql/product/mutations/product_type/product_type_delete.py
  saleor/graphql/product/mutations/product_type/product_type_update.py
  saleor/graphql/product/mutations/product_variant/__init__.py
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/graphql/product/mutations/product_variant/product_variant_delete.py
  saleor/graphql/product/mutations/product_variant/product_variant_preorder_deactivate.py
  saleor/graphql/product/mutations/product_variant/product_variant_reorder.py
  saleor/graphql/product/mutations/product_variant/product_variant_set_default.py
  saleor/graphql/product/mutations/product_variant/product_variant_update.py
  saleor/graphql/product/mutations/product_variant/variant_media_assign.py
  saleor/graphql/product/mutations/product_variant/variant_media_unassign.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/mutations/test_product_media_reorder.py
  saleor/graphql/product/tests/mutations/test_product_variant_preorder_deactivate.py
  saleor/graphql/product/tests/test_product_discounted_price.py
  saleor/graphql/product/types/__init__.py
  saleor/graphql/product/types/categories.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/translations/types.py
  saleor/graphql/webhook/subscription_types.py
Labels: skip changelog

#11288 Fix updating plugin configuration
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/plugins/base_plugin.py
Labels: 3.8

#11289 Fix updating plugin configuration
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/plugins/base_plugin.py
Labels: 3.7

#11290 Fix updating plugin configuration
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/plugins/base_plugin.py
Labels: 3.6

#11291 Fix updating plugin configuration
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/plugins/base_plugin.py
Labels: 3.5

#11292 Fix updating plugin configuration
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/plugins/base_plugin.py
Labels: 3.4

#11293 Fix updating plugin configuration
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/plugins/base_plugin.py
Labels: 3.3

#11294 Fix updating plugin configuration
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/plugins/base_plugin.py
Labels: 3.2

#11295 Fix updating plugin configuration
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/plugins/base_plugin.py
Labels: 3.1

#11296 add schemaVersion field to Shop type
  CHANGELOG.md
  saleor/graphql/schema.graphql
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
  saleor/order/utils.py
Labels: 3.5

#11297 add schemaVersion field to Shop type
  CHANGELOG.md
  saleor/graphql/schema.graphql
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
Labels: 3.6

#11298 add schemaVersion field to Shop type
  CHANGELOG.md
  saleor/graphql/schema.graphql
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
Labels: 3.7

#11299 add schemaVersion field to Shop type
  CHANGELOG.md
  saleor/graphql/schema.graphql
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
Labels: 3.8

#11300 Include fully qualified API URL in communication between Saleor and Apps
  saleor/app/headers.py
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/plugins/webhook/tests/utils.py
Labels: 3.8

#11301 Include fully qualified API URL in communication between Saleor and Apps
  saleor/app/headers.py
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/plugins/webhook/tests/utils.py
Labels: 3.7

#11302 Include fully qualified API URL in communication between Saleor and Apps
  saleor/app/headers.py
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/core/utils/__init__.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/plugins/webhook/tests/utils.py
Labels: 3.6

#11303 Include fully qualified API URL in communication between Saleor and Apps
  saleor/app/headers.py
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/core/utils/__init__.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
Labels: 3.5

#11308 add schemaVersion field to Shop type (#11296)
  saleor/graphql/schema.graphql
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
Labels: 3.4

#11309 add schemaVersion field to Shop type (#11296)
  saleor/graphql/schema.graphql
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
Labels: 3.3

#11311 add schemaVersion field to Shop type (#11296)
  saleor/graphql/schema.graphql
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
Labels: 3.2

#11312 add schemaVersion field to Shop type (#11296)
  saleor/graphql/schema.graphql
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
Labels: 3.1

#11226 Order app structure improvement
  saleor/graphql/order/tests/mutations/__init__.py
  saleor/graphql/order/tests/mutations/test_draft_order_bulk_delete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_delete.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/tests/mutations/test_fulfillment.py
  saleor/graphql/order/tests/mutations/test_fulfillment_refund_products.py
  saleor/graphql/order/tests/mutations/test_fulfillment_return_products.py
  saleor/graphql/order/tests/mutations/test_order_add_note.py
  saleor/graphql/order/tests/mutations/test_order_bulk_cancel.py
  saleor/graphql/order/tests/mutations/test_order_cancel.py
  saleor/graphql/order/tests/mutations/test_order_capture.py
  saleor/graphql/order/tests/mutations/test_order_confirm.py
  saleor/graphql/order/tests/mutations/test_order_discount.py
  saleor/graphql/order/tests/mutations/test_order_line_delete.py
  saleor/graphql/order/tests/mutations/test_order_line_update.py
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/graphql/order/tests/mutations/test_order_mark_as_paid.py
  saleor/graphql/order/tests/mutations/test_order_price_expiration.py
  saleor/graphql/order/tests/mutations/test_order_refund.py
  saleor/graphql/order/tests/mutations/test_order_update.py
  saleor/graphql/order/tests/mutations/test_order_update_shipping.py
  saleor/graphql/order/tests/mutations/test_order_void.py
  saleor/graphql/order/tests/queries/__init__.py
  saleor/graphql/order/tests/queries/test_draft_order.py
  saleor/graphql/order/tests/queries/test_draft_order_with_filter.py
  saleor/graphql/order/tests/queries/test_draft_order_with_sort.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/tests/queries/test_order_by_token.py
  saleor/graphql/order/tests/queries/test_order_can_finalize.py
  saleor/graphql/order/tests/queries/test_order_events.py
  saleor/graphql/order/tests/queries/test_order_get_variants.py
  saleor/graphql/order/tests/queries/test_order_invoices.py
  saleor/graphql/order/tests/queries/test_order_line.py
  saleor/graphql/order/tests/queries/test_order_payment_event.py
  saleor/graphql/order/tests/queries/test_order_shipping_method.py
  saleor/graphql/order/tests/queries/test_order_tax.py
  saleor/graphql/order/tests/queries/test_order_with_filter.py
  saleor/graphql/order/tests/queries/test_order_with_sort.py
  saleor/graphql/order/tests/queries/test_pagination.py
  saleor/graphql/order/tests/test_draft_order_validate.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/tests/test_order_clean.py
  saleor/graphql/order/tests/test_order_payment.py
  saleor/graphql/order/tests/utils.py
  saleor/tests/fixtures.py
Labels: skip changelog

#11287 Add plugin manager promise
  saleor/graphql/app/dataloaders.py
  saleor/graphql/order/types.py
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/product/types/products.py
Labels: 3.8

#11331 Fix fetching excluded shipping methods
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.8

#11327 Fix cleaning manifest data during app instalation
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: skip changelog

#11335 Fix fetching excluded shipping methods
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.6

#11334 Fix fetching excluded shipping methods
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.7

#11350 Fix product availability
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/warehouse/dataloaders.py
Labels: 3.6

#11356 Fix product availability
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/order/utils.py
Labels: 3.5

#11353 Fix product availability
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/warehouse/dataloaders.py
Labels: 3.7

#11354 Fix product availability
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/warehouse/dataloaders.py
Labels: 3.8

#11355 Fix product availability
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/warehouse/dataloaders.py
Labels: skip changelog

#11339 Fix cleaning manifest data during app instalation
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.8

#11340 Fix cleaning manifest data during app instalation
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.7

#11341 Fix cleaning manifest data during app instalation
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.6

#11344 Fix cleaning manifest data during app instalation
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.4

#11345 Fix cleaning manifest data during app instalation
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.3

#11346 Fix cleaning manifest data during app instalation
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.2

#11347 Fix cleaning manifest data during app instalation
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.1

#11342 Fix cleaning manifest data during app instalation
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.5
