Repository saleor/saleor, pull requests merged in 2022-05, with the labels that each got.

#9674 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#9622 Improve warehouse filtering performance
  saleor/account/migrations/0065_address_warehouse_address_search_gin.py
  saleor/account/models.py
  saleor/graphql/core/tests/test_graphql.py
  saleor/graphql/utils/filters.py
  saleor/graphql/warehouse/filters.py
  saleor/graphql/warehouse/types.py
Labels: performance

#9707 Add dataloader for FulfillmentLines
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/order/dataloaders.py
  saleor/graphql/order/types.py
Labels: performance

#9720 Bump dependencies
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: test deployment

#9776 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#9726 Improved metadata permissions for apps
  saleor/core/jwt.py
  saleor/core/tests/test_jwt.py
  saleor/graphql/app/resolvers.py
  saleor/graphql/app/schema.py
  saleor/graphql/app/tests/queries/test_app.py
  saleor/graphql/app/tests/queries/test_apps.py
  saleor/graphql/app/types.py
  saleor/graphql/context.py
  saleor/graphql/core/fields.py
  saleor/graphql/meta/permissions.py
  saleor/graphql/meta/tests/test_meta_mutations.py
  saleor/graphql/schema.graphql
Labels: test deployment

#9819 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#9850 Bump pyjwt to 2.4.0 - main
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies

#9851 Bump pyjwt to 2.4.0 - 3.3
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies

#9853 Bump pyjwt to 2.4.0
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.1

#9855 Optimize memory usage on update products search vector - 3.3
  saleor/core/search_tasks.py
  saleor/product/search.py
Labels: performance

#9795 Add new fields to Order type to show authorize/charge statuses
  CHANGELOG.md
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/graphql/checkout/tests/test_checkout_complete.py
  saleor/graphql/order/enums.py
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/order/types.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/schema.graphql
  saleor/order/__init__.py
  saleor/order/actions.py
  saleor/order/migrations/0148_auto_20220519_1118.py
  saleor/order/migrations/0149_add_fields_for_authorize_and_charge.py
  saleor/order/migrations/0150_update_authorize_and_charge_status.py
  saleor/order/models.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
  saleor/payment/tests/test_payment.py
  saleor/payment/utils.py
Labels: test deployment
