Repository saleor/saleor, pull requests merged in 2022-06, with the labels that each got.

#9929 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
  saleor/order/utils.py
Labels: test deployment, :robot: bot

#9944 Disable query counter steps on forked repositories
  .github/workflows/pytest.yml
Labels: bug

#9905 Fix returning errors in payloads from subscription webhooks.
  CHANGELOG.md
  saleor/__init__.py
  saleor/graphql/tests/fixtures.py
  saleor/graphql/utils/__init__.py
  saleor/graphql/views.py
  saleor/graphql/webhook/subscription_payload.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/settings.py
Labels: test deployment

#9951 Optimize 0139_fulfil_orderline_token_old_id_created_at migration
  saleor/checkout/migrations/0044_fulfill_checkout_line_new_fields.py
  saleor/order/migrations/0139_fulfil_orderline_token_old_id_created_at.py
Labels: performance

#9990 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#9998 Fix invalid undiscounted total on order line
  saleor/order/tests/test_order_utils.py
  saleor/order/utils.py
Labels: reviewed

#9997 Fix invalid undiscounted total on order line
  saleor/order/tests/test_order_utils.py
  saleor/order/utils.py
Labels: reviewed

#10013 Add data migration for fixing invalid undiscounted total on order lines
  saleor/order/__init__.py
  saleor/order/app.py
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
  saleor/order/migrations/0151_merge_20220615_1224.py
  saleor/order/migrations/0153_merge_20220615_1232.py
Labels: reviewed

#10041 Move send order updated task outside migration in 3.4
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
  saleor/order/tasks.py
Labels: reviewed

#10032 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#10042 Move send_order_updated task outside migration in main
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
  saleor/order/tasks.py
Labels: reviewed

#10009 Optimize 0041_fulfill_orderdiscount_token_created_at_old_id migration
  saleor/discount/migrations/0041_fulfill_orderdiscount_token_created_at_old_id.py
Labels: performance

#10064 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot
