Repository saleor/saleor, pull requests merged in 2022-04, with the labels that each got.

#9388 Switch payload ids from DB's to Graphql
  CHANGELOG.md
  saleor/account/notifications.py
  saleor/account/tests/test_notifications.py
  saleor/csv/notifications.py
  saleor/giftcard/notifications.py
  saleor/giftcard/tests/test_notifications.py
  saleor/graphql/core/utils/__init__.py
  saleor/graphql/invoice/tests/test_send_invoice_notification.py
  saleor/graphql/order/tests/test_order.py
  saleor/invoice/notifications.py
  saleor/invoice/tests/test_notifications.py
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/order/tests/test_order.py
  saleor/plugins/admin_email/tasks.py
  saleor/plugins/sendgrid/tasks.py
  saleor/plugins/sendgrid/tests/test_tasks.py
  saleor/plugins/user_email/tasks.py
  saleor/plugins/user_email/tests/test_tasks.py
Labels: 3.2

#9467 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#9516 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#9534 Drop distinct and icontains in favor of ilike in apps filtering
  saleor/graphql/app/filters.py
Labels: performance

#9535 Refactor csv filters to improve performance
  saleor/graphql/csv/filters.py
Labels: performance

#9542 Improve attributes filters performance
  saleor/graphql/attribute/filters.py
Labels: performance

#9541 Improve discount filters performance
  saleor/graphql/discount/filters.py
Labels: bug, performance

#9539 Improve menus filtering performance
  saleor/graphql/menu/filters.py
Labels: performance

#9540 Improve shipping zone filters performance
  saleor/graphql/shipping/filters.py
Labels: performance

#9554 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#9573 Fix for raising Permission Denied when Anonymous user calls checkout.customer field
  CHANGELOG.md
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
Labels: test deployment

#9569 Use error code checkout_not_found for mutation order create from checkout
  CHANGELOG.md
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/mutations/order_create_from_checkout.py
  saleor/graphql/core/mutations.py
  saleor/graphql/schema.graphql
Labels: test deployment

#9572 Optimize stock warehouse resolver performance
  saleor/graphql/warehouse/types.py
Labels: performance

#9611 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot

#9344 Full-text search for products
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements_dev.txt
  saleor/core/management/commands/update_search_indexes.py
  saleor/core/search_tasks.py
  saleor/core/tests/test_postgresql_search.py
  saleor/core/utils/random_data.py
  saleor/graphql/attribute/bulk_mutations.py
  saleor/graphql/attribute/mutations.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_delete.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_update.py
  saleor/graphql/attribute/tests/mutations/test_bulk_delete.py
  saleor/graphql/core/connection.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/mutations/attributes.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/sorters.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_product.py
  saleor/graphql/product/tests/test_variant.py
  saleor/graphql/schema.graphql
  saleor/order/migrations/0130_save_order_token_in_relation_models.py
  saleor/order/migrations/0134_rewrite_order_gift_cards_relation.py
  saleor/product/migrations/0164_auto_20220311_1430.py
  saleor/product/migrations/0165_update_product_search_document.py
  saleor/product/models.py
  saleor/product/search.py
  saleor/product/tests/test_product_search.py
  saleor/tests/fixtures.py
Labels: test deployment
