Repository saleor/saleor, pull requests merged in 2022-12, with the labels that each got.

#11362 Fix failing save on stripe plugin
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/base_plugin.py
  saleor/plugins/tests/test_plugins.py
Labels: skip changelog

#11363 Fix failing save on stripe plugin
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/base_plugin.py
  saleor/plugins/tests/test_plugins.py
Labels: 3.1

#11364 Fix failing save on stripe plugin
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/base_plugin.py
  saleor/plugins/tests/test_plugins.py
Labels: 3.2

#11365 Fix failing save on stripe plugin
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/base_plugin.py
  saleor/plugins/tests/test_plugins.py
Labels: 3.3

#11367 Fix failing save on stripe plugin
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/base_plugin.py
  saleor/plugins/tests/test_plugins.py
Labels: 3.4

#11370 Fix failing save on stripe plugin
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/base_plugin.py
  saleor/plugins/tests/test_plugins.py
Labels: 3.7

#11375 Add default tax calculation strategy
  saleor/checkout/calculations.py
  saleor/checkout/tests/test_calculations.py
  saleor/graphql/tax/tests/queries/test_tax_configurations.py
  saleor/graphql/tax/types.py
  saleor/tax/migrations/0006_alter_taxconfiguration_tax_calculation_strategy.py
  saleor/tax/models.py
Labels: skip changelog

#11374 Fix typo in admin email templates
  saleor/plugins/admin_email/default_email_templates/export_failed.html
  saleor/plugins/admin_email/default_email_templates/export_success.html
  saleor/plugins/admin_email/default_email_templates/password_reset.html
  saleor/plugins/admin_email/default_email_templates/set_password.html
  saleor/plugins/admin_email/default_email_templates/staff_confirm_order.html
Labels: skip changelog

#11376 Fix method for getting image thumbnail
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: skip changelog

#11387 Fix invalid get_product_image_thumbnail email common method
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: 3.6

#11385 Fix invalid get_product_image_thumbnail email common method
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: 3.8

#11386 Fix invalid get_product_image_thumbnail email common method
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: 3.7

#11377 Fix typo in admin email templates
  saleor/plugins/admin_email/default_email_templates/export_failed.html
  saleor/plugins/admin_email/default_email_templates/export_success.html
  saleor/plugins/admin_email/default_email_templates/password_reset.html
  saleor/plugins/admin_email/default_email_templates/set_password.html
  saleor/plugins/admin_email/default_email_templates/staff_confirm_order.html
Labels: 3.8

#11397 Fix calculating order `undiscounted_total` price
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
Labels: test deployment, 3.8

#11398 Fix calculating order `undiscounted_total` price
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
Labels: 3.7

#11401 Fix calculating order `undiscounted_total` price
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
Labels: 3.6

#11402 Fix calculating order `undiscounted_total` price
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
Labels: 3.5

#11408 Fix calculating order `undiscounted_total` price
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
Labels: 3.9

#11409 Fix calculating order `undiscounted_total` price
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
Labels: skip changelog

#11389 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#11404 Fix calculating order `undiscounted_total` price
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/test_checkout_complete.py
  saleor/tests/fixtures.py
Labels: 3.3

#11411 Update query cost for attribute values
  saleor/graphql/query_cost_map.py
Labels: skip changelog

#11429 Update query cost for attribute values
  saleor/graphql/query_cost_map.py
Labels: 3.1

#11421 Update query cost for attribute values
  saleor/graphql/query_cost_map.py
Labels: 3.9

#11422 Update query cost for attribute values
  saleor/graphql/query_cost_map.py
Labels: 3.8

#11423 Update query cost for attribute values
  saleor/graphql/query_cost_map.py
Labels: 3.7

#11424 Update query cost for attribute values
  saleor/graphql/query_cost_map.py
Labels: 3.6

#11426 Update query cost for attribute values
  saleor/graphql/query_cost_map.py
Labels: 3.4

#11427 Update query cost for attribute values
  saleor/graphql/query_cost_map.py
Labels: 3.3

#11428 Update query cost for attribute values
  saleor/graphql/query_cost_map.py
Labels: 3.2

#11360 Fix filtering by numeric values
  saleor/graphql/product/filters.py
  saleor/graphql/product/tests/test_product.py
Labels: test deployment, 3.6

#11366 Handle providing empty strings as `lte` and `gte` date type
  saleor/graphql/attribute/types.py
  saleor/graphql/core/scalars.py
  saleor/graphql/core/tests/test_scalars.py
  saleor/graphql/core/types/common.py
  saleor/graphql/giftcard/bulk_mutations.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/giftcard/types.py
  saleor/graphql/order/tests/queries/test_draft_order_with_filter.py
  saleor/graphql/page/types.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/mutations/collection/collection_create.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
Labels: skip changelog

#11435 Fix filtering by numeric values
  saleor/graphql/product/filters.py
  saleor/graphql/product/tests/test_product.py
Labels: 3.5

#11434 Fix filtering by numeric values
  saleor/graphql/product/filters.py
  saleor/graphql/product/tests/test_product.py
Labels: 3.7

#11436 Fix filtering by numeric values
  saleor/graphql/product/filters.py
  saleor/graphql/product/tests/test_product.py
Labels: 3.8

#11439 Handle providing empty strings as `lte` and `gte` date type
  saleor/graphql/attribute/types.py
  saleor/graphql/core/scalars.py
  saleor/graphql/core/tests/test_scalars.py
  saleor/graphql/core/types/common.py
  saleor/graphql/giftcard/bulk_mutations.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/giftcard/types.py
  saleor/graphql/order/tests/queries/test_draft_order_with_filter.py
  saleor/graphql/page/types.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/mutations/collection/collection_create.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
Labels: 3.9

#11431 Replace usage of load_app with promise of app
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/mutations/permission_group.py
  saleor/graphql/account/mutations/staff.py
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/schema.py
  saleor/graphql/account/types.py
  saleor/graphql/account/utils.py
  saleor/graphql/app/dataloaders.py
  saleor/graphql/app/schema.py
  saleor/graphql/app/types.py
  saleor/graphql/checkout/mutations/checkout_complete.py
  saleor/graphql/checkout/mutations/checkout_create.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/checkout_lines_update.py
  saleor/graphql/checkout/mutations/order_create_from_checkout.py
  saleor/graphql/context.py
  saleor/graphql/csv/mutations.py
  saleor/graphql/giftcard/bulk_mutations.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/invoice/mutations.py
  saleor/graphql/meta/permissions.py
  saleor/graphql/order/bulk_mutations/orders.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/fulfillment_approve.py
  saleor/graphql/order/mutations/fulfillment_cancel.py
  saleor/graphql/order/mutations/fulfillment_refund_products.py
  saleor/graphql/order/mutations/fulfillment_return_products.py
  saleor/graphql/order/mutations/fulfillment_update_tracking.py
  saleor/graphql/order/mutations/order_add_note.py
  saleor/graphql/order/mutations/order_cancel.py
  saleor/graphql/order/mutations/order_capture.py
  saleor/graphql/order/mutations/order_confirm.py
  saleor/graphql/order/mutations/order_discount_add.py
  saleor/graphql/order/mutations/order_discount_delete.py
  saleor/graphql/order/mutations/order_discount_update.py
  saleor/graphql/order/mutations/order_fulfill.py
  saleor/graphql/order/mutations/order_line_delete.py
  saleor/graphql/order/mutations/order_line_discount_remove.py
  saleor/graphql/order/mutations/order_line_discount_update.py
  saleor/graphql/order/mutations/order_line_update.py
  saleor/graphql/order/mutations/order_lines_create.py
  saleor/graphql/order/mutations/order_mark_as_paid.py
  saleor/graphql/order/mutations/order_refund.py
  saleor/graphql/order/mutations/order_void.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/webhook/mutations.py
  saleor/graphql/webhook/resolvers.py
  saleor/graphql/webhook/schema.py
Labels: 3.8

#11446 Bump certifi to 2022.12.07
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.1

#11447 Bump certifi to 2022.12.07
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.2

#11448 Bump certifi to 2022.12.07
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.3

#11449 Bump certifi to 2022.12.07
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.4

#11451 Bump certifi to 2022.12.07
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.6

#11452 Bump certifi to 2022.12.07
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.7

#11453 Bump certifi to 2022.12.07
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.8

#11455 Bump certifi to 2022.12.07
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, main

#11454 Bump certifi to 2022.12.07
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.9

#11444 Handle providing empty strings as `lte` and `gte` date type
  saleor/graphql/attribute/types.py
  saleor/graphql/core/scalars.py
  saleor/graphql/core/tests/test_scalars.py
  saleor/graphql/core/types/common.py
  saleor/graphql/giftcard/bulk_mutations.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/giftcard/types.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/page/types.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
Labels: 3.5

#11442 Handle providing empty strings as `lte` and `gte` date type
  saleor/graphql/attribute/types.py
  saleor/graphql/core/scalars.py
  saleor/graphql/core/tests/test_scalars.py
  saleor/graphql/core/types/common.py
  saleor/graphql/giftcard/bulk_mutations.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/giftcard/types.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/page/types.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
Labels: 3.6

#11441 Handle providing empty strings as `lte` and `gte` date type
  saleor/graphql/attribute/types.py
  saleor/graphql/core/scalars.py
  saleor/graphql/core/tests/test_scalars.py
  saleor/graphql/core/types/common.py
  saleor/graphql/giftcard/bulk_mutations.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/giftcard/types.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/page/types.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
Labels: 3.7

#11445 Replace usage of load_app with promise of app
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/mutations/permission_group.py
  saleor/graphql/account/mutations/staff.py
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/schema.py
  saleor/graphql/account/types.py
  saleor/graphql/account/utils.py
  saleor/graphql/app/dataloaders.py
  saleor/graphql/app/schema.py
  saleor/graphql/app/types.py
  saleor/graphql/checkout/mutations/checkout_complete.py
  saleor/graphql/checkout/mutations/checkout_create.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/checkout_lines_update.py
  saleor/graphql/checkout/mutations/order_create_from_checkout.py
  saleor/graphql/context.py
  saleor/graphql/csv/mutations/export_gift_cards.py
  saleor/graphql/csv/mutations/export_products.py
  saleor/graphql/giftcard/bulk_mutations.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/invoice/mutations.py
  saleor/graphql/meta/permissions.py
  saleor/graphql/order/bulk_mutations/orders.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/fulfillment_approve.py
  saleor/graphql/order/mutations/fulfillment_cancel.py
  saleor/graphql/order/mutations/fulfillment_refund_products.py
  saleor/graphql/order/mutations/fulfillment_return_products.py
  saleor/graphql/order/mutations/fulfillment_update_tracking.py
  saleor/graphql/order/mutations/order_add_note.py
  saleor/graphql/order/mutations/order_cancel.py
  saleor/graphql/order/mutations/order_capture.py
  saleor/graphql/order/mutations/order_confirm.py
  saleor/graphql/order/mutations/order_discount_add.py
  saleor/graphql/order/mutations/order_discount_delete.py
  saleor/graphql/order/mutations/order_discount_update.py
  saleor/graphql/order/mutations/order_fulfill.py
  saleor/graphql/order/mutations/order_line_delete.py
  saleor/graphql/order/mutations/order_line_discount_remove.py
  saleor/graphql/order/mutations/order_line_discount_update.py
  saleor/graphql/order/mutations/order_line_update.py
  saleor/graphql/order/mutations/order_lines_create.py
  saleor/graphql/order/mutations/order_mark_as_paid.py
  saleor/graphql/order/mutations/order_refund.py
  saleor/graphql/order/mutations/order_void.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/mutations/product/product_delete.py
  saleor/graphql/product/mutations/product_variant/product_variant_delete.py
  saleor/graphql/webhook/mutations.py
  saleor/graphql/webhook/resolvers.py
  saleor/graphql/webhook/schema.py
Labels: skip changelog

#11443 Replace usage of load_app with promise of app
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/mutations/permission_group.py
  saleor/graphql/account/mutations/staff.py
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/schema.py
  saleor/graphql/account/types.py
  saleor/graphql/account/utils.py
  saleor/graphql/app/dataloaders.py
  saleor/graphql/app/schema.py
  saleor/graphql/app/types.py
  saleor/graphql/checkout/mutations/checkout_complete.py
  saleor/graphql/checkout/mutations/checkout_create.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/checkout_lines_update.py
  saleor/graphql/checkout/mutations/order_create_from_checkout.py
  saleor/graphql/context.py
  saleor/graphql/csv/mutations/export_gift_cards.py
  saleor/graphql/csv/mutations/export_products.py
  saleor/graphql/giftcard/bulk_mutations.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/invoice/mutations.py
  saleor/graphql/meta/permissions.py
  saleor/graphql/order/bulk_mutations/orders.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/fulfillment_approve.py
  saleor/graphql/order/mutations/fulfillment_cancel.py
  saleor/graphql/order/mutations/fulfillment_refund_products.py
  saleor/graphql/order/mutations/fulfillment_return_products.py
  saleor/graphql/order/mutations/fulfillment_update_tracking.py
  saleor/graphql/order/mutations/order_add_note.py
  saleor/graphql/order/mutations/order_cancel.py
  saleor/graphql/order/mutations/order_capture.py
  saleor/graphql/order/mutations/order_confirm.py
  saleor/graphql/order/mutations/order_discount_add.py
  saleor/graphql/order/mutations/order_discount_delete.py
  saleor/graphql/order/mutations/order_discount_update.py
  saleor/graphql/order/mutations/order_fulfill.py
  saleor/graphql/order/mutations/order_line_delete.py
  saleor/graphql/order/mutations/order_line_discount_remove.py
  saleor/graphql/order/mutations/order_line_discount_update.py
  saleor/graphql/order/mutations/order_line_update.py
  saleor/graphql/order/mutations/order_lines_create.py
  saleor/graphql/order/mutations/order_mark_as_paid.py
  saleor/graphql/order/mutations/order_refund.py
  saleor/graphql/order/mutations/order_void.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/mutations/product/product_delete.py
  saleor/graphql/product/mutations/product_variant/product_variant_delete.py
  saleor/graphql/webhook/mutations.py
  saleor/graphql/webhook/resolvers.py
  saleor/graphql/webhook/schema.py
Labels: 3.9

#11440 Handle providing empty strings as `lte` and `gte` date type
  saleor/graphql/attribute/types.py
  saleor/graphql/core/scalars.py
  saleor/graphql/core/tests/test_scalars.py
  saleor/graphql/core/types/common.py
  saleor/graphql/giftcard/bulk_mutations.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/giftcard/types.py
  saleor/graphql/order/tests/test_order.py
  saleor/graphql/page/types.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/mutations/products.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
Labels: 3.8

#11438 Fix filtering by numeric values
  saleor/graphql/product/filters.py
  saleor/graphql/product/tests/queries/test_products_query_with_filter.py
Labels: skip changelog

#11469 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
  saleor/checkout/utils.py
  saleor/product/utils/__init__.py
Labels: test deployment, :robot: bot, skip changelog

#11472 Fix invalid default values for decimal fields
  saleor/discount/models.py
  saleor/order/models.py
  saleor/shipping/models.py
Labels: 3.7

#11430 Fix `rich-text` attribute validation for non-text blocks
  saleor/core/tests/test_editorjs.py
  saleor/core/utils/editorjs.py
  saleor/graphql/attribute/tests/test_utils.py
Labels: 3.9

#11496 Add migration for fixing order undiscounted total price
  saleor/order/migrations/0140_fix_order_undiscounted_total.py
Labels: migrations perf test, 3.3

#11497 Add migration for fixing order undiscounted total price
  saleor/order/migrations/0140_fix_order_undiscounted_total.py
  saleor/order/migrations/0152_merge_20221215_1217.py
Labels: 3.4

#11498 Add migration for fixing order undiscounted total price
  saleor/order/migrations/0140_fix_order_undiscounted_total.py
  saleor/order/migrations/0152_merge_20221215_1217.py
  saleor/order/migrations/0155_merge_20221215_1223.py
Labels: 3.5

#11499 Add migration for fixing order undiscounted total price
  saleor/order/migrations/0140_fix_order_undiscounted_total.py
  saleor/order/migrations/0152_merge_20221215_1217.py
  saleor/order/migrations/0155_merge_20221215_1223.py
  saleor/order/migrations/0156_merge_20221215_1235.py
Labels: 3.6

#11500 Add migration for fixing order undiscounted total price
  saleor/order/migrations/0140_fix_order_undiscounted_total.py
  saleor/order/migrations/0152_merge_20221215_1217.py
  saleor/order/migrations/0155_merge_20221215_1223.py
  saleor/order/migrations/0156_merge_20221215_1235.py
Labels: 3.7

#11501 Add migration for fixing order undiscounted total price
  saleor/order/migrations/0140_fix_order_undiscounted_total.py
  saleor/order/migrations/0152_merge_20221215_1217.py
  saleor/order/migrations/0155_merge_20221215_1223.py
  saleor/order/migrations/0156_merge_20221215_1235.py
  saleor/order/migrations/0159_merge_20221215_1244.py
Labels: 3.8

#11502 Add migration for fixing order undiscounted total price
  saleor/order/migrations/0140_fix_order_undiscounted_total.py
  saleor/order/migrations/0152_merge_20221215_1217.py
  saleor/order/migrations/0155_merge_20221215_1223.py
  saleor/order/migrations/0156_merge_20221215_1235.py
  saleor/order/migrations/0159_merge_20221215_1244.py
  saleor/order/migrations/0160_merge_20221215_1253.py
Labels: 3.9

#11503 Add migration for fixing order undiscounted total price
  saleor/order/migrations/0140_fix_order_undiscounted_total.py
  saleor/order/migrations/0152_merge_20221215_1217.py
  saleor/order/migrations/0155_merge_20221215_1223.py
  saleor/order/migrations/0156_merge_20221215_1235.py
  saleor/order/migrations/0159_merge_20221215_1244.py
  saleor/order/migrations/0160_merge_20221215_1253.py
Labels: skip changelog

#11504 Stop sending regular payload to subscription webhooks
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_webhook.py
  saleor/plugins/webhook/utils.py
Labels: bug, skip changelog

#11511 Add ability to set a custom Celery queue for async webhook
  CHANGELOG.md
  saleor/plugins/webhook/tasks.py
  saleor/settings.py
Labels: performance

#11484 Fix `rich-text` attribute validation for non-text blocks
  saleor/core/tests/test_editorjs.py
  saleor/core/utils/editorjs.py
  saleor/graphql/attribute/tests/test_utils.py
Labels: skip changelog

#11485 Fix invalid default values for decimal fields
  saleor/discount/models.py
  saleor/order/models.py
  saleor/shipping/models.py
Labels: 3.8

#11486 Fix invalid default values for decimal fields
  saleor/discount/models.py
  saleor/order/models.py
  saleor/shipping/models.py
Labels: 3.9

#11487 Fix invalid default values for decimal fields
  saleor/discount/models.py
  saleor/order/models.py
  saleor/shipping/models.py
Labels: skip changelog

#11526 Add ability to set a custom Celery queue for async webhook
  saleor/plugins/webhook/tasks.py
  saleor/settings.py
Labels: 3.9

#11525 Add ability to set a custom Celery queue for async webhook
  saleor/plugins/webhook/tasks.py
  saleor/settings.py
Labels: 3.8

#11524 Add ability to set a custom Celery queue for async webhook
  saleor/plugins/webhook/tasks.py
  saleor/settings.py
Labels: 3.7

#11523 Add ability to set a custom Celery queue for async webhook
  saleor/plugins/webhook/tasks.py
  saleor/settings.py
Labels: 3.6

#11522 Add ability to set a custom Celery queue for async webhook
  saleor/plugins/webhook/tasks.py
  saleor/settings.py
Labels: 3.5

#11528 Fix migrations conflict
  saleor/order/migrations/0161_merge_20221219_1838.py
Labels: skip changelog

#11519 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#11509 Fix double avatax requests for automatically confirmed orders
  saleor/order/actions.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: test deployment, skip changelog

#11533 Make variants sale resolver use DB replica instead of writer DB
  saleor/graphql/discount/types.py
Labels: performance, 3.7

#11549 Use DB replica for sale resolver instead of writer DB
  saleor/graphql/discount/types.py
Labels: 3.7

#11543 Fix double avatax requests for created order
  saleor/order/actions.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.1

#11542 Fix double avatax requests for created order
  saleor/order/actions.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.2

#11541 Fix double avatax requests for created order
  saleor/order/actions.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.3

#11540 Fix double avatax requests for created order
  saleor/order/actions.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.4

#11539 Fix double avatax requests for created order
  saleor/order/actions.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.5

#11538 Fix double avatax requests for created order
  saleor/order/actions.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.6

#11536 Fix double avatax requests for created order
  saleor/order/actions.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.8

#11535 Fix double avatax requests for created order
  saleor/order/actions.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.9

#11546 Make variants sale resolver use DB replica instead of writer DB
  saleor/graphql/discount/types.py
Labels: performance, 3.9

#11545 Make variants sale resolver use DB replica instead of writer DB
  saleor/graphql/discount/types.py
Labels: performance, 3.8

#11544 Make variants sale resolver use DB replica instead of writer DB
  saleor/graphql/discount/types.py
Labels: performance, skip changelog

#11574 Add missing DB index for account private metadata
  saleor/account/migrations/0063_user_user_p_meta_jsonb_path_idx.py
  saleor/account/models.py
Labels: performance, 3.1

#11587 Fix Avalara order validation on digital orders.
  saleor/order/tests/test_order_actions.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/tests/fixtures.py
Labels: test deployment, 3.1

#11591 Fix Avalara order validation on digital orders.
  saleor/order/tests/test_order_actions.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/tests/fixtures.py
Labels: 3.4

#11592 Fix Avalara order validation on digital orders.
  saleor/order/tests/test_order_actions.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/tests/fixtures.py
Labels: 3.5

#11590 Fix Avalara order validation on digital orders.
  saleor/order/tests/test_order_actions.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/tests/fixtures.py
Labels: 3.3

#11589 Fix Avalara order validation on digital orders.
  saleor/order/tests/test_order_actions.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/tests/fixtures.py
Labels: 3.2

#11593 Use replicas to fetching discount info
  saleor/discount/utils.py
  saleor/graphql/discount/dataloaders.py
Labels: skip changelog

#11603 Use replicas to fetching discount info
  saleor/discount/utils.py
  saleor/graphql/discount/dataloaders.py
Labels: 3.1

#11602 Use replicas to fetching discount info
  saleor/discount/utils.py
  saleor/graphql/discount/dataloaders.py
Labels: 3.2

#11601 Use replicas to fetching discount info
  saleor/discount/utils.py
  saleor/graphql/discount/dataloaders.py
Labels: 3.3

#11600 Use replicas to fetching discount info
  saleor/discount/utils.py
  saleor/graphql/discount/dataloaders.py
Labels: 3.4

#11599 Use replicas to fetching discount info
  saleor/discount/utils.py
  saleor/graphql/discount/dataloaders.py
Labels: 3.5

#11598 Use replicas to fetching discount info
  saleor/discount/utils.py
  saleor/graphql/discount/dataloaders.py
Labels: 3.6

#11597 Use replicas to fetching disount info
  saleor/discount/utils.py
  saleor/graphql/discount/dataloaders.py
Labels: 3.7

#11596 Use replicas to fetching discount info
  saleor/discount/utils.py
  saleor/graphql/discount/dataloaders.py
Labels: 3.8

#11595 Use replicas to fetching discount info
  saleor/discount/utils.py
  saleor/graphql/discount/dataloaders.py
Labels: 3.9
