Repository saleor/saleor, pull requests merged in 2023-11, with the labels that each got.

#14371 Fix order.chargeStatus calculated incorrectly
  saleor/graphql/order/mutations/order_grant_refund_create.py
  saleor/graphql/order/mutations/order_grant_refund_update.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_create.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_update.py
  saleor/order/migrations/0165_fix_order_charge_status_with_transactions.py
  saleor/order/migrations/tasks/saleor3_13.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
Labels: order, 3.13, transactions

#14526 Fix order.chargeStatus calculated incorrectly
  saleor/celeryconf.py
  saleor/graphql/order/mutations/order_grant_refund_create.py
  saleor/graphql/order/mutations/order_grant_refund_update.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_create.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_update.py
  saleor/order/migrations/0165_fix_order_charge_status_with_transactions.py
  saleor/order/migrations/0170_merge_20231030_0857.py
  saleor/order/migrations/tasks/saleor3_13.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
Labels: order, 3.14, transactions

#14531 Fix order.chargeStatus calculated incorrectly
  saleor/celeryconf.py
  saleor/graphql/order/mutations/order_grant_refund_create.py
  saleor/graphql/order/mutations/order_grant_refund_update.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_create.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_update.py
  saleor/order/migrations/0165_fix_order_charge_status_with_transactions.py
  saleor/order/migrations/0170_merge_20231030_0857.py
  saleor/order/migrations/0174_merge_20231030_1033.py
  saleor/order/migrations/tasks/saleor3_13.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
Labels: order, 3.15, transactions

#14532 Fix order.chargeStatus calculated incorrectly
  saleor/celeryconf.py
  saleor/graphql/order/mutations/order_grant_refund_create.py
  saleor/graphql/order/mutations/order_grant_refund_update.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_create.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_update.py
  saleor/order/migrations/0165_fix_order_charge_status_with_transactions.py
  saleor/order/migrations/0170_merge_20231030_0857.py
  saleor/order/migrations/0174_merge_20231030_1033.py
  saleor/order/migrations/0175_merge_20231030_1040.py
  saleor/order/migrations/tasks/saleor3_13.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
Labels: order, transactions, 3.16

#14534 Fix order.chargeStatus calculated incorrectly
  saleor/celeryconf.py
  saleor/graphql/order/mutations/order_grant_refund_create.py
  saleor/graphql/order/mutations/order_grant_refund_update.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_create.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_update.py
  saleor/order/migrations/0165_fix_order_charge_status_with_transactions.py
  saleor/order/migrations/0170_merge_20231030_0857.py
  saleor/order/migrations/0174_merge_20231030_1033.py
  saleor/order/migrations/0175_merge_20231030_1040.py
  saleor/order/migrations/0178_merge_20231030_1055.py
  saleor/order/migrations/tasks/saleor3_13.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
Labels: order, transactions, 3.17

#14538 Fix order.chargeStatus calculated incorrectly
  saleor/graphql/order/mutations/order_grant_refund_create.py
  saleor/graphql/order/mutations/order_grant_refund_update.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_create.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_update.py
  saleor/order/migrations/0165_fix_order_charge_status_with_transactions.py
  saleor/order/migrations/0170_merge_20231030_0857.py
  saleor/order/migrations/0174_merge_20231030_1033.py
  saleor/order/migrations/0175_merge_20231030_1040.py
  saleor/order/migrations/0178_merge_20231030_1055.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
Labels: migrations perf test, order, skip changelog, transactions

#14380 TransactionAPI: fix pending amounts for async action request
  saleor/payment/utils.py
  saleor/plugins/webhook/tests/test_tasks.py
Labels: 3.13, transactions

#14539 TransactionAPI: fix pending amounts for async action request
  saleor/payment/utils.py
  saleor/plugins/webhook/tests/test_tasks.py
Labels: 3.14, transactions

#14541 TransactionAPI: fix pending amounts for async action request
  saleor/payment/utils.py
  saleor/plugins/webhook/tests/test_tasks.py
Labels: 3.15, transactions

#14542 TransactionAPI: fix pending amounts for async action request
  saleor/payment/utils.py
  saleor/plugins/webhook/tests/test_tasks.py
Labels: transactions, 3.16

#14543 TransactionAPI: fix pending amounts for async action request
  saleor/payment/utils.py
  saleor/plugins/webhook/tests/test_tasks.py
Labels: transactions, 3.17

#14544 TransactionAPI: fix pending amounts for async action request
  saleor/payment/utils.py
  saleor/plugins/webhook/tests/test_tasks.py
Labels: skip changelog, transactions, skip migrations perf test

#14537 Fix migrations dependencies and revert options
  saleor/discount/migrations/0065_remove_voucher_code_index.py
  saleor/discount/migrations/0067_voucher_single_use.py
  saleor/product/migrations/0187_auto_20230614_0838.py
Labels: skip changelog, promotions, skip migrations perf test

#14461 Fix inccorect statuses provided by order.paymentStatus when order is paid with transactions
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/types.py
Labels: order, 3.13, transactions

#14546 Fix inccorect statuses provided by order.paymentStatus when order is paid with transactions
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/types.py
Labels: order, 3.14, transactions

#14547 Fix inccorect statuses provided by order.paymentStatus when order is paid with transactions
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/types.py
Labels: order, 3.15, transactions

#14549 Fix inccorect statuses provided by order.paymentStatus when order is paid with transactions
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/types.py
Labels: order, transactions, 3.16

#14550 Fix inccorect statuses provided by order.paymentStatus when order is paid with transactions
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/types.py
Labels: order, transactions, 3.17

#14551 Fix inccorect statuses provided by order.paymentStatus when order is paid with transactions
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/types.py
Labels: order, skip changelog, transactions, skip migrations perf test

#14568 Adjustment for Include draft orders in voucher usage
  saleor/graphql/channel/mutations/channel_create.py
  saleor/graphql/channel/mutations/utils.py
  saleor/graphql/schema.graphql
Labels: voucher

#14558 Fix failing discounted price calculations when PromotionRule was deleted in the meantime
  saleor/product/tests/test_product_minimal_variant_price.py
  saleor/product/utils/variant_prices.py
Labels: promotions, 3.17

#14562 Fix for 'NoneType' object has no attribute 'full_clean' in VoucherUpdate mutation
  saleor/graphql/discount/mutations/voucher/voucher_create.py
  saleor/graphql/discount/tests/mutations/test_voucher_update.py
Labels: test deployment, voucher, 3.17

#14512 Add voucher to checkout query.
  CHANGELOG.md
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
  saleor/graphql/discount/dataloaders.py
  saleor/graphql/schema.graphql
Labels: test deployment, checkout, voucher

#14581 Fix 0187_auto_20230614_0838 migration dependencies
  saleor/product/migrations/0187_auto_20230614_0838.py
Labels: promotions, 3.17

#14583 Fix failing discounted price calculations when PromotionRule was deleted in the meantime
  saleor/product/tests/test_product_minimal_variant_price.py
  saleor/product/utils/variant_prices.py
Labels: skip changelog, promotions, 3.18, skip migrations perf test

#14573 Fix authorize and charge statuses for checkout
  saleor/checkout/calculations.py
  saleor/checkout/migrations/0060_fix_charge_and_authorize_status_for_empty_checkouts.py
  saleor/checkout/migrations/tasks/__init__.py
  saleor/checkout/payment_utils.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/tests/test_payment_utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/test_checkout_filters.py
  saleor/graphql/checkout/types.py
Labels: checkout, migrations perf test, skip changelog, transactions

#14499 Add missing refund fields to fulfillment
  saleor/graphql/order/tests/queries/test_fulfillment.py
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/plugins/webhook/tests/subscription_webhooks/payloads.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
Labels: order, 3.14

#14574 Add missing refund fields to fulfillment
  saleor/graphql/order/tests/queries/test_fulfillment.py
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/plugins/webhook/tests/subscription_webhooks/payloads.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
Labels: order, 3.15

#14575 Add missing refund fields to fulfillment
  saleor/graphql/order/tests/queries/test_fulfillment.py
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/plugins/webhook/tests/subscription_webhooks/payloads.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
Labels: order, 3.16

#14576 Add missing refund fields to fullfillment
  saleor/graphql/order/tests/queries/test_fulfillment.py
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/plugins/webhook/tests/subscription_webhooks/payloads.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
Labels: order, 3.17

#14577 Add missing refund fields to fulfillment
  saleor/graphql/order/tests/queries/test_fulfillment.py
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/plugins/webhook/tests/subscription_webhooks/payloads.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
Labels: order, skip changelog, skip migrations perf test

#14590 [TEST] Unable to update voucher's single use settings after using one of the codes CORE_0926
  saleor/tests/e2e/checkout/test_checkout_unable_to_update_single_use_settings_after_usage.py
  saleor/tests/e2e/vouchers/utils/__init__.py
  saleor/tests/e2e/vouchers/utils/voucher_update.py
Labels: voucher, skip changelog

#14589 [Test] Should be able to pay for the part of checkout using gift card
  saleor/tests/e2e/checkout/test_pay_for_part_of_checkout_with_gift_card.py
  saleor/tests/e2e/checkout/test_pay_for_total_checkout_with_gift_card.py
Labels: skip changelog

#14533 [TEST] Export voucher codes
  saleor/tests/e2e/vouchers/test_export_voucher_codes.py
  saleor/tests/e2e/vouchers/utils/__init__.py
  saleor/tests/e2e/vouchers/utils/voucher_codes_export.py
Labels: voucher, skip changelog

#14601 Fix page publish flaky test
  saleor/tests/fixtures.py
Labels: skip changelog, tests, skip migrations perf test

#14600 [Test] Should be able to create a page with each type of attribute
  saleor/tests/e2e/attributes/utils/__init__.py
  saleor/tests/e2e/attributes/utils/create_attribute.py
  saleor/tests/e2e/attributes/utils/prepare_attributes.py
  saleor/tests/e2e/pages/__init__.py
  saleor/tests/e2e/pages/test_create_page_with_all_attributes_types.py
  saleor/tests/e2e/pages/utils/__init__.py
  saleor/tests/e2e/pages/utils/page_create.py
  saleor/tests/e2e/pages/utils/page_type_create.py
Labels: skip changelog

#14567 Use Poetry across the board and cache package managers in Docker
  .devcontainer/Dockerfile
  .github/workflows/publish-containers.yml
  .github/workflows/pytest.yml
  CONTRIBUTING.md
  Dockerfile
  saleor/settings.py
Labels: skip changelog, ci

#14591 fix cached user
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: bug, 3.14

#14602 Publish containers adjustments
  .github/workflows/publish-containers.yml
  Dockerfile
Labels: 3.17

#14603 Publish containers adjustment
  .github/workflows/publish-containers.yml
  Dockerfile
Labels: 3.16

#14604 Publish containers adjustment
  .github/workflows/publish-containers.yml
  Dockerfile
Labels: 3.15

#14605 Publish containers adjustment
  .github/workflows/publish-containers.yml
  Dockerfile
Labels: 3.14

#14606 Publish containers adjustment
  .github/workflows/publish-containers.yml
  Dockerfile
Labels: 3.13

#14607 Publish containers adjustment
  .github/workflows/publish-containers.yml
  Dockerfile
Labels: 3.12

#14608 Publish containers adjustment
  .github/workflows/publish-containers.yml
  Dockerfile
Labels: 3.11

#14009 [Test] Should be able to buy gift card in the checkout
  saleor/tests/e2e/account/utils/__init__.py
  saleor/tests/e2e/account/utils/me.py
  saleor/tests/e2e/checkout/test_buy_gift_card_in_the_checkout.py
  saleor/tests/e2e/gift_cards/utils/__init__.py
  saleor/tests/e2e/gift_cards/utils/gift_cards_query.py
  saleor/tests/e2e/product/utils/product_type.py
  saleor/tests/e2e/shop/utils/shop_update_settings.py
Labels: skip changelog

#14566 Don't reattempt webhook delivery after non-transient HTTP errors
  CHANGELOG.md
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/tests/__init__.py
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: webhooks

#14610 [TEST] Should be able to remove voucher from checkout CORE_0917
  saleor/tests/e2e/checkout/test_should_be_able_to_remove_voucher_code_from_checkout.py
  saleor/tests/e2e/checkout/utils/__init__.py
  saleor/tests/e2e/checkout/utils/checkout_remove_promo_code.py
Labels: voucher, skip changelog

#14631 Fix slug creation
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: skip changelog, main

#14630 Fix slug creation
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: skip changelog, 3.17

#14629 Fix slug creation
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: skip changelog, 3.16

#14628 Fix slug creation
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: skip changelog, 3.15

#14633 [Test] Staff should be able to create simple product
  saleor/tests/e2e/product/test_create_simple_product.py
Labels: skip changelog

#14634 fix cached user (#14591)
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: bug, 3.15

#14636 fix cached user (#14591)
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: bug, 3.17

#14642 fix cached user (#14591)
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: skip changelog, skip migrations perf test

#14638 Update SECURITY.md
  SECURITY.md
Labels: skip changelog

#14640 Remove obsolete comment
  saleor/graphql/app/dataloaders.py
Labels: skip changelog

#14644 [TEST] Unable to register account with existing email and login with invalid credentials CORE_1503 & CORE_1506
  saleor/tests/e2e/account/test_should_not_be_able_to_create_account_with_existing_email.py
  saleor/tests/e2e/account/test_should_not_be_able_to_login_with_invalid_credentials.py
  saleor/tests/e2e/account/utils/__init__.py
  saleor/tests/e2e/account/utils/account_register.py
  saleor/tests/e2e/account/utils/token_create.py
Labels: skip changelog

#14650 Use image metadata version instead of the old env vars
  .github/workflows/publish-containers.rst
  .github/workflows/publish-containers.yml
Labels: skip changelog, ci

#14639 Fix unserializable decimal values in catalogue predicate.
  saleor/discount/migrations/0064_alter_promotionrule_catalogue_predicate.py
  saleor/discount/models.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
Labels: test deployment, promotions, 3.17

#14616 Fix unserializable decimal values in catalogue predicate.
  saleor/discount/migrations/0064_alter_promotionrule_catalogue_predicate.py
  saleor/discount/migrations/0068_merge_20231106_1013.py
  saleor/discount/models.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
Labels: bug, skip changelog, promotions

#14643 [TEST] Should be able to use multiple gift cards in checkout
  saleor/tests/e2e/checkout/test_checkout_use_multiple_gift_cards.py
  saleor/tests/e2e/gift_cards/utils/__init__.py
  saleor/tests/e2e/gift_cards/utils/gift_card_bulk_create.py
Labels: skip changelog

#14658 Use image metadata version instead of the old env vars
  .github/workflows/publish-containers.rst
  .github/workflows/publish-containers.yml
Labels: skip changelog, 3.13, ci

#14657 Use image metadata version instead of the old env vars
  .github/workflows/publish-containers.rst
  .github/workflows/publish-containers.yml
Labels: skip changelog, 3.14, ci

#14656 Use image metadata version instead of the old env vars
  .github/workflows/publish-containers.rst
  .github/workflows/publish-containers.yml
Labels: skip changelog, 3.15, ci

#14655 Use image metadata version instead of the old env vars
  .github/workflows/publish-containers.rst
  .github/workflows/publish-containers.yml
Labels: skip changelog, 3.16, ci

#14654 Use image metadata version instead of the old env vars
  .github/workflows/publish-containers.rst
  .github/workflows/publish-containers.yml
Labels: skip changelog, 3.17, ci

#14659 Use image metadata version instead of the old env vars
  .github/workflows/publish-containers.rst
  .github/workflows/publish-containers.yml
Labels: skip changelog, 3.12, ci

#14637 [TEST] Should be able to add add a gift card to a checkout before email
  saleor/tests/e2e/checkout/test_checkout_add_gift_card_before_email.py
  saleor/tests/e2e/checkout/utils/__init__.py
  saleor/tests/e2e/checkout/utils/checkout_email_update.py
  saleor/tests/e2e/gift_cards/utils/gift_card_create.py
Labels: skip changelog

#14485 Add max_sort_order field as cache to reduce database operations
  saleor/attribute/migrations/0029_attribute_max_sort_order.py
  saleor/attribute/migrations/tasks/__init__.py
  saleor/attribute/migrations/tasks/saleor3_14.py
  saleor/attribute/models/base.py
  saleor/attribute/tests/models/test_base.py
  saleor/celeryconf.py
  saleor/core/models.py
Labels: 3.14

#14680 [TEST] Create and update customer's metadata CORE_1513 & CORE_1514
  saleor/tests/e2e/users/__init__.py
  saleor/tests/e2e/users/test_create_and_update_customer_with_metadata.py
  saleor/tests/e2e/users/test_should_bulk_update_customers_metadata.py
  saleor/tests/e2e/users/utils/__init__.py
  saleor/tests/e2e/users/utils/create_customer.py
  saleor/tests/e2e/users/utils/customer_bulk_update.py
  saleor/tests/e2e/users/utils/customer_update.py
Labels: skip changelog

#14682 Update GraphQL Playground
  templates/graphql/playground.html
Labels: skip changelog

#14668 Start linting dependencies
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  saleor/graphql/core/scalars.py
Labels: skip changelog, ci

#14662 Bump poetry to 1.7.0
  .devcontainer/Dockerfile
  .github/workflows/pytest.yml
  .github/workflows/test-migrations-compatibility.yml
  Dockerfile
Labels: skip changelog

#14671 Drop defaultTransactionFlowStrategy from orderSettings
  CHANGELOG.md
  saleor/graphql/channel/mutations/channel_create.py
  saleor/graphql/channel/mutations/utils.py
  saleor/graphql/channel/tests/mutations/test_channel_create.py
  saleor/graphql/channel/tests/mutations/test_channel_update.py
  saleor/graphql/channel/tests/queries/test_channel.py
  saleor/graphql/channel/types.py
  saleor/graphql/core/descriptions.py
  saleor/graphql/payment/mutations/transaction/transaction_initialize.py
  saleor/graphql/schema.graphql
  saleor/graphql/shop/mutations/order_settings_update.py
  saleor/graphql/shop/tests/mutations/test_order_settings_update.py
Labels: test deployment, 3.18

#14598 Fixes for granted refund logic
  saleor/graphql/order/mutations/order_grant_refund_create.py
  saleor/graphql/order/mutations/order_grant_refund_update.py
  saleor/graphql/order/mutations/order_grant_refund_utils.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_create.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_update.py
Labels: order, 3.15

#14672 Fixes for granted refund logic
  saleor/graphql/order/mutations/order_grant_refund_create.py
  saleor/graphql/order/mutations/order_grant_refund_update.py
  saleor/graphql/order/mutations/order_grant_refund_utils.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_create.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_update.py
Labels: order, 3.16

#14673 Fixes for granted refund logic
  saleor/graphql/order/mutations/order_grant_refund_create.py
  saleor/graphql/order/mutations/order_grant_refund_update.py
  saleor/graphql/order/mutations/order_grant_refund_utils.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_create.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_update.py
Labels: order, 3.17

#14674 Fixes for granted refund logic
  saleor/graphql/order/mutations/order_grant_refund_create.py
  saleor/graphql/order/mutations/order_grant_refund_update.py
  saleor/graphql/order/mutations/order_grant_refund_utils.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_create.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_update.py
Labels: order, skip changelog

#14670 Refactor fetching variants for predicates
  saleor/discount/tasks.py
  saleor/discount/utils.py
  saleor/graphql/discount/mutations/bulk_mutations.py
  saleor/graphql/discount/mutations/promotion/promotion_bulk_delete.py
  saleor/graphql/discount/tests/test_utils.py
  saleor/graphql/discount/utils.py
Labels: promotions

#14664 Extend PromotionRule with `checkout_and_order_predicate` field
  saleor/discount/migrations/0069_promotionrule_checkout_and_order_predicate.py
  saleor/discount/models.py
Labels: skip changelog, promotions, skip migrations perf test

#14678 Fix amount value comparison in transaction webhooks
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: transactions, 3.17

#14683 [TEST] Should create and update staff with metadata CORE_1515
  saleor/tests/e2e/users/test_create_and_update_staff_with_metadata.py
  saleor/tests/e2e/users/utils/__init__.py
  saleor/tests/e2e/users/utils/staff_create.py
  saleor/tests/e2e/users/utils/staff_update.py
Labels: skip changelog

#14669 Add fixes for StripePlugin
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: payments, 3.12

#14690 Add fixes for StripePlugin
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: payments, skip changelog, skip migrations perf test

#14686 Add fixes for StripePlugin
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: payments, 3.14

#14687 Add fixes for StripePlugin
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: payments, 3.15

#14688 Add fixes for StripePlugin
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: payments, 3.16

#14689 Add fixes for StripePlugin
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: payments, 3.17

#14685 Add fixes for StripePlugin
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: payments, 3.13

#13957 Fix amount value comparison in transaction webhooks
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.15, transactions

#13956 Fix amount value comparison in transaction webhooks
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.14, transactions

#13955 Fix amount value comparison in transaction webhooks
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.13, transactions

#14599 Extend description of PRODUCT_VARIANT_DELETED enum
  saleor/graphql/schema.graphql
  saleor/graphql/webhook/enums.py
Labels: skip changelog

#14699 Update GraphiQL
  templates/graphql/playground.html
Labels: test deployment, 3.14

#14698 Update GraphiQL
  templates/graphql/playground.html
Labels: 3.15

#14697 Update GraphiQL
  templates/graphql/playground.html
Labels: 3.16

#14700 Update GraphiQL
  templates/graphql/playground.html
Labels: 3.17

#14704 Fix failing checkout.0060 migration
  saleor/checkout/migrations/tasks/saleor3_13.py
Labels: 3.14

#14705 Fix failing checkout.0060 migration
  saleor/checkout/migrations/tasks/saleor3_13.py
Labels: 3.15

#14707 Fix failing checkout.0060 migration
  saleor/checkout/migrations/tasks/saleor3_13.py
Labels: 3.17

#14708 Fix failing checkout.0060 migration
  saleor/checkout/migrations/0060_fix_charge_and_authorize_status_for_empty_checkouts.py
Labels: migrations perf test, skip changelog

#13407 Simplify Product - Attribute relation
  CHANGELOG.md
  saleor/attribute/migrations/0038_remove_assignedproductattribute.py
  saleor/attribute/models/__init__.py
  saleor/attribute/models/base.py
  saleor/attribute/models/product.py
  saleor/attribute/tasks.py
  saleor/attribute/tests/model_helpers.py
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/core/utils/random_data.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/products_data/utils.py
  saleor/csv/utils/__init__.py
  saleor/csv/utils/export.py
  saleor/graphql/attribute/bulk_mutations.py
  saleor/graphql/attribute/mutations/attribute_value_delete.py
  saleor/graphql/attribute/mutations/attribute_value_update.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_delete.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_update.py
  saleor/graphql/attribute/tests/queries/test_attributes_sort.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_type_bulk_delete.py
  saleor/graphql/product/dataloaders/attributes.py
  saleor/graphql/product/filters.py
  saleor/graphql/product/mutations/attributes.py
  saleor/graphql/product/mutations/product/product_create.py
  saleor/graphql/product/mutations/product/product_delete.py
  saleor/graphql/product/mutations/product/product_update.py
  saleor/graphql/product/mutations/product_type/product_type_delete.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/queries/test_products_query.py
  saleor/graphql/product/tests/queries/test_products_query_with_filter.py
  saleor/graphql/product/tests/queries/test_products_query_with_where.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/product/managers.py
  saleor/product/search.py
  saleor/static/populatedb_data.json
  saleor/tests/fixtures.py
  saleor/webhook/payloads.py
  saleor/webhook/serializers.py
  saleor/webhook/tests/test_webhook_serializers.py
Labels: attributes, migrations perf test, product, 3.18

#14710 Adjust PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip changelog, skip migrations perf test

#14711 Move sale migration celery task.
  saleor/celeryconf.py
  saleor/discount/migrations/0047_migrate_sales_to_promotions.py
  saleor/discount/migrations/tasks/saleor3_17.py
  saleor/discount/tasks.py
Labels: skip changelog, 3.18

#14692 Add erorr handling when stock to create already exists
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/schema.graphql
  saleor/product/error_codes.py
Labels: bug, skip changelog, 3.14

#14713 Add max_sort_order field as cache to reduce database operations
  saleor/attribute/migrations/0029_attribute_max_sort_order.py
  saleor/attribute/migrations/0030_merge_20231110_1243.py
  saleor/attribute/migrations/tasks/__init__.py
  saleor/attribute/migrations/tasks/saleor3_14.py
  saleor/attribute/models/base.py
  saleor/attribute/tests/models/test_base.py
  saleor/celeryconf.py
  saleor/core/models.py
Labels: 3.15

#14731 Add max_sort_order field as cache to reduce database operations
  saleor/attribute/migrations/0029_attribute_max_sort_order.py
  saleor/attribute/migrations/0030_merge_20231110_1243.py
  saleor/attribute/migrations/0037_merge_20231113_1050.py
  saleor/attribute/migrations/0039_merge_20231113_1132.py
  saleor/attribute/migrations/tasks/saleor3_14.py
  saleor/attribute/models/base.py
  saleor/attribute/tests/models/test_base.py
  saleor/celeryconf.py
  saleor/core/models.py
Labels: 3.18

#14548 Use replicas in resolvers
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/schema.py
  saleor/graphql/account/types.py
  saleor/graphql/app/resolvers.py
  saleor/graphql/app/types.py
  saleor/graphql/attribute/resolvers.py
  saleor/graphql/attribute/schema.py
  saleor/graphql/attribute/types.py
  saleor/graphql/channel/resolvers.py
  saleor/graphql/channel/schema.py
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/core/utils/resolvers.py
  saleor/graphql/csv/resolvers.py
  saleor/graphql/csv/schema.py
  saleor/graphql/discount/resolvers.py
  saleor/graphql/discount/schema.py
  saleor/graphql/discount/types/vouchers.py
  saleor/graphql/giftcard/resolvers.py
  saleor/graphql/giftcard/schema.py
  saleor/graphql/menu/resolvers.py
  saleor/graphql/menu/schema.py
  saleor/graphql/page/resolvers.py
  saleor/graphql/page/schema.py
  saleor/graphql/page/types.py
  saleor/graphql/payment/resolvers.py
  saleor/graphql/payment/schema.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/resolvers.py
  saleor/graphql/shipping/schema.py
  saleor/graphql/shipping/tests/test_shipping_zones_query.py
  saleor/graphql/shipping/types.py
  saleor/graphql/shop/resolvers.py
  saleor/graphql/shop/schema.py
  saleor/graphql/shop/types.py
  saleor/graphql/tax/schema.py
  saleor/graphql/translations/resolvers.py
  saleor/graphql/translations/schema.py
  saleor/graphql/translations/types.py
  saleor/graphql/warehouse/resolvers.py
  saleor/graphql/warehouse/schema.py
  saleor/graphql/warehouse/types.py
  saleor/graphql/webhook/resolvers.py
  saleor/graphql/webhook/types.py
Labels: performance, 3.14

#14738 Add error handling when stock to create already exists
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/schema.graphql
  saleor/product/error_codes.py
Labels: bug, skip changelog, 3.15

#14737 Add error handling when stock to create already exists
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/schema.graphql
  saleor/product/error_codes.py
Labels: bug, skip changelog, 3.16

#14739 Add error handling when stock to create already exists
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/schema.graphql
  saleor/product/error_codes.py
Labels: bug, skip changelog, 3.17

#14740 Add error handling when stock to create already exists
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/schema.graphql
  saleor/product/error_codes.py
Labels: bug, skip changelog, main

#14736 Bump main to 3.19.0-a.0
  CHANGELOG.md
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
  saleor/graphql/core/descriptions.py
Labels: skip changelog

#14742 Fix failing tests for channel listing and local time
  saleor/graphql/product/tests/deprecated/test_product_channel_listing_update.py
  saleor/graphql/product/tests/mutations/test_product_channel_listing_update.py
Labels: skip changelog

#14744 Fix few resolvers which were missed in replicas during 3.14 replica PR
  saleor/graphql/order/resolvers.py
  saleor/graphql/payment/resolvers.py
  saleor/graphql/product/resolvers.py
Labels: performance, 3.14

#14716 Add max_sort_order field as cache to reduce database operations
  saleor/attribute/migrations/0029_attribute_max_sort_order.py
  saleor/attribute/migrations/0030_merge_20231110_1243.py
  saleor/attribute/migrations/0037_merge_20231113_1050.py
  saleor/attribute/migrations/0039_merge_20231113_1132.py
  saleor/attribute/models/base.py
  saleor/attribute/tests/models/test_base.py
  saleor/core/models.py
Labels: skip changelog, main

#14741 Do not remove checkouts with active transaction items
  saleor/checkout/tasks.py
  saleor/checkout/tests/test_tasks.py
Labels: checkout, 3.13, transactions

#14749 Do not remove checkout with active transaction items
  saleor/checkout/tasks.py
  saleor/checkout/tests/test_tasks.py
Labels: checkout, 3.14, transactions

#14750 Do not remove checkout with active transaction items
  saleor/checkout/tasks.py
  saleor/checkout/tests/test_tasks.py
Labels: checkout, 3.15, transactions

#14751 Do not remove checkout with active transaction items
  saleor/checkout/tasks.py
  saleor/checkout/tests/test_tasks.py
Labels: checkout, transactions, 3.16

#14752 Do not remove checkout with active transaction items
  saleor/checkout/tasks.py
  saleor/checkout/tests/test_tasks.py
Labels: checkout, transactions, 3.17

#14753 Do not remove checkout with active transaction items
  saleor/checkout/tasks.py
  saleor/checkout/tests/test_tasks.py
Labels: checkout, transactions, 3.18

#14754 Do not remove checkout with active transaction items
  saleor/checkout/tasks.py
  saleor/checkout/tests/test_tasks.py
Labels: checkout, skip changelog, transactions, skip migrations perf test

#14095 Add taxes to undiscounted order prices
  CHANGELOG.md
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/checkout/tests/test_utils.py
  saleor/checkout/utils.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/tests/queries/test_order_line.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
Labels: test deployment

#14743 Use replicas in resolvers
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/schema.py
  saleor/graphql/account/types.py
  saleor/graphql/app/resolvers.py
  saleor/graphql/app/types.py
  saleor/graphql/attribute/resolvers.py
  saleor/graphql/attribute/schema.py
  saleor/graphql/attribute/types.py
  saleor/graphql/channel/resolvers.py
  saleor/graphql/channel/schema.py
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/core/utils/resolvers.py
  saleor/graphql/csv/resolvers.py
  saleor/graphql/csv/schema.py
  saleor/graphql/discount/resolvers.py
  saleor/graphql/discount/schema.py
  saleor/graphql/discount/types/vouchers.py
  saleor/graphql/giftcard/resolvers.py
  saleor/graphql/giftcard/schema.py
  saleor/graphql/menu/resolvers.py
  saleor/graphql/menu/schema.py
  saleor/graphql/order/resolvers.py
  saleor/graphql/page/resolvers.py
  saleor/graphql/page/schema.py
  saleor/graphql/page/types.py
  saleor/graphql/payment/resolvers.py
  saleor/graphql/payment/schema.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/resolvers.py
  saleor/graphql/shipping/schema.py
  saleor/graphql/shipping/tests/queries/test_shipping_zone.py
  saleor/graphql/shipping/types.py
  saleor/graphql/shop/resolvers.py
  saleor/graphql/shop/schema.py
  saleor/graphql/shop/types.py
  saleor/graphql/tax/schema.py
  saleor/graphql/translations/resolvers.py
  saleor/graphql/translations/schema.py
  saleor/graphql/translations/types.py
  saleor/graphql/warehouse/resolvers.py
  saleor/graphql/warehouse/schema.py
  saleor/graphql/warehouse/types.py
  saleor/graphql/webhook/resolvers.py
  saleor/graphql/webhook/subscription_types.py
  saleor/graphql/webhook/types.py
Labels: performance, 3.15

#14746 Use replicas in resolvers
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/schema.py
  saleor/graphql/account/types.py
  saleor/graphql/app/resolvers.py
  saleor/graphql/app/types.py
  saleor/graphql/attribute/resolvers.py
  saleor/graphql/attribute/schema.py
  saleor/graphql/attribute/types.py
  saleor/graphql/channel/resolvers.py
  saleor/graphql/channel/schema.py
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/core/utils/resolvers.py
  saleor/graphql/csv/resolvers.py
  saleor/graphql/csv/schema.py
  saleor/graphql/discount/resolvers.py
  saleor/graphql/discount/schema.py
  saleor/graphql/discount/types/vouchers.py
  saleor/graphql/giftcard/resolvers.py
  saleor/graphql/giftcard/schema.py
  saleor/graphql/menu/resolvers.py
  saleor/graphql/menu/schema.py
  saleor/graphql/order/resolvers.py
  saleor/graphql/page/resolvers.py
  saleor/graphql/page/schema.py
  saleor/graphql/page/types.py
  saleor/graphql/payment/resolvers.py
  saleor/graphql/payment/schema.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/resolvers.py
  saleor/graphql/shipping/schema.py
  saleor/graphql/shipping/tests/queries/test_shipping_zone.py
  saleor/graphql/shipping/types.py
  saleor/graphql/shop/resolvers.py
  saleor/graphql/shop/schema.py
  saleor/graphql/shop/types.py
  saleor/graphql/tax/schema.py
  saleor/graphql/translations/resolvers.py
  saleor/graphql/translations/schema.py
  saleor/graphql/translations/types.py
  saleor/graphql/warehouse/resolvers.py
  saleor/graphql/warehouse/schema.py
  saleor/graphql/warehouse/types.py
  saleor/graphql/webhook/resolvers.py
  saleor/graphql/webhook/subscription_types.py
  saleor/graphql/webhook/types.py
Labels: performance, 3.16

#14756 Use replicas in resolvers
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/schema.py
  saleor/graphql/account/types.py
  saleor/graphql/app/resolvers.py
  saleor/graphql/app/types.py
  saleor/graphql/attribute/resolvers.py
  saleor/graphql/attribute/schema.py
  saleor/graphql/attribute/types.py
  saleor/graphql/channel/resolvers.py
  saleor/graphql/channel/schema.py
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/core/utils/resolvers.py
  saleor/graphql/csv/resolvers.py
  saleor/graphql/csv/schema.py
  saleor/graphql/discount/resolvers.py
  saleor/graphql/discount/schema.py
  saleor/graphql/discount/types/sales.py
  saleor/graphql/discount/types/vouchers.py
  saleor/graphql/giftcard/resolvers.py
  saleor/graphql/giftcard/schema.py
  saleor/graphql/menu/resolvers.py
  saleor/graphql/menu/schema.py
  saleor/graphql/order/resolvers.py
  saleor/graphql/page/resolvers.py
  saleor/graphql/page/schema.py
  saleor/graphql/page/types.py
  saleor/graphql/payment/resolvers.py
  saleor/graphql/payment/schema.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/resolvers.py
  saleor/graphql/shipping/schema.py
  saleor/graphql/shipping/tests/queries/test_shipping_zone.py
  saleor/graphql/shipping/types.py
  saleor/graphql/shop/resolvers.py
  saleor/graphql/shop/schema.py
  saleor/graphql/shop/types.py
  saleor/graphql/tax/schema.py
  saleor/graphql/translations/resolvers.py
  saleor/graphql/translations/schema.py
  saleor/graphql/translations/types.py
  saleor/graphql/warehouse/resolvers.py
  saleor/graphql/warehouse/schema.py
  saleor/graphql/warehouse/types.py
  saleor/graphql/webhook/resolvers.py
  saleor/graphql/webhook/subscription_types.py
  saleor/graphql/webhook/types.py
Labels: performance, 3.18

#14763 Fix order_by in get_product_attributes
  saleor/attribute/tests/model_helpers.py
Labels: skip changelog, main

#14764 Fix handling stock errors when IGNORE_FAILED policy used
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
Labels: bug, skip changelog, 3.14

#14762 Fix max_sort_order calculations when value was None
  saleor/attribute/models/base.py
  saleor/attribute/tests/models/test_base.py
Labels: skip changelog, main

#14757 Use replicas in resolvers main
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/schema.py
  saleor/graphql/account/types.py
  saleor/graphql/app/resolvers.py
  saleor/graphql/app/types.py
  saleor/graphql/attribute/resolvers.py
  saleor/graphql/attribute/schema.py
  saleor/graphql/attribute/types.py
  saleor/graphql/channel/resolvers.py
  saleor/graphql/channel/schema.py
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/core/utils/resolvers.py
  saleor/graphql/csv/resolvers.py
  saleor/graphql/csv/schema.py
  saleor/graphql/discount/resolvers.py
  saleor/graphql/discount/schema.py
  saleor/graphql/discount/types/sales.py
  saleor/graphql/discount/types/vouchers.py
  saleor/graphql/giftcard/resolvers.py
  saleor/graphql/giftcard/schema.py
  saleor/graphql/menu/resolvers.py
  saleor/graphql/menu/schema.py
  saleor/graphql/order/resolvers.py
  saleor/graphql/page/resolvers.py
  saleor/graphql/page/schema.py
  saleor/graphql/page/types.py
  saleor/graphql/payment/resolvers.py
  saleor/graphql/payment/schema.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/resolvers.py
  saleor/graphql/shipping/schema.py
  saleor/graphql/shipping/tests/queries/test_shipping_zone.py
  saleor/graphql/shipping/types.py
  saleor/graphql/shop/resolvers.py
  saleor/graphql/shop/schema.py
  saleor/graphql/shop/types.py
  saleor/graphql/tax/schema.py
  saleor/graphql/translations/resolvers.py
  saleor/graphql/translations/schema.py
  saleor/graphql/translations/types.py
  saleor/graphql/warehouse/resolvers.py
  saleor/graphql/warehouse/schema.py
  saleor/graphql/warehouse/types.py
  saleor/graphql/webhook/resolvers.py
  saleor/graphql/webhook/subscription_types.py
  saleor/graphql/webhook/types.py
Labels: performance, skip changelog, main

#14776 Fix order_by in get_product_attributes
  saleor/attribute/tests/model_helpers.py
Labels: 3.18

#14777 Fix max_sort_order calculations when value was None
  saleor/attribute/models/base.py
  saleor/attribute/tests/models/test_base.py
Labels: 3.17

#14778 Fix max_sort_order calculations when value was None
  saleor/attribute/models/base.py
  saleor/attribute/tests/models/test_base.py
Labels: 3.18

#14781 Fix max_sort_order calculations when value was None
  saleor/attribute/models/base.py
  saleor/attribute/tests/models/test_base.py
Labels: 3.15

#14782 Fix max_sort_order calculations when value was None
  saleor/attribute/models/base.py
  saleor/attribute/tests/models/test_base.py
Labels: 3.14

#14800 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
Labels: test deployment, :robot: bot, skip changelog

#14802 remove redundant if statement in fulfillment_tracking_update function
  saleor/order/actions.py
Labels: 3.16

#14789 Update Readme
  README.md
Labels: skip changelog, skip migrations perf test

#14805 [Test] Update test for not started promotion to use freezgun
  saleor/tests/e2e/orders/discounts/test_order_promotion_not_applied_when_not_within_time_range.py
Labels: skip changelog

#14803 Fix error handling for required value attributes in productBulkCreate
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/tests/fixtures.py
Labels: bug, 3.14

#14790 Lazy legacy payload generation
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/discount/tests/mutations/test_sale_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_create.py
  saleor/graphql/page/tests/mutations/test_page_delete.py
  saleor/graphql/page/tests/mutations/test_page_types_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_update.py
  saleor/graphql/product/tests/mutations/test_product_delete.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: 3.14

#14807 Lazy legacy payload generation
  saleor/graphql/account/tests/mutations/staff/test_customer_delete.py
  saleor/graphql/discount/tests/mutations/test_sale_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_create.py
  saleor/graphql/page/tests/mutations/test_page_delete.py
  saleor/graphql/page/tests/mutations/test_page_types_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_update.py
  saleor/graphql/product/tests/mutations/test_product_delete.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: 3.15

#14786 FIX for migration from 3.17 version
  saleor/discount/migrations/0055_vouchercode.py
  saleor/discount/migrations/0065_vouchercode_created_at_check.py
  saleor/discount/migrations/0069_merge_20231117_0959.py
  saleor/graphql/discount/dataloaders.py
Labels: skip changelog

#14806 Deprecate ordersTotal, reportProductSales and homepageEvents
  CHANGELOG.md
  saleor/graphql/order/schema.py
  saleor/graphql/product/schema.py
  saleor/graphql/schema.graphql
Labels: main

#14816 Add error handling when stock to create already exists
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/schema.graphql
  saleor/product/error_codes.py
Labels: bug, skip changelog, 3.18

#14815 Fix error handling for required value attributes in productBulkCreate
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/tests/fixtures.py
Labels: skip changelog, 3.15

#14814 Fix error handling for required value attributes in productBulkCreate
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/tests/fixtures.py
Labels: skip changelog, 3.16
