Repository saleor/saleor, pull requests merged in 2023-02, with the labels that each got.

#11861 Fix attribute validation errors in ProductVariantBulkCreate
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_create.py
Labels: 3.11

#11880 Upgrade Django to 3.2.17
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.11

#11881 Upgrade Django to 3.2.17
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.10

#11882 Upgrade Django to 3.2.17
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.9

#11883 Upgrade Django to 3.2.17
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.8

#11884 Upgrade Django to 3.2.17
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.7

#11879 Upgrade Django to 3.2.17
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, main

#11859 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#11889 Bump isort version to handle issue with failing pre-commit build
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements_dev.txt
Labels: 3.11

#11890 Bump isort version to handle issue with failing pre-commit build
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements_dev.txt
Labels: 3.9

#11891 Bump isort package in pyproject, to match other branches
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements_dev.txt
Labels: 3.8

#11892 Bump isort version to handle issue with failing pre-commit build
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements_dev.txt
Labels: 3.7

#11809 Exclude apps with pending installations from app queries.
  saleor/app/installation_utils.py
  saleor/app/migrations/0020_app_is_installed.py
  saleor/app/models.py
  saleor/app/tasks.py
  saleor/app/tests/test_app_tasks.py
  saleor/graphql/app/resolvers.py
  saleor/graphql/app/tests/queries/test_app.py
  saleor/graphql/app/tests/queries/test_apps.py
  saleor/site/models.py
Labels: skip changelog

#11866 Validate the object type inside get_payment function
  saleor/payment/gateways/adyen/tests/webhooks/test_get_payment.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.9

#11867 Validate the object type inside get_payment function
  saleor/payment/gateways/adyen/tests/webhooks/test_get_payment.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.10

#11868 Validate the object type inside get_payment function
  saleor/payment/gateways/adyen/tests/webhooks/test_get_payment.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: skip changelog

#11869 Validate the object type inside get_payment function
  saleor/payment/gateways/adyen/tests/webhooks/test_get_payment.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.11

#11902 Validate the object type inside get_payment function
  saleor/payment/gateways/adyen/tests/webhooks/test_get_payment.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.7

#11903 Validate the object type inside get_payment function
  saleor/payment/gateways/adyen/tests/webhooks/test_get_payment.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.8

#11843 Fix warehouse address update to country with different validation rules
  saleor/account/forms.py
  saleor/graphql/warehouse/tests/test_warehouse.py
Labels: skip changelog

#11840 Fix payload for send_user_change_email_notification
  CHANGELOG.md
  saleor/account/notifications.py
  saleor/account/tests/test_notifications.py
  saleor/plugins/user_email/tasks.py
  saleor/plugins/user_email/tests/test_tasks.py
Labels: test deployment

#11832 Fix shipping price update
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/types.py
Labels: skip changelog

#11893 Optimize queries in migration order 0139_fulfil_orderline_token_old_id_created_at
  saleor/order/migrations/0139_fulfil_orderline_token_old_id_created_at.py
Labels: performance, 3.9

#11933 Update mypy to the 1.0.0 release
  .github/workflows/pytest.yml
  .github/workflows/test-migrations-compatibility.yml
  .pre-commit-config.yaml
  .vscode/settings.json
  Dockerfile
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/graphql/webhook/mutations/webhook_dry_run.py
  saleor/site/models.py
Labels: technical debt, skip changelog

#11900 Optimize 0044_fulfill_checkout_line_new_fields migration
  saleor/checkout/migrations/0044_fulfill_checkout_line_new_fields.py
Labels: performance, 3.9

#11874 Optimize order 0150_update_authorize_and_charge_status migration
  saleor/order/migrations/0150_update_authorize_and_charge_status.py
Labels: performance, 3.9

#11922 Optimize queries in migration 0139_fix_undiscounted_total_on_lines
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: performance, 3.9

#11942 Upgrade cryptography to 39.0.1
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.10

#11943 Upgrade cryptography to 39.0.1
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.9

#11944 Upgrade cryptography to 39.0.1
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.8

#11945 Upgrade cryptography to 39.0.1
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.7

#11946 Upgrade cryptography to 39.0.1
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.1

#11947 Upgrade cryptography to 39.0.1
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, main

#11940 Update mypy
  .github/workflows/pytest.yml
  .github/workflows/test-migrations-compatibility.yml
  .pre-commit-config.yaml
  Dockerfile
  poetry.lock
  pyproject.toml
  requirements_dev.txt
Labels: 3.11

#11951 Optimize queries in migration 0139_fix_undiscounted_total_on_lines
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: performance, main, skip changelog

#11939 Fix CI
  .github/workflows/pytest.yml
  .github/workflows/test-migrations-compatibility.yml
  Dockerfile
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.10

#11932 Optimize queries in migration order 0139_fulfil_orderline_token_old_id_created_at
  saleor/order/migrations/0139_fulfil_orderline_token_old_id_created_at.py
Labels: performance, main, skip changelog

#11929 Optimize queries in migration order 0158_migrate_base_shipping_price_amount
  saleor/order/migrations/0158_migrate_base_shipping_price_amount.py
Labels: performance, main, skip changelog

#11921 Fix shipping price update
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/types.py
Labels: 3.11

#11911 Use `GITHUB_OUTPUT` instead of deprecated `::set-output`
  .github/workflows/publish-containers.yml
  .github/workflows/test-env-deploy.yml
Labels: technical debt, skip changelog

#11645 Prepare for moving orderSettings to Channel
  saleor/channel/migrations/0006_order_settings_fields.py
  saleor/channel/migrations/0007_order_settings_per_channel.py
  saleor/channel/models.py
  saleor/graphql/shop/mutations.py
  saleor/graphql/shop/tests/test_shop.py
  saleor/site/models.py
Labels: skip changelog, 3.11

#11966 Use default db for synchronous tax webhooks
  saleor/graphql/account/mutations/base.py
  saleor/graphql/context.py
  saleor/graphql/core/context.py
  saleor/graphql/core/mutations.py
  saleor/graphql/core/tests/test_graphql.py
  saleor/graphql/order/schema.py
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/product/mutations/digital_contents.py
  saleor/graphql/webhook/subscription_payload.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_webhook.py
Labels: 3.11

#11967 Use default db for synchronous tax webhooks
  saleor/graphql/account/mutations/base.py
  saleor/graphql/context.py
  saleor/graphql/core/context.py
  saleor/graphql/core/mutations.py
  saleor/graphql/core/tests/test_graphql.py
  saleor/graphql/order/schema.py
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/product/mutations/digital_contents.py
  saleor/graphql/webhook/subscription_payload.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_webhook.py
Labels: 3.10

#11949 Optimize queries in migration 0139_fix_undiscounted_total_on_lines
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: performance, 3.11

#11948 Optimize queries in migration 0139_fix_undiscounted_total_on_lines
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: performance, 3.10

#11931 Optimize queries in migration order 0139_fulfil_orderline_token_old_id_created_at
  saleor/order/migrations/0139_fulfil_orderline_token_old_id_created_at.py
Labels: performance, 3.11

#11930 Optimize queries in migration order 0139_fulfil_orderline_token_old_id_created_at
  saleor/order/migrations/0139_fulfil_orderline_token_old_id_created_at.py
Labels: performance, skip changelog, 3.10

#11928 Optimize queries in migration order 0158_migrate_base_shipping_price_amount
  saleor/order/migrations/0158_migrate_base_shipping_price_amount.py
Labels: performance, 3.11

#11927 Optimize queries in migration order 0158_migrate_base_shipping_price_amount
  saleor/order/migrations/0158_migrate_base_shipping_price_amount.py
Labels: performance, 3.10

#11973 Trigger `GIFT_CARD_CREATED` event in `gift_cards_create` utility
  CHANGELOG.md
  saleor/giftcard/tests/test_utils.py
  saleor/giftcard/utils.py
Labels: 3.11

#11972 Trigger `GIFT_CARD_CREATED` event in `gift_cards_create` utility
  CHANGELOG.md
  saleor/giftcard/tests/test_utils.py
  saleor/giftcard/utils.py
Labels: 3.10

#11977 Fix __run_payment_webhook kwargs.
  saleor/plugins/webhook/plugin.py
Labels: 3.10

#11976 Fix __run_payment_webhook kwargs.
  saleor/plugins/webhook/plugin.py
Labels: 3.11

#11975 Fix __run_payment_webhook kwargs.
  saleor/plugins/webhook/plugin.py
Labels: bug, skip changelog

#11961 Fix error in case of not provided orderSetting
  saleor/graphql/channel/mutations/channel_create.py
  saleor/graphql/channel/mutations/channel_update.py
  saleor/graphql/channel/tests/mutations/test_channel_update.py
Labels: skip changelog

#11918 Media update webhooks
  CHANGELOG.md
  poetry.lock
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/graphql/product/mutations/product/product_media_delete.py
  saleor/graphql/product/mutations/product/product_media_update.py
  saleor/graphql/product/tests/mutations/test_product_media_create.py
  saleor/graphql/product/tests/mutations/test_product_media_delete.py
  saleor/graphql/product/tests/mutations/test_product_media_update.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/webhook/enums.py
  saleor/graphql/webhook/subscription_payload.py
  saleor/graphql/webhook/subscription_types.py
  saleor/graphql/webhook/tests/mutations/test_webhook_dry_run.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/tests/fixtures.py
  saleor/thumbnail/views.py
  saleor/webhook/event_types.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: webhooks

#11833 Add native gzip support to the core
  CHANGELOG.md
  saleor/asgi/__init__.py
  saleor/asgi/gzip_compression.py
  saleor/asgi/tests/conftest.py
  saleor/asgi/tests/test_gzip.py
Labels: performance

#11981 Remove __str__ methods returning data
  saleor/account/models.py
  saleor/graphql/meta/mutations.py
  saleor/site/models.py
  saleor/site/tests/test_site_settings.py
Labels: skip changelog

#11982 Modify comment for PositiveDecimal to clarify it also accepts 0
  saleor/graphql/core/scalars.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#12003 Upgrade Django to 3.2.18
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.11

#12004 Upgrade Django to 3.2.18
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.10

#12005 Upgrade Django to 3.2.18
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.9

#12006 Upgrade Django to 3.2.18
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.8

#12007 Upgrade Django to 3.2.18
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.7

#12008 Upgrade Django to 3.2.18
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.1

#12010 Upgrade Django to 3.2.18
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, main

#11997 Fix email image payload
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
Labels: test deployment

#12000 Add missing support for simple requests in the CORS flow
  saleor/asgi/cors_handler.py
  saleor/asgi/tests/test_cors.py
  saleor/settings.py
Labels: bug, skip changelog

#11984 Fix migrations failing when missing site settings
  saleor/channel/migrations/0007_order_settings_per_channel.py
  saleor/channel/migrations/0008_update_null_order_settings.py
Labels: skip changelog

#11904 Add new inputs to ProductVariantBulkUpdate and allow to remove stocks and channel listings
  CHANGELOG.md
  saleor/graphql/core/types/common.py
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/mutations/product/product_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/schema.graphql
  saleor/product/utils/variants.py
Labels: test deployment, approved-breaking-change

#12029 Fix default db setup to replica.
  saleor/graphql/core/context.py
Labels: bug, 3.11

#12028 Fix default db setup to replica.
  saleor/graphql/core/context.py
Labels: bug, 3.10

#12027 Fix default db setup to replica.
  saleor/graphql/core/context.py
Labels: bug, skip changelog

#12025 Fix move order settings migration
  saleor/channel/migrations/0007_order_settings_per_channel.py
Labels: 3.11

#11974 Use default db for synchronous tax webhooks
  saleor/graphql/account/mutations/base.py
  saleor/graphql/context.py
  saleor/graphql/core/context.py
  saleor/graphql/core/mutations.py
  saleor/graphql/core/tests/test_graphql.py
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/product/mutations/digital_contents.py
  saleor/graphql/webhook/subscription_payload.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_webhook.py
Labels: 3.9

#12031 Fix email image payload
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
Labels: 3.10

#12032 Fix email image payload
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
Labels: 3.11

#12033 Fix email image payload
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
Labels: skip changelog

#12038 Include access-control-allow-credentials in the simple CORS flow
  saleor/asgi/cors_handler.py
  saleor/asgi/tests/test_cors.py
Labels: bug, skip changelog

#12044 Add sending order ids in batches in post migration signal
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: 3.9

#12053 Fix column name typo in SQL
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: 3.9

#11978 Webhook custom headers
  CHANGELOG.md
  saleor/app/error_codes.py
  saleor/app/installation_utils.py
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
  saleor/graphql/schema.graphql
  saleor/graphql/webhook/mutations/webhook_create.py
  saleor/graphql/webhook/mutations/webhook_update.py
  saleor/graphql/webhook/tests/mutations/test_webhook_create.py
  saleor/graphql/webhook/tests/mutations/test_webhook_update.py
  saleor/graphql/webhook/types.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/site/tests/test_site_settings.py
  saleor/webhook/error_codes.py
  saleor/webhook/migrations/0009_webhook_custom_headers.py
  saleor/webhook/models.py
  saleor/webhook/tests/test_webhook_validators.py
  saleor/webhook/validators.py
Labels: webhooks

#12050 Add sending order ids in batches in post migration signal
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: 3.10

#12052 Add sending order ids in batches in post migration signal
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: main, skip changelog

#12051 Add sending order ids in batches in post migration signal
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: 3.11

#12047 Drop event fields against events from query validation.
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: bug, webhooks, skip changelog

#11996 Default to serving 4K images instead of originals
  CHANGELOG.md
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/account/types.py
  saleor/graphql/core/types/common.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/mutations/test_product_media_delete.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/types/categories.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/plugins/email_common.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/thumbnail/__init__.py
  saleor/thumbnail/utils.py
  saleor/thumbnail/views.py
Labels: performance

#12055 Set flat rates as default tax calculation strategy
  saleor/graphql/tax/tests/queries/test_tax_configurations.py
  saleor/graphql/tax/types.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/tax/migrations/0007_auto_20230217_0837.py
  saleor/tests/fixtures.py
Labels: 3.9

#12067 Set flat rates as default tax calculation strategy
  saleor/graphql/tax/tests/queries/test_tax_configurations.py
  saleor/graphql/tax/types.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/tax/migrations/0007_auto_20230217_0837.py
  saleor/tests/fixtures.py
Labels: 3.10

#12068 Set flat rates as default tax calculation strategy
  saleor/graphql/tax/tests/queries/test_tax_configurations.py
  saleor/graphql/tax/types.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/tax/migrations/0007_auto_20230217_0837.py
  saleor/tests/fixtures.py
Labels: 3.11

#11989 remove unused variable `query_cost`
  saleor/graphql/views.py
Labels: skip changelog

#12058 Make custom header name case-insensitive.
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
  saleor/graphql/webhook/mutations/webhook_create.py
  saleor/graphql/webhook/tests/mutations/test_webhook_create.py
  saleor/graphql/webhook/tests/mutations/test_webhook_update.py
  saleor/webhook/tests/test_webhook_validators.py
  saleor/webhook/validators.py
Labels: bug, webhooks, skip changelog

#12066 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#12100 Fix saving metadata in variant bulk mutations
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
Labels: 3.11

#12113 Change batch size to leave margin for payload
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: 3.9

#12118 Change batch size to leave margin for payload
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: main, skip changelog

#12116 Change batch size to leave margin for payload
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: 3.10

#12117 Change batch size to leave margin for payload
  saleor/order/migrations/0139_fix_undiscounted_total_on_lines.py
Labels: 3.11

#12077 Optimize 0044_fulfill_checkout_line_new_fields migration
  saleor/checkout/migrations/0044_fulfill_checkout_line_new_fields.py
Labels: performance, 3.11

#12075 Optimize 0044_fulfill_checkout_line_new_fields migration
  saleor/checkout/migrations/0044_fulfill_checkout_line_new_fields.py
Labels: performance, 3.10

#12081 Optimize order 0150_update_authorize_and_charge_status migration
  saleor/order/migrations/0150_update_authorize_and_charge_status.py
Labels: performance, 3.10

#12082 Optimize order 0150_update_authorize_and_charge_status migration
  saleor/order/migrations/0150_update_authorize_and_charge_status.py
Labels: performance, 3.11

#12121 Fix CI
  .github/workflows/pytest.yml
Labels: 3.8

#12120 Fix CI
  .github/workflows/pytest.yml
Labels: 3.7

#12078 Optimize 0044_fulfill_checkout_line_new_fields migration
  saleor/checkout/migrations/0044_fulfill_checkout_line_new_fields.py
Labels: performance, skip changelog

#12073 Optimize 0044_fulfill_checkout_line_new_fields migration
  saleor/checkout/migrations/0044_fulfill_checkout_line_new_fields.py
Labels: performance, 3.7

#12079 Optimize order 0150_update_authorize_and_charge_status migration
  saleor/order/migrations/0150_update_authorize_and_charge_status.py
Labels: performance, 3.7

#12080 Optimize order 0150_update_authorize_and_charge_status migration
  saleor/order/migrations/0150_update_authorize_and_charge_status.py
Labels: performance, 3.8

#12074 Optimize 0044_fulfill_checkout_line_new_fields migration
  saleor/checkout/migrations/0044_fulfill_checkout_line_new_fields.py
Labels: performance, 3.8

#12045 Fix order filtering by charge status
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/queries/test_order_with_filter.py
Labels: skip changelog, 3.9

#12083 Optimize order 0150_update_authorize_and_charge_status migration
  saleor/order/migrations/0150_update_authorize_and_charge_status.py
Labels: performance, skip changelog

#12124 Fix order filtering by charge status
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/queries/test_order_with_filter.py
Labels: skip changelog, 3.11

#12125 Fix order filtering by charge status
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/queries/test_order_with_filter.py
Labels: skip changelog

#12103 Set unusable password on OIDC users
  CHANGELOG.md
  saleor/account/migrations/0076_fill_empty_passwords.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: bug

#12137 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#12141 Add manage_page_types_and_attributes permission to PageType
  saleor/graphql/page/tests/queries/test_page_type.py
  saleor/graphql/page/types.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#12158 Fix Avalara tax calculation for JPY currency
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[False-3493-4297-3.0-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[False-4300-5289-0.0-False].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[True-3484-4285-0.0-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[True-4280-5264-5.0-False].yaml
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/tests/fixtures.py
Labels: test deployment, 3.9
