Repository saleor/saleor, pull requests merged in 2023-01, with the labels that each got.

#11584 Add missing DB index for account private metadata
  saleor/account/migrations/0063_user_user_p_meta_jsonb_path_idx.py
  saleor/account/migrations/0065_merge_20221227_1254.py
  saleor/account/migrations/0066_merge_20221227_1315.py
  saleor/account/migrations/0071_merge_0066_merge_20221227_1315_0070_alter_user_uuid.py
  saleor/account/migrations/0072_merge_20221227_1353.py
  saleor/account/models.py
Labels: performance, skip changelog

#11583 Add missing DB index for account private metadata
  saleor/account/migrations/0063_user_user_p_meta_jsonb_path_idx.py
  saleor/account/migrations/0065_merge_20221227_1254.py
  saleor/account/migrations/0066_merge_20221227_1315.py
  saleor/account/migrations/0071_merge_0066_merge_20221227_1315_0070_alter_user_uuid.py
  saleor/account/models.py
Labels: performance, 3.9

#11582 Add missing DB index for account private metadata
  saleor/account/migrations/0063_user_user_p_meta_jsonb_path_idx.py
  saleor/account/migrations/0065_merge_20221227_1254.py
  saleor/account/migrations/0066_merge_20221227_1315.py
  saleor/account/migrations/0071_merge_0066_merge_20221227_1315_0070_alter_user_uuid.py
  saleor/account/models.py
Labels: performance, 3.8

#11581 Add missing DB index for account private metadata
  saleor/account/migrations/0063_user_user_p_meta_jsonb_path_idx.py
  saleor/account/migrations/0065_merge_20221227_1254.py
  saleor/account/migrations/0066_merge_20221227_1315.py
  saleor/account/migrations/0071_merge_0066_merge_20221227_1315_0070_alter_user_uuid.py
  saleor/account/models.py
Labels: performance, 3.7

#11580 Add missing DB index for account private metadata
  saleor/account/migrations/0063_user_user_p_meta_jsonb_path_idx.py
  saleor/account/migrations/0065_merge_20221227_1254.py
  saleor/account/migrations/0066_merge_20221227_1315.py
  saleor/account/migrations/0071_merge_0066_merge_20221227_1315_0070_alter_user_uuid.py
  saleor/account/models.py
Labels: performance, 3.6

#11579 Add missing DB index for account private metadata
  saleor/account/migrations/0063_user_user_p_meta_jsonb_path_idx.py
  saleor/account/migrations/0065_merge_20221227_1254.py
  saleor/account/migrations/0066_merge_20221227_1315.py
  saleor/account/models.py
Labels: performance, 3.5

#11578 Add missing DB index for account private metadata
  saleor/account/migrations/0063_user_user_p_meta_jsonb_path_idx.py
  saleor/account/migrations/0065_merge_20221227_1254.py
  saleor/account/migrations/0066_merge_20221227_1315.py
  saleor/account/models.py
Labels: performance, 3.4

#11577 Add missing DB index for account private metadata
  saleor/account/migrations/0063_user_user_p_meta_jsonb_path_idx.py
  saleor/account/migrations/0065_merge_20221227_1254.py
  saleor/account/models.py
Labels: performance, 3.3

#11576 Add missing DB index for account private metadata
  saleor/account/migrations/0063_user_user_p_meta_jsonb_path_idx.py
  saleor/account/migrations/0065_merge_20221227_1254.py
  saleor/account/models.py
Labels: performance, 3.2

#11571 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#11612 Bump pillow to 9.4.0
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.1

#11613 Bump pillow to 9.4.0
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.2

#11614 Bump pillow to 9.4.0
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.3

#11615 Bump pillow to 9.4.0
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.4

#11616 Bump pillow to 9.4.0
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.5

#11617 Bump pillow to 9.4.0
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.6

#11618 Bump pillow to 9.4.0
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.7

#11619 Bump pillow to 9.4.0
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.8

#11620 Bump pillow to 9.4.0
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.9

#11621 Add missing merge migration
  saleor/account/migrations/0074_merge_20230102_0914.py
Labels: skip changelog

#11554 Add migrations to improve initial DB state with default objects
  saleor/page/migrations/0028_add_default_page_type.py
  saleor/shipping/migrations/0033_add_default_shipping.py
  saleor/tax/migrations/0002_add_default_tax_configs.py
  saleor/warehouse/migrations/0031_create_default_warehouse.py
Labels: skip changelog

#11632 Fix propagating voucher value when tax calculation is disabled
  CHANGELOG.md
  saleor/checkout/base_calculations.py
  saleor/checkout/calculations.py
  saleor/checkout/tests/test_calculations.py
  saleor/tax/calculations/checkout.py
Labels: test deployment

#11638 Require django-stubs-ext
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: skip changelog

#11648 Rework checkout total calculation
  saleor/checkout/calculations.py
  saleor/checkout/tests/test_calculations.py
Labels: skip changelog

#11651 Rework checkout total calculation
  saleor/checkout/calculations.py
  saleor/checkout/tests/test_calculations.py
Labels: 3.9

#11663 Fix measurements installation; update deps.
  .github/workflows/pytest.yml
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: skip changelog

#11642 Fix drop Django Auth migration
  Dockerfile
  saleor/app/migrations/0018_auto_20221122_1148.py
Labels: test deployment, skip changelog

#11690 Add sphinxcontrib-applehelp to test migration workflow
  .github/workflows/test-migrations-compatibility.yml
Labels: skip changelog

#11677 Workaround for failing sphinxcontrib-applehelp dependency
  .github/workflows/pytest.yml
  .pre-commit-config.yaml
  Dockerfile
Labels: 3.2

#11679 Workaround for failing sphinxcontrib-applehelp dependency
  .github/workflows/pytest.yml
  .pre-commit-config.yaml
  Dockerfile
Labels: 3.3

#11680 Workaround for failing sphinxcontrib-applehelp dependency
  .github/workflows/pytest.yml
  .pre-commit-config.yaml
  Dockerfile
Labels: 3.4

#11681 Workaround for failing sphinxcontrib-applehelp dependency
  .github/workflows/pytest.yml
  .pre-commit-config.yaml
  Dockerfile
Labels: 3.5

#11682 Workaround for failing sphinxcontrib-applehelp dependency
  .github/workflows/pytest.yml
  .pre-commit-config.yaml
  Dockerfile
Labels: 3.6

#11683 Workaround for failing sphinxcontrib-applehelp dependency
  .github/workflows/pytest.yml
  .pre-commit-config.yaml
  Dockerfile
Labels: 3.7

#11684 Workaround for failing sphinxcontrib-applehelp dependency
  .github/workflows/pytest.yml
  .pre-commit-config.yaml
  Dockerfile
Labels: 3.8

#11685 Workaround for failing sphinxcontrib-applehelp dependency
  .github/workflows/pytest.yml
  Dockerfile
Labels: 3.9

#11667 Fix missing psp references for some adyen payments
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_additional_actions.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
Labels: 3.3

#11668 Fix missing psp references for some adyen payments
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_additional_actions.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
Labels: 3.4

#11669 Fix missing psp references for some adyen payments
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_additional_actions.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
Labels: 3.5

#11670 Fix missing psp references for some adyen payments
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_additional_actions.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
Labels: 3.6

#11671 Fix missing psp references for some adyen payments
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_additional_actions.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
Labels: 3.7

#11672 Fix missing psp references for some adyen payments
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_additional_actions.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
Labels: 3.8

#11673 Fix missing psp references for some adyen payments
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_additional_actions.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
Labels: 3.9

#11674 Fix missing psp references for some adyen payments
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_additional_actions.py
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
Labels: skip changelog

#11692 Fix failing adyen confirm
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: skip changelog

#11700 Fix failing adyen confirm
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.2

#11699 Fix failing adyen confirm
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.3

#11698 Fix failing adyen confirm
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.4

#11697 Fix failing adyen confirm
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.5

#11696 Fix failing adyen confirm
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.6

#11695 Fix failing adyen confirm
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.7

#11694 Fix failing adyen confirm
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.8

#11693 Fix failing adyen confirm
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.9

#11650 Fix incorrect payment captured amount for Adyen
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/utils.py
Labels: 3.1

#11712 Add sphinxcontrib-applehelp to test migration workflow
  .github/workflows/test-migrations-compatibility.yml
Labels: 3.9

#11703 Fix incorrect payment captured amount for Adyen
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/utils.py
Labels: 3.2

#11705 Fix incorrect payment captured amount for Adyen
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/utils.py
Labels: 3.4

#11706 Fix incorrect payment captured amount for Adyen
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/utils.py
Labels: 3.5

#11708 Fix incorrect payment captured amount for Adyen
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/utils.py
Labels: 3.8

#11709 Fix incorrect payment captured amount for Adyen
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/utils.py
Labels: 3.9

#11710 Fix incorrect payment captured amount for Adyen
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/utils.py
Labels: skip changelog

#11711 Fix incorrect payment captured amount for Adyen
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_notifications.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/utils.py
Labels: 3.7

#11688 Fix app constraint name
  saleor/app/migrations/0019_fix_constraint_names_in_app_app_permisons.py
Labels: test deployment, skip changelog

#11732 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#11724 Update Heroku configs
  README.md
  app.json
Labels: skip changelog

#11734 Fix null and nonnull comparison in sorting product media
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/types/products.py
  saleor/tests/fixtures.py
Labels: skip changelog

#11741 Fix media sort
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/types/products.py
  saleor/tests/fixtures.py
Labels: 3.10

#11739 Fix failing mutations for swatch attributes
  saleor/graphql/attribute/types.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/product/tests/mutations/test_product_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/graphql/schema.graphql
Labels: skip changelog, 3.9

#11744 Fix failing mutations for swatch attributes
  saleor/graphql/attribute/types.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/product/tests/mutations/test_product_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#11743 Fix failing mutations for swatch attributes
  saleor/graphql/attribute/types.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/product/tests/mutations/test_product_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/graphql/schema.graphql
Labels: 3.10

#11740 Fix media sort
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/types/products.py
  saleor/tests/fixtures.py
Labels: 3.9

#11745 Delete warehouse reservations in clearorders command
  saleor/core/management/commands/clearorders.py
Labels: 3.10

#11746 Delete warehouse reservations in clearorders command
  saleor/core/management/commands/clearorders.py
Labels: skip changelog

#11751 Use the latest v3 release of the GraphQL Inspector
  .github/workflows/graphql-inspector.yml
Labels: skip changelog

#11752 Update the CodeQL analyzer action to v2
  .github/workflows/codeql-analysis.yml
Labels: skip changelog

#11761 Downgrade buildkit version in container image publisher CI
  .github/workflows/publish-containers.yml
Labels: bug, skip changelog

#11763 Update the support matrix
  SECURITY.md
Labels: skip changelog

#11764 Downgrade buildkit version in container image publisher CI
  .github/workflows/publish-containers.yml
Labels: 3.1

#11765 Downgrade buildkit version in container image publisher CI
  .github/workflows/publish-containers.yml
Labels: 3.2

#11766 Downgrade buildkit version in container image publisher CI
  .github/workflows/publish-containers.yml
Labels: 3.3

#11767 Downgrade buildkit version in container image publisher CI
  .github/workflows/publish-containers.yml
Labels: 3.4

#11768 Downgrade buildkit version in container image publisher CI
  .github/workflows/publish-containers.yml
Labels: 3.5

#11769 Downgrade buildkit version in container image publisher CI
  .github/workflows/publish-containers.yml
Labels: 3.6

#11770 Downgrade buildkit version in container image publisher CI
  .github/workflows/publish-containers.yml
Labels: 3.7

#11771 Downgrade buildkit version in container image publisher CI
  .github/workflows/publish-containers.yml
Labels: 3.8

#11772 Downgrade buildkit version in container image publisher CI
  .github/workflows/publish-containers.yml
Labels: 3.9

#11773 Downgrade buildkit version in container image publisher CI
  .github/workflows/publish-containers.yml
Labels: 3.10

#11754 change thumbnails sizes keys to str
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: skip changelog, 3.9

#11747 Delete warehouse reservations in clearorders command
  saleor/core/management/commands/clearorders.py
Labels: 3.9

#11774 change thumbnails sizes keys to str
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: skip changelog

#11762 Fix updating prices in confirmed order
  saleor/graphql/order/mutations/orders.py
  saleor/graphql/order/tests/test_order.py
Labels: 3.1

#11775 Fix thumbnails size key error main
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: skip changelog

#11785 Disable websocket support in uvicorn
  CHANGELOG.md
  saleor/asgi/gunicorn_worker.py
Labels: bug

#11760 fix parameters in stripe update payment method
  saleor/payment/gateways/stripe/stripe_api.py
  saleor/payment/gateways/stripe/tests/test_plugin.py
  saleor/payment/gateways/stripe/tests/test_plugin_deprecated.py
  saleor/payment/gateways/stripe/tests/test_stripe_api.py
Labels: skip changelog

#11795 [Bugfix] Fix issue with checkout complete for free shippng voucher without tax class
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_preprocess_order_creation_shipping_voucher_no_tax_class_on_delivery_method.yaml
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.9

#11793 Fix thumbnails keys
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: 3.7

#11777 Fix createsuperuser command
  saleor/account/management/commands/createsuperuser.py
  saleor/account/models.py
  saleor/account/tests/test_account_command.py
  saleor/graphql/tests/fixtures.py
  saleor/tests/fixtures.py
Labels: skip changelog

#11796 [Bugfix] Fix issue with checkout complete for free shippng voucher without tax class
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_preprocess_order_creation_shipping_voucher_no_tax_class_on_delivery_method.yaml
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/site/models.py
Labels: skip changelog

#11784 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#11807 Add Celery beat expiration option in update product search entry
  saleor/product/tasks.py
  saleor/settings.py
Labels: performance, skip changelog

#11805 Remove preorders, discounts and addresses in clearorders command
  saleor/core/management/commands/clearorders.py
  saleor/core/utils/random_data.py
Labels: skip changelog

#11813 Remove preorders, discounts and addresses in clearorders command
  saleor/core/management/commands/clearorders.py
  saleor/core/utils/random_data.py
Labels: 3.10

#11812 Remove preorders, discounts and addresses in clearorders command
  saleor/core/management/commands/clearorders.py
  saleor/core/utils/random_data.py
Labels: 3.9

#11810 Fix createsuperuser command
  saleor/account/management/commands/createsuperuser.py
  saleor/account/models.py
  saleor/account/tests/test_account_command.py
  saleor/graphql/tests/fixtures.py
  saleor/tests/fixtures.py
Labels: skip changelog, 3.10

#11815 Update readme
  README.md
Labels: skip changelog

#11814 Fix OIDC plugin crashing when given a JWT without an exp claim
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: bug

#11826 Fix stock events triggers
  saleor/graphql/product/bulk_mutations/products.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
Labels: skip changelog

#11835 Fix null metadata values in tax class migration
  saleor/tax/migrations/0004_migrate_tax_classes.py
Labels: 3.9

#11836 Fix null metadata values in tax class migration
  saleor/tax/migrations/0004_migrate_tax_classes.py
Labels: 3.10

#11837 Fix null metadata values in tax class migration
  saleor/tax/migrations/0004_migrate_tax_classes.py
Labels: 3.11

#11842 Fix warehouse address update to country with different validation rules
  saleor/account/forms.py
  saleor/graphql/warehouse/tests/test_warehouse.py
Labels: skip changelog

#11860 Revert "Downgrade buildkit version"
  .github/workflows/publish-containers.yml
Labels: technical debt
