Repository saleor/saleor, pull requests merged in 2023-10, with the labels that each got.

#14145 Strict connection timeout settings
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/core/http_client.py
  saleor/graphql/app/mutations/app_fetch_manifest.py
  saleor/graphql/app/tests/mutations/test_app_fetch_manifest.py
  saleor/graphql/core/validators/file.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/payment/gateways/adyen/tests/utils/test_apple_pay.py
  saleor/payment/gateways/adyen/utils/apple_pay.py
  saleor/payment/gateways/adyen/utils/common.py
  saleor/payment/gateways/authorize_net/__init__.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/payment/gateways/np_atobarai/const.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/openid_connect/utils.py
  saleor/settings.py
Labels: 3.16

#14122 Use voucher code in `VoucherCustomer`
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/discount/migrations/0054_vouchercustomer_vouchercode.py
  saleor/discount/migrations/0055_vouchercustomer_voucher_code_index.py
  saleor/discount/migrations/0056_set_vouchercustomer_codes.py
  saleor/discount/migrations/0057_alter_vouchercustomer_code_and_drop_voucher.py
  saleor/discount/models.py
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils.py
  saleor/order/tasks.py
  saleor/tests/fixtures.py
Labels: voucher

#14147 Add `singleUse` voucher
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/utils.py
  saleor/discount/migrations/0058_voucher_single_use.py
  saleor/discount/models.py
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/discount/mutations/voucher/voucher_create.py
  saleor/graphql/discount/tests/mutations/test_voucher_create.py
  saleor/graphql/discount/tests/mutations/test_voucher_update.py
  saleor/graphql/discount/types/vouchers.py
  saleor/graphql/schema.graphql
Labels: voucher

#14148 Strict connection timeout settings
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/core/http_client.py
  saleor/graphql/app/mutations/app_fetch_manifest.py
  saleor/graphql/app/tests/mutations/test_app_fetch_manifest.py
  saleor/graphql/core/validators/file.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/payment/gateways/adyen/tests/utils/test_apple_pay.py
  saleor/payment/gateways/adyen/utils/apple_pay.py
  saleor/payment/gateways/adyen/utils/common.py
  saleor/payment/gateways/authorize_net/__init__.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/payment/gateways/np_atobarai/const.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/openid_connect/utils.py
  saleor/settings.py
Labels: skip changelog

#14160 Upgrade urllib3 to v1.26.17
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.11

#14155 Upgrade urllib3 to v1.26.17
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.16

#14156 Upgrade urllib3 to v1.26.17
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.15

#14157 Upgrade urllib3 to v1.26.17
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.14

#14158 Upgrade urllib3 to v1.26.17
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.13

#14094 change `User-Agent` header for webhooks to `Saleor/version`
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/__init__.py
  saleor/app/installation_utils.py
  saleor/core/http_client.py
  saleor/core/tests/test_http_client.py
  saleor/payment/gateways/adyen/utils/apple_pay.py
Labels: webhooks, skip changelog

#14161 Upgrade urllib3 to v1.26.17
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, main

#14163 Add customizable schedule frequency for update-search tasks
  saleor/settings.py
Labels: 3.16

#14162 Fix task migrating sales to promotions
  saleor/discount/migrations/tasks/saleor3_16.py
Labels: promotions, 3.16

#14172 Fix usage of replica in get_webhooks_for_event
  saleor/plugins/webhook/plugin.py
  saleor/webhook/utils.py
Labels: 3.14

#14173 Fix usage of replica in get_webhooks_for_event
  saleor/plugins/webhook/plugin.py
  saleor/webhook/utils.py
Labels: 3.15

#14174 Fix usage of replica in get_webhooks_for_event
  saleor/plugins/webhook/plugin.py
  saleor/webhook/utils.py
Labels: 3.16

#14132 [TEST] Promotions query with different params CORE_2118
  saleor/tests/e2e/metadata/__init__.py
  saleor/tests/e2e/metadata/utils/__init__.py
  saleor/tests/e2e/metadata/utils/update_metadata.py
  saleor/tests/e2e/metadata/utils/update_private_metadata.py
  saleor/tests/e2e/promotions/test_promotions_query_with_different_parameters.py
  saleor/tests/e2e/promotions/utils/promotion_create.py
  saleor/tests/e2e/promotions/utils/promotions_query.py
Labels: skip changelog, promotions

#14176 Fix migrate sales to promotions task
  saleor/discount/migrations/0048_remigrate_sales_to_promotions.py
  saleor/discount/migrations/tasks/saleor3_16.py
  saleor/product/utils/variant_prices.py
Labels: promotions, 3.16

#14168 Fix migration for migrating sales to promotions and discounted price recalculation
  saleor/discount/migrations/0047_migrate_sales_to_promotions.py
  saleor/discount/migrations/0048_remigrate_sales_to_promotions.py
  saleor/discount/migrations/0050_merge_20231004_1306.py
  saleor/product/utils/variant_prices.py
Labels: skip changelog, promotions, 3.17

#14184 Fix sale created resolver
  saleor/graphql/discount/tests/queries/test_sales.py
  saleor/graphql/discount/types/sales.py
Labels: 3.14

#14124 Add VoucherCodeBulkDelete mutation
  saleor/discount/error_codes.py
  saleor/graphql/core/enums.py
  saleor/graphql/core/types/__init__.py
  saleor/graphql/core/types/common.py
  saleor/graphql/discount/mutations/__init__.py
  saleor/graphql/discount/mutations/voucher/voucher_code_bulk_delete.py
  saleor/graphql/discount/schema.py
  saleor/graphql/discount/tests/benchmark/test_voucher_code_bulk_delete.py
  saleor/graphql/discount/tests/mutations/test_voucher_code_bulk_delete.py
  saleor/graphql/discount/types/__init__.py
  saleor/graphql/discount/types/vouchers.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: voucher

#14177 Order bulk create allow to import archive orders
  CHANGELOG.md
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
  saleor/graphql/order/tests/mutations/test_order_bulk_create.py
Labels: test deployment, 3.17, main

#14133 Deprecate external_url in Invoice in favour of url
  CHANGELOG.md
  saleor/graphql/invoice/types.py
  saleor/graphql/order/tests/mutations/test_order_bulk_create.py
  saleor/graphql/schema.graphql
Labels: invoice

#14190 Fix sale created resolver
  saleor/graphql/discount/tests/queries/test_sales.py
  saleor/graphql/discount/types/sales.py
Labels: 3.15

#14189 Clear discount 0047 migration
  saleor/discount/migrations/0047_migrate_sales_to_promotions.py
  saleor/discount/migrations/tasks/saleor3_16.py
Labels: 3.16

#14191 Fix sale created resolver
  saleor/graphql/discount/tests/queries/test_sales.py
  saleor/graphql/discount/types/sales.py
Labels: 3.16

#14192 Fix sale created resolver
  saleor/graphql/discount/tests/queries/test_sales.py
Labels: skip changelog, 3.17, main

#14201 Add missing ordering in dataloaders
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/discount/dataloaders.py
  saleor/graphql/order/dataloaders.py
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/shipping/dataloaders.py
  saleor/graphql/warehouse/dataloaders.py
Labels: 3.17

#14200 Add missing ordering in dataloaders
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/discount/dataloaders.py
  saleor/graphql/order/dataloaders.py
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/shipping/dataloaders.py
  saleor/graphql/warehouse/dataloaders.py
Labels: skip changelog, main

#14204 Bump to 3.18
  CHANGELOG.md
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
  saleor/graphql/core/descriptions.py
Labels: main

#14202 Fix sale created resolver
  saleor/graphql/discount/tests/queries/test_sales.py
Labels: 3.17

#14220 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#14209 Ref 13142 : Minor fix in description of payment module.
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#14221 [TEST] Sale updated by promotionTranslation cannot be handled by sale mutations and queries
  saleor/tests/e2e/promotions/test_unable_to_query_nor_mutate_sale_updated_by_promotion_translations.py
Labels: skip changelog, promotions

#14205 Add missing payload fields
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/graphql/order/types.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#14198 Add transaction items deletion to cleardb command
  CHANGELOG.md
  saleor/core/management/commands/cleardb.py
  saleor/core/tests/test_core.py
Labels: bug, main

#14222 Bump django to 3.2.22
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.16

#14223 Bump django to 3.2.22
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.15

#14224 Bump django to 3.2.22
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.14

#14225 Bump django to 3.2.22
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.17

#14226 Bump django to 3.2.22
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.12

#14227 Bump django to 3.2.22
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.13

#14228 Bump django to 3.2.22
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.11

#14229 Bump django to 3.2.22
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: skip changelog, main

#14237 Add missing payload fields
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/graphql/order/types.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: 3.17

#14238 Add missing payload fields
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/graphql/order/types.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: skip changelog, main

#14239 Fix voucher update without codes
  saleor/graphql/discount/mutations/voucher/voucher_create.py
  saleor/graphql/discount/mutations/voucher/voucher_update.py
  saleor/graphql/discount/tests/mutations/test_voucher_create.py
  saleor/graphql/discount/tests/mutations/test_voucher_update.py
Labels: voucher, skip changelog

#14242 Move migration tasks to migration code
  saleor/attribute/migrations/0034_assignedpageattributevalue_page_data_migration.py
  saleor/attribute/migrations/0036_assignedproductattributevalue_product_data_migration.py
  saleor/attribute/migrations/tasks/__init__.py
  saleor/attribute/migrations/tasks/saleor3_16.py
  saleor/attribute/tests/test_page_attributes_migration.py
  saleor/celeryconf.py
Labels: 3.17

#14230 [Test] Voucher that applies only to a single cheapest eligible product
  saleor/tests/e2e/checkout/test_checkout_calculate_correct_discount_for_sale_and_voucher.py
  saleor/tests/e2e/checkout/test_checkout_use_voucher_for_cheapest_product.py
  saleor/tests/e2e/checkout/test_checkout_with_fixed_voucher.py
  saleor/tests/e2e/checkout/test_checkout_with_free_shipping_voucher.py
  saleor/tests/e2e/checkout/test_checkout_with_promotion_and_voucher.py
  saleor/tests/e2e/checkout/test_staff_user_can_use_voucher_for_staff_only.py
  saleor/tests/e2e/checkout/utils/checkout_add_promo_code.py
  saleor/tests/e2e/checkout/utils/checkout_create.py
  saleor/tests/e2e/vouchers/utils/voucher_create.py
Labels: skip changelog

#14234 [TEST] Unable to void payment when no payment was made on the order CORE_0210
  saleor/tests/e2e/orders/test_unable_to_void_order_without_payment.py
  saleor/tests/e2e/orders/utils/__init__.py
  saleor/tests/e2e/orders/utils/order_void.py
Labels: skip changelog

#14232 Add missing payload fields (#14205)
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/graphql/order/types.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: 3.15

#14233 Add missing payload fields (#14205)
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/graphql/order/types.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: 3.16

#14244 [TEST] Customer should not be able to use voucher for staff only CORE_0905
  saleor/tests/e2e/checkout/test_checkout_user_cannot_use_voucher_for_staff_only.py
Labels: voucher, skip changelog, promotions

#14245 [TEST] Staff can void payment CORE_0116
  saleor/tests/e2e/checkout/test_checkout_void_payment.py
  saleor/tests/e2e/checkout/test_should_pay_for_checkout_with_gift_card.py
  saleor/tests/e2e/checkout/test_unlogged_customer_should_not_be_able_to_buy_product_without_shipping_option.py
  saleor/tests/e2e/checkout/utils/checkout_payment_create.py
  saleor/tests/e2e/orders/utils/order_void.py
Labels: skip changelog

#14250 Fix passing shipping address to Adyen (#14246)
  saleor/payment/gateways/adyen/tests/utils/test_common.py
  saleor/payment/gateways/adyen/utils/common.py
Labels: skip changelog

#14249 Fix passing shipping address to Adyen (#14246)
  saleor/payment/gateways/adyen/tests/utils/test_common.py
  saleor/payment/gateways/adyen/utils/common.py
Labels: 3.17

#14248 Fix passing shipping address to Adyen (#14246)
  saleor/payment/gateways/adyen/tests/utils/test_common.py
  saleor/payment/gateways/adyen/utils/common.py
Labels: 3.16

#14247 Fix passing shipping address to Adyen (#14246)
  saleor/payment/gateways/adyen/tests/utils/test_common.py
  saleor/payment/gateways/adyen/utils/common.py
Labels: 3.15

#14252 [TEST] Should be able to remove shipping method from checkout CORE_0115
  saleor/tests/e2e/checkout/test_checkout_should_be_able_to_remove_shipping_method.py
  saleor/tests/e2e/checkout/utils/checkout_delivery_method_update.py
Labels: skip changelog

#14254 [TEST] Unable to void once voided payment CORE_0218
  saleor/tests/e2e/orders/test_order_void_once_voided_payment.py
  saleor/tests/e2e/orders/test_order_void_payment.py
  saleor/tests/e2e/orders/utils/order_query.py
Labels: skip changelog

#14266 Bump kciter/aws-ecr-action to v4 for migrations perf test
  .github/workflows/migrations-perf-test.yml
Labels: migrations perf test, skip changelog

#14265 Bump kciter/aws-ecr-action to v4 for migrations perf test
  .github/workflows/migrations-perf-test.yml
Labels: migrations perf test

#14255 [TEST] Unable to void order marked as paid CORE_0211
  saleor/tests/e2e/orders/test_unable_to_void_order_marked_as_paid.py
  saleor/tests/e2e/orders/utils/order_mark_as_paid.py
  saleor/tests/e2e/orders/utils/order_query.py
Labels: skip changelog

#14280 Move update product search vector to celery task
  saleor/graphql/attribute/bulk_mutations.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/mutations/attributes.py
  saleor/graphql/product/mutations/product/product_create.py
  saleor/graphql/product/mutations/product/product_update.py
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/graphql/product/mutations/product_variant/product_variant_delete.py
  saleor/graphql/product/tests/mutations/test_product_create.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/product/search.py
  saleor/product/tests/test_product_search.py
Labels: bug, 3.15

#14271 [TEST] Fulfill order and add tracking number CORE_0219
  saleor/tests/e2e/account/test_should_create_account_without_email_confirmation.py
  saleor/tests/e2e/orders/test_order_fulfill_and_add_tracking.py
  saleor/tests/e2e/orders/utils/__init__.py
  saleor/tests/e2e/orders/utils/order_fulfill.py
  saleor/tests/e2e/orders/utils/order_fulfill_add_tracking.py
  saleor/tests/e2e/orders/utils/order_lines_create.py
  saleor/tests/e2e/shop/utils/shop_update_settings.py
Labels: skip changelog

#14269 Drop recursion from migrations
  saleor/attribute/migrations/0034_assignedpageattributevalue_page_data_migration.py
  saleor/attribute/migrations/0036_assignedproductattributevalue_product_data_migration.py
  saleor/discount/migrations/0047_migrate_sales_to_promotions.py
Labels: 3.17

#14263 [Test] Calculate simple taxes based on shipping country tax rate
  saleor/tests/e2e/checkout/test_checkout_calculate_simple_taxes_based_on_shipping_country.py
  saleor/tests/e2e/checkout/utils/__init__.py
  saleor/tests/e2e/checkout/utils/checkout_complete.py
  saleor/tests/e2e/checkout/utils/checkout_delivery_method_update.py
  saleor/tests/e2e/checkout/utils/query_checkout.py
  saleor/tests/e2e/shipping_zone/utils/shipping_zone.py
  saleor/tests/e2e/taxes/__init__.py
  saleor/tests/e2e/taxes/utils/__init__.py
  saleor/tests/e2e/taxes/utils/query_tax_configurations.py
  saleor/tests/e2e/taxes/utils/tax_configuration_update.py
  saleor/tests/e2e/taxes/utils/tax_country_configuration_update.py
Labels: skip changelog

#14256 Fix null amount when transaction amount is 0
  saleor/graphql/payment/mutations.py
  saleor/graphql/webhook/subscription_types.py
Labels: 3.14

#14272 Fix null amount when transaction amount is 0
  saleor/graphql/payment/mutations/transaction/transaction_request_action.py
  saleor/graphql/webhook/subscription_types.py
Labels: 3.15

#14273 Fix null amount when transaction amount is 0
  saleor/graphql/payment/mutations/transaction/transaction_request_action.py
  saleor/graphql/webhook/subscription_types.py
Labels: 3.16

#14274 Fix null amount when transaction amount is 0
  saleor/graphql/payment/mutations/transaction/transaction_request_action.py
  saleor/graphql/webhook/subscription_types.py
Labels: 3.17

#14275 Fix null amount when transaction amount is 0
  saleor/graphql/payment/mutations/transaction/transaction_request_action.py
  saleor/graphql/webhook/subscription_types.py
Labels: skip changelog, main

#14283 Move update product search vector to celery task
  saleor/graphql/attribute/bulk_mutations.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/mutations/attributes.py
  saleor/graphql/product/mutations/product/product_create.py
  saleor/graphql/product/mutations/product/product_update.py
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/graphql/product/mutations/product_variant/product_variant_delete.py
  saleor/graphql/product/tests/mutations/test_product_create.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/product/search.py
  saleor/product/tests/test_product_search.py
Labels: skip changelog

#14281 Move update product search vector to celery task
  saleor/graphql/attribute/bulk_mutations.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/mutations/attributes.py
  saleor/graphql/product/mutations/product/product_create.py
  saleor/graphql/product/mutations/product/product_update.py
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/graphql/product/mutations/product_variant/product_variant_delete.py
  saleor/graphql/product/tests/mutations/test_product_create.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/product/search.py
  saleor/product/tests/test_product_search.py
Labels: bug, 3.16

#14284 [TEST] Order cancel fulfillment CORE_0220 & Order create invoice with metadata CORE_0212
  saleor/tests/e2e/orders/test_order_cancel_fulfillment.py
  saleor/tests/e2e/orders/test_order_create_invoice_with_metadata.py
  saleor/tests/e2e/orders/utils/__init__.py
  saleor/tests/e2e/orders/utils/order_fulfillment_cancel.py
  saleor/tests/e2e/orders/utils/order_invoice_create.py
Labels: skip changelog

#14296 Add transaction items deletion to cleardb command
  saleor/core/management/commands/cleardb.py
  saleor/core/tests/test_core.py
Labels: 3.14

#14295 Add transaction items deletion to cleardb command
  saleor/core/management/commands/cleardb.py
  saleor/core/tests/test_core.py
Labels: 3.15

#14294 Add transaction items deletion to cleardb command
  saleor/core/management/commands/cleardb.py
  saleor/core/tests/test_core.py
Labels: 3.16

#14293 Add transaction items deletion to cleardb command
  saleor/core/management/commands/cleardb.py
  saleor/core/tests/test_core.py
Labels: 3.17

#14315 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#14240 Optimize webhooks calls in bulk mutations
  CHANGELOG.md
  saleor/graphql/account/bulk_mutations/customer_bulk_delete.py
  saleor/graphql/account/bulk_mutations/customer_bulk_update.py
  saleor/graphql/account/tests/bulk_mutations/test_customer_bulk_delete.py
  saleor/graphql/core/mutations.py
  saleor/graphql/discount/mutations/bulk_mutations.py
  saleor/graphql/discount/tests/mutations/test_sale_bulk_delete.py
  saleor/graphql/discount/tests/mutations/test_voucher_bulk_delete.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_activate.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_create.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_deactivate.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_delete.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_activate.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_create.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_deactivate.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_delete.py
  saleor/graphql/menu/bulk_mutations/menu_bulk_delete.py
  saleor/graphql/menu/bulk_mutations/menu_item_bulk_delete.py
  saleor/graphql/menu/tests/bulk_mutations/test_menu_bulk_delete.py
  saleor/graphql/menu/tests/bulk_mutations/test_menu_item_bulk_delete.py
  saleor/graphql/order/bulk_mutations/order_bulk_cancel.py
  saleor/graphql/order/schema.py
  saleor/graphql/order/tests/mutations/test_order_bulk_cancel.py
  saleor/graphql/product/bulk_mutations/collection_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_create.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/benchmark/test_variant_stocks.py
  saleor/graphql/product/tests/deprecated/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/bulk_mutations/shipping_price_bulk_delete.py
  saleor/graphql/shipping/bulk_mutations/shipping_zone_bulk_delete.py
  saleor/graphql/shipping/tests/mutations/test_bulk_delete.py
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/graphql/warehouse/tests/bulk_mutations/test_stock_bulk_update.py
  saleor/order/actions.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/product/tests/test_category.py
  saleor/product/utils/__init__.py
Labels: performance, webhooks, skip changelog

#14277 Drop sale tables and celery tasks
  saleor/discount/migrations/0055_drop_sales_from_db.py
  saleor/discount/tasks.py
  saleor/product/tasks.py
  saleor/product/tests/deprecated/__init__.py
  saleor/product/tests/deprecated/test_tasks.py
Labels: test deployment, skip changelog, promotions, 3.18

#14241 Adjust order line discount info
  saleor/checkout/complete_checkout.py
  saleor/discount/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/order/utils.py
  saleor/tests/e2e/checkout/test_checkout_calculate_correct_discount_for_sale_and_voucher.py
  saleor/tests/e2e/checkout/test_checkout_product_on_fixed_sale.py
  saleor/tests/e2e/checkout/test_checkout_product_on_percentage_sale.py
  saleor/tests/e2e/checkout/test_checkout_products_on_fixed_promotion.py
  saleor/tests/e2e/checkout/test_checkout_products_on_percentage_promotion.py
  saleor/tests/e2e/checkout/test_checkout_with_promotion_and_voucher.py
  saleor/tests/e2e/orders/test_apply_better_promotion_to_product.py
  saleor/tests/e2e/orders/test_order_product_with_percentage_promotion.py
  saleor/tests/e2e/orders/test_order_products_from_the_same_category_on_fixed_promotion.py
  saleor/tests/e2e/orders/test_order_products_on_fixed_promotion.py
  saleor/tests/e2e/orders/test_order_products_on_fixed_sale.py
  saleor/tests/e2e/orders/test_order_products_on_percentage_sale.py
  saleor/tests/e2e/orders/test_order_products_on_promotion_and_manual_order_discount.py
  saleor/tests/e2e/orders/test_order_promotion_still_applied_to_the_order_when_promotion_is_removed.py
Labels: test deployment, promotions, 3.17

#14323 Fix duplicated authorization plugin calls
  saleor/core/auth_backend.py
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/tests/test_context.py
  saleor/plugins/tests/sample_plugins.py
Labels: skip changelog, main

#14321 Fix duplicated authorization plugin calls
  saleor/core/auth_backend.py
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/tests/test_context.py
  saleor/plugins/tests/sample_plugins.py
Labels: 3.17

#14319 Fix duplicated authorization plugin calls
  saleor/core/auth_backend.py
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/tests/test_context.py
  saleor/plugins/tests/sample_plugins.py
Labels: 3.16

#14318 Fix duplicated authorization plugin calls
  saleor/core/auth_backend.py
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/tests/test_context.py
  saleor/plugins/tests/sample_plugins.py
Labels: 3.15

#14317 Fix descriptions to not include storefront
  saleor/graphql/checkout/types.py
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
  saleor/graphql/order/types.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/tax/mutations/tax_configuration_update.py
  saleor/graphql/tax/types.py
Labels: skip changelog

#13854 misleading Domain description fixed
  saleor/graphql/schema.graphql
  saleor/graphql/shop/types.py
Labels: skip changelog

#14324 [Test] Order calculate simple taxes based on product type tax class rate
  saleor/tests/e2e/orders/test_order_calculate_simple_taxes_product_type_tax_class.py
  saleor/tests/e2e/orders/utils/draft_order_complete.py
  saleor/tests/e2e/orders/utils/draft_order_update.py
  saleor/tests/e2e/orders/utils/order_lines_create.py
Labels: skip changelog

#14322 Adjust order line discount info
  saleor/checkout/complete_checkout.py
  saleor/discount/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/order/utils.py
  saleor/tests/e2e/checkout/test_checkout_calculate_correct_discount_for_sale_and_voucher.py
  saleor/tests/e2e/checkout/test_checkout_product_on_fixed_sale.py
  saleor/tests/e2e/checkout/test_checkout_product_on_percentage_sale.py
  saleor/tests/e2e/checkout/test_checkout_products_on_fixed_promotion.py
  saleor/tests/e2e/checkout/test_checkout_products_on_percentage_promotion.py
  saleor/tests/e2e/checkout/test_checkout_with_promotion_and_voucher.py
  saleor/tests/e2e/orders/test_apply_better_promotion_to_product.py
  saleor/tests/e2e/orders/test_order_product_with_percentage_promotion.py
  saleor/tests/e2e/orders/test_order_products_from_the_same_category_on_fixed_promotion.py
  saleor/tests/e2e/orders/test_order_products_on_fixed_promotion.py
  saleor/tests/e2e/orders/test_order_products_on_fixed_sale.py
  saleor/tests/e2e/orders/test_order_products_on_percentage_sale.py
  saleor/tests/e2e/orders/test_order_products_on_promotion_and_manual_order_discount.py
  saleor/tests/e2e/orders/test_order_promotion_still_applied_to_the_order_when_promotion_is_removed.py
Labels: skip changelog, promotions, main

#14257 Enforce decision about migrations performance test
  .github/workflows/migrations-perf-test-check.yml
Labels: skip changelog, skip migrations perf test

#14332 [Test] Checkout calculate simple taxes base on product tax class rate
  saleor/tests/e2e/checkout/test_checkout_calculate_simple_taxes_product_tax_class.py
  saleor/tests/e2e/product/utils/__init__.py
  saleor/tests/e2e/product/utils/product_update.py
Labels: skip changelog

#14335 [TEST] Calculate simple tax based on shipping address tax class for order
  saleor/tests/e2e/orders/test_order_calculate_simple_tax_based_on_shipping_address_tax_class.py
  saleor/tests/e2e/orders/utils/order_lines_create.py
Labels: skip changelog

#14334 Pytest should delete all temporary files
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
Labels: skip changelog

#14325 optimize webhooks calls in bulk mutations
  saleor/graphql/account/bulk_mutations/customer_bulk_delete.py
  saleor/graphql/account/bulk_mutations/customer_bulk_update.py
  saleor/graphql/account/tests/test_bulk_delete.py
  saleor/graphql/core/mutations.py
  saleor/graphql/discount/mutations/bulk_mutations.py
  saleor/graphql/discount/tests/mutations/test_sale_bulk_delete.py
  saleor/graphql/discount/tests/mutations/test_voucher_bulk_delete.py
  saleor/graphql/giftcard/bulk_mutations.py
  saleor/graphql/giftcard/tests/mutations/test_gift_card_bulk_activate.py
  saleor/graphql/giftcard/tests/mutations/test_gift_card_bulk_create.py
  saleor/graphql/giftcard/tests/mutations/test_gift_card_bulk_deactivate.py
  saleor/graphql/giftcard/tests/mutations/test_gift_card_bulk_delete.py
  saleor/graphql/menu/bulk_mutations.py
  saleor/graphql/menu/tests/test_bulk_delete.py
  saleor/graphql/order/bulk_mutations/order_bulk_cancel.py
  saleor/graphql/order/schema.py
  saleor/graphql/order/tests/mutations/test_order_bulk_cancel.py
  saleor/graphql/product/bulk_mutations/collection_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_create.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/benchmark/test_variant_stocks.py
  saleor/graphql/product/tests/deprecated/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/shipping/bulk_mutations.py
  saleor/graphql/shipping/tests/mutations/test_bulk_delete.py
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/graphql/warehouse/tests/test_stock_bulk_update.py
  saleor/order/actions.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/product/tests/test_category.py
  saleor/product/utils/__init__.py
Labels: 3.14

#14329 optimize webhooks calls in bulk mutations
  saleor/graphql/account/bulk_mutations/customer_bulk_delete.py
  saleor/graphql/account/bulk_mutations/customer_bulk_update.py
  saleor/graphql/account/bulk_mutations/staff_bulk_delete.py
  saleor/graphql/account/tests/bulk_mutations/test_customer_bulk_delete.py
  saleor/graphql/core/mutations.py
  saleor/graphql/discount/mutations/bulk_mutations.py
  saleor/graphql/discount/tests/mutations/test_sale_bulk_delete.py
  saleor/graphql/discount/tests/mutations/test_voucher_bulk_delete.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_activate.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_create.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_deactivate.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_delete.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_activate.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_create.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_deactivate.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_delete.py
  saleor/graphql/menu/bulk_mutations/menu_bulk_delete.py
  saleor/graphql/menu/bulk_mutations/menu_item_bulk_delete.py
  saleor/graphql/menu/tests/bulk_mutations/test_menu_bulk_delete.py
  saleor/graphql/menu/tests/bulk_mutations/test_menu_item_bulk_delete.py
  saleor/graphql/order/bulk_mutations/order_bulk_cancel.py
  saleor/graphql/order/schema.py
  saleor/graphql/order/tests/mutations/test_order_bulk_cancel.py
  saleor/graphql/product/bulk_mutations/collection_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_create.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/benchmark/test_variant_stocks.py
  saleor/graphql/product/tests/deprecated/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/shipping/bulk_mutations/shipping_price_bulk_delete.py
  saleor/graphql/shipping/bulk_mutations/shipping_zone_bulk_delete.py
  saleor/graphql/shipping/tests/mutations/test_bulk_delete.py
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/graphql/warehouse/tests/bulk_mutations/test_stock_bulk_update.py
  saleor/order/actions.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/product/tests/test_category.py
  saleor/product/utils/__init__.py
Labels: 3.15

#14331 optimize webhooks calls in bulk mutations
  saleor/graphql/account/bulk_mutations/customer_bulk_delete.py
  saleor/graphql/account/bulk_mutations/customer_bulk_update.py
  saleor/graphql/account/bulk_mutations/staff_bulk_delete.py
  saleor/graphql/account/tests/bulk_mutations/test_customer_bulk_delete.py
  saleor/graphql/core/mutations.py
  saleor/graphql/discount/mutations/bulk_mutations.py
  saleor/graphql/discount/tests/mutations/test_sale_bulk_delete.py
  saleor/graphql/discount/tests/mutations/test_voucher_bulk_delete.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_activate.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_create.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_deactivate.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_delete.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_activate.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_create.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_deactivate.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_delete.py
  saleor/graphql/menu/bulk_mutations/menu_bulk_delete.py
  saleor/graphql/menu/bulk_mutations/menu_item_bulk_delete.py
  saleor/graphql/menu/tests/bulk_mutations/test_menu_bulk_delete.py
  saleor/graphql/menu/tests/bulk_mutations/test_menu_item_bulk_delete.py
  saleor/graphql/order/bulk_mutations/order_bulk_cancel.py
  saleor/graphql/order/schema.py
  saleor/graphql/order/tests/mutations/test_order_bulk_cancel.py
  saleor/graphql/product/bulk_mutations/collection_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_create.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/benchmark/test_variant_stocks.py
  saleor/graphql/product/tests/deprecated/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/shipping/bulk_mutations/shipping_price_bulk_delete.py
  saleor/graphql/shipping/bulk_mutations/shipping_zone_bulk_delete.py
  saleor/graphql/shipping/tests/mutations/test_bulk_delete.py
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/graphql/warehouse/tests/bulk_mutations/test_stock_bulk_update.py
  saleor/order/actions.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/product/tests/test_category.py
  saleor/product/utils/__init__.py
Labels: 3.16

#14338 optimize webhooks calls in bulk mutations
  saleor/graphql/account/bulk_mutations/customer_bulk_delete.py
  saleor/graphql/account/bulk_mutations/customer_bulk_update.py
  saleor/graphql/account/bulk_mutations/staff_bulk_delete.py
  saleor/graphql/account/tests/bulk_mutations/test_customer_bulk_delete.py
  saleor/graphql/core/mutations.py
  saleor/graphql/discount/mutations/bulk_mutations.py
  saleor/graphql/discount/tests/mutations/test_sale_bulk_delete.py
  saleor/graphql/discount/tests/mutations/test_voucher_bulk_delete.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_activate.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_create.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_deactivate.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_delete.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_activate.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_create.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_deactivate.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_delete.py
  saleor/graphql/menu/bulk_mutations/menu_bulk_delete.py
  saleor/graphql/menu/bulk_mutations/menu_item_bulk_delete.py
  saleor/graphql/menu/tests/bulk_mutations/test_menu_bulk_delete.py
  saleor/graphql/menu/tests/bulk_mutations/test_menu_item_bulk_delete.py
  saleor/graphql/order/bulk_mutations/order_bulk_cancel.py
  saleor/graphql/order/schema.py
  saleor/graphql/order/tests/mutations/test_order_bulk_cancel.py
  saleor/graphql/product/bulk_mutations/collection_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_create.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/benchmark/test_variant_stocks.py
  saleor/graphql/product/tests/deprecated/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/shipping/bulk_mutations/shipping_price_bulk_delete.py
  saleor/graphql/shipping/bulk_mutations/shipping_zone_bulk_delete.py
  saleor/graphql/shipping/tests/mutations/test_bulk_delete.py
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/graphql/warehouse/tests/bulk_mutations/test_stock_bulk_update.py
  saleor/order/actions.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/product/tests/test_category.py
  saleor/product/utils/__init__.py
Labels: 3.17

#14336 Fix draft order voucher assignment
  CHANGELOG.md
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/schema.graphql
  saleor/order/calculations.py
  saleor/order/error_codes.py
Labels: test deployment, main

#14348 Update codeowners for openid_connect plugin
  .github/CODEOWNERS
Labels: skip changelog

#14345 User caching for OIDC
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: performance, 3.14

#14339 [Test] Digital order taxes based on billing country tax rate
  saleor/tests/e2e/checkout/test_checkout_calculate_simple_taxes_based_on_shipping_country.py
  saleor/tests/e2e/checkout/test_checkout_calculate_simple_taxes_product_type_tax_class.py
  saleor/tests/e2e/orders/test_order_calculate_simple_taxes_for_digital_product.py
  saleor/tests/e2e/orders/utils/draft_order_create.py
  saleor/tests/e2e/product/utils/preparing_product.py
Labels: skip changelog

#14356 [Test] Digital Checkout calculates simple taxes based on Billing address
  saleor/tests/e2e/checkout/test_checkout_calculate_simple_taxes_for_digital_product.py
Labels: skip changelog

#14351 Assign `voucher_code` to order in checkout complete
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
Labels: voucher

#14286 Drop recursion from migrations and move migration tasks to migration code
  saleor/attribute/migrations/0034_assignedpageattributevalue_page_data_migration.py
  saleor/attribute/migrations/0036_assignedproductattributevalue_product_data_migration.py
  saleor/attribute/migrations/tasks/__init__.py
  saleor/attribute/migrations/tasks/saleor3_16.py
  saleor/attribute/tests/test_page_attributes_migration.py
  saleor/celeryconf.py
  saleor/discount/migrations/0047_migrate_sales_to_promotions.py
Labels: skip changelog, 3.18, main

#14340 Optimize queries to database when initializing PluginsManager
  saleor/graphql/plugins/mutations.py
  saleor/plugins/manager.py
  saleor/plugins/tests/test_manager.py
Labels: skip changelog, main

#14361 [TEST] Checkout with percentage voucher CORE_0902
  saleor/tests/e2e/checkout/test_checkout_with_percentage_voucher.py
Labels: voucher, skip changelog

#14359 [TEST] Fixed voucher code should not result in a negative variant price CORE_0911
  saleor/tests/e2e/checkout/test_checkout_with_fixed_voucher_should_not_result_in_negative_variant_price.py
  saleor/tests/e2e/checkout/utils/checkout_add_promo_code.py
Labels: voucher, skip changelog

#14328 Update draft order mutations
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/checkout/utils.py
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/order/utils.py
  saleor/tests/fixtures.py
Labels: voucher

#14367 Optimize queries to database when initializing PluginsManager
  saleor/graphql/plugins/mutations.py
  saleor/plugins/manager.py
  saleor/plugins/tests/test_manager.py
Labels: 3.14

#14366 Optimize queries to database when initializing PluginsManager
  saleor/graphql/plugins/mutations.py
  saleor/plugins/manager.py
  saleor/plugins/tests/test_manager.py
Labels: 3.15

#14365 Optimize queries to database when initializing PluginsManager
  saleor/graphql/plugins/mutations.py
  saleor/plugins/manager.py
  saleor/plugins/tests/test_manager.py
Labels: 3.16

#14364 Optimize queries to database when initializing PluginsManager
  saleor/graphql/plugins/mutations.py
  saleor/plugins/manager.py
  saleor/plugins/tests/test_manager.py
Labels: 3.17

#14372 [TEST] Should not be able to exceed voucher usage with a limit per customer CORE_0910
  saleor/tests/e2e/checkout/test_checkout_with_voucher_limit_per_customer.py
  saleor/tests/e2e/vouchers/utils/__init__.py
  saleor/tests/e2e/vouchers/utils/query_voucher.py
Labels: voucher, skip changelog

#14363 Add migration to populate voucher_code in BaseDiscount
  saleor/discount/migrations/0065_basediscount_add_voucher_code.py
  saleor/discount/migrations/0066_basediscount_voucher_code_add_index.py
  saleor/discount/migrations/0067_basediscount_voucher_code.py
  saleor/discount/models.py
  saleor/order/migrations/0177_order_voucher_to_voucher_code_migration.py
Labels: voucher

#14377 [Test] Calculate shipping prices based on tax class
  saleor/tests/e2e/checkout/test_checkout_calculate_simple_taxes_based_on_shipping_tax_class.py
  saleor/tests/e2e/orders/test_order_calculate_simple_taxes_based_on_shipping_tax_class.py
  saleor/tests/e2e/orders/utils/order_lines_create.py
  saleor/tests/e2e/shipping_zone/utils/__init__.py
  saleor/tests/e2e/shipping_zone/utils/shipping_price_update.py
Labels: skip changelog

#13940 Add test for testing memory usage for celery task
  conftest.py
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/product/tests/test_tasks.py
  saleor/tests/fixtures.py
Labels: 3.14

#14383 [TEST] Should not be able to use not started nor expired order in the checkout CORE_0920 CORE_0921
  saleor/tests/e2e/checkout/test_checkout_unable_to_use_expired_voucher.py
  saleor/tests/e2e/checkout/test_checkout_unable_to_use_not_started_voucher.py
  saleor/tests/e2e/checkout/utils/checkout_create.py
Labels: voucher, skip changelog

#14379 [TEST] Should not be able to exceed voucher usage limit CORE_0909
  saleor/tests/e2e/checkout/test_checkout_unable_to_exceed_voucher_usage_limit.py
Labels: voucher, skip changelog

#14378 Fix generating slug for product create mutation
  saleor/core/utils/__init__.py
  saleor/graphql/product/tests/mutations/test_product_create.py
Labels: 3.14

#14396 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#14385 Release voucher after draft order delete.
  saleor/graphql/order/mutations/draft_order_delete.py
  saleor/graphql/order/tests/mutations/test_draft_order_delete.py
  saleor/tests/fixtures.py
Labels: voucher

#14314 Ensure zero-downtime support
  saleor/discount/migrations/0055_vouchercode.py
  saleor/discount/migrations/0056_voucher_code_indexes.py
  saleor/discount/migrations/0057_move_codes_to_new_model.py
  saleor/discount/migrations/0058_vouchercustomer_vouchercode.py
  saleor/discount/migrations/0059_auto_20230821_0730.py
  saleor/discount/migrations/0059_vouchercustomer_voucher_code_index.py
  saleor/discount/migrations/0060_set_vouchercustomer_codes.py
  saleor/discount/migrations/0061_basediscount_add_voucher_code.py
  saleor/discount/migrations/0062_basediscount_voucher_code_add_index.py
  saleor/discount/migrations/0063_basediscount_voucher_code.py
  saleor/discount/migrations/0064_merge_20231020_1334.py
  saleor/discount/migrations/0065_remove_voucher_code_index.py
  saleor/discount/migrations/0066_clear_voucher_and_vouchercustomer.py
  saleor/discount/migrations/0067_voucher_single_use.py
  saleor/order/migrations/0177_set_order_voucher_code.py
Labels: voucher

#14381 Adjust `OrderBulkCreate`
  CHANGELOG.md
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
  saleor/graphql/order/tests/mutations/test_order_bulk_create.py
  saleor/graphql/schema.graphql
Labels: voucher

#14399 Fix generating slug for product create mutation
  saleor/core/utils/__init__.py
  saleor/graphql/product/tests/mutations/test_product_create.py
Labels: skip changelog, 3.15

#14400 Fix generating slug for product create mutation
  saleor/core/utils/__init__.py
  saleor/graphql/product/tests/mutations/test_product_create.py
Labels: skip changelog, 3.16

#14404 Voucher codes export
  saleor/csv/notifications.py
  saleor/csv/tasks.py
  saleor/csv/tests/export/test_export.py
  saleor/csv/utils/export.py
  saleor/graphql/csv/mutations/__init__.py
  saleor/graphql/csv/mutations/export_voucher_codes.py
  saleor/graphql/csv/schema.py
  saleor/graphql/csv/tests/mutations/test_export_voucher_codes.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/graphql/webhook/enums.py
  saleor/graphql/webhook/subscription_types.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/tests/fixtures.py
  saleor/webhook/event_types.py
Labels: voucher, skip changelog

#14410 Simplify `orderBulkCreate` mutation.
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
Labels: voucher

#14411 Fix voucher mutations
  saleor/graphql/discount/mutations/voucher/voucher_create.py
  saleor/graphql/discount/tests/mutations/test_voucher_create.py
  saleor/graphql/discount/tests/mutations/test_voucher_update.py
Labels: voucher

#14422 Bump urllib3
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.14

#14419 Bump urllib3
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.17

#14424 Bump urllib3
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.12

#14423 Bump urllib3
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.13

#14421 Bump urllib3
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.15

#14402 Fix generating slug for product create mutation
  saleor/core/utils/__init__.py
  saleor/graphql/product/tests/mutations/test_product_create.py
Labels: skip changelog, main

#14401 Fix generating slug for product create mutation
  saleor/core/utils/__init__.py
  saleor/graphql/product/tests/mutations/test_product_create.py
Labels: skip changelog, 3.17

#14426 Optimize webhooks calls in bulk mutations
  CHANGELOG.md
  saleor/graphql/account/bulk_mutations/staff_bulk_delete.py
  saleor/graphql/attribute/bulk_mutations.py
  saleor/graphql/attribute/mutations/attribute_bulk_update.py
  saleor/graphql/discount/mutations/promotion/promotion_bulk_delete.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
Labels: webhooks, skip changelog

#14398 Add test for testing memory usage for celery task
  conftest.py
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/product/tests/test_tasks.py
  saleor/tests/fixtures.py
Labels: skip changelog, main

#14413 Remove redundant webhook calls during export tasks.
  saleor/csv/tests/export/test_export.py
  saleor/csv/utils/export.py
  saleor/graphql/csv/tests/mutations/test_export_gift_cards.py
  saleor/graphql/csv/tests/mutations/test_export_products.py
Labels: bug, test deployment, webhooks, skip changelog

#14384 [TEST] Should apply voucher to the specific product per order core_0915
  saleor/tests/e2e/checkout/test_checkout_apply_voucher_to_the_specific_product_per_order.py
Labels: voucher, skip changelog

#14397 Remove CustomerVoucher creation from draftOrderCreate
  saleor/discount/utils.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
Labels: voucher

#14457 Update GraphQL Playground
  templates/graphql/playground.html
Labels: skip changelog

#14451 Optimize webhooks calls in bulk mutations
  saleor/graphql/account/bulk_mutations/staff_bulk_delete.py
  saleor/graphql/account/tests/bulk_mutations/test_staff_bulk_delete.py
  saleor/graphql/attribute/bulk_mutations.py
  saleor/graphql/attribute/mutations/attribute_bulk_update.py
  saleor/graphql/discount/mutations/promotion/promotion_bulk_delete.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
Labels: webhooks, 3.17

#14450 Optimize webhooks calls in bulk mutations
  saleor/graphql/account/bulk_mutations/staff_bulk_delete.py
  saleor/graphql/account/tests/bulk_mutations/test_staff_bulk_delete.py
  saleor/graphql/attribute/bulk_mutations.py
  saleor/graphql/attribute/mutations/attribute_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
Labels: webhooks, 3.16

#14448 Optimize webhooks calls in bulk mutations
  saleor/graphql/account/bulk_mutations/staff_bulk_delete.py
  saleor/graphql/account/tests/bulk_mutations/test_staff_bulk_delete.py
  saleor/graphql/attribute/bulk_mutations.py
  saleor/graphql/attribute/mutations/attribute_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
Labels: webhooks, 3.15

#14442 Optimize webhooks calls in bulk mutations
  saleor/graphql/account/bulk_mutations/staff_bulk_delete.py
  saleor/graphql/account/tests/test_bulk_delete.py
  saleor/graphql/attribute/bulk_mutations.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
Labels: webhooks, 3.14

#14445 Update CHANGELOG.md
  CHANGELOG.md
Labels: voucher, 3.18

#14454 add proper event_type when locking webhooks
  saleor/graphql/account/bulk_mutations/staff_bulk_delete.py
  saleor/graphql/account/tests/bulk_mutations/test_staff_bulk_delete.py
  saleor/graphql/discount/mutations/promotion/promotion_bulk_delete.py
Labels: webhooks, skip changelog, skip migrations perf test

#14447 Improve GraphQL ID validation messages
  CHANGELOG.md
  saleor/graphql/account/tests/queries/test_address.py
  saleor/graphql/account/tests/queries/test_user.py
  saleor/graphql/attribute/tests/mutations/test_attribute_bulk_update.py
  saleor/graphql/attribute/tests/queries/test_attribute_query.py
  saleor/graphql/channel/tests/queries/test_channel.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/core/tests/test_base_mutation.py
  saleor/graphql/core/tests/test_graphql.py
  saleor/graphql/core/utils/__init__.py
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/csv/tests/queries/test_export_file.py
  saleor/graphql/discount/tests/queries/test_sale.py
  saleor/graphql/discount/tests/queries/test_voucher.py
  saleor/graphql/giftcard/tests/queries/test_gift_card.py
  saleor/graphql/menu/tests/mutations/test_menu_item_move.py
  saleor/graphql/menu/tests/queries/test_menu.py
  saleor/graphql/menu/tests/queries/test_menu_item.py
  saleor/graphql/order/tests/mutations/test_order_bulk_create.py
  saleor/graphql/order/tests/mutations/test_utils.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/page/tests/queries/test_page.py
  saleor/graphql/page/tests/queries/test_page_type.py
  saleor/graphql/payment/mutations/base.py
  saleor/graphql/payment/tests/queries/test_payments_query.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_type_query.py
  saleor/graphql/product/tests/queries/test_product_variants_query.py
  saleor/graphql/product/tests/queries/test_variant_query.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_digital_content.py
  saleor/graphql/shipping/tests/queries/test_shipping_zone.py
  saleor/graphql/warehouse/tests/queries/test_stock.py
  saleor/graphql/warehouse/tests/queries/test_warehouse.py
  saleor/graphql/webhook/tests/mutations/test_delivery_retry.py
  saleor/graphql/webhook/tests/queries/test_webhook.py
Labels: graphql
