Repository saleor/saleor, pull requests merged in 2023-03, with the labels that each got.

#12161 Fix loading related_order when related id is the old order_id
  saleor/graphql/order/dataloaders.py
  saleor/graphql/order/tests/queries/test_order_events.py
  saleor/graphql/order/types.py
Labels: test deployment, 3.9

#12169 Fix Avalara tax calculation for JPY currency
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[False-3493-4297-3.0-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[False-4300-5289-0.0-False].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[True-3484-4285-0.0-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[True-4280-5264-5.0-False].yaml
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/tests/fixtures.py
Labels: 3.10

#12171 Fix Avalara tax calculation for JPY currency
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[False-3493-4297-3.0-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[False-4300-5289-0.0-False].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[True-3484-4285-0.0-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[True-4280-5264-5.0-False].yaml
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/tests/fixtures.py
Labels: skip changelog

#12170 Fix Avalara tax calculation for JPY currency
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[False-3493-4297-3.0-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[False-4300-5289-0.0-False].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[True-3484-4285-0.0-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[True-4280-5264-5.0-False].yaml
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/tests/fixtures.py
Labels: 3.11

#12181 Fix handling generating payload for shipping methods with removed channel listings
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_sample_payloads.py
Labels: skip changelog, 3.10

#12182 Fix handling generating payload for shipping methods with removed channel listings
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_sample_payloads.py
Labels: skip changelog, 3.11

#12184 Fix handling generating payload for shipping methods with removed channel listings
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_sample_payloads.py
Labels: skip changelog

#12192 Fixes for GraphiQL playground
  CHANGELOG.md
  templates/graphql/playground.html
Labels: Fast Lane

#12174 Fix loading related_order when related id is the old order_id
  saleor/graphql/order/dataloaders.py
  saleor/graphql/order/tests/queries/test_order_events.py
  saleor/graphql/order/types.py
Labels: skip changelog

#12173 Fix loading related_order when related id is the old order_id
  saleor/graphql/order/dataloaders.py
  saleor/graphql/order/tests/queries/test_order_events.py
  saleor/graphql/order/types.py
Labels: 3.11

#12172 Fix loading related_order when related id is the old order_id
  saleor/graphql/order/dataloaders.py
  saleor/graphql/order/tests/queries/test_order_events.py
  saleor/graphql/order/types.py
Labels: 3.10

#12122 Fix invalid discount calculaion for specific product voucher that is applied once per order
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
Labels: test deployment, 3.9

#12202 Fix deadlock between adyen webhook and checkoutComplete
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_api_response.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: skip changelog

#12198 Fix invalid discount calculaion for specific product voucher that is applied once per order
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
Labels: skip changelog

#12197 Fix invalid discount calculaion for specific product voucher that is applied once per order
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
Labels: 3.11

#12196 Fix invalid discount calculaion for specific product voucher that is applied once per order
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
Labels: 3.10

#12199 Fix deadlock between adyen webhook and checkout complete
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_api_response.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.10

#12200 Fix deadlock between adyen webhook and checkout complete
  saleor/payment/gateways/adyen/tests/webhooks/test_handle_api_response.py
  saleor/payment/gateways/adyen/webhooks.py
Labels: 3.11

#12194 Fix integrity error with returning products with old ids
  saleor/order/actions.py
  saleor/order/tests/test_order_actions_create_fulfillments_for_returned_products.py
Labels: 3.9

#12208 Update Security Policy Links
  SECURITY.md
Labels: skip changelog

#12206 Fix integrity error with returning products with old ids
  saleor/order/actions.py
  saleor/order/tests/test_order_actions_create_fulfillments_for_returned_products.py
Labels: skip changelog

#12204 Fix integrity error with returning products with old ids
  saleor/order/actions.py
  saleor/order/tests/test_order_actions_create_fulfillments_for_returned_products.py
Labels: skip changelog, 3.10

#12213 Do not require tax class for shipping tax calculation in avatax plugin
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_get_order_shipping_tax_rate_shipping_with_tax_class.yaml
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.12

#12214 Do not require tax class for shipping tax calculation in avatax plugin
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_get_order_shipping_tax_rate_shipping_with_tax_class.yaml
  saleor/plugins/avatax/tests/test_avatax.py
Labels: skip changelog

#12227 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#12193 Change log-level to info for webhook delivery tasks
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
Labels: skip changelog

#12231 Fix order shipping Avatax tax calculations for JPY currency
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_order_total_for_JPY.yaml
  saleor/plugins/avatax/tests/test_avatax.py
Labels: test deployment, 3.9

#12232 Fix order shipping Avatax tax calculations for JPY currency
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_order_total_for_JPY.yaml
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.10

#12233 Fix order shipping Avatax tax calculations for JPY currency
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_order_total_for_JPY.yaml
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.11

#12234 Fix order shipping Avatax tax calculations for JPY currency
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_order_total_for_JPY.yaml
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.12

#12235 Fix order shipping Avatax tax calculations for JPY currency
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_order_total_for_JPY.yaml
  saleor/plugins/avatax/tests/test_avatax.py
Labels: skip changelog

#12230 Fix integrity error with returning products with old ids
  saleor/order/actions.py
  saleor/order/tests/test_order_actions_create_fulfillments_for_returned_products.py
Labels: skip changelog, 3.12

#12246 Revert JWT expiration error code
  saleor/graphql/core/mutations.py
  saleor/graphql/core/tests/test_base_mutation.py
  saleor/graphql/utils/__init__.py
Labels: 3.7

#12249 Revert JWT expiration error code
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/core/mutations.py
  saleor/graphql/core/tests/test_base_mutation.py
  saleor/graphql/utils/__init__.py
Labels: 3.8

#12250 Revert JWT expiration error code
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/core/mutations.py
  saleor/graphql/core/tests/test_base_mutation.py
  saleor/graphql/utils/__init__.py
Labels: 3.9

#12253 Revert JWT expiration error code
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/core/mutations.py
  saleor/graphql/core/tests/test_base_mutation.py
  saleor/graphql/utils/__init__.py
Labels: 3.12

#12254 Revert JWT expiration error code
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/core/mutations.py
  saleor/graphql/core/tests/test_base_mutation.py
  saleor/graphql/utils/__init__.py
Labels: skip changelog

#12139 Add StocksBulkUpdate mutation
  CHANGELOG.md
  saleor/graphql/api.py
  saleor/graphql/core/descriptions.py
  saleor/graphql/core/enums.py
  saleor/graphql/core/types/__init__.py
  saleor/graphql/core/types/common.py
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/schema.graphql
  saleor/graphql/warehouse/bulk_mutations/__init__.py
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/graphql/warehouse/schema.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/graphql/warehouse/tests/test_stock_bulk_update.py
  saleor/tests/fixtures.py
  saleor/warehouse/error_codes.py
Labels: test deployment

#12207 Update Avatax tests to always use env variables for configuration
  saleor/plugins/avatax/tests/conftest.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: skip changelog

#12256 Fix invalid draft order prices when using staff discount
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/tests/fixtures.py
Labels: test deployment, 3.9

#12264 Fix invalid draft order prices when using staff discount
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/tests/fixtures.py
Labels: 3.10

#12265 Fix invalid draft order prices when using staff discount
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/tests/fixtures.py
Labels: 3.11

#12266 Fix invalid draft order prices when using staff discount
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/tests/fixtures.py
Labels: 3.12

#12267 Fix invalid draft order prices when using staff discount
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/tests/fixtures.py
Labels: skip changelog

#12263 Update Avatax tests to alwyas use env variables for configuration
  saleor/plugins/avatax/tests/conftest.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.8

#12261 Update Avatax tests to alwyas use env variables for configuration
  saleor/plugins/avatax/tests/conftest.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.10

#12259 Update Avatax tests to alwyas use env variables for configuration
  saleor/plugins/avatax/tests/conftest.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.12

#12262 Update Avatax tests to alwyas use env variables for configuration
  saleor/plugins/avatax/tests/conftest.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.9

#12260 Update Avatax tests to alwyas use env variables for configuration
  saleor/plugins/avatax/tests/conftest.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: 3.11

#12270 Add AvaTax Excise plugin
  saleor/plugins/avatax_excise/__init__.py
  saleor/plugins/avatax_excise/plugin.py
  saleor/plugins/avatax_excise/tasks.py
  saleor/plugins/avatax_excise/tests/__init__.py
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_calculate_checkout_line_total[False-30.00-31.80-False].yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_calculate_checkout_line_total[True-15.00-16.80-False].yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_calculate_checkout_shipping.yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_calculate_checkout_total[False-39.98-41.65-4.0-False].yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_calculate_checkout_total[False-43.98-45.90-0.0-False].yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_calculate_checkout_total[True-24.98-25.76-4.0-False].yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_calculate_checkout_total[True-28.98-30.01-0.0-False].yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_calculate_checkout_total_excise_data[20-38.76-False-202000000-172-destination0-metadata0].yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_calculate_checkout_total_excise_data[20.00-24.95-False-202015500-170-destination1-metadata1].yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_calculate_order_line_unit.yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_calculate_order_line_unit_the_order_changed.yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_calculate_order_total.yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_order_created.yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_preprocess_order_creation.yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_avatax_excise/test_preprocess_order_creation_wrong_data.yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_tasks/test_api_post_request_task_with_invalid_productcodes.yaml
  saleor/plugins/avatax_excise/tests/cassettes/test_tasks/test_api_post_request_task_with_valid_productcodes.yaml
  saleor/plugins/avatax_excise/tests/conftest.py
  saleor/plugins/avatax_excise/tests/test_avatax_excise.py
  saleor/plugins/avatax_excise/tests/test_tasks.py
  saleor/plugins/avatax_excise/utils.py
  saleor/settings.py
Labels: 3.8

#12271 Upgrade GraphiQL to `2.4` for playground
  CHANGELOG.md
  templates/graphql/playground.html
Labels: Fast Lane

#12279 Update Dashboard screenshot in the readme
  README.md
Labels: skip changelog

#12297 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
  saleor/core/utils/anonymization.py
  saleor/site/patch_sites.py
Labels: test deployment, :robot: bot, skip changelog

#12272 Create order discounts for all voucher types
  CHANGELOG.md
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
Labels: test deployment

#12085 Throttle password reset mutation per user
  saleor/account/error_codes.py
  saleor/account/migrations/0064_user_last_password_reset_request.py
  saleor/account/migrations/0072_merge_20230221_0956.py
  saleor/account/models.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/schema.graphql
  saleor/settings.py
Labels: 3.7

#12086 Throttle password reset mutation per user
  saleor/account/error_codes.py
  saleor/account/migrations/0064_user_last_password_reset_request.py
  saleor/account/migrations/0072_merge_20230221_0956.py
  saleor/account/models.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/schema.graphql
  saleor/settings.py
Labels: 3.8

#12088 Throttle password reset mutation per user
  saleor/account/error_codes.py
  saleor/account/migrations/0064_user_last_password_reset_request.py
  saleor/account/migrations/0072_merge_20230221_0956.py
  saleor/account/migrations/0076_merge_20230221_1002.py
  saleor/account/models.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/schema.graphql
  saleor/settings.py
Labels: 3.10

#12089 Throttle password reset mutation per user
  saleor/account/error_codes.py
  saleor/account/migrations/0064_user_last_password_reset_request.py
  saleor/account/migrations/0072_merge_20230221_0956.py
  saleor/account/migrations/0076_merge_20230221_1002.py
  saleor/account/models.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/schema.graphql
  saleor/settings.py
Labels: 3.11

#12087 Throttle password reset mutation per user
  saleor/account/error_codes.py
  saleor/account/migrations/0064_user_last_password_reset_request.py
  saleor/account/migrations/0072_merge_20230221_0956.py
  saleor/account/models.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/schema.graphql
  saleor/settings.py
Labels: 3.9

#12283 Throttle password reset mutation per user
  saleor/account/error_codes.py
  saleor/account/migrations/0064_user_last_password_reset_request.py
  saleor/account/migrations/0072_merge_20230221_0956.py
  saleor/account/migrations/0076_merge_20230221_1002.py
  saleor/account/migrations/0077_merge_20230310_1107.py
  saleor/account/models.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/schema.graphql
  saleor/settings.py
Labels: 3.12

#12300 Add checkout payment statuses. Connect availablePaymentGateway with transaction flow
  saleor/checkout/__init__.py
  saleor/checkout/actions.py
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0058_auto_20230313_1602.py
  saleor/checkout/models.py
  saleor/checkout/payment_utils.py
  saleor/checkout/tests/test_calculations.py
  saleor/graphql/checkout/enums.py
  saleor/graphql/checkout/filters.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/tests/test_checkout_filters.py
  saleor/graphql/checkout/types.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_payment_gateway_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/schema.graphql
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_payment_webhook.py
  saleor/plugins/webhook/tests/test_tax_webhook.py
  saleor/webhook/tests/conftest.py
Labels: test deployment

#12325 Add backwards compatibility for taxCode field
  CHANGELOG.md
  saleor/graphql/product/mutations/product/product_create.py
  saleor/graphql/product/mutations/product_type/product_type_create.py
  saleor/graphql/product/mutations/utils.py
  saleor/graphql/product/tests/deprecated/test_utils.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/schema.graphql
  saleor/plugins/avatax/tests/deprecated/__init__.py
  saleor/plugins/avatax/tests/deprecated/test_tax_code_mutations.py
Labels: test deployment

#12330 Add backwards compatibility for taxCode field
  saleor/graphql/product/mutations/product/product_create.py
  saleor/graphql/product/mutations/product_type/product_type_create.py
  saleor/graphql/product/mutations/utils.py
  saleor/graphql/product/tests/deprecated/test_utils.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/schema.graphql
  saleor/plugins/avatax/tests/deprecated/__init__.py
  saleor/plugins/avatax/tests/deprecated/test_tax_code_mutations.py
Labels: 3.12

#12331 Add backwards compatibility for taxCode field
  saleor/graphql/product/mutations/product/product_create.py
  saleor/graphql/product/mutations/product_type/product_type_create.py
  saleor/graphql/product/mutations/utils.py
  saleor/graphql/product/tests/deprecated/test_utils.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/schema.graphql
  saleor/plugins/avatax/tests/deprecated/__init__.py
  saleor/plugins/avatax/tests/deprecated/test_tax_code_mutations.py
Labels: 3.11

#12332 Add backwards compatibility for taxCode field
  saleor/graphql/product/mutations/product/product_create.py
  saleor/graphql/product/mutations/product_type/product_type_create.py
  saleor/graphql/product/mutations/utils.py
  saleor/graphql/product/tests/deprecated/test_utils.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/schema.graphql
  saleor/plugins/avatax/tests/deprecated/__init__.py
  saleor/plugins/avatax/tests/deprecated/test_tax_code_mutations.py
Labels: 3.10

#12333 Add backwards compatibility for taxCode field
  saleor/graphql/product/mutations/product/product_create.py
  saleor/graphql/product/mutations/product_type/product_type_create.py
  saleor/graphql/product/mutations/utils.py
  saleor/graphql/product/tests/deprecated/test_utils.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/schema.graphql
  saleor/plugins/avatax/tests/deprecated/__init__.py
  saleor/plugins/avatax/tests/deprecated/test_tax_code_mutations.py
Labels: 3.9

#12341 Fix tax class permissions
  saleor/graphql/order/tests/queries/test_order_line.py
  saleor/graphql/order/types.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_type_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/tests/test_shipping_zones_query.py
  saleor/graphql/shipping/types.py
  saleor/tests/fixtures.py
Labels: 3.12

#12342 Fix tax class permissions
  saleor/graphql/order/tests/queries/test_order_line.py
  saleor/graphql/order/types.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_type_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/tests/test_shipping_zones_query.py
  saleor/graphql/shipping/types.py
  saleor/tests/fixtures.py
Labels: 3.11

#12343 Fix tax class permissions
  saleor/graphql/order/tests/queries/test_order_line.py
  saleor/graphql/order/types.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_type_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/tests/test_shipping_zones_query.py
  saleor/graphql/shipping/types.py
  saleor/tests/fixtures.py
Labels: 3.10

#12344 Fix tax class permissions
  saleor/graphql/order/tests/queries/test_order_line.py
  saleor/graphql/order/types.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_type_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/graphql/shipping/tests/test_shipping_zones_query.py
  saleor/graphql/shipping/types.py
  saleor/tests/fixtures.py
Labels: 3.9

#12286 Change the way of storing the transaction amounts
  saleor/graphql/order/tests/mutations/test_order_mark_as_paid.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/tests/queries/test_order_total_balance.py
  saleor/graphql/order/tests/queries/test_order_with_filter.py
  saleor/graphql/order/types.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/schema.graphql
  saleor/order/__init__.py
  saleor/order/migrations/0164_auto_20230310_1118.py
  saleor/order/migrations/0164_order_events_rename_transaction_events.py
  saleor/order/tests/test_order_actions.py
  saleor/order/utils.py
  saleor/payment/gateway.py
  saleor/payment/tests/test_transaction_item_calculations.py
  saleor/payment/transaction_item_calculations.py
  saleor/payment/utils.py
Labels: test deployment

#12339 Use replicas on order queries
  saleor/graphql/order/resolvers.py
  saleor/graphql/order/schema.py
Labels: skip changelog

#12338 Use replicas on order queries
  saleor/graphql/order/resolvers.py
  saleor/graphql/order/schema.py
Labels: 3.12

#12337 Use replicas on order queries
  saleor/graphql/order/resolvers.py
  saleor/graphql/order/schema.py
Labels: 3.11

#12336 Use replicas on order queries
  saleor/graphql/order/resolvers.py
  saleor/graphql/order/schema.py
Labels: 3.10

#12347 Fix thumbnail generation
  saleor/thumbnail/tests/test_utils.py
  saleor/thumbnail/utils.py
Labels: skip changelog

#12360 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#12359 Add app id to extension access token
  saleor/core/jwt.py
  saleor/core/tests/test_jwt.py
Labels: skip changelog

#12320 Add webhook checkoutFullyPaid
  saleor/checkout/actions.py
  saleor/checkout/tests/test_actions.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/schema.graphql
  saleor/graphql/webhook/subscription_types.py
  saleor/graphql/webhook/tests/mutations/test_webhook_dry_run.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/tests/test_manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/event_types.py
Labels: test deployment

#12323 Allow to run blocked fields on checkout type in sync transaction webhook
  saleor/graphql/checkout/utils.py
  saleor/graphql/webhook/subscription_payload.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_payment_gateway_initialize_session.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_initialize_session.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_process_session.py
  saleor/webhook/event_types.py
Labels: test deployment

#12378 Split fulfillment tests
  saleor/graphql/order/tests/mutations/test_fulfillment_approve.py
  saleor/graphql/order/tests/mutations/test_fulfillment_cancel.py
  saleor/graphql/order/tests/mutations/test_fulfillment_update_tracking.py
  saleor/graphql/order/tests/mutations/test_order_fulfill.py
  saleor/graphql/order/tests/queries/test_fulfillment.py
Labels: skip changelog

#12386 [Support for payment apps] Fix incorrect payload returned by mutations for field `data`
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_payment_gateway_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/payment/utils.py
Labels: payments

#12392 Change `requiredSaleorVersion` prerelease policy
  saleor/app/manifest_validations.py
  saleor/app/tests/test_validators.py
Labels: skip changelog

#12383 [Support for payment apps] Use token as ID for TransactionItem
  saleor/channel/migrations/0010_channel_default_transaction_flow_strategy.py
  saleor/checkout/migrations/0058_auto_20230313_1602.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/test_meta_mutations.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_action.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/graphql/webhook/subscription_types.py
  saleor/graphql/webhook/tests/mutations/test_webhook_dry_run.py
  saleor/order/search.py
  saleor/payment/migrations/0048_populate_transaction_item_token.py
  saleor/payment/migrations/0049_auto_20230322_0634.py
  saleor/payment/models.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_action_request_subscription.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_cancelation_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_charge_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_initialize_session.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_process_session.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_refund_requested.py
  saleor/plugins/webhook/tests/test_tasks.py
  saleor/plugins/webhook/tests/test_transaction_initialize_session_webhook.py
  saleor/plugins/webhook/tests/test_transaction_process_session_webhook.py
  saleor/tests/fixtures.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: payments

#12237 Add zero-downtime support for support-refund
  saleor/celeryconf.py
  saleor/payment/__init__.py
  saleor/payment/migrations/0038_auto_20230223_0926.py
  saleor/payment/migrations/0039_transactionevent_currency.py
  saleor/payment/migrations/0040_migrate_renamed_fields.py
  saleor/payment/migrations/0041_add_calculation_transaction_events.py
  saleor/payment/migrations/tasks/saleor3_12.py
  saleor/payment/models.py
Labels: skip changelog

#12417 Add missing currency in tests required for backward compatibility
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/payment/tests/queries/test_transaction.py
Labels: skip changelog

#12421 Upgrade Redis to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.12

#12422 Upgrade Redis to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.11

#12423 Upgrade Redis to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.10

#12424 Upgrade Redis to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.9

#12425 Upgrade Redis to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.8

#12426 Upgrade Redis to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.7

#12409 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#12329 Add App Store mention to README
  README.md
Labels: skip changelog

#12177 Add ProductBulkCreate mutation
  CHANGELOG.md
  saleor/graphql/core/enums.py
  saleor/graphql/core/types/__init__.py
  saleor/graphql/core/types/common.py
  saleor/graphql/product/bulk_mutations/__init__.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/mutations/cassettes/test_product_bulk_create/test_product_bulk_create_with_media_with_media_url.yaml
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/schema.graphql
  saleor/product/error_codes.py
Labels: test deployment

#12412 [Support for payment apps] Allow to return 0 an an amount
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: payments

#12373 [Support for payment apps] zero downtime migrations
  saleor/graphql/payment/mutations.py
  saleor/payment/migrations/0042_auto_20230320_1252.py
  saleor/payment/migrations/0043_populate_transaction_item_token.py
  saleor/payment/migrations/tasks/saleor3_12.py
  saleor/payment/models.py
  saleor/tests/fixtures.py
Labels: payments, 3.12

#12436 Upgrade Redis to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.12

#12440 Upgrade Redis to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, main

#12439 Upgrade Redis to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.9

#12438 Upgrade Redis to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.10

#12437 Upgrade Redis to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.11
