Repository saleor/saleor, pull requests merged in 2023-05, with the labels that each got.

#12646 fix checkout metadata fetches to not create checkout metadata objects
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/meta/types.py
  saleor/payment/gateways/adyen/utils/common.py
  saleor/payment/utils.py
  saleor/webhook/payloads.py
Labels: test deployment

#12716 Add cache for SHIPPING_LIST_METHODS_FOR_CHECKOUT event
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/shipping.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_list_shipping_methods_for_checkout.py
Labels: test deployment

#12735 Add cache for SHIPPING_LIST_METHODS_FOR_CHECKOUT event
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/shipping.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_list_shipping_methods_for_checkout.py
Labels: 3.13

#12736 Add cache for SHIPPING_LIST_METHODS_FOR_CHECKOUT event
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/shipping.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_list_shipping_methods_for_checkout.py
Labels: main, skip changelog

#12737 Fix updating metadata in CheckoutShippingMethodUpdate mutation
  saleor/graphql/checkout/mutations/checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/deprecated/test_checkout_shipping_method_update.py
Labels: test deployment, 3.13

#12729 Fix checkout metadata fetches to not create checkout metadata objects
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/deprecated/test_checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/meta/types.py
  saleor/payment/gateways/adyen/utils/common.py
  saleor/payment/utils.py
  saleor/webhook/payloads.py
Labels: main, skip changelog

#12730 Fix checkout metadata fetches to not create checkout metadata objects
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/deprecated/test_checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/meta/types.py
  saleor/payment/gateways/adyen/utils/common.py
  saleor/payment/utils.py
  saleor/webhook/payloads.py
Labels: 3.12

#12731 Fix checkout metadata fetches to not create checkout metadata objects
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/deprecated/test_checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/meta/types.py
  saleor/payment/gateways/adyen/utils/common.py
  saleor/payment/utils.py
  saleor/webhook/payloads.py
Labels: 3.11

#12732 Fix checkout metadata fetches to not create checkout metadata objects
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/deprecated/test_checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/meta/types.py
  saleor/payment/gateways/adyen/utils/common.py
  saleor/payment/utils.py
  saleor/webhook/payloads.py
Labels: 3.10

#12746 Upgrade django to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, main

#12739 Upgrade django to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.13

#12740 Upgrade django to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.12

#12742 Upgrade django to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.10

#12743 Upgrade django to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.9

#12745 Upgrade django to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.7

#12751 Fix failing mutations when updating checkout metadata
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/test_meta_mutations.py
  saleor/graphql/meta/types.py
Labels: test deployment, 3.13

#12753 Fix failing mutations when updating checkout metadata
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/test_meta_mutations.py
  saleor/graphql/meta/types.py
Labels: 3.12

#12754 Fix failing mutations when updating checkout metadata
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/test_meta_mutations.py
  saleor/graphql/meta/types.py
Labels: 3.11

#12755 Fix failing mutations when updating checkout metadata
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/test_meta_mutations.py
  saleor/graphql/meta/types.py
Labels: 3.10

#12756 Fix failing mutations when updating checkout metadata
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/test_meta_mutations.py
  saleor/graphql/meta/types.py
Labels: main, skip changelog

#12763 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#12628 Add mutation to create checkout from order
  CHANGELOG.md
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/enums.py
  saleor/graphql/checkout/mutations/__init__.py
  saleor/graphql/checkout/mutations/checkout_create.py
  saleor/graphql/checkout/mutations/checkout_create_from_order.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create_from_order.py
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/order/utils.py
  saleor/graphql/schema.graphql
Labels: test deployment, checkout

#12669 Change ordering of update in product discounted price task
  saleor/product/utils/variant_prices.py
Labels: 3.9

#12687 Change ordering of update in product discounted price task
  saleor/product/utils/variant_prices.py
Labels: 3.11

#12689 Change ordering of update in product discounted price task
  saleor/product/utils/variant_prices.py
Labels: 3.13

#12690 Change ordering of update in product discounted price task
  saleor/product/utils/variant_prices.py
Labels: skip changelog

#12782 Fix saving seo fields
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/product/tests/mutations/test_product_update.py
Labels: main, skip changelog

#12783 Fix saving seo fields
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/product/tests/mutations/test_product_update.py
Labels: skip changelog, 3.13

#12784 Fix saving seo fields
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/product/tests/mutations/test_product_update.py
Labels: skip changelog, 3.12

#12785 Fix saving seo fields
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/product/tests/mutations/test_product_update.py
Labels: skip changelog, 3.11

#12786 Fix saving seo fields
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/product/tests/mutations/test_product_update.py
Labels: skip changelog, 3.10

#12790 Add flag to StripePlugin to control if receipt_email should be included in the request
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/tests/conftest.py
  saleor/payment/gateways/stripe/tests/test_plugin.py
Labels: skip changelog

#12792 Add flag to StripePlugin to control if receipt_email should be included in the request
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/tests/conftest.py
  saleor/payment/gateways/stripe/tests/test_plugin.py
Labels: 3.12

#12793 Add flag to StripePlugin to control if receipt_email should be included in the request
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/tests/conftest.py
  saleor/payment/gateways/stripe/tests/test_plugin.py
Labels: 3.13

#12778 Extend allowed mutations list for read only mode
  saleor/graphql/middleware.py
Labels: skip changelog

#12779 Extend allowed mutations list for read only mode
  saleor/graphql/middleware.py
Labels: 3.13

#12808 Fix Avalara test for generate request data with click and collect
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_get_checkout_tax_data_with_single_point.yaml
  saleor/plugins/avatax/tests/test_avatax.py
Labels: skip changelog

#12781 Move ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL flag to SiteSettings model
  CHANGELOG.md
  saleor/demo/settings.py
  saleor/graphql/account/mutations/account.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/schema.graphql
  saleor/graphql/shop/mutations.py
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/types.py
  saleor/settings.py
  saleor/site/migrations/0037_sitesettings_enable_account_confirmation_by_email.py
  saleor/site/migrations/0038_auto_20230510_1107.py
  saleor/site/models.py
Labels: test deployment

#12819 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#12806 Cleanup db and migrations after 3.13 release
  saleor/celeryconf.py
  saleor/order/migrations/0163_order_events_rename_transaction_events.py
  saleor/order/migrations/tasks/saleor3_13.py
  saleor/payment/migrations/0050_drop_unused_transaction_fields.py
Labels: migrations perf test, skip changelog

#12804 Optimize App type resolvers
  saleor/graphql/app/dataloaders.py
  saleor/graphql/app/tests/benchmarks/test_apps.py
  saleor/graphql/app/types.py
  saleor/graphql/webhook/dataloaders.py
Labels: performance, 3.9

#12836 Allow staff user to update transaction assigned to another staff
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/payment/utils.py
  saleor/graphql/schema.graphql
Labels: test deployment, skip changelog, transactions

#12839 Allow staff user to update transaction assigned to another staff
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/payment/utils.py
  saleor/graphql/schema.graphql
Labels: 3.13, transactions

#12842 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip changelog

#12832 Refresh the Avalara cassettes for JPY related tests
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[3493-4297-3.0-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[3495-4297-3.0-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY[4300-5289-0.0-False].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY_with_sale[3484-4285-0.0-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY_with_sale[3485-4285-0.0-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_for_JPY_with_sale[4280-5264-5.0-False].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_order_total_for_JPY.yaml
  saleor/plugins/avatax/tests/test_avatax.py
Labels: skip changelog

#12809 Fix incorrect calculations for transactions
  saleor/payment/tests/test_transaction_item_calculations.py
  saleor/payment/transaction_item_calculations.py
Labels: test deployment, skip changelog

#12846 Fix incorrect calculations for transactions
  saleor/payment/tests/test_transaction_item_calculations.py
  saleor/payment/transaction_item_calculations.py
Labels: 3.13, transactions

#12841 Prevent crashing `CreateOrderFromCehckout` when the line is deleted in the meantime
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/graphql/checkout/mutations/order_create_from_checkout.py
Labels: test deployment, 3.12

#12714 Fix setting webhook activity using `isActive` field in the App manifest
  saleor/app/installation_utils.py
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: bug, skip changelog

#12853 Optimize App type resolvers
  saleor/graphql/app/dataloaders.py
  saleor/graphql/app/tests/benchmarks/test_apps.py
  saleor/graphql/app/types.py
  saleor/graphql/webhook/dataloaders.py
Labels: performance, 3.13

#12852 Optimize App type resolvers
  saleor/graphql/app/dataloaders.py
  saleor/graphql/app/tests/benchmarks/test_apps.py
  saleor/graphql/app/types.py
  saleor/graphql/webhook/dataloaders.py
Labels: performance, 3.12

#12851 Optimize App type resolvers
  saleor/graphql/app/dataloaders.py
  saleor/graphql/app/tests/benchmarks/test_apps.py
  saleor/graphql/app/types.py
  saleor/graphql/webhook/dataloaders.py
Labels: performance, 3.11

#12850 Optimize App type resolvers
  saleor/graphql/app/dataloaders.py
  saleor/graphql/app/tests/benchmarks/test_apps.py
  saleor/graphql/app/types.py
  saleor/graphql/webhook/dataloaders.py
Labels: performance, 3.10

#12854 Optimize App type resolvers
  saleor/graphql/app/dataloaders.py
  saleor/graphql/app/tests/benchmarks/test_apps.py
  saleor/graphql/app/types.py
  saleor/graphql/webhook/dataloaders.py
Labels: performance, main, skip changelog

#12710 Add possibility to delete expired orders
  CHANGELOG.md
  saleor/celeryconf.py
  saleor/channel/migrations/0012_channel_delete_expired_orders_after.py
  saleor/channel/models.py
  saleor/graphql/channel/mutations/channel_create.py
  saleor/graphql/channel/mutations/channel_update.py
  saleor/graphql/channel/mutations/utils.py
  saleor/graphql/channel/tests/mutations/test_channel_create.py
  saleor/graphql/channel/tests/mutations/test_channel_update.py
  saleor/graphql/channel/tests/queries/test_channel.py
  saleor/graphql/channel/types.py
  saleor/graphql/core/scalars.py
  saleor/graphql/schema.graphql
  saleor/order/migrations/0165_order_expired_at.py
  saleor/order/migrations/0166_order_propagate_expired_at.py
  saleor/order/migrations/tasks/saleor3_14.py
  saleor/order/models.py
  saleor/order/tasks.py
  saleor/order/tests/test_tasks.py
  saleor/settings.py
Labels: test deployment, order

#12848 Set missing transaction fields when calling orderMarkAsPaid
  saleor/graphql/order/tests/mutations/test_order_mark_as_paid.py
  saleor/order/actions.py
  saleor/payment/utils.py
Labels: test deployment, order, skip changelog, transactions

#12864 Fix recalculating tax in draft order on country change
  saleor/tax/calculations/order.py
  saleor/tax/tests/test_order_calculations.py
Labels: test deployment, 3.12

#12827 Improve feature_request template to format graphql
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: skip changelog

#12856 Fix `create_order_from_checkout` with vouchers
  saleor/checkout/complete_checkout.py
  saleor/checkout/fetch.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
Labels: test deployment, 3.12

#12818 Fix error on shipping zone update mutation when countires are missing
  SECURITY.md
  saleor/graphql/shipping/mutations/shippings.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_update.py
Labels: test deployment, main, skip changelog

#12883 Fix recalculating tax on country change in draft order
  saleor/tax/calculations/order.py
  saleor/tax/tests/test_order_calculations.py
Labels: 3.9

#12884 Fix recalculating tax on country change in draft order
  saleor/tax/calculations/order.py
  saleor/tax/tests/test_order_calculations.py
Labels: 3.10

#12885 Fix recalculating tax on country change in draft order
  saleor/tax/calculations/order.py
  saleor/tax/tests/test_order_calculations.py
Labels: 3.11

#12879 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#12895 Fix crashing checkout complete
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_associate_checkout_with_account.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/graphql/checkout/mutations/checkout_complete.py
  saleor/graphql/checkout/mutations/order_create_from_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: main, skip changelog

#12893 Fix crashing checkout complete
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/graphql/checkout/mutations/checkout_complete.py
  saleor/graphql/checkout/mutations/order_create_from_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: 3.13

#12901 Disallow redirects for external requests
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/management/commands/install_app.py
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/graphql/app/mutations/app_fetch_manifest.py
  saleor/graphql/core/validators/file.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/payment/gateways/adyen/tests/utils/test_apple_pay.py
  saleor/payment/gateways/adyen/utils/apple_pay.py
  saleor/payment/gateways/authorize_net/__init__.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/openid_connect/utils.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
Labels: main, skip changelog

#12902 Disallow redirects for external requests
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/management/commands/install_app.py
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/graphql/app/mutations/app_fetch_manifest.py
  saleor/graphql/core/validators/file.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/payment/gateways/adyen/tests/utils/test_apple_pay.py
  saleor/payment/gateways/adyen/utils/apple_pay.py
  saleor/payment/gateways/authorize_net/__init__.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/openid_connect/utils.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
Labels: skip changelog, 3.13

#12903 Disallow redirects for external requests
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/management/commands/install_app.py
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/graphql/app/mutations/app_fetch_manifest.py
  saleor/graphql/core/validators/file.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/payment/gateways/adyen/tests/utils/test_apple_pay.py
  saleor/payment/gateways/adyen/utils/apple_pay.py
  saleor/payment/gateways/authorize_net/__init__.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/openid_connect/utils.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
Labels: skip changelog, 3.12

#12906 Disallow redirects for external requests
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/management/commands/install_app.py
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/graphql/app/mutations/app_fetch_manifest.py
  saleor/graphql/core/validators/file.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/payment/gateways/adyen/tests/utils/test_apple_pay.py
  saleor/payment/gateways/adyen/utils/apple_pay.py
  saleor/payment/gateways/authorize_net/__init__.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/openid_connect/utils.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
Labels: skip changelog, 3.9

#12907 Disallow redirects for external requests
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/management/commands/install_app.py
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/graphql/app/mutations.py
  saleor/graphql/core/validators/file.py
  saleor/graphql/product/mutations/products.py
  saleor/payment/gateways/adyen/tests/utils/test_apple_pay.py
  saleor/payment/gateways/adyen/utils/apple_pay.py
  saleor/payment/gateways/authorize_net/__init__.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax_excise/utils.py
  saleor/plugins/openid_connect/utils.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
Labels: 3.8, skip changelog

#12908 Disallow redirects for external requests
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/management/commands/install_app.py
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/graphql/app/mutations.py
  saleor/graphql/core/validators/file.py
  saleor/graphql/product/mutations/products.py
  saleor/payment/gateways/adyen/tests/utils/test_apple_pay.py
  saleor/payment/gateways/adyen/utils/apple_pay.py
  saleor/payment/gateways/authorize_net/__init__.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/openid_connect/utils.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
Labels: 3.7, skip changelog

#12921 Upgrade requests to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, main

#12914 Upgrade requests to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.13

#12915 Upgrade requests to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.12

#12916 Upgrade requests to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.11

#12918 Upgrade requests to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.9

#12919 Upgrade requests to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.8

#12920 Upgrade requests to latest patch version
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.7

#12863 Match orders to user when creating new user or changing email with OIDC plugin
  CHANGELOG.md
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: main

#12887 Fix recalculating tax on country change in draft order
  saleor/tax/calculations/order.py
  saleor/tax/tests/test_order_calculations.py
Labels: skip changelog

#12929 Fix error on shipping zone update mutation when countries are missing
  saleor/graphql/shipping/mutations/shippings.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_update.py
Labels: 3.11

#12930 Fix error on shipping zone update mutation when countries are missing…
  SECURITY.md
  saleor/graphql/shipping/mutations/shippings.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_update.py
Labels: 3.13

#12931 Fix error on shipping zone update mutation when countires are missing
  saleor/graphql/shipping/mutations/shippings.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_update.py
Labels: 3.12

#12932 Fix error on shipping zone update mutation when countires are missing
  saleor/graphql/shipping/mutations/shippings.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_update.py
Labels: 3.9

#12858 Add types for granted refund to include lines
  saleor/graphql/order/dataloaders.py
  saleor/graphql/order/tests/queries/test_order_granted_refunds.py
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
  saleor/order/migrations/0165_auto_20230518_0854.py
  saleor/order/models.py
Labels: order

#12927 Split discount types
  saleor/graphql/discount/types.py
  saleor/graphql/discount/types/__init__.py
  saleor/graphql/discount/types/discounts.py
  saleor/graphql/discount/types/sales.py
  saleor/graphql/discount/types/vouchers.py
Labels: skip changelog

#12269 Order bulk create
  CHANGELOG.md
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/core/enums.py
  saleor/graphql/core/scalars.py
  saleor/graphql/core/types/common.py
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
  saleor/graphql/order/bulk_mutations/utils.py
  saleor/graphql/order/enums.py
  saleor/graphql/order/mutations/order_discount_add.py
  saleor/graphql/order/mutations/order_discount_common.py
  saleor/graphql/order/mutations/order_discount_update.py
  saleor/graphql/order/mutations/order_line_discount_update.py
  saleor/graphql/order/schema.py
  saleor/graphql/order/tests/benchmark/test_order_bulk_create.py
  saleor/graphql/order/tests/integration/test_bulk_order.py
  saleor/graphql/order/tests/mutations/test_order_bulk_create.py
  saleor/graphql/order/tests/mutations/test_utils.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/schema.graphql
  saleor/graphql/webhook/enums.py
  saleor/graphql/webhook/subscription_types.py
  saleor/graphql/webhook/tests/mutations/test_webhook_dry_run.py
  saleor/order/__init__.py
  saleor/order/actions.py
  saleor/order/error_codes.py
  saleor/order/migrations/0167_bulk_order_create_20230315_1312.py
  saleor/order/migrations/0168_order_bulk_permission.py
  saleor/order/migrations/0169_alter_order_options.py
  saleor/order/models.py
  saleor/permission/enums.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/tests/fixtures.py
  saleor/webhook/event_types.py
Labels: test deployment, feature branch, order, bulk

#12958 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#12946 Add possibility to easily set API patch for test APIClient
  saleor/graphql/tests/fixtures.py
Labels: skip changelog

#12950 Add order_by pk to InvoicesByOrderIdLoader.
  saleor/graphql/invoice/dataloaders.py
  saleor/invoice/migrations/0009_alter_invoice_options.py
  saleor/invoice/models.py
Labels: skip changelog

#12869 Add missing actions to transaction webhook responses
  saleor/payment/interface.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
  saleor/plugins/webhook/tests/test_tasks.py
Labels: 3.13, transactions

#12845 Add missing `actions` field to transaction's webhook resonses
  saleor/payment/interface.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
  saleor/plugins/webhook/tests/test_tasks.py
Labels: test deployment, skip changelog, transactions

#12964 Fix failing test after changes in kwargs used for webhook request
  saleor/plugins/webhook/tests/test_tasks.py
Labels: skip changelog

#12975 Fix failing test after changes in kwargs used for webhook request
  saleor/plugins/webhook/tests/test_tasks.py
Labels: 3.13

#12974 Fix setting webhook activity using `isActive` field in the App manifest
  saleor/app/installation_utils.py
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.9

#12972 Fix setting webhook activity using `isActive` field in the App manifest
  saleor/app/installation_utils.py
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.10

#12971 Fix setting webhook activity using `isActive` field in the App manifest
  saleor/app/installation_utils.py
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.11

#12970 Fix setting webhook activity using `isActive` field in the App manifest
  saleor/app/installation_utils.py
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.12

#12361 Add brand field to app manifest
  CHANGELOG.md
  saleor/app/__init__.py
  saleor/app/app.py
  saleor/app/installation_utils.py
  saleor/app/management/commands/install_app.py
  saleor/app/manifest_validations.py
  saleor/app/migrations/0025_auto_20230420_1544.py
  saleor/app/models.py
  saleor/app/signals.py
  saleor/app/tasks.py
  saleor/app/tests/test_installation_utils.py
  saleor/app/tests/test_validators.py
  saleor/app/validators.py
  saleor/graphql/app/dataloaders.py
  saleor/graphql/app/mutations/app_fetch_manifest.py
  saleor/graphql/app/tests/mutations/test_app_fetch_manifest.py
  saleor/graphql/app/tests/queries/test_app.py
  saleor/graphql/app/tests/queries/test_apps_installations.py
  saleor/graphql/app/types.py
  saleor/graphql/core/dataloaders.py
  saleor/graphql/core/enums.py
  saleor/graphql/core/tests/test_core.py
  saleor/graphql/core/tests/test_file_validation.py
  saleor/graphql/core/types/__init__.py
  saleor/graphql/core/types/common.py
  saleor/graphql/core/utils/__init__.py
  saleor/graphql/core/validators/file.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
  saleor/thumbnail/__init__.py
  saleor/thumbnail/migrations/0003_auto_20230412_1943.py
  saleor/thumbnail/models.py
  saleor/thumbnail/tests/test_utils.py
  saleor/thumbnail/tests/test_validators.py
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/utils.py
  saleor/thumbnail/validators.py
  saleor/thumbnail/views.py
Labels: test deployment, main

#12977 Fix typos in tests
  saleor/app/tests/cassettes/test_app_commands/test_creates_app_from_manifest.yaml
  saleor/app/tests/cassettes/test_app_commands/test_creates_app_from_manifest_activate_app.yaml
  saleor/app/tests/cassettes/test_app_commands/test_creates_app_from_manifest_app_has_all_required_permissions.yaml
  saleor/app/tests/cassettes/test_app_commands/test_creates_app_from_manifest_installation_failed.yaml
  saleor/app/tests/cassettes/test_app_commands/test_creates_app_from_manifest_sends_token.yaml
  saleor/app/tests/cassettes/test_app_tasks/test_install_app_task.yaml
  saleor/app/tests/cassettes/test_app_tasks/test_install_app_task_request_timeout.yaml
  saleor/app/tests/cassettes/test_app_tasks/test_install_app_task_wrong_format_of_target_token_url.yaml
  saleor/app/tests/cassettes/test_sends_data_to_target_url.yaml
  saleor/graphql/app/tests/mutations/cassettes/test_app_fetch_manifest/test_app_fetch_manifest.yaml
  saleor/graphql/app/tests/mutations/cassettes/test_app_fetch_manifest/test_app_fetch_manifest_incorrect_permission_in_manifest.yaml
  saleor/graphql/app/tests/mutations/cassettes/test_app_fetch_manifest/test_app_fetch_manifest_with_audience.yaml
  saleor/graphql/app/tests/mutations/test_app_fetch_manifest.py
Labels: main, skip changelog

#12968 Fix setting webhook activity using `isActive` field in the App manifest
  saleor/app/installation_utils.py
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
Labels: 3.13
