Repository saleor/saleor, pull requests merged in 2023-06, with the labels that each got.

#12988 Upgrade cryptography to latest patch version
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, main

#12981 Upgrade cryptography to latest patch version
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.13

#12982 Upgrade cryptography to latest patch version
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.12

#12983 Upgrade cryptography to latest patch version
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.11

#12984 Upgrade cryptography to latest patch version
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.10

#12985 Upgrade cryptography to latest patch version
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.9

#12986 Upgrade cryptography to latest patch version
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.8

#12987 Upgrade cryptography to latest patch version
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.7

#12990 Bump drop version from 3.14 to 3.15 for deprecated fields in transaction API
  saleor/graphql/core/descriptions.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#12969 Clean up discount mutations
  saleor/graphql/discount/mutations/__init__.py
  saleor/graphql/discount/mutations/sale/__init__.py
  saleor/graphql/discount/mutations/sale/sale_add_catalogues.py
  saleor/graphql/discount/mutations/sale/sale_base_catalogue.py
  saleor/graphql/discount/mutations/sale/sale_base_discount_catalogue.py
  saleor/graphql/discount/mutations/sale/sale_channel_listing_update.py
  saleor/graphql/discount/mutations/sale/sale_create.py
  saleor/graphql/discount/mutations/sale/sale_delete.py
  saleor/graphql/discount/mutations/sale/sale_remove_catalogues.py
  saleor/graphql/discount/mutations/sale/sale_update.py
  saleor/graphql/discount/mutations/voucher/__init__.py
  saleor/graphql/discount/mutations/voucher/voucher_add_catalogues.py
  saleor/graphql/discount/mutations/voucher/voucher_channel_listing_update.py
  saleor/graphql/discount/mutations/voucher/voucher_create.py
  saleor/graphql/discount/mutations/voucher/voucher_delete.py
  saleor/graphql/discount/mutations/voucher/voucher_remove_catalogues.py
  saleor/graphql/discount/mutations/voucher/voucher_update.py
  saleor/graphql/discount/schema.py
  saleor/graphql/discount/tests/mutations/test_sale_channel_listing_update.py
  saleor/graphql/product/tests/test_product_discounted_price.py
Labels: skip changelog

#12965 Add AttributeBulkTranslate and AttributeValueBulkTranslate mutations
  CHANGELOG.md
  saleor/graphql/attribute/schema.py
  saleor/graphql/core/enums.py
  saleor/graphql/core/types/__init__.py
  saleor/graphql/core/types/common.py
  saleor/graphql/schema.graphql
  saleor/graphql/translations/mutations.py
  saleor/graphql/translations/mutations/__init__.py
  saleor/graphql/translations/mutations/attribute_bulk_translate.py
  saleor/graphql/translations/mutations/attribute_translate.py
  saleor/graphql/translations/mutations/attribute_value_bulk_translate.py
  saleor/graphql/translations/mutations/attribute_value_translate.py
  saleor/graphql/translations/mutations/category_translate.py
  saleor/graphql/translations/mutations/collection_translate.py
  saleor/graphql/translations/mutations/menu_item_translate.py
  saleor/graphql/translations/mutations/page_translate.py
  saleor/graphql/translations/mutations/product_translate.py
  saleor/graphql/translations/mutations/product_variant_translate.py
  saleor/graphql/translations/mutations/sale_translate.py
  saleor/graphql/translations/mutations/shipping_price_translate.py
  saleor/graphql/translations/mutations/shop_settings_translate.py
  saleor/graphql/translations/mutations/utils.py
  saleor/graphql/translations/mutations/voucher_translate.py
  saleor/graphql/translations/tests/mutations/__init__.py
  saleor/graphql/translations/tests/mutations/test_attribute_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_attribute_value_bulk_transalte.py
  saleor/tests/fixtures.py
  saleor/translations/__init__.py
  saleor/translations/error_codes.py
Labels: test deployment

#12994 Use `webhookDryRun` mutation's context instead of creating dummy one
  saleor/graphql/webhook/mutations/webhook_dry_run.py
  saleor/graphql/webhook/subscription_types.py
  saleor/graphql/webhook/tests/mutations/test_webhook_dry_run.py
Labels: webhooks, skip changelog

#13015 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#12960 Where filters for products
  CHANGELOG.md
  saleor/graphql/core/connection.py
  saleor/graphql/core/types/common.py
  saleor/graphql/core/types/filter_input.py
  saleor/graphql/product/filters.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/queries/test_products_query.py
  saleor/graphql/product/tests/queries/test_products_query_with_where.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_category_filtering.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/types/categories.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/schema.graphql
  saleor/graphql/utils/filters.py
  saleor/product/migrations/0184_product_product_gin.py
  saleor/product/models.py
  saleor/tests/fixtures.py
Labels: test deployment, filters, product

#12993 Improve search indexing order in search building tasks
  saleor/core/search_tasks.py
Labels: performance, 3.9

#12935 Allow to use external references for attributes in product mutations
  CHANGELOG.md
  saleor/graphql/attribute/tests/mutations/test_attribute_update.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/types.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/deprecated/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_create.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_create.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: test deployment

#12926 Fix draft order shipping method update
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/order_update_shipping.py
  saleor/graphql/order/mutations/utils.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/types.py
Labels: test deployment, 3.9

#13028 Fix draft order shipping method update
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/order_update_shipping.py
  saleor/graphql/order/mutations/utils.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/types.py
Labels: skip changelog, 3.10

#13021 Drop migration celery task for order.expired_at field
  saleor/celeryconf.py
  saleor/order/migrations/0166_order_propagate_expired_at.py
  saleor/order/migrations/tasks/saleor3_14.py
Labels: skip changelog, 3.15

#13000 Add promotion webhooks
  saleor/discount/migrations/0045_promotion_promotionrule.py
  saleor/discount/models.py
  saleor/graphql/discount/mutations/promotion/promotion_create.py
  saleor/graphql/discount/mutations/promotion/promotion_delete.py
  saleor/graphql/discount/mutations/promotion/promotion_update.py
  saleor/graphql/discount/tests/mutations/test_promotion_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_delete.py
  saleor/graphql/discount/tests/mutations/test_promotion_update.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/graphql/webhook/enums.py
  saleor/graphql/webhook/subscription_types.py
  saleor/graphql/webhook/tests/mutations/test_webhook_dry_run.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/payloads.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/webhook/event_types.py
Labels: promotions

#13041 Improve search indexing order in search building tasks
  saleor/core/search_tasks.py
Labels: performance, main, skip changelog

#13040 Improve search indexing order in search building tasks
  saleor/core/search_tasks.py
Labels: performance, 3.14

#13039 Improve search indexing order in search building tasks
  saleor/core/search_tasks.py
Labels: performance, 3.13

#13038 Improve search indexing order in search building tasks
  saleor/core/search_tasks.py
Labels: performance, 3.12

#13036 Improve search indexing order in search building tasks
  saleor/core/search_tasks.py
Labels: performance, 3.10

#13056 Allow to add a gift card to a checkout without email
  CHANGELOG.md
  saleor/giftcard/tests/test_utils.py
  saleor/giftcard/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
  saleor/graphql/giftcard/tests/queries/test_gift_card.py
  saleor/graphql/giftcard/types.py
  saleor/graphql/schema.graphql
  saleor/order/utils.py
Labels: 3.14

#13057 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#13004 Where filters by ids
  CHANGELOG.md
  saleor/graphql/product/filters.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/queries/test_product_variants_query_with_where.py
  saleor/graphql/product/tests/test_category_filtering.py
  saleor/graphql/product/tests/test_collection_filtering_and_sorting_with_channels.py
  saleor/graphql/schema.graphql
Labels: test deployment, filters

#13079 Fix draft order shipping method update
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/order_update_shipping.py
  saleor/graphql/order/mutations/utils.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/types.py
Labels: test deployment, 3.11

#13099 Fix draft order shipping method update
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/order_update_shipping.py
  saleor/graphql/order/mutations/utils.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/types.py
Labels: skip changelog, 3.12

#13100 Fix draft order shipping method update
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/order_update_shipping.py
  saleor/graphql/order/mutations/utils.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/types.py
Labels: skip changelog, 3.13

#13102 Fix draft order shipping method update
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/order_update_shipping.py
  saleor/graphql/order/mutations/utils.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/types.py
Labels: skip changelog, 3.14

#13103 Fix draft order shipping method update
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/order_update_shipping.py
  saleor/graphql/order/mutations/utils.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/types.py
Labels: skip changelog

#13075 Add `Saleor-Schema-Version` header to app installation handshake
  CHANGELOG.md
  saleor/__init__.py
  saleor/app/headers.py
  saleor/app/installation_utils.py
  saleor/app/management/commands/create_app.py
  saleor/app/management/commands/install_app.py
  saleor/app/tests/cassettes/test_app_commands/test_creates_app_from_manifest_sends_token.yaml
  saleor/app/tests/test_app_commands.py
  saleor/app/tests/test_installation_utils.py
  saleor/graphql/app/mutations/app_fetch_manifest.py
  saleor/graphql/app/tests/mutations/test_app_fetch_manifest.py
  saleor/graphql/shop/types.py
Labels: main

#13105 Assign app as a transaction owner if missing
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
Labels: 3.14

#13104 Assign app as a transaction owner if missing
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
Labels: 3.13

#13118 Bump dependencies
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#13121 Bump dependencies for new bookworm
  Dockerfile
Labels: dependencies, test deployment

#13123 Bump dependencies for new bookworm
  Dockerfile
Labels: skip changelog, 3.10

#13124 Bump dependencies for new bookworm
  Dockerfile
Labels: skip changelog, 3.11

#13125 Bump dependencies for new bookworm
  Dockerfile
Labels: skip changelog, 3.12

#13127 Bump dependencies for new bookworm
  Dockerfile
Labels: skip changelog, 3.14

#13134 Bump dependencies for new bookworm
  Dockerfile
Labels: 3.7, skip changelog

#13135 Bump dependencies for new bookworm
  Dockerfile
Labels: 3.8, skip changelog

#13066 Update descriptions
  saleor/graphql/checkout/types.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#13147 Split warehouse module
  saleor/graphql/product/tests/queries/test_variant_query.py
  saleor/graphql/warehouse/mutations.py
  saleor/graphql/warehouse/mutations/__init__.py
  saleor/graphql/warehouse/mutations/base.py
  saleor/graphql/warehouse/mutations/warehouse_create.py
  saleor/graphql/warehouse/mutations/warehouse_delete.py
  saleor/graphql/warehouse/mutations/warehouse_shipping_zone_assign.py
  saleor/graphql/warehouse/mutations/warehouse_shipping_zone_unassign.py
  saleor/graphql/warehouse/mutations/warehouse_update.py
  saleor/graphql/warehouse/tests/bulk_mutations/__init__.py
  saleor/graphql/warehouse/tests/bulk_mutations/test_stock_bulk_update.py
  saleor/graphql/warehouse/tests/mutations/__init__.py
  saleor/graphql/warehouse/tests/mutations/test_warehouse_create.py
  saleor/graphql/warehouse/tests/mutations/test_warehouse_delete.py
  saleor/graphql/warehouse/tests/mutations/test_warehouse_shipping_zone_assign.py
  saleor/graphql/warehouse/tests/mutations/test_warehouse_shipping_zone_unassign.py
  saleor/graphql/warehouse/tests/mutations/test_warehouse_update.py
  saleor/graphql/warehouse/tests/queries/__init__.py
  saleor/graphql/warehouse/tests/queries/test_stock.py
  saleor/graphql/warehouse/tests/queries/test_stocks.py
  saleor/graphql/warehouse/tests/queries/test_stocks_filtering.py
  saleor/graphql/warehouse/tests/queries/test_warehouse.py
  saleor/graphql/warehouse/tests/queries/test_warehouses.py
  saleor/graphql/warehouse/tests/queries/test_warehouses_filtering.py
  saleor/graphql/warehouse/tests/queries/test_warehouses_pagination.py
  saleor/graphql/warehouse/tests/test_stock.py
  saleor/graphql/warehouse/tests/test_warehouse.py
Labels: skip changelog, hackathon

#13148 Remove unused django-versatileimagefield package
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/account/migrations/0026_user_avatar.py
  saleor/product/migrations/0001_initial.py
  saleor/product/migrations/0030_auto_20170206_0407.py
  saleor/product/migrations/0044_auto_20180108_0814.py
  saleor/product/migrations/0053_auto_20180305_1002.py
  saleor/product/migrations/0143_rename_product_images_to_product_media.py
Labels: hackathon

#13146 Remove unused google-measurement-protocol package
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/core/analytics.py
  saleor/core/middleware.py
  saleor/core/tests/test_analytics.py
  saleor/graphql/checkout/mutations/checkout_complete.py
  saleor/graphql/checkout/mutations/order_create_from_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
  saleor/graphql/order/tests/mutations/test_order_bulk_create.py
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
  saleor/order/actions.py
  saleor/settings.py
Labels: hackathon

#13149 Split shop module
  saleor/graphql/shop/mutations.py
  saleor/graphql/shop/mutations/__init__.py
  saleor/graphql/shop/mutations/gift_card_settings_update.py
  saleor/graphql/shop/mutations/order_settings_update.py
  saleor/graphql/shop/mutations/shop_address_update.py
  saleor/graphql/shop/mutations/shop_domain_update.py
  saleor/graphql/shop/mutations/shop_fetch_tax_rates.py
  saleor/graphql/shop/mutations/shop_settings_update.py
  saleor/graphql/shop/mutations/staff_notification_recipient_create.py
  saleor/graphql/shop/mutations/staff_notification_recipient_delete.py
  saleor/graphql/shop/mutations/staff_notification_recipient_update.py
  saleor/graphql/shop/tests/mutations/__init__.py
  saleor/graphql/shop/tests/mutations/test_gift_card_settings_update.py
  saleor/graphql/shop/tests/mutations/test_order_settings_update.py
  saleor/graphql/shop/tests/mutations/test_shop_address_update.py
  saleor/graphql/shop/tests/mutations/test_shop_domain_update.py
  saleor/graphql/shop/tests/mutations/test_shop_settings_update.py
  saleor/graphql/shop/tests/mutations/test_staff_notification_recipient_create.py
  saleor/graphql/shop/tests/mutations/test_staff_notification_recipient_update.py
  saleor/graphql/shop/tests/queries/__init__.py
  saleor/graphql/shop/tests/queries/test_gift_card_settings.py
  saleor/graphql/shop/tests/queries/test_order_settings.py
  saleor/graphql/shop/tests/queries/test_shop.py
  saleor/graphql/shop/tests/test_shop.py
  saleor/graphql/shop/tests/test_shop_taxes.py
Labels: skip changelog, hackathon

#13145 Bump google-i18n-address
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/account/i18n.py
Labels: skip changelog

#13158 Bump devcontainer dependencies
  .devcontainer/Dockerfile
Labels: skip changelog

#13154 Split shipping module
  saleor/graphql/shipping/bulk_mutations/__init__.py
  saleor/graphql/shipping/bulk_mutations/shipping_price_bulk_delete.py
  saleor/graphql/shipping/bulk_mutations/shipping_zone_bulk_delete.py
  saleor/graphql/shipping/mutations/__init__.py
  saleor/graphql/shipping/mutations/base.py
  saleor/graphql/shipping/mutations/shipping_method_channel_listing_update.py
  saleor/graphql/shipping/mutations/shipping_price_create.py
  saleor/graphql/shipping/mutations/shipping_price_delete.py
  saleor/graphql/shipping/mutations/shipping_price_exclude_products.py
  saleor/graphql/shipping/mutations/shipping_price_remove_product_from_exclude.py
  saleor/graphql/shipping/mutations/shipping_price_update.py
  saleor/graphql/shipping/mutations/shipping_zone_create.py
  saleor/graphql/shipping/mutations/shipping_zone_delete.py
  saleor/graphql/shipping/mutations/shipping_zone_update.py
  saleor/graphql/shipping/schema.py
  saleor/graphql/shipping/tests/benchmark/test_shipping_methods.py
  saleor/graphql/shipping/tests/mutations/test_bulk_delete.py
  saleor/graphql/shipping/tests/mutations/test_shipping_method_channel_listing_update.py
  saleor/graphql/shipping/tests/mutations/test_shipping_price_create.py
  saleor/graphql/shipping/tests/mutations/test_shipping_price_exclude_products.py
  saleor/graphql/shipping/tests/mutations/test_shipping_price_remove_product_from_exclude.py
  saleor/graphql/shipping/tests/mutations/test_shipping_price_update.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_create.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_update.py
  saleor/graphql/shipping/tests/queries/__init__.py
  saleor/graphql/shipping/tests/queries/test_shipping_zone.py
  saleor/graphql/shipping/tests/queries/test_shipping_zones.py
  saleor/graphql/shipping/tests/queries/test_shipping_zones_filtering.py
Labels: skip changelog, hackathon

#13160 Split payment module
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/mutations/__init__.py
  saleor/graphql/payment/mutations/base.py
  saleor/graphql/payment/mutations/payment/__init__.py
  saleor/graphql/payment/mutations/payment/checkout_payment_create.py
  saleor/graphql/payment/mutations/payment/payment_capture.py
  saleor/graphql/payment/mutations/payment/payment_check_balance.py
  saleor/graphql/payment/mutations/payment/payment_gateway_initialize.py
  saleor/graphql/payment/mutations/payment/payment_initialize.py
  saleor/graphql/payment/mutations/payment/payment_refund.py
  saleor/graphql/payment/mutations/payment/payment_void.py
  saleor/graphql/payment/mutations/transaction/__init__.py
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/mutations/transaction/transaction_initialize.py
  saleor/graphql/payment/mutations/transaction/transaction_process.py
  saleor/graphql/payment/mutations/transaction/transaction_request_action.py
  saleor/graphql/payment/mutations/transaction/transaction_update.py
  saleor/graphql/payment/mutations/transaction/utils.py
  saleor/graphql/payment/tests/benchmark/test_payment_transactions.py
  saleor/graphql/payment/tests/deprecated/test_checkout_payment_create.py
  saleor/graphql/payment/tests/mutations/test_check_payment_balance.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/graphql/payment/tests/mutations/test_payment_capture.py
  saleor/graphql/payment/tests/mutations/test_payment_initialize.py
  saleor/graphql/payment/tests/mutations/test_payment_void.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/queries/test_payment_capture.py
  saleor/graphql/payment/tests/queries/test_payment_refund.py
  saleor/graphql/payment/tests/queries/test_payment_sources.py
  saleor/graphql/payment/tests/queries/test_payments_query.py
Labels: skip changelog, hackathon

#13161 Remove redundant image dataloader
  saleor/graphql/order/types.py
  saleor/graphql/product/dataloaders/__init__.py
  saleor/graphql/product/dataloaders/products.py
Labels: skip changelog

#13164 Update GraphQL playground
  templates/graphql/playground.html
Labels: skip changelog

#13156 Drop translation proxy
  CHANGELOG.md
  saleor/attribute/models/base.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/core/utils/translations.py
  saleor/discount/models.py
  saleor/menu/models.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
  saleor/page/models.py
  saleor/product/migrations/0059_generate_variant_name_from_attrs.py
  saleor/product/models.py
  saleor/product/tests/test_translation.py
  saleor/shipping/models.py
  saleor/shipping/tests/test_translation.py
  saleor/site/models.py
Labels: hackathon

#13101 Add 'promotions' query.
  saleor/graphql/discount/filters.py
  saleor/graphql/discount/resolvers.py
  saleor/graphql/discount/schema.py
  saleor/graphql/discount/sorters.py
  saleor/graphql/discount/tests/queries/test_promotions.py
  saleor/graphql/discount/types/promotions.py
  saleor/graphql/schema.graphql
  saleor/tests/fixtures.py
Labels: promotions

#13155 Add missing descriptions to account types
  CHANGELOG.md
  saleor/graphql/account/schema.py
  saleor/graphql/account/types.py
  saleor/graphql/schema.graphql
Labels: hackathon

#13163 Add missing descriptions to app types
  CHANGELOG.md
  saleor/app/management/commands/create_app.py
  saleor/app/management/commands/install_app.py
  saleor/graphql/app/mutations/app_fetch_manifest.py
  saleor/graphql/app/mutations/app_install.py
  saleor/graphql/app/types.py
  saleor/graphql/schema.graphql
Labels: hackathon

#13152 Add dataloader for ShippingZone warehouses
  saleor/graphql/shipping/tests/benchmark/test_shipping_zones.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_update.py
  saleor/graphql/shipping/types.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/tests/fixtures.py
Labels: performance, hackathon

#13166 Add missing descriptions to channel types
  CHANGELOG.md
  saleor/graphql/channel/mutations/channel_create.py
  saleor/graphql/channel/types.py
  saleor/graphql/schema.graphql
Labels: hackathon

#13171 Add benchmark for checkout giftcards
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
Labels: 3.9

#13165 Add missing descriptions to attribute types
  CHANGELOG.md
  saleor/graphql/attribute/types.py
  saleor/graphql/schema.graphql
Labels: hackathon

#13172 Fix dataloader for shipping methods to be more explicit
  saleor/graphql/shipping/dataloaders.py
Labels: skip changelog, hackathon

#13167 Add missing descriptions to checkout types
  CHANGELOG.md
  saleor/graphql/checkout/types.py
  saleor/graphql/schema.graphql
Labels: hackathon

#13168 Split meta module
  saleor/graphql/account/mutations/account.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/checkout/mutations/checkout_complete.py
  saleor/graphql/checkout/mutations/checkout_create.py
  saleor/graphql/checkout/mutations/order_create_from_checkout.py
  saleor/graphql/invoice/mutations.py
  saleor/graphql/meta/inputs.py
  saleor/graphql/meta/mutations/__init__.py
  saleor/graphql/meta/mutations/base.py
  saleor/graphql/meta/mutations/delete_metadata.py
  saleor/graphql/meta/mutations/delete_private_metadata.py
  saleor/graphql/meta/mutations/update_metadata.py
  saleor/graphql/meta/mutations/update_private_metadata.py
  saleor/graphql/meta/mutations/utils.py
  saleor/graphql/meta/tests/mutations/__init__.py
  saleor/graphql/meta/tests/mutations/test_account.py
  saleor/graphql/meta/tests/mutations/test_app.py
  saleor/graphql/meta/tests/mutations/test_attribute.py
  saleor/graphql/meta/tests/mutations/test_checkout.py
  saleor/graphql/meta/tests/mutations/test_delete_metadata.py
  saleor/graphql/meta/tests/mutations/test_delete_private_metadata.py
  saleor/graphql/meta/tests/mutations/test_discount.py
  saleor/graphql/meta/tests/mutations/test_gift_card.py
  saleor/graphql/meta/tests/mutations/test_invoice.py
  saleor/graphql/meta/tests/mutations/test_menu.py
  saleor/graphql/meta/tests/mutations/test_order.py
  saleor/graphql/meta/tests/mutations/test_page.py
  saleor/graphql/meta/tests/mutations/test_payment.py
  saleor/graphql/meta/tests/mutations/test_product.py
  saleor/graphql/meta/tests/mutations/test_shipping.py
  saleor/graphql/meta/tests/mutations/test_update_metadata.py
  saleor/graphql/meta/tests/mutations/test_update_private_metadata.py
  saleor/graphql/meta/tests/mutations/test_warehouse.py
  saleor/graphql/meta/tests/queries/__init__.py
  saleor/graphql/meta/tests/queries/test_account.py
  saleor/graphql/meta/tests/queries/test_app.py
  saleor/graphql/meta/tests/queries/test_attribute.py
  saleor/graphql/meta/tests/queries/test_checkout.py
  saleor/graphql/meta/tests/queries/test_discount.py
  saleor/graphql/meta/tests/queries/test_gift_card.py
  saleor/graphql/meta/tests/queries/test_meta_filters.py
  saleor/graphql/meta/tests/queries/test_order.py
  saleor/graphql/meta/tests/queries/test_page.py
  saleor/graphql/meta/tests/queries/test_payment.py
  saleor/graphql/meta/tests/queries/test_product.py
  saleor/graphql/meta/tests/queries/test_warehouse.py
  saleor/graphql/meta/tests/queries/utils.py
  saleor/graphql/meta/tests/test_meta_mutations.py
  saleor/graphql/meta/tests/test_meta_queries.py
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
  saleor/graphql/payment/mutations/payment/checkout_payment_create.py
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/mutations/category/category_create.py
  saleor/graphql/product/mutations/collection/collection_create.py
  saleor/graphql/product/mutations/digital_contents.py
  saleor/graphql/product/mutations/product/product_create.py
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
Labels: skip changelog, hackathon

#13174 Split menu module
  saleor/graphql/menu/bulk_mutations.py
  saleor/graphql/menu/bulk_mutations/__init__.py
  saleor/graphql/menu/bulk_mutations/menu_bulk_delete.py
  saleor/graphql/menu/bulk_mutations/menu_item_bulk_delete.py
  saleor/graphql/menu/mutations.py
  saleor/graphql/menu/mutations/__init__.py
  saleor/graphql/menu/mutations/assign_navigation.py
  saleor/graphql/menu/mutations/menu_create.py
  saleor/graphql/menu/mutations/menu_delete.py
  saleor/graphql/menu/mutations/menu_item_create.py
  saleor/graphql/menu/mutations/menu_item_delete.py
  saleor/graphql/menu/mutations/menu_item_move.py
  saleor/graphql/menu/mutations/menu_item_update.py
  saleor/graphql/menu/mutations/menu_update.py
  saleor/graphql/menu/tests/bulk_mutations/__init__.py
  saleor/graphql/menu/tests/bulk_mutations/test_menu_bulk_delete.py
  saleor/graphql/menu/tests/bulk_mutations/test_menu_item_bulk_delete.py
  saleor/graphql/menu/tests/mutations/__init__.py
  saleor/graphql/menu/tests/mutations/test_assign_navigation.py
  saleor/graphql/menu/tests/mutations/test_menu_create.py
  saleor/graphql/menu/tests/mutations/test_menu_delete.py
  saleor/graphql/menu/tests/mutations/test_menu_item_create.py
  saleor/graphql/menu/tests/mutations/test_menu_item_delete.py
  saleor/graphql/menu/tests/mutations/test_menu_item_move.py
  saleor/graphql/menu/tests/mutations/test_menu_item_update.py
  saleor/graphql/menu/tests/mutations/test_menu_update.py
  saleor/graphql/menu/tests/queries/__init__.py
  saleor/graphql/menu/tests/queries/test_menu.py
  saleor/graphql/menu/tests/queries/test_menu_item.py
  saleor/graphql/menu/tests/queries/test_menu_items.py
  saleor/graphql/menu/tests/queries/test_menus.py
  saleor/graphql/menu/tests/queries/test_menus_filtering.py
  saleor/graphql/menu/tests/queries/test_menus_sorting.py
  saleor/graphql/menu/tests/test_menu.py
Labels: skip changelog, hackathon

#13178 Add giftcard by checkout id dataloader
  saleor/graphql/checkout/tests/test_checkout_promo_codes.py
  saleor/graphql/checkout/types.py
  saleor/graphql/giftcard/dataloaders.py
Labels: performance, 3.9, hackathon

#13180 Split giftcard module
  saleor/graphql/giftcard/bulk_mutations/__init__.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_activate.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_create.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_deactivate.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_delete.py
  saleor/graphql/giftcard/mutations.py
  saleor/graphql/giftcard/mutations/__init__.py
  saleor/graphql/giftcard/mutations/gift_card_activate.py
  saleor/graphql/giftcard/mutations/gift_card_add_note.py
  saleor/graphql/giftcard/mutations/gift_card_create.py
  saleor/graphql/giftcard/mutations/gift_card_deactivate.py
  saleor/graphql/giftcard/mutations/gift_card_delete.py
  saleor/graphql/giftcard/mutations/gift_card_resend.py
  saleor/graphql/giftcard/mutations/gift_card_update.py
  saleor/graphql/giftcard/mutations/utils.py
  saleor/graphql/giftcard/tests/bulk_mutations/__init__.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_activate.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_create.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_deactivate.py
  saleor/graphql/giftcard/tests/bulk_mutations/test_gift_card_bulk_delete.py
  saleor/graphql/giftcard/tests/mutations/test_gift_card_create.py
  saleor/graphql/giftcard/tests/mutations/test_gift_card_resend.py
Labels: skip changelog, hackathon

#13175 Drop integration with openexchangerates API
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/core/tests/test_core.py
  saleor/core/utils/__init__.py
  saleor/graphql/product/tests/test_variant_pricing.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
  saleor/graphql/schema.graphql
  saleor/product/tests/test_product_availability.py
  saleor/product/utils/availability.py
  saleor/settings.py
Labels: hackathon

#13184 Add missing descriptions to csv export types
  CHANGELOG.md
  saleor/graphql/csv/types.py
  saleor/graphql/schema.graphql
Labels: hackathon

#13150 Add benchmark test for exportFiles events
  conftest.py
  saleor/graphql/csv/tests/benchmark/__init__.py
  saleor/graphql/csv/tests/benchmark/fixtures.py
  saleor/graphql/csv/tests/benchmark/test_export_file.py
Labels: 3.9

#13169 Use dataloader for channels in Order and Checkout
  conftest.py
  saleor/graphql/checkout/tests/benchmark/fixtures.py
  saleor/graphql/checkout/tests/benchmark/test_checkouts.py
  saleor/graphql/checkout/types.py
  saleor/graphql/order/tests/benchmark/fixtures.py
  saleor/graphql/order/tests/benchmark/test_order.py
  saleor/graphql/order/types.py
Labels: performance, hackathon

#13179 Drop vatlayer package
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  saleor/graphql/core/types/common.py
  saleor/graphql/schema.graphql
  saleor/graphql/shop/resolvers.py
  saleor/graphql/shop/tests/test_shop_taxes.py
  saleor/graphql/shop/types.py
  saleor/settings.py
  saleor/tax/migrations/0005_migrate_vatlayer.py
Labels: skip changelog, hackathon

#13176 Split invoice module
  saleor/graphql/invoice/mutations.py
  saleor/graphql/invoice/mutations/__init__.py
  saleor/graphql/invoice/mutations/invoice_create.py
  saleor/graphql/invoice/mutations/invoice_delete.py
  saleor/graphql/invoice/mutations/invoice_request.py
  saleor/graphql/invoice/mutations/invoice_request_delete.py
  saleor/graphql/invoice/mutations/invoice_send_notification.py
  saleor/graphql/invoice/mutations/invoice_update.py
  saleor/graphql/invoice/tests/test_invoice_create.py
  saleor/graphql/invoice/tests/test_invoice_request.py
  saleor/graphql/invoice/tests/test_invoice_update.py
  saleor/graphql/invoice/tests/test_send_invoice_notification.py
Labels: skip changelog, hackathon

#13132 Added createdByEmail filter in GiftCard
  CHANGELOG.md
  saleor/graphql/giftcard/filters.py
  saleor/graphql/giftcard/tests/queries/test_gift_card_filtering.py
  saleor/graphql/schema.graphql
Labels: main

#13193 Add dataloader for ShippingZone warehouses
  saleor/graphql/shipping/tests/benchmark/test_shipping_zones.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_update.py
  saleor/graphql/shipping/types.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/tests/fixtures.py
Labels: performance, 3.10

#13194 Add dataloader for ShippingZone warehouses
  saleor/graphql/shipping/tests/benchmark/test_shipping_zones.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_update.py
  saleor/graphql/shipping/types.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/tests/fixtures.py
Labels: performance, 3.11

#13195 Add dataloader for ShippingZone warehouses
  saleor/graphql/shipping/tests/benchmark/test_shipping_zones.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_update.py
  saleor/graphql/shipping/types.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/tests/fixtures.py
Labels: performance, 3.12

#13198 Add dataloader for ShippingZone warehouses
  saleor/graphql/shipping/tests/benchmark/test_shipping_zones.py
  saleor/graphql/shipping/tests/mutations/test_shipping_zone_update.py
  saleor/graphql/shipping/types.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/tests/fixtures.py
Labels: performance, main, skip changelog

#13202 Use dataloader for channels in Order and Checkout
  conftest.py
  saleor/graphql/checkout/tests/benchmark/fixtures.py
  saleor/graphql/checkout/tests/benchmark/test_checkouts.py
  saleor/graphql/checkout/types.py
  saleor/graphql/order/tests/benchmark/fixtures.py
  saleor/graphql/order/tests/benchmark/test_order.py
  saleor/graphql/order/types.py
Labels: performance, 3.11

#13203 Use dataloader for channels in Order and Checkout
  conftest.py
  saleor/graphql/checkout/tests/benchmark/fixtures.py
  saleor/graphql/checkout/tests/benchmark/test_checkouts.py
  saleor/graphql/checkout/types.py
  saleor/graphql/order/tests/benchmark/fixtures.py
  saleor/graphql/order/tests/benchmark/test_order.py
  saleor/graphql/order/types.py
Labels: performance, 3.12

#13204 Use dataloader for channels in Order and Checkout
  conftest.py
  saleor/graphql/checkout/tests/benchmark/fixtures.py
  saleor/graphql/checkout/tests/benchmark/test_checkouts.py
  saleor/graphql/checkout/types.py
  saleor/graphql/order/tests/benchmark/fixtures.py
  saleor/graphql/order/tests/benchmark/test_order.py
  saleor/graphql/order/types.py
Labels: performance, 3.13

#13205 Use dataloader for channels in Order and Checkout
  conftest.py
  saleor/graphql/checkout/tests/benchmark/fixtures.py
  saleor/graphql/checkout/tests/benchmark/test_checkouts.py
  saleor/graphql/checkout/types.py
  saleor/graphql/order/tests/benchmark/fixtures.py
  saleor/graphql/order/tests/benchmark/test_order.py
  saleor/graphql/order/types.py
Labels: performance, 3.14

#13162 Add ACCOUNT_CONFIRMATION_REQUESTED event
  CHANGELOG.md
  saleor/account/notifications.py
  saleor/graphql/account/mutations/account/account_register.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/test_account.py
  saleor/graphql/schema.graphql
  saleor/graphql/webhook/enums.py
  saleor/graphql/webhook/subscription_types.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/webhook/event_types.py
Labels: test deployment, hackathon

#13192 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: test deployment, :robot: bot, skip changelog

#13159 Unify country fetching
  CHANGELOG.md
  saleor/core/utils/country.py
  saleor/graphql/checkout/mutations/checkout_create.py
  saleor/graphql/checkout/mutations/checkout_create_from_order.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
  saleor/order/utils.py
  saleor/tax/calculations/checkout.py
  saleor/tax/tests/test_utils.py
  saleor/tax/utils.py
Labels: test deployment, hackathon

#13153 Factories in fixtures
  saleor/attribute/tests/test_utils.py
  saleor/core/tests/test_search_tasks.py
  saleor/graphql/order/tests/queries/test_order_with_filter.py
  saleor/graphql/order/tests/queries/test_pagination.py
  saleor/graphql/product/tests/mutations/test_product_type_create.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/tests/fixtures.py
Labels: technical debt, skip changelog, hackathon

#13014 Include lines in transaction's refund requests
  CHANGELOG.md
  saleor/graphql/core/enums.py
  saleor/graphql/core/types/common.py
  saleor/graphql/order/dataloaders.py
  saleor/graphql/order/enums.py
  saleor/graphql/order/mutations/order_grant_refund_create.py
  saleor/graphql/order/mutations/order_grant_refund_update.py
  saleor/graphql/order/mutations/order_grant_refund_utils.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_create.py
  saleor/graphql/order/tests/mutations/test_order_grant_refund_update.py
  saleor/graphql/order/tests/queries/test_order_granted_refunds.py
  saleor/graphql/order/types.py
  saleor/graphql/payment/mutations/__init__.py
  saleor/graphql/payment/mutations/transaction/__init__.py
  saleor/graphql/payment/mutations/transaction/transaction_request_action.py
  saleor/graphql/payment/mutations/transaction/transaction_request_refund_for_granted_refund.py
  saleor/graphql/payment/schema.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_action.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_refund_for_granted_refund.py
  saleor/graphql/schema.graphql
  saleor/graphql/webhook/subscription_types.py
  saleor/order/error_codes.py
  saleor/order/migrations/0171_auto_20230518_0854.py
  saleor/order/models.py
  saleor/payment/error_codes.py
  saleor/payment/gateway.py
  saleor/payment/interface.py
  saleor/payment/tests/test_gateway.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_refund_requested.py
  saleor/webhook/event_types.py
Labels: test deployment

#13225 Fix saving multiselect attrs using external refs in bulk mutations
  saleor/graphql/attribute/utils.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: skip changelog, 3.14

#13238 Remove Heroku as suggested method of deployment
  .gitignore
  .nvmrc
  Procfile
  README.md
  app.json
  runtime.txt
Labels: skip changelog

#13237 fix: #13181 dataloaders for `is_shipping_required` resolver
  saleor/graphql/order/types.py
Labels: skip changelog

#13233 Add ACCOUNT_CHANGE_EMAIL_REQUESTED event
  CHANGELOG.md
  saleor/graphql/account/mutations/account/request_email_change.py
  saleor/graphql/account/tests/mutations/account/test_account_request_deletion.py
  saleor/graphql/account/tests/mutations/account/test_request_email_change.py
  saleor/graphql/schema.graphql
  saleor/graphql/webhook/enums.py
  saleor/graphql/webhook/subscription_types.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/payloads.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/webhook/event_types.py
Labels: test deployment, hackathon

#13214 Add GiftCardsByCheckoutIdLoader
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/test_checkout_promo_codes.py
  saleor/graphql/checkout/types.py
  saleor/graphql/giftcard/dataloaders.py
Labels: main, skip changelog

#13210 Add GiftCardsByCheckoutIdLoader
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/test_checkout_promo_codes.py
  saleor/graphql/checkout/types.py
  saleor/graphql/giftcard/dataloaders.py
Labels: 3.10, hackathon

#13211 Add GiftCardsByCheckoutIdLoader
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/test_checkout_promo_codes.py
  saleor/graphql/checkout/types.py
  saleor/graphql/giftcard/dataloaders.py
Labels: 3.11, hackathon

#13240 Add giftcard by checkout id dataloader
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/test_checkout_promo_codes.py
  saleor/graphql/checkout/types.py
  saleor/graphql/giftcard/dataloaders.py
Labels: 3.12, hackathon

#13242 Add giftcard by checkout id dataloader
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/test_checkout_promo_codes.py
  saleor/graphql/checkout/types.py
  saleor/graphql/giftcard/dataloaders.py
Labels: 3.14, hackathon

#13243 Fix typo in dataloader name
  saleor/graphql/checkout/types.py
  saleor/graphql/giftcard/dataloaders.py
Labels: 3.9, hackathon

#13120 Drop deprecated fields from transactionsAPI for 3.14
  saleor/celeryconf.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/payment/migrations/0051_alter_transactionitem_available_actions.py
  saleor/payment/migrations/tasks/__init__.py
  saleor/payment/migrations/tasks/saleor3_14.py
  saleor/payment/models.py
  saleor/payment/utils.py
  saleor/plugins/webhook/tests/test_tasks.py
Labels: 3.14

#13255 Add EventsByExportFileIdLoader
  saleor/graphql/csv/dataloaders.py
  saleor/graphql/csv/types.py
Labels: 3.10, hackathon

#13253 Add EventsByExportFileIdLoader
  saleor/graphql/csv/dataloaders.py
  saleor/graphql/csv/types.py
Labels: 3.11, hackathon

#13252 Add EventsByExportFileIdLoader
  saleor/graphql/csv/dataloaders.py
  saleor/graphql/csv/types.py
Labels: 3.14, hackathon

#13251 Add EventsByExportFileIdLoader
  saleor/graphql/csv/dataloaders.py
  saleor/graphql/csv/types.py
Labels: 3.13, hackathon
