Repository saleor/saleor, pull requests merged in 2023-12, with the labels that each got.

#14836 Test for Voucher without any codes
  saleor/graphql/discount/tests/mutations/test_voucher_create.py
  saleor/graphql/discount/tests/queries/test_vouchers.py
Labels: skip changelog

#14897 Downgrade sentry sdk
  poetry.lock
  pyproject.toml
Labels: dependencies

#14901 Sunsetting demo.saleor.io in favour of storefront.saleor.io
  .github/workflows/publish-containers.yml
Labels: skip changelog

#14900 Sunsetting demo.saleor.io in favour of storefront.saleor.io
  .github/workflows/publish-containers.yml
Labels: skip changelog

#14856 Rename discount permission name after Promotion Feature
  saleor/discount/migrations/0070_alter_promotion_options.py
  saleor/discount/models.py
Labels: migrations perf test, skip changelog, main

#14885 Add lock to avoid deadlocks between checkout process and payment plugins
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
Labels: checkout, 3.14

#14890 Add lock to avoid deadlocks between checkout process and payment plugins
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
Labels: checkout, 3.16

#14891 Add lock to avoid deadlocks between checkout process and payment plugins
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
Labels: checkout, 3.17

#14892 Add lock to avoid deadlocks between checkout process and payment plugins
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
Labels: checkout, 3.18

#14893 Add lock to avoid deadlocks between checkout process and payment plugins
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
Labels: checkout, skip changelog, skip migrations perf test

#14923 Add an upper index on user email
  saleor/account/migrations/0082_auto_20231204_1419.py
  saleor/account/migrations/0083_merge_20231205_1315.py
Labels: 3.15

#14929 Add an upper index on user email
  saleor/account/migrations/0082_auto_20231204_1419.py
  saleor/account/migrations/0083_merge_20231205_1315.py
Labels: 3.17

#14930 Add an upper index on user email
  saleor/account/migrations/0082_auto_20231204_1419.py
  saleor/account/migrations/0083_merge_20231205_1315.py
Labels: 3.18

#14931 Add an upper index on user email
  saleor/account/migrations/0082_auto_20231204_1419.py
  saleor/account/migrations/0083_merge_20231205_1315.py
Labels: migrations perf test, skip changelog, main

#14924 Fix attributes save performance
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/graphql/attribute/tests/benchmark/test_attribute.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_delete.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_update.py
  saleor/graphql/attribute/tests/mutations/test_bulk_delete.py
  saleor/graphql/attribute/tests/queries/test_attribute_filter.py
  saleor/graphql/attribute/tests/queries/test_attribute_where.py
  saleor/graphql/attribute/tests/queries/test_attributes_sort.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/page/tests/mutations/test_page_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_delete.py
  saleor/graphql/page/tests/mutations/test_page_reorder_attribute_values.py
  saleor/graphql/page/tests/mutations/test_page_type_delete.py
  saleor/graphql/page/tests/mutations/test_page_types_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_update.py
  saleor/graphql/page/tests/queries/test_page.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/mutations/test_product_delete.py
  saleor/graphql/product/tests/mutations/test_product_type_delete.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_products_query_with_filter.py
  saleor/graphql/product/tests/queries/test_products_query_with_where.py
  saleor/graphql/product/tests/queries/test_variant_query.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_product_pagination.py
  saleor/graphql/product/tests/test_product_sorting_attributes.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/product/tests/test_generate_and_set_variant_name.py
  saleor/product/tests/test_product.py
  saleor/tests/fixtures.py
Labels: performance, skip changelog, 3.17

#14823 Release funds for abandoned checkouts
  saleor/celeryconf.py
  saleor/checkout/actions.py
  saleor/checkout/migrations/0060_fix_charge_and_authorize_status_for_empty_checkouts.py
  saleor/checkout/migrations/0061_checkout_last_transaction_modified_at_and_refundable.py
  saleor/checkout/migrations/0062_update_checkout_last_transaction_modified_at_and_refundable.py
  saleor/checkout/migrations/tasks/saleor3_14.py
  saleor/checkout/models.py
  saleor/checkout/payment_utils.py
  saleor/checkout/tests/test_actions.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/payment/gateway.py
  saleor/payment/migrations/0052_transactionitem_last_refund_success.py
  saleor/payment/models.py
  saleor/payment/tasks.py
  saleor/payment/tests/test_gateway.py
  saleor/payment/tests/test_tasks.py
  saleor/payment/tests/test_transaction_item_calculations.py
  saleor/payment/tests/test_utils.py
  saleor/payment/transaction_item_calculations.py
  saleor/payment/utils.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_tasks.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/settings.py
  saleor/tests/fixtures.py
Labels: checkout, 3.14, transactions

#14839 Release funds for abandoned checkouts
  saleor/celeryconf.py
  saleor/checkout/actions.py
  saleor/checkout/migrations/0060_fix_charge_and_authorize_status_for_empty_checkouts.py
  saleor/checkout/migrations/0061_checkout_last_transaction_modified_at_and_refundable.py
  saleor/checkout/migrations/0062_update_checkout_last_transaction_modified_at_and_refundable.py
  saleor/checkout/migrations/tasks/saleor3_14.py
  saleor/checkout/models.py
  saleor/checkout/payment_utils.py
  saleor/checkout/tests/test_actions.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/payment/gateway.py
  saleor/payment/migrations/0052_transactionitem_last_refund_success.py
  saleor/payment/migrations/0054_merge_20231122_0828.py
  saleor/payment/models.py
  saleor/payment/tasks.py
  saleor/payment/tests/test_gateway.py
  saleor/payment/tests/test_tasks.py
  saleor/payment/tests/test_transaction_item_calculations.py
  saleor/payment/tests/test_utils.py
  saleor/payment/transaction_item_calculations.py
  saleor/payment/utils.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_tasks.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/settings.py
  saleor/tests/fixtures.py
Labels: checkout, transactions, 3.16

#14841 Release funds for abandoned checkouts
  saleor/celeryconf.py
  saleor/checkout/actions.py
  saleor/checkout/migrations/0060_fix_charge_and_authorize_status_for_empty_checkouts.py
  saleor/checkout/migrations/0061_checkout_last_transaction_modified_at_and_refundable.py
  saleor/checkout/migrations/0062_update_checkout_last_transaction_modified_at_and_refundable.py
  saleor/checkout/migrations/tasks/saleor3_14.py
  saleor/checkout/models.py
  saleor/checkout/payment_utils.py
  saleor/checkout/tests/test_actions.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/payment/gateway.py
  saleor/payment/migrations/0052_transactionitem_last_refund_success.py
  saleor/payment/migrations/0054_merge_20231122_0828.py
  saleor/payment/models.py
  saleor/payment/tasks.py
  saleor/payment/tests/test_gateway.py
  saleor/payment/tests/test_tasks.py
  saleor/payment/tests/test_transaction_item_calculations.py
  saleor/payment/tests/test_utils.py
  saleor/payment/transaction_item_calculations.py
  saleor/payment/utils.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_tasks.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/settings.py
  saleor/tests/fixtures.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: checkout, transactions, 3.18

#14870 Release funds for abandoned checkouts
  saleor/checkout/actions.py
  saleor/checkout/migrations/0060_fix_charge_and_authorize_status_for_empty_checkouts.py
  saleor/checkout/migrations/0061_checkout_last_transaction_modified_at_and_refundable.py
  saleor/checkout/migrations/0062_update_checkout_last_transaction_modified_at_and_refundable.py
  saleor/checkout/migrations/tasks/saleor3_14.py
  saleor/checkout/models.py
  saleor/checkout/payment_utils.py
  saleor/checkout/tests/test_actions.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/payment/gateway.py
  saleor/payment/migrations/0052_transactionitem_last_refund_success.py
  saleor/payment/migrations/0054_merge_20231122_0828.py
  saleor/payment/models.py
  saleor/payment/tasks.py
  saleor/payment/tests/test_gateway.py
  saleor/payment/tests/test_tasks.py
  saleor/payment/tests/test_transaction_item_calculations.py
  saleor/payment/tests/test_utils.py
  saleor/payment/transaction_item_calculations.py
  saleor/payment/utils.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_tasks.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/settings.py
  saleor/tests/fixtures.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: checkout, skip changelog, transactions, skip migrations perf test

#14940 Fix attributes save performance
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/graphql/attribute/tests/benchmark/test_attribute.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_delete.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_update.py
  saleor/graphql/attribute/tests/mutations/test_bulk_delete.py
  saleor/graphql/attribute/tests/queries/test_attribute_filter.py
  saleor/graphql/attribute/tests/queries/test_attribute_where.py
  saleor/graphql/attribute/tests/queries/test_attributes_sort.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/page/tests/mutations/test_page_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_delete.py
  saleor/graphql/page/tests/mutations/test_page_reorder_attribute_values.py
  saleor/graphql/page/tests/mutations/test_page_type_delete.py
  saleor/graphql/page/tests/mutations/test_page_types_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_update.py
  saleor/graphql/page/tests/queries/test_page.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/mutations/test_product_delete.py
  saleor/graphql/product/tests/mutations/test_product_type_delete.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_products_query_with_filter.py
  saleor/graphql/product/tests/queries/test_products_query_with_where.py
  saleor/graphql/product/tests/queries/test_variant_query.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_product_pagination.py
  saleor/graphql/product/tests/test_product_sorting_attributes.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/product/tests/test_generate_and_set_variant_name.py
  saleor/product/tests/test_product.py
  saleor/tests/fixtures.py
Labels: performance, skip changelog, 3.14

#14938 Fix attributes save performance
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/graphql/attribute/tests/benchmark/test_attribute.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_delete.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_update.py
  saleor/graphql/attribute/tests/mutations/test_bulk_delete.py
  saleor/graphql/attribute/tests/queries/test_attribute_filter.py
  saleor/graphql/attribute/tests/queries/test_attribute_where.py
  saleor/graphql/attribute/tests/queries/test_attributes_sort.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/page/tests/mutations/test_page_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_delete.py
  saleor/graphql/page/tests/mutations/test_page_reorder_attribute_values.py
  saleor/graphql/page/tests/mutations/test_page_type_delete.py
  saleor/graphql/page/tests/mutations/test_page_types_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_update.py
  saleor/graphql/page/tests/queries/test_page.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/mutations/test_product_delete.py
  saleor/graphql/product/tests/mutations/test_product_type_delete.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_products_query_with_filter.py
  saleor/graphql/product/tests/queries/test_products_query_with_where.py
  saleor/graphql/product/tests/queries/test_variant_query.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_product_pagination.py
  saleor/graphql/product/tests/test_product_sorting_attributes.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/product/tests/test_generate_and_set_variant_name.py
  saleor/product/tests/test_product.py
  saleor/tests/fixtures.py
Labels: performance, skip changelog, 3.16

#14941 Optimize collection update and delete
  saleor/graphql/product/mutations/collection/collection_create.py
  saleor/graphql/product/mutations/collection/collection_delete.py
  saleor/product/tasks.py
  saleor/settings.py
Labels: performance, 3.17

#14911 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  saleor/csv/utils/product_headers.py
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/discount/utils.py
  saleor/product/utils/variants.py
Labels: test deployment, :robot: bot, skip changelog

#14858 Fix handling subscription with empty data
  saleor/graphql/checkout/mutations/checkout_add_promo_code.py
  saleor/plugins/webhook/shipping.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/plugins/webhook/tests/test_list_shipping_methods_for_checkout.py
  saleor/plugins/webhook/tests/test_shipping_webhook.py
Labels: webhooks, 3.14

#14921 Always use active app to process transactionAPI actions
  saleor/graphql/app/dataloaders.py
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/payment/gateway.py
  saleor/payment/tests/test_gateway.py
Labels: 3.14, transactions

#14933 Always use active app to process transactionAPI actions
  saleor/graphql/app/dataloaders.py
  saleor/graphql/payment/mutations/transaction/transaction_initialize.py
  saleor/graphql/payment/mutations/transaction/transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/payment/gateway.py
  saleor/payment/tests/test_gateway.py
Labels: skip changelog, transactions

#14934 Always use active app to process transactionAPI actions
  saleor/graphql/app/dataloaders.py
  saleor/graphql/payment/mutations/transaction/transaction_initialize.py
  saleor/graphql/payment/mutations/transaction/transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/payment/gateway.py
  saleor/payment/tests/test_gateway.py
Labels: transactions, 3.18

#14935 Always use active app to process transactionAPI actions
  saleor/graphql/app/dataloaders.py
  saleor/graphql/payment/mutations/transaction/transaction_initialize.py
  saleor/graphql/payment/mutations/transaction/transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/payment/gateway.py
  saleor/payment/tests/test_gateway.py
Labels: transactions, 3.17

#14936 Always use active app to process transactionAPI actions
  saleor/graphql/app/dataloaders.py
  saleor/graphql/payment/mutations/transaction/transaction_initialize.py
  saleor/graphql/payment/mutations/transaction/transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/payment/gateway.py
  saleor/payment/tests/test_gateway.py
Labels: transactions, 3.16

#14937 Always use active app to process transactionAPI actions
  saleor/graphql/app/dataloaders.py
  saleor/graphql/payment/mutations/transaction/transaction_initialize.py
  saleor/graphql/payment/mutations/transaction/transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/payment/gateway.py
  saleor/payment/tests/test_gateway.py
Labels: 3.15, transactions

#14846 Refactor order price calculation.
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/order/mutations/order_line_discount_update.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_order_discount.py
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/test_base_calculations/__init__.py
  saleor/order/tests/test_base_order_line_total.py
  saleor/order/tests/test_base_order_total.py
  saleor/order/tests/test_calculations.py
  saleor/order/tests/test_discount_calculations.py
  saleor/tax/calculations/order.py
  saleor/tax/tests/test_order_calculations.py
  saleor/tests/e2e/orders/discounts/test_order_products_on_promotion_and_manual_order_discount.py
Labels: test deployment, order, skip changelog, discount

#14994 Remove optional field from validation
  saleor/plugins/webhook/shipping.py
Labels: bug, 3.14

#15002 Allow switching channel with the same currency.
  saleor/graphql/discount/mutations/promotion/promotion_rule_update.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_update.py
Labels: bug, skip changelog, promotions

#15003 Make allow_replica argument required in get_plugins_manager function
  saleor/core/auth_backend.py
  saleor/graphql/plugins/dataloaders.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: webhooks, skip changelog, skip migrations perf test

#14991 Migration for idempotency key
  saleor/payment/migrations/0053_auto_20231211_0850.py
  saleor/payment/migrations/0054_add_idempotency_key_indexes.py
  saleor/payment/models.py
Labels: 3.14, transactions

#14996 Migration for idempotency key
  saleor/payment/migrations/0053_auto_20231211_0850.py
  saleor/payment/migrations/0054_add_idempotency_key_indexes.py
  saleor/payment/migrations/0055_merge_20231212_1610.py
  saleor/payment/models.py
Labels: 3.15, transactions

#14997 Migration for idempotency key
  saleor/payment/migrations/0053_auto_20231211_0850.py
  saleor/payment/migrations/0054_add_idempotency_key_indexes.py
  saleor/payment/migrations/0055_merge_20231212_1610.py
  saleor/payment/models.py
Labels: transactions, 3.16

#14998 Migration for idempotency key
  saleor/payment/migrations/0053_auto_20231211_0850.py
  saleor/payment/migrations/0054_add_idempotency_key_indexes.py
  saleor/payment/migrations/0055_merge_20231212_1610.py
  saleor/payment/models.py
Labels: transactions, 3.17

#14999 Migration for idempotency key
  saleor/payment/migrations/0053_auto_20231211_0850.py
  saleor/payment/migrations/0054_add_idempotency_key_indexes.py
  saleor/payment/migrations/0055_merge_20231212_1610.py
  saleor/payment/models.py
Labels: transactions, 3.18

#15000 Migration for idempotency key
  saleor/payment/migrations/0053_auto_20231211_0850.py
  saleor/payment/migrations/0054_add_idempotency_key_indexes.py
  saleor/payment/migrations/0055_merge_20231212_1610.py
  saleor/payment/models.py
Labels: migrations perf test, skip changelog, transactions

#14957 Fix handling subscription with empty data
  saleor/graphql/checkout/mutations/checkout_add_promo_code.py
  saleor/plugins/webhook/shipping.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/plugins/webhook/tests/test_list_shipping_methods_for_checkout.py
  saleor/plugins/webhook/tests/test_shipping_webhook.py
Labels: bug, 3.15

#14958 Fix handling subscription with empty data
  saleor/graphql/checkout/mutations/checkout_add_promo_code.py
  saleor/plugins/webhook/shipping.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/plugins/webhook/tests/test_list_shipping_methods_for_checkout.py
  saleor/plugins/webhook/tests/test_shipping_webhook.py
Labels: bug, 3.16

#14987 Fix handling subscription with empty data
  saleor/graphql/checkout/mutations/checkout_add_promo_code.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/plugins/webhook/tests/test_list_shipping_methods_for_checkout.py
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/webhook/transport/shipping.py
  saleor/webhook/transport/synchronous/transport.py
Labels: 3.17

#14988 Fix handling subscription with empty data
  saleor/graphql/checkout/mutations/checkout_add_promo_code.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/plugins/webhook/tests/test_list_shipping_methods_for_checkout.py
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/webhook/transport/shipping.py
  saleor/webhook/transport/synchronous/transport.py
Labels: 3.18

#14989 Fix handling subscription with empty data
  saleor/graphql/checkout/mutations/checkout_add_promo_code.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/plugins/webhook/tests/test_list_shipping_methods_for_checkout.py
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/webhook/transport/shipping.py
  saleor/webhook/transport/synchronous/transport.py
Labels: skip changelog

#14945 Optimize products filtering
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/product/models.py
Labels: performance, 3.14

#14955 Fix stripe api breaking change in plugin.
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: 3.15

#14954 Fix stripe api breaking change in plugin.
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: 3.16

#14953 Fix stripe api breaking change in plugin.
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: 3.17

#14952 Fix stripe api breaking change in plugin.
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: 3.18

#14982 Process `handle-promotion-toggle` task in batches.
  saleor/core/schedules.py
  saleor/discount/tasks.py
Labels: performance, test deployment, skip changelog, promotions

#15032 Process `handle-promotion-toggle` task in batches.
  saleor/core/schedules.py
  saleor/discount/tasks.py
Labels: promotions, 3.18

#15031 Process `handle-promotion-toggle` task in batches.
  saleor/core/schedules.py
  saleor/discount/tasks.py
Labels: promotions, 3.17

#14984 Optimize updating discounted prices for promotions
  saleor/discount/__init__.py
  saleor/discount/migrations/0066_promotionrule_variants.py
  saleor/discount/migrations/0067_fulfill_promotionrule_variants.py
  saleor/discount/migrations/0068_promotion_start_end_date_indexes.py
  saleor/discount/migrations/tasks/saleor3_17.py
  saleor/discount/models.py
  saleor/discount/tasks.py
  saleor/discount/tests/test_rounding_issue.py
  saleor/discount/tests/test_tasks.py
  saleor/discount/tests/test_utils/test_calculate_discounted_price_for_promotions.py
  saleor/discount/tests/test_utils/test_fetch_active_promotion_rules.py
  saleor/discount/tests/test_utils/test_get_variants_to_promotions_map.py
  saleor/discount/utils.py
  saleor/graphql/discount/mutations/bulk_mutations.py
  saleor/graphql/discount/mutations/promotion/promotion_bulk_delete.py
  saleor/graphql/discount/mutations/promotion/promotion_delete.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_create.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_delete.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_update.py
  saleor/graphql/discount/mutations/sale/sale_base_catalogue.py
  saleor/graphql/discount/mutations/sale/sale_delete.py
  saleor/graphql/discount/mutations/sale/sale_update.py
  saleor/graphql/discount/mutations/utils.py
  saleor/graphql/discount/tests/mutations/test_promotion_bulk_delete.py
  saleor/graphql/discount/tests/mutations/test_promotion_delete.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_delete.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_update.py
  saleor/graphql/discount/tests/mutations/test_sale_catalogues_add.py
  saleor/graphql/discount/tests/mutations/test_sale_catalogues_remove.py
  saleor/graphql/discount/tests/mutations/test_sale_delete.py
  saleor/graphql/discount/tests/mutations/test_sale_update.py
  saleor/graphql/discount/utils.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/tests/deprecated/test_product_channel_listing_update.py
  saleor/graphql/product/tests/test_product_discounted_price.py
  saleor/graphql/product/tests/test_variant_channel_listing_update.py
  saleor/product/models.py
  saleor/product/tasks.py
  saleor/product/tests/deprecated/test_tasks.py
  saleor/product/tests/test_fetch_variants_for_promotion_rules.py
  saleor/product/tests/test_product_minimal_variant_price.py
  saleor/product/tests/test_tasks.py
  saleor/product/utils/variant_prices.py
  saleor/product/utils/variants.py
  saleor/tests/fixtures.py
  saleor/webhook/tests/test_webhook_serializers.py
Labels: migrations perf test, promotions

#14553 Drop `bulkOrderCreateInput.voucher` field.
  CHANGELOG.md
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
  saleor/graphql/order/tests/mutations/test_order_bulk_create.py
  saleor/graphql/schema.graphql
Labels: voucher

#15041 Fix failing test.
  saleor/plugins/webhook/tests/test_shipping_webhook.py
Labels: bug, 3.15

#15042 Fix failing test.
  saleor/plugins/webhook/tests/test_shipping_webhook.py
Labels: bug, 3.17

#15030 Do not call Avatax when using flat rate
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: taxes, 3.14

#15035 Do not call Avatax when using flat rate
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: taxes, 3.16

#15036 Do not call Avatax when using flat rate
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: taxes, 3.17

#15037 Do not call Avatax when using flat rate
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: taxes, 3.18

#15038 Do not call Avatax when using flat rate
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
Labels: taxes, skip changelog, skip migrations perf test

#14964 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  saleor/account/models.py
  saleor/checkout/models.py
  saleor/core/utils/random_data.py
  saleor/graphql/account/types.py
  saleor/graphql/account/utils.py
  saleor/graphql/channel/utils.py
  saleor/graphql/product/mutations/collection/collection_delete.py
  saleor/graphql/product/tests/benchmark/test_collection.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/shipping/mutations/base.py
  saleor/graphql/warehouse/dataloaders.py
  saleor/graphql/warehouse/mutations/warehouse_shipping_zone_assign.py
  saleor/product/managers.py
  saleor/warehouse/models.py
Labels: test deployment, :robot: bot, skip changelog

#15040 Optimize updating discounted prices for promotions
  saleor/discount/__init__.py
  saleor/discount/migrations/0066_promotionrule_variants.py
  saleor/discount/migrations/0067_fulfill_promotionrule_variants.py
  saleor/discount/migrations/0068_promotion_start_end_date_indexes.py
  saleor/discount/migrations/0070_merge_20231215_0911.py
  saleor/discount/migrations/0071_merge_20231215_0943.py
  saleor/discount/models.py
  saleor/discount/tasks.py
  saleor/discount/tests/test_rounding_issue.py
  saleor/discount/tests/test_tasks.py
  saleor/discount/tests/test_utils/test_calculate_discounted_price_for_promotions.py
  saleor/discount/tests/test_utils/test_fetch_active_promotion_rules.py
  saleor/discount/tests/test_utils/test_get_variants_to_promotions_map.py
  saleor/discount/utils.py
  saleor/graphql/discount/mutations/bulk_mutations.py
  saleor/graphql/discount/mutations/promotion/promotion_bulk_delete.py
  saleor/graphql/discount/mutations/promotion/promotion_delete.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_create.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_delete.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_update.py
  saleor/graphql/discount/mutations/sale/sale_base_catalogue.py
  saleor/graphql/discount/mutations/sale/sale_delete.py
  saleor/graphql/discount/mutations/sale/sale_update.py
  saleor/graphql/discount/mutations/utils.py
  saleor/graphql/discount/tests/mutations/test_promotion_bulk_delete.py
  saleor/graphql/discount/tests/mutations/test_promotion_delete.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_delete.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_update.py
  saleor/graphql/discount/tests/mutations/test_sale_catalogues_add.py
  saleor/graphql/discount/tests/mutations/test_sale_catalogues_remove.py
  saleor/graphql/discount/tests/mutations/test_sale_delete.py
  saleor/graphql/discount/tests/mutations/test_sale_update.py
  saleor/graphql/discount/utils.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/tests/deprecated/test_product_channel_listing_update.py
  saleor/graphql/product/tests/test_product_discounted_price.py
  saleor/graphql/product/tests/test_variant_channel_listing_update.py
  saleor/product/models.py
  saleor/product/tasks.py
  saleor/product/tests/test_fetch_variants_for_promotion_rules.py
  saleor/product/tests/test_product_minimal_variant_price.py
  saleor/product/tests/test_tasks.py
  saleor/product/utils/variant_prices.py
  saleor/product/utils/variants.py
  saleor/tests/fixtures.py
  saleor/webhook/tests/test_webhook_serializers.py
Labels: migrations perf test, skip changelog, promotions

#15027 Add missing checkout resolver to transactionItem
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_cancelation_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_charge_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_refund_requested.py
Labels: 3.14

#15043 Add missing checkout resolver to transactionItem
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_cancelation_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_charge_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_refund_requested.py
Labels: 3.15

#15044 Add missing checkout resolver to transactionItem
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_cancelation_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_charge_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_refund_requested.py
Labels: 3.16

#15046 Add missing checkout resolver to transactionItem
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_cancelation_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_charge_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_refund_requested.py
Labels: 3.17

#15047 Add missing checkout resolver to transactionItem
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_cancelation_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_charge_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_refund_requested.py
Labels: 3.18

#15048 Add missing checkout resolver to transactionItem
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_cancelation_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_charge_requested.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_transaction_refund_requested.py
Labels: skip changelog, skip migrations perf test

#15049 Fix test for clearing promotion rule variants
  saleor/discount/tests/test_tasks.py
  saleor/tests/fixtures.py
Labels: 3.17

#15050 Fix test for clearing promotion rule variants
  saleor/discount/tests/test_tasks.py
  saleor/tests/fixtures.py
Labels: 3.18

#14985 Bulk create attribute value
  saleor/attribute/models/base.py
  saleor/graphql/attribute/enums.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/page/tests/mutations/test_page_update.py
  saleor/graphql/product/tests/benchmark/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
Labels: performance, 3.14

#15053 Fix `visible_to_user` makes unnecessary calls when the channel is not passed.
  saleor/graphql/product/tests/benchmark/test_collection.py
  saleor/product/models.py
  saleor/product/tests/test_collections_availability.py
  saleor/product/tests/test_product_availability.py
  saleor/tests/settings.py
Labels: 3.14

#15066 add collections handling for product bulk create
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: bulk, 3.14

#15065 Fix INSUFFICIENT_STOCK error not returning order lines ids
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/utils.py
  saleor/warehouse/availability.py
Labels: bug, skip changelog, 3.14

#15070 Fix rule variants recalculation
  saleor/discount/tasks.py
  saleor/discount/tests/test_tasks.py
  saleor/product/tests/test_fetch_variants_for_promotion_rules.py
  saleor/product/utils/variants.py
Labels: promotions, 3.18

#15073 Fix collections order in CheckoutLinesInfoByCheckoutTokenLoader
  saleor/graphql/checkout/dataloaders.py
Labels: skip changelog, 3.17

#15074 Fix collections order in CheckoutLinesInfoByCheckoutTokenLoader
  saleor/graphql/checkout/dataloaders.py
Labels: skip changelog, 3.18

#15059 Fix visible_to_user makes unnecessary calls when the channel is not passed.
  saleor/graphql/product/tests/benchmark/test_collection.py
  saleor/product/managers.py
  saleor/product/tests/test_collections_availability.py
  saleor/product/tests/test_product_availability.py
  saleor/tests/settings.py
Labels: 3.15

#15060 Fix visible_to_user makes unnecessary calls when the channel is not passed.
  saleor/graphql/product/tests/benchmark/test_collection.py
  saleor/product/managers.py
  saleor/product/tests/test_collections_availability.py
  saleor/product/tests/test_product_availability.py
  saleor/tests/settings.py
Labels: 3.16

#15061 Fix visible_to_user makes unnecessary calls when the channel is not passed.
  saleor/graphql/product/tests/benchmark/test_collection.py
  saleor/product/managers.py
  saleor/product/tests/test_collections_availability.py
  saleor/product/tests/test_product_availability.py
  saleor/tests/settings.py
Labels: 3.17

#15080 Fix collections order in CheckoutLinesInfoByCheckoutTokenLoader
  saleor/graphql/checkout/dataloaders.py
Labels: skip changelog, 3.14

#15079 Fix collections order in CheckoutLinesInfoByCheckoutTokenLoader
  saleor/graphql/checkout/dataloaders.py
Labels: skip changelog, 3.15

#15078 Fix collections order in CheckoutLinesInfoByCheckoutTokenLoader
  saleor/graphql/checkout/dataloaders.py
Labels: skip changelog, 3.16

#15076 Fix collections order in CheckoutLinesInfoByCheckoutTokenLoader
  saleor/graphql/checkout/dataloaders.py
Labels: skip changelog, main

#15082 Fix for discount migrations on main branch
  saleor/discount/migrations/0072_auto_20231213_1413.py
  saleor/discount/migrations/0073_auto_20231213_1535.py
Labels: skip changelog, skip migrations perf test

#15063 Fix visible_to_user makes unnecessary calls when the channel is not passed.
  saleor/graphql/product/tests/benchmark/test_collection.py
  saleor/product/tests/test_collections_availability.py
  saleor/product/tests/test_product_availability.py
  saleor/tests/settings.py
Labels: skip changelog, main

#15062 Fix visible_to_user makes unnecessary calls when the channel is not passed.
  saleor/graphql/product/tests/benchmark/test_collection.py
  saleor/product/managers.py
  saleor/product/tests/test_collections_availability.py
  saleor/product/tests/test_product_availability.py
  saleor/tests/settings.py
Labels: 3.18

#14932 Order subtotal propagation logic for version 3.18
  saleor/celeryconf.py
  saleor/order/migrations/0180_auto_20231108_0908.py
  saleor/order/migrations/0181_order_subtotal_as_a_field.py
  saleor/order/migrations/tasks/saleor3_18.py
  saleor/order/models.py
Labels: 3.18

#14887 Extend order with subtotal
  saleor/checkout/complete_checkout.py
  saleor/discount/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/order/calculations.py
  saleor/order/migrations/0180_auto_20231108_0908.py
  saleor/order/migrations/0181_order_subtotal_as_a_field.py
  saleor/order/models.py
  saleor/order/notifications.py
  saleor/order/tests/test_calculations.py
  saleor/order/tests/test_notifications.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
  saleor/tax/tests/test_order_calculations.py
  saleor/tests/fixtures.py
Labels: skip changelog

#15084 Handle invalid image MIME type during thumbnail generation
  saleor/graphql/core/tests/test_file_validation.py
  saleor/graphql/core/validators/file.py
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/utils.py
  saleor/thumbnail/views.py
Labels: 3.17

#15018 Optimize products filtering
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/product/managers.py
Labels: performance, skip changelog, main

#15019 Optimize products filtering
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/product/managers.py
Labels: performance, 3.18

#15020 Optimize products filtering
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/product/managers.py
Labels: performance, 3.17

#15021 Optimize products filtering
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/product/managers.py
Labels: performance, 3.16

#15022 Optimize products filtering
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/product/managers.py
Labels: performance, 3.15

#15085 add missing autodiscover for attributer migration tasks.
  saleor/celeryconf.py
Labels: bug, 3.16, celery

#15087 Handle invalid image MIME type during thumbnail generation
  saleor/graphql/core/tests/test_file_validation.py
  saleor/graphql/core/validators/file.py
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/utils.py
  saleor/thumbnail/views.py
Labels: 3.18

#15088 Handle invalid image MIME type during thumbnail generation
  saleor/graphql/core/tests/test_file_validation.py
  saleor/graphql/core/validators/file.py
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/utils.py
  saleor/thumbnail/views.py
Labels: skip changelog, skip migrations perf test

#15089 Handle invalid image MIME type during thumbnail generation
  saleor/graphql/core/tests/test_file_validation.py
  saleor/graphql/core/validators/file.py
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/utils.py
  saleor/thumbnail/views.py
Labels: 3.16

#15090 Handle invalid image MIME type during thumbnail generation
  saleor/graphql/core/tests/test_file_validation.py
  saleor/graphql/core/validators/file.py
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/utils.py
  saleor/thumbnail/views.py
Labels: 3.15

#15091 Handle invalid image MIME type during thumbnail generation
  saleor/graphql/core/tests/test_file_validation.py
  saleor/graphql/core/validators/file.py
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/utils.py
  saleor/thumbnail/views.py
Labels: 3.14

#15093 Optimise webhooks in promotion toggle task
  saleor/discount/tasks.py
  saleor/plugins/manager.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/webhook/plugin.py
Labels: skip changelog, skip migrations perf test

#15068 add collections handling for product bulk create
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: 3.15

#15069 add collections handling for product bulk create
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: bulk, 3.16

#15072 add collections handling for product bulk create
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: bulk, 3.17

#15017 Use replica in collection_product_updated_task
  saleor/product/tasks.py
Labels: performance, 3.17

#15095 Fix collections saving for ProductBulkCreate
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: skip changelog, 3.14

#15058 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
Labels: test deployment, :robot: bot, skip changelog

#15094 Change limit and add validation for product media alt field
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/graphql/product/mutations/product/product_media_update.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_media_create.py
  saleor/graphql/product/tests/mutations/test_product_media_update.py
  saleor/product/migrations/0186_alter_productmedia_alt.py
  saleor/product/models.py
Labels: 3.14

#15103 Fix order subtotal migration
  saleor/order/migrations/0181_order_subtotal_as_a_field.py
Labels: migrations perf test, skip changelog

#15105 Fix order subtotal migration
  saleor/order/migrations/tasks/saleor3_18.py
Labels: 3.18

#15014 Add separated queues for Order and Checkout events
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_webhook.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/settings.py
  saleor/tests/settings.py
Labels: skip changelog, 3.14

#15106 Update pspReference when recieving different event than success
  saleor/checkout/actions.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.15, transactions

#15107 Update pspReference when recieving different event than success
  saleor/checkout/actions.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: transactions, 3.16

#15108 Update pspReference when recieving different event than success
  saleor/checkout/actions.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: transactions, 3.17

#15109 Update pspReference when recieving different event than success
  saleor/checkout/actions.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: transactions, 3.18

#15110 Update pspReference when recieving different event than success
  saleor/checkout/actions.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: skip changelog, transactions, skip migrations perf test

#15100 Update pspReference when recieving different event than success
  saleor/checkout/actions.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.14, transactions

#15111 Fix failing unit test with incorrect assert
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
Labels: 3.17

#15127 Add replica usage to more DB queries
  saleor/graphql/warehouse/dataloaders.py
  saleor/plugins/manager.py
  saleor/product/models.py
Labels: 3.14

#15128 Add replica usage to more DB queries
  saleor/graphql/warehouse/dataloaders.py
  saleor/plugins/manager.py
  saleor/product/managers.py
Labels: 3.15

#15129 Add replica usage to more DB queries
  saleor/graphql/warehouse/dataloaders.py
  saleor/plugins/manager.py
  saleor/product/managers.py
Labels: 3.16

#15130 Add replica usage to more DB queries
  saleor/graphql/warehouse/dataloaders.py
  saleor/plugins/manager.py
  saleor/product/managers.py
Labels: 3.17

#15131 Add replica usage to more DB queries
  saleor/graphql/warehouse/dataloaders.py
  saleor/plugins/manager.py
  saleor/product/managers.py
Labels: 3.18

#15132 Add replica usage to more DB queries
  saleor/graphql/warehouse/dataloaders.py
  saleor/plugins/manager.py
  saleor/product/managers.py
Labels: skip changelog

#14977 Optimize collections create and delete
  saleor/graphql/product/mutations/collection/collection_create.py
  saleor/graphql/product/mutations/collection/collection_delete.py
  saleor/product/tasks.py
  saleor/settings.py
Labels: performance, 3.14

#14978 Optimize collections create and delete
  saleor/graphql/product/mutations/collection/collection_create.py
  saleor/graphql/product/mutations/collection/collection_delete.py
  saleor/product/tasks.py
  saleor/settings.py
Labels: performance, 3.15

#14979 Optimize collections create and delete
  saleor/graphql/product/mutations/collection/collection_create.py
  saleor/graphql/product/mutations/collection/collection_delete.py
  saleor/product/tasks.py
  saleor/settings.py
Labels: performance, 3.16

#14980 Optimize collections create and delete
  saleor/graphql/product/mutations/collection/collection_create.py
  saleor/graphql/product/mutations/collection/collection_delete.py
  saleor/product/tasks.py
  saleor/settings.py
Labels: performance, 3.18

#14981 Optimize collections create and delete
  saleor/graphql/product/mutations/collection/collection_create.py
  saleor/graphql/product/mutations/collection/collection_delete.py
  saleor/graphql/product/tests/benchmark/test_collection.py
  saleor/product/tasks.py
  saleor/settings.py
Labels: performance, skip changelog, main

#14843 Add an LRU cache for GraphQL document parser and validator
  CHANGELOG.md
  saleor/core/utils/cache.py
  saleor/core/utils/tests/__init__.py
  saleor/core/utils/tests/test_cache.py
  saleor/core/utils/tests/test_editorjs.py
  saleor/core/utils/tests/test_serializer.py
  saleor/core/utils/tests/test_url.py
  saleor/graphql/api.py
  saleor/graphql/core/fields.py
  saleor/graphql/core/scalars.py
  saleor/graphql/core/tests/test_view.py
  saleor/graphql/product/tests/mutations/test_product_create.py
  saleor/graphql/tests/utils.py
  saleor/graphql/views.py
  saleor/urls.py
Labels: performance, graphql

#15126 Fix invoice generation
  saleor/order/models.py
  saleor/plugins/invoicing/tests/test_invoicing.py
Labels: skip changelog

#15116 Fix multiple db queries in dataloaders
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
Labels: skip changelog, skip migrations perf test

#15133 Fix multiple db queries in dataloaders
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
Labels: 3.14

#15134 Fix multiple db queries in dataloaders
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
Labels: 3.15

#15135 Fix multiple db queries in dataloaders
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
Labels: 3.16

#15136 Fix multiple db queries in dataloaders
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
Labels: 3.17

#15137 Fix multiple db queries in dataloaders
  saleor/graphql/plugins/dataloaders.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
Labels: 3.18
