Repository saleor/saleor, pull requests merged in 2024-02, with the labels that each got.

#15325 Call product prices calculation tasks in db transaction
  saleor/graphql/discount/mutations/promotion/promotion_create.py
  saleor/graphql/discount/mutations/promotion/promotion_update.py
  saleor/graphql/discount/mutations/sale/sale_channel_listing_update.py
  saleor/graphql/discount/mutations/sale/sale_create.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/mutations/collection/collection_add_products.py
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/product/tests/test_category.py
  saleor/product/utils/__init__.py
Labels: skip changelog

#15324 Call product prices calculation tasks in on_commit
  saleor/graphql/discount/mutations/promotion/promotion_create.py
  saleor/graphql/discount/mutations/promotion/promotion_update.py
  saleor/graphql/discount/mutations/sale/sale_channel_listing_update.py
  saleor/graphql/discount/mutations/sale/sale_create.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/mutations/collection/collection_add_products.py
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/product/tests/test_category.py
  saleor/product/utils/__init__.py
Labels: 3.18

#15271 Call product prices calculation tasks in on_commit
  saleor/graphql/discount/mutations/promotion/promotion_create.py
  saleor/graphql/discount/mutations/promotion/promotion_update.py
  saleor/graphql/discount/mutations/sale/sale_channel_listing_update.py
  saleor/graphql/discount/mutations/sale/sale_create.py
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/mutations/collection/collection_add_products.py
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/product/tests/test_category.py
  saleor/product/utils/__init__.py
Labels: test deployment

#15338 Move discounted_price_dirty flag to ProductChannelListing
  saleor/discount/utils.py
  saleor/graphql/discount/mutations/promotion/promotion_bulk_delete.py
  saleor/graphql/discount/mutations/promotion/promotion_delete.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_create.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_delete.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_update.py
  saleor/graphql/discount/mutations/sale/sale_delete.py
  saleor/graphql/discount/mutations/sale/sale_update.py
  saleor/graphql/discount/tests/mutations/test_promotion_delete.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_delete.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_update.py
  saleor/graphql/discount/tests/mutations/test_sale_catalogues_add.py
  saleor/graphql/discount/tests/mutations/test_sale_catalogues_remove.py
  saleor/graphql/discount/tests/mutations/test_sale_delete.py
  saleor/graphql/discount/tests/mutations/test_sale_update.py
  saleor/graphql/product/tests/deprecated/test_product_channel_listing_update.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_create.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_delete.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_category.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_product_discounted_price.py
  saleor/graphql/product/tests/test_variant_channel_listing_update.py
  saleor/product/migrations/0191_productchannellisting_discounted_price_dirty.py
  saleor/product/models.py
  saleor/product/tasks.py
  saleor/product/tests/test_category.py
  saleor/product/utils/product.py
Labels: performance, skip changelog, promotions

#15347 Order promotions performance.
  saleor/discount/utils.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
Labels: performance, promotions

#15352 Optimize `fetch_promotion_rules_for_checkout` function.
  saleor/discount/tests/test_utils/test_fetch_promotion_rules_for_checkout.py
  saleor/discount/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/product/utils/variants.py
Labels: performance, promotions

#15335 Clear gift line when not applicable
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_checkout.py
  saleor/discount/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/tests/fixtures.py
Labels: promotions

#15330 Add filter by promotion type
  saleor/graphql/discount/filters.py
  saleor/graphql/discount/tests/queries/test_promotions_filtering.py
  saleor/graphql/schema.graphql
Labels: test deployment, promotions

#15235 lowercase file extension before validation
  saleor/graphql/core/tests/test_file_validation.py
  saleor/graphql/core/validators/file.py
Labels: skip changelog

#15309 Always apply discount from single promotion rule
  CHANGELOG.md
  saleor/discount/tests/test_utils/test_calculate_discounted_price_for_promotions.py
  saleor/discount/tests/test_utils/test_get_variants_to_promotions_map.py
  saleor/discount/utils.py
  saleor/product/tests/test_product_minimal_variant_price.py
  saleor/product/utils/variant_prices.py
Labels: test deployment

#13973 fix: streetAddress1, streetAddress2 field validation #12389
  CHANGELOG.md
  saleor/account/i18n.py
  saleor/account/tests/test_account.py
Labels: python, address

#15360 Fix attributes save performance
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/graphql/attribute/tests/benchmark/test_attribute.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_delete.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_update.py
  saleor/graphql/attribute/tests/mutations/test_bulk_delete.py
  saleor/graphql/attribute/tests/queries/test_attribute_filter.py
  saleor/graphql/attribute/tests/queries/test_attribute_where.py
  saleor/graphql/attribute/tests/queries/test_attributes_sort.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/page/tests/mutations/test_page_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_delete.py
  saleor/graphql/page/tests/mutations/test_page_reorder_attribute_values.py
  saleor/graphql/page/tests/mutations/test_page_type_delete.py
  saleor/graphql/page/tests/mutations/test_page_types_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_update.py
  saleor/graphql/page/tests/queries/test_page.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/mutations/test_product_delete.py
  saleor/graphql/product/tests/mutations/test_product_type_delete.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_products_query_with_filter.py
  saleor/graphql/product/tests/queries/test_products_query_with_where.py
  saleor/graphql/product/tests/queries/test_variant_query.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_product_pagination.py
  saleor/graphql/product/tests/test_product_sorting_attributes.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/product/tests/test_generate_and_set_variant_name.py
  saleor/product/tests/test_product.py
  saleor/tests/fixtures.py
  saleor/webhook/tests/test_webhook_serializers.py
Labels: attributes, test deployment

#15361 Fix attributes save performance
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/graphql/attribute/tests/benchmark/test_attribute.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_delete.py
  saleor/graphql/attribute/tests/mutations/test_attribute_value_update.py
  saleor/graphql/attribute/tests/mutations/test_bulk_delete.py
  saleor/graphql/attribute/tests/queries/test_attribute_filter.py
  saleor/graphql/attribute/tests/queries/test_attribute_where.py
  saleor/graphql/attribute/tests/queries/test_attributes_sort.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/page/tests/mutations/test_page_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_delete.py
  saleor/graphql/page/tests/mutations/test_page_reorder_attribute_values.py
  saleor/graphql/page/tests/mutations/test_page_type_delete.py
  saleor/graphql/page/tests/mutations/test_page_types_bulk_delete.py
  saleor/graphql/page/tests/mutations/test_page_update.py
  saleor/graphql/page/tests/queries/test_page.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/mutations/test_product_delete.py
  saleor/graphql/product/tests/mutations/test_product_type_delete.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_products_query_with_filter.py
  saleor/graphql/product/tests/queries/test_products_query_with_where.py
  saleor/graphql/product/tests/queries/test_variant_query.py
  saleor/graphql/product/tests/test_attributes.py
  saleor/graphql/product/tests/test_bulk_delete.py
  saleor/graphql/product/tests/test_product_pagination.py
  saleor/graphql/product/tests/test_product_sorting_attributes.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/product/tests/test_generate_and_set_variant_name.py
  saleor/product/tests/test_product.py
  saleor/tests/fixtures.py
  saleor/webhook/tests/test_webhook_serializers.py
Labels: attributes, skip changelog

#15351 Add token field as optional argument to transaction mutations and query
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/schema.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_action.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: 3.14

#15362 Add token field as optional argument to transaction mutations and query
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/mutations/transaction/transaction_process.py
  saleor/graphql/payment/mutations/transaction/transaction_request_action.py
  saleor/graphql/payment/mutations/transaction/transaction_request_refund_for_granted_refund.py
  saleor/graphql/payment/mutations/transaction/transaction_update.py
  saleor/graphql/payment/mutations/transaction/utils.py
  saleor/graphql/payment/schema.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_action.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_refund_for_granted_refund.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: 3.15

#15365 Add token field as optional argument to transaction mutations and query
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/mutations/transaction/transaction_process.py
  saleor/graphql/payment/mutations/transaction/transaction_request_action.py
  saleor/graphql/payment/mutations/transaction/transaction_request_refund_for_granted_refund.py
  saleor/graphql/payment/mutations/transaction/transaction_update.py
  saleor/graphql/payment/mutations/transaction/utils.py
  saleor/graphql/payment/schema.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_action.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_refund_for_granted_refund.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: 3.16

#15366 Add token field as optional argument to transaction mutations and query
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/mutations/transaction/transaction_process.py
  saleor/graphql/payment/mutations/transaction/transaction_request_action.py
  saleor/graphql/payment/mutations/transaction/transaction_request_refund_for_granted_refund.py
  saleor/graphql/payment/mutations/transaction/transaction_update.py
  saleor/graphql/payment/mutations/transaction/utils.py
  saleor/graphql/payment/schema.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_action.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_refund_for_granted_refund.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: 3.17

#15367 Add token field as optional argument to transaction mutations and query
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/mutations/transaction/transaction_process.py
  saleor/graphql/payment/mutations/transaction/transaction_request_action.py
  saleor/graphql/payment/mutations/transaction/transaction_request_refund_for_granted_refund.py
  saleor/graphql/payment/mutations/transaction/transaction_update.py
  saleor/graphql/payment/mutations/transaction/utils.py
  saleor/graphql/payment/schema.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_action.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_refund_for_granted_refund.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: 3.18

#15368 Add token field as optional argument to transaction mutations and query
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/mutations/transaction/transaction_process.py
  saleor/graphql/payment/mutations/transaction/transaction_request_action.py
  saleor/graphql/payment/mutations/transaction/transaction_request_refund_for_granted_refund.py
  saleor/graphql/payment/mutations/transaction/transaction_update.py
  saleor/graphql/payment/mutations/transaction/utils.py
  saleor/graphql/payment/schema.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_action.py
  saleor/graphql/payment/tests/mutations/test_transaction_request_refund_for_granted_refund.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: skip changelog, main

#15379 Update populatedb after atribute refactor
  saleor/core/utils/random_data.py
  saleor/static/populatedb_data.json
Labels: attributes, 3.17

#15380 Update populatedb after atribute refactor
  saleor/core/utils/random_data.py
  saleor/static/populatedb_data.json
Labels: attributes, 3.16

#15397 Make task's expiration date (time limit) configurable
  saleor/core/tasks.py
  saleor/settings.py
Labels: 3.18

#15398 Make task's expiration date (time limit) configurable
  saleor/core/tasks.py
  saleor/settings.py
Labels: 3.17

#15399 Make task's expiration date (time limit) configurable
  saleor/core/tasks.py
  saleor/settings.py
Labels: 3.16

#15400 Make task's expiration date (time limit) configurable
  saleor/core/tasks.py
  saleor/settings.py
Labels: 3.15

#15372 Clear db leftovers after attribute refactor
  CHANGELOG.md
  saleor/attribute/migrations/0040_clear_assignedattributes.py
Labels: attributes, test deployment, skip migrations perf test

#15393 Fix gifts validation in promotion mutations
  saleor/graphql/discount/mutations/promotion/validators.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
Labels: skip changelog, promotions, skip migrations perf test

#15392 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  saleor/graphql/discount/utils.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/graphql/utils/__init__.py
  saleor/graphql/utils/sorting.py
Labels: test deployment, :robot: bot, skip changelog

#15373 Fix setting invalid identifier
  saleor/app/management/commands/create_app.py
  saleor/app/migrations/0028_set_identifier.py
  saleor/app/migrations/tasks/saleor3_14.py
  saleor/app/tests/test_app_commands.py
  saleor/graphql/app/mutations/app_create.py
  saleor/graphql/app/tests/mutations/test_app_create.py
Labels: 3.14

#15375 Fix setting invalid identifier
  saleor/app/management/commands/create_app.py
  saleor/app/migrations/0028_set_identifier.py
  saleor/app/migrations/tasks/saleor3_14.py
  saleor/app/tests/test_app_commands.py
  saleor/graphql/app/mutations/app_create.py
  saleor/graphql/app/tests/mutations/test_app_create.py
Labels: 3.16

#15376 Fix setting invalid identifier
  saleor/app/management/commands/create_app.py
  saleor/app/migrations/0028_set_identifier.py
  saleor/app/migrations/tasks/saleor3_14.py
  saleor/app/tests/test_app_commands.py
  saleor/graphql/app/mutations/app_create.py
  saleor/graphql/app/tests/mutations/test_app_create.py
Labels: 3.17

#15401 Remove outdated EventDelivery, EventDeliveryAttempt and EventPayload in batches
  saleor/core/tasks.py
  saleor/settings.py
Labels: 3.14

#15378 Fix setting invalid identifier
  saleor/app/management/commands/create_app.py
  saleor/app/migrations/0028_set_identifier.py
  saleor/app/tests/test_app_commands.py
  saleor/graphql/app/mutations/app_create.py
  saleor/graphql/app/tests/mutations/test_app_create.py
Labels: main, 3.19

#15394 Add discussion template
  .github/DISCUSSION_TEMPLATE/RFC.yml
Labels: skip changelog, skip migrations perf test

#15402 Fix gift reward creation during checkout creation
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create_from_order.py
Labels: skip changelog, promotions, skip migrations perf test

#15292 Block when tax failed
  CHANGELOG.md
  saleor/app/management/commands/create_app.py
  saleor/app/migrations/0029_alter_app_identifier.py
  saleor/app/models.py
  saleor/app/tests/test_utils.py
  saleor/app/utils.py
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0065_checkout_tax_error.py
  saleor/checkout/models.py
  saleor/core/taxes.py
  saleor/core/tests/test_taxes.py
  saleor/graphql/app/mutations/app_create.py
  saleor/graphql/app/tests/mutations/test_app_create.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/payment/mutations/transaction/transaction_process.py
  saleor/graphql/schema.graphql
  saleor/graphql/shop/tests/queries/test_shop.py
  saleor/graphql/shop/types.py
  saleor/graphql/tax/mutations/tax_configuration_update.py
  saleor/graphql/tax/tests/fragments.py
  saleor/graphql/tax/tests/mutations/test_tax_configuration_update.py
  saleor/graphql/tax/tests/queries/test_tax_configuration.py
  saleor/graphql/tax/types.py
  saleor/order/calculations.py
  saleor/order/migrations/0183_order_tax_error.py
  saleor/order/models.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/tests/test_manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_payment_webhook.py
  saleor/plugins/webhook/tests/test_payment_webhook_utils.py
  saleor/plugins/webhook/tests/test_tax_webhook.py
  saleor/tax/migrations/0008_auto_20240122_1353.py
  saleor/tax/models.py
  saleor/tax/tests/test_utils.py
  saleor/tax/utils.py
  saleor/webhook/transport/list_stored_payment_methods.py
Labels: migrations perf test

#15403 Fix query with available variants for gift promotion.
  saleor/discount/utils.py
Labels: bug, skip changelog, promotions, 3.19

#15404 Limit update webhook triggers
  saleor/graphql/context.py
  saleor/graphql/core/context.py
  saleor/graphql/core/tests/test_context.py
  saleor/graphql/page/dataloaders.py
  saleor/graphql/page/tests/queries/test_page.py
  saleor/graphql/page/tests/queries/test_page_type.py
  saleor/graphql/page/types.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/dataloaders/__init__.py
  saleor/graphql/product/dataloaders/attributes.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_type_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/tests/test_context.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/graphql/translations/types.py
  saleor/graphql/webhook/subscription_payload.py
  saleor/graphql/webhook/subscription_types.py
  saleor/graphql/webhook/tests/test_subscription_payload.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/settings.py
  saleor/webhook/transport/asynchronous/tests/__init__.py
  saleor/webhook/transport/asynchronous/tests/test_create_deliveries_for_subscriptions.py
  saleor/webhook/transport/asynchronous/transport.py
Labels: skip changelog

#15423 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
Labels: test deployment, :robot: bot, skip changelog

#15442 Raise an error when product is empty in `ProductVariantCreate` mutation
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_create.py
Labels: skip changelog, skip migrations perf test

#15432 Fix setting `search_document` for new users created via OpenID
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/utils.py
Labels: auth, 3.14

#15436 Add crit header to jwt/jws
  saleor/core/jwt_manager.py
Labels: 3.15

#15438 Add crit header to jwt/jws
  saleor/core/jwt_manager.py
Labels: 3.17

#15437 Add crit header to jwt/jws
  saleor/core/jwt_manager.py
Labels: 3.16

#15439 Add crit header to jwt/jws
  saleor/core/jwt_manager.py
Labels: 3.18

#15440 Add crit header to jwt/jws
  saleor/core/jwt_manager.py
Labels: 3.19

#15441 Add crit header to jwt/jws
  saleor/core/jwt_manager.py
Labels: skip changelog, main

#15445 Raise an error when product is empty in `ProductVariantCreate` mutation
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_create.py
Labels: 3.19

#15448 Raise an error when product is empty in `ProductVariantCreate` mutation
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_create.py
Labels: 3.16

#15449 Raise an error when product is empty in `ProductVariantCreate` mutation
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_create.py
Labels: 3.15

#15451 Fix setting `search_document` for new users created via OpenID
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.15

#15452 Fix setting `search_document` for new users created via OpenID
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.16

#15453 Fix setting `search_document` for new users created via OpenID
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.17

#15454 Fix setting `search_document` for new users created via OpenID
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.18

#15455 Fix setting `search_document` for new users created via OpenID
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.19

#15456 Fix setting `search_document` for new users created via OpenID
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/utils.py
Labels: skip changelog

#15467 Revert "Add crit header to jwt/jws (#15435)"
  saleor/core/jwt_manager.py
Labels: 3.14

#15468 Revert "Add crit header to jwt/jws (#15436)"
  saleor/core/jwt_manager.py
Labels: 3.15

#15469 Revert "Add crit header to jwt/jws (#15437)"
  saleor/core/jwt_manager.py
Labels: 3.16

#15470 Revert "Add crit header to jwt/jws (#15438)"
  saleor/core/jwt_manager.py
Labels: 3.17

#15471 Revert "Add crit header to jwt/jws (#15439)"
  saleor/core/jwt_manager.py
Labels: 3.18

#15472 Revert "Add crit header to jwt/jws (#15440)"
  saleor/core/jwt_manager.py
Labels: 3.19

#15473 Revert "Add crit header to jwt/jws (#15441)"
  saleor/core/jwt_manager.py
Labels: skip changelog

#15480 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
Labels: test deployment, :robot: bot, skip changelog

#15433 Add plugin to tax configuration
  CHANGELOG.md
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_calculations.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/core/taxes.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/schema.graphql
  saleor/graphql/tax/mutations/tax_configuration_update.py
  saleor/graphql/tax/tests/mutations/test_tax_configuration_update.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/plugins/__init__.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/manager.py
Labels: test deployment, skip changelog, 3.19

#15460 Add plugin to tax configuration
  CHANGELOG.md
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_calculations.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/core/taxes.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/schema.graphql
  saleor/graphql/tax/mutations/tax_configuration_update.py
  saleor/graphql/tax/tests/mutations/test_tax_configuration_update.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/plugins/__init__.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/manager.py
Labels: main

#15481 Update `redirectUrl` description in `AccountRegisterInput`
  saleor/graphql/account/mutations/account/account_register.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#15426 Fix `FLAT_RATE` tax calculation for Click and Collect option.
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/mutations/checkout_shipping_address_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/schema.graphql
  saleor/tax/utils.py
Labels: bug, checkout, skip changelog, 3.14, shopping

#15465 Fix error for invalid promotion ID in `promotionRuleCreate`
  saleor/graphql/discount/mutations/promotion/promotion_rule_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
Labels: 3.17

#15484 Fix unhandled error in `AccountRegister`
  saleor/graphql/account/mutations/account/account_register.py
  saleor/graphql/account/tests/mutations/account/test_account_register.py
Labels: 3.18

#15492 Bulk create attribute value
  saleor/attribute/models/base.py
  saleor/attribute/utils.py
  saleor/graphql/attribute/enums.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/product/tests/benchmark/test_product_bulk_create.py
Labels: attributes, 3.18

#15493 Bulk create attribute value
  saleor/attribute/models/base.py
  saleor/attribute/utils.py
  saleor/graphql/attribute/enums.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/product/tests/benchmark/test_product_bulk_create.py
Labels: attributes, 3.19

#15494 Bulk create attribute value
  saleor/attribute/models/base.py
  saleor/attribute/utils.py
  saleor/graphql/attribute/enums.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/product/tests/benchmark/test_product_bulk_create.py
Labels: attributes, skip changelog

#15486 Fix save checkout shipping_address for Click and Collect option.
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: checkout, skip changelog, 3.14, main, shopping

#15487 Fix tax calculation for Click and Collect option.
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/mutations/checkout_shipping_address_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/schema.graphql
Labels: bug, checkout, 3.15, shopping

#15488 Fix tax calculation for Click and Collect option.
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/mutations/checkout_shipping_address_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/schema.graphql
Labels: bug, checkout, 3.16, shopping

#15489 Fix tax calculation for Click and Collect option.
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/mutations/checkout_shipping_address_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/schema.graphql
Labels: bug, checkout, 3.17, shopping

#15490 Fix tax calculation for Click and Collect option.
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/mutations/checkout_shipping_address_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/schema.graphql
Labels: bug, checkout, 3.18, shopping

#15491 Fix tax calculation for Click and Collect option.
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/mutations/checkout_shipping_address_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/schema.graphql
Labels: bug, checkout, 3.19, shopping

#15496 Fix error for invalid promotion ID in `promotionRuleCreate`
  saleor/graphql/discount/mutations/promotion/promotion_rule_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
Labels: 3.18

#15497 Fix error for invalid promotion ID in `promotionRuleCreate`
  saleor/graphql/discount/mutations/promotion/promotion_rule_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
Labels: 3.19

#15498 Fix error for invalid promotion ID in `promotionRuleCreate`
  saleor/graphql/discount/mutations/promotion/promotion_rule_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
Labels: skip changelog

#15500 Fix unhandled error in `AccountRegister`
  saleor/graphql/account/mutations/account/account_register.py
  saleor/graphql/account/tests/mutations/account/test_account_register.py
Labels: 3.19

#15502 Fix unhandled error in `AccountRegister`
  saleor/graphql/account/mutations/account/account_register.py
  saleor/graphql/account/tests/mutations/account/test_account_register.py
Labels: 3.17

#15503 Fix unhandled error in `AccountRegister`
  saleor/graphql/account/mutations/account/account_register.py
  saleor/graphql/account/tests/mutations/account/test_account_register.py
Labels: 3.16

#15504 Fix unhandled error in `AccountRegister`
  saleor/graphql/account/mutations/account/account_register.py
  saleor/graphql/account/tests/mutations/account/test_account_register.py
Labels: 3.15
