Repository saleor/saleor, pull requests merged in 2024-12, with the labels that each got.

#17109 Add tests fot completing checkout with voucher that 0 the total price
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/tests/test_order_from_checkout.py
Labels: skip changelog, main

#17113 Handle case when task is None in Celery Task formatter
  saleor/core/logging.py
Labels: 3.17

#17112 Handle case when task is None in Celery Task formatter
  saleor/core/logging.py
Labels: 3.18

#17111 Handle case when task is None in Celery Task formatter
  saleor/core/logging.py
Labels: 3.19

#17121 Release 3.20.57
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17048 Update unit discount fields description
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#17108 Handle case when task is None in Celery Task formatter
  saleor/core/logging.py
Labels: skip changelog, main

#17123 Unify the lock logic for allocations and stocks
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/warehouse/management.py
  saleor/warehouse/reservations.py
  saleor/warehouse/tasks.py
  saleor/warehouse/tests/test_tasks.py
Labels: 3.20

#17132 deps: upgrade requests-hardened to latest version
  poetry.lock
  pyproject.toml
  saleor/core/tests/cassettes/test_http_client/test_http_client_disallows_private_ip_ranges[http].yaml
  saleor/core/tests/cassettes/test_http_client/test_http_client_disallows_private_ip_ranges[https].yaml
  saleor/core/tests/test_http_client.py
Labels: dependencies, skip changelog, observability

#16992 Fix gross prices as default values when prices entered with taxes
  CHANGELOG.md
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/fixtures/order.py
  saleor/order/tests/test_calculations.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/tax/calculations/order.py
  saleor/tax/tests/test_order_calculations.py
Labels: pricing

#17133 Fix for fetching all translations when using translate bulk mutation
  saleor/graphql/translations/mutations/utils.py
  saleor/graphql/translations/tests/mutations/test_attribute_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_attribute_value_bulk_transalte.py
  saleor/graphql/translations/tests/mutations/test_product_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_product_variant_bulk_translate.py
  saleor/tests/fixtures.py
Labels: 3.19

#17131 Fix for fetching all translations when using translate bulk mutation
  saleor/graphql/translations/mutations/utils.py
  saleor/graphql/translations/tests/mutations/test_attribute_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_attribute_value_bulk_transalte.py
  saleor/graphql/translations/tests/mutations/test_product_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_product_variant_bulk_translate.py
  saleor/tests/fixtures.py
Labels: 3.20

#17105 Fix for fetching all translations when using translate bulk mutation
  saleor/attribute/tests/fixtures/attribute.py
  saleor/graphql/translations/mutations/utils.py
  saleor/graphql/translations/tests/mutations/test_attribute_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_attribute_value_bulk_transalte.py
  saleor/graphql/translations/tests/mutations/test_product_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_product_variant_bulk_translate.py
Labels: skip changelog

#17127 Update unit discount fields description
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
Labels: 3.20, check patches

#17137 Fix gross prices as default values when prices entered with taxes
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/fixtures/order.py
  saleor/order/tests/test_calculations.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/tax/calculations/order.py
  saleor/tax/tests/test_order_calculations.py
  saleor/tests/fixtures.py
Labels: taxes, 3.19, check patches

#17138 Fix gross prices as default values when prices entered with taxes
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/fixtures/order.py
  saleor/order/tests/test_calculations.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/tax/calculations/order.py
  saleor/tax/tests/test_order_calculations.py
  saleor/tests/fixtures.py
Labels: taxes, 3.20, check patches

#17140 Release 3.20.59
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17139 Fix failing fetching checkout when checkout line is deleted in meantime
  saleor/graphql/checkout/dataloaders/promotion_rule_infos.py
  saleor/graphql/checkout/tests/test_checkout.py
Labels: skip changelog, main

#17143 Catch and handle Integrity and Database error in automatic checkout completion
  saleor/checkout/tasks.py
  saleor/checkout/tests/test_tasks.py
Labels: 3.20

#17147 Release 3.20.60
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17149 deps: upgrade requests-hardened to latest version
  poetry.lock
  pyproject.toml
  saleor/core/tests/cassettes/test_http_client/test_http_client_disallows_private_ip_ranges[http].yaml
  saleor/core/tests/cassettes/test_http_client/test_http_client_disallows_private_ip_ranges[https].yaml
  saleor/core/tests/test_http_client.py
Labels: dependencies, skip changelog

#17146 Catch and handle Integrity and Database error in automatic checkout completion
  saleor/checkout/tasks.py
  saleor/checkout/tests/test_tasks.py
Labels: skip changelog, main

#16586 Generate sync webhook payloads in the dataloaders for filtering checkout shipping methods.
  saleor/app/tests/fixtures/webhooks/shipping_app.py
  saleor/checkout/fetch.py
  saleor/graphql/app/dataloaders/__init__.py
  saleor/graphql/app/dataloaders/app.py
  saleor/graphql/app/dataloaders/apps.py
  saleor/graphql/checkout/dataloaders/checkout_infos.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
  saleor/graphql/webhook/dataloaders/__init__.py
  saleor/graphql/webhook/dataloaders/models.py
  saleor/graphql/webhook/dataloaders/pregenerated_payload_for_checkout_tax.py
  saleor/graphql/webhook/dataloaders/pregenerated_payloads_for_checkout_filter_shipping_methods.py
  saleor/graphql/webhook/dataloaders/request_context.py
  saleor/graphql/webhook/tests/pregenerated_subscription/test_checkout_resolvers.py
  saleor/graphql/webhook/tests/pregenerated_subscription/test_exclude_shipping_methods_pregenerated_payloads.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/webhook/transport/shipping.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/utils.py
Labels: skip changelog

#17150 fix: allow running git-diff on poetry.lock
  .gitattributes
Labels: bug, skip changelog

#17152 Prevent creation of fulfillment in case of race thread
  saleor/graphql/order/mutations/order_fulfill.py
  saleor/graphql/order/tests/mutations/test_order_fulfill.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_delete.py
  saleor/order/actions.py
  saleor/order/tests/test_fulfillments_actions.py
  saleor/order/utils.py
Labels: 3.20

#17155 Release 3.20.61
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17156 Prevent creation of fulfillment in case of race thread
  saleor/graphql/order/mutations/order_fulfill.py
  saleor/graphql/order/tests/mutations/test_order_fulfill.py
  saleor/graphql/product/bulk_mutations/product_variant_bulk_delete.py
  saleor/order/actions.py
  saleor/order/tests/test_fulfillments_actions.py
  saleor/order/utils.py
Labels: skip changelog, main, 3.21

#17141 Add timeout to pubsub interface used by webhook events
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/settings.py
  saleor/webhook/transport/utils.py
Labels: 3.20

#17158 Release 3.20.62
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17159 Fix circular imports
  saleor/core/payments.py
  saleor/discount/utils/promotion.py
  saleor/graphql/webhook/mutations/webhook_trigger.py
  saleor/plugins/webhook/plugin.py
  saleor/webhook/observability/obfuscation.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_tasks.py
  saleor/webhook/transport/asynchronous/tests/test_deferred_payload.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: skip changelog

#17162 Release 3.20.63
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17165 Add workflow to check licenses
  .github/workflows/check-licenses.yaml
Labels: skip changelog

#17163 Log when async event is sent from transaction
  saleor/webhook/transport/asynchronous/transport.py
Labels: skip changelog

#17164 code-owners: remove infra guild
  .github/CODEOWNERS
Labels: skip changelog

#17173 Add pre-generated payload for PAYMENT_GATEWAY_INITIALIZE_SESSION
  saleor/app/tests/fixtures/webhooks/payment_app.py
  saleor/app/tests/fixtures/webhooks/tax_app.py
  saleor/checkout/tests/test_calculations.py
  saleor/graphql/payment/tests/mutations/test_payment_gateway_initialize.py
  saleor/plugins/webhook/plugin.py
Labels: skip changelog

#17177 Add pre-generated payload for transaction sync webhooks
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/plugins/webhook/plugin.py
  saleor/tests/fixtures.py
Labels: check patches

#17180 Release 3.20.65
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17181 Add pre-generated payload for transaction sync webhooks (#17177)
  saleor/app/tests/fixtures/webhooks/payment_app.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/plugins/webhook/plugin.py
Labels: skip changelog

#17175 deps: upgrade requests-hardened to v1.0.0
  poetry.lock
  pyproject.toml
Labels: dependencies, skip changelog

#17192 Simplify attribute lookup queries
  saleor/graphql/attribute/mutations/attribute_bulk_update.py
Labels: skip changelog

#17189 Fix product sorting over collection order
  CHANGELOG.md
  saleor/graphql/product/sorters.py
  saleor/graphql/product/tests/test_product_sorting.py
Labels: test deployment
