Repository saleor/saleor, pull requests merged in 2024-01, with the labels that each got.

#15142 Do not choose id for fake users at random
  saleor/core/utils/anonymization.py
  saleor/core/utils/random_data.py
Labels: skip changelog

#15148 Add stockBulkUpdate performance fix
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
Labels: performance, skip changelog, bulk, 3.14

#15141 Unify timeouts for webhooks
  saleor/plugins/webhook/const.py
  saleor/plugins/webhook/shipping.py
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/settings.py
Labels: 3.14

#15149 Add stockBulkUpdate performance fix
  saleor/graphql/schema.graphql
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/tests/fixtures.py
Labels: performance, skip changelog, bulk, 3.15

#15152 Add stockBulkUpdate performance fix
  saleor/graphql/schema.graphql
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/tests/fixtures.py
Labels: performance, skip changelog, bulk, 3.16

#15151 Add stockBulkUpdate performance fix
  saleor/graphql/schema.graphql
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/tests/fixtures.py
Labels: performance, skip changelog, bulk, 3.17

#15153 Add stockBulkUpdate performance fix
  saleor/graphql/schema.graphql
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/tests/fixtures.py
Labels: performance, skip changelog, bulk, 3.18

#15101 Add collections handling for product bulk create
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: bulk, 3.15

#15102 Add collections handling for product bulk create
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: bulk, 3.16

#15077 add collections handling for product bulk create
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: bulk, 3.18

#15081 add collections handling for product bulk create
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
Labels: skip changelog, bulk

#15112 Change limit and add validation for product media alt field
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/graphql/product/mutations/product/product_media_update.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_media_create.py
  saleor/graphql/product/tests/mutations/test_product_media_update.py
  saleor/graphql/product/utils.py
  saleor/product/migrations/0186_alter_productmedia_alt.py
  saleor/product/migrations/0187_merge_20231221_1030.py
  saleor/product/models.py
Labels: 3.15

#15113 Change limit and add validation for product media alt field
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/graphql/product/mutations/product/product_media_update.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_media_create.py
  saleor/graphql/product/tests/mutations/test_product_media_update.py
  saleor/graphql/product/utils.py
  saleor/product/migrations/0186_alter_productmedia_alt.py
  saleor/product/migrations/0188_merge_20231221_1119.py
  saleor/product/models.py
Labels: 3.16

#15114 Change limit and add validation for product media alt field
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/graphql/product/mutations/product/product_media_update.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_media_create.py
  saleor/graphql/product/tests/mutations/test_product_media_update.py
  saleor/graphql/product/utils.py
  saleor/product/migrations/0186_alter_productmedia_alt.py
  saleor/product/migrations/0190_merge_20231221_1250.py
  saleor/product/models.py
Labels: 3.17

#15143 Change limit and add validation for product media alt field
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/graphql/product/mutations/product/product_media_update.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_media_create.py
  saleor/graphql/product/tests/mutations/test_product_media_update.py
  saleor/graphql/product/utils.py
  saleor/product/migrations/0186_alter_productmedia_alt.py
  saleor/product/migrations/0190_merge_20231221_1337.py
  saleor/product/models.py
Labels: 3.18

#15115 Change limit and add validation for product media alt field
  saleor/graphql/product/bulk_mutations/product_bulk_create.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/graphql/product/mutations/product/product_media_update.py
  saleor/graphql/product/tests/mutations/test_product_bulk_create.py
  saleor/graphql/product/tests/mutations/test_product_media_create.py
  saleor/graphql/product/tests/mutations/test_product_media_update.py
  saleor/graphql/product/utils.py
  saleor/product/migrations/0186_alter_productmedia_alt.py
  saleor/product/migrations/0190_merge_20231221_1356.py
  saleor/product/models.py
Labels: skip changelog

#15157 Unify the timouts for webhooks (#15141)
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/settings.py
Labels: 3.17

#15156 Unify the timeouts for webhooks (#15141)
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/settings.py
Labels: 3.16

#15155 Unify the timeouts for webhooks (#15141)
  saleor/plugins/webhook/const.py
  saleor/plugins/webhook/shipping.py
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/settings.py
Labels: 3.15

#15158 Unify the timeouts for webhooks (#15141)
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/settings.py
Labels: 3.18

#15150 Fix return value type in `send_webhook_using_aws_sqs`
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: skip changelog

#15159 Unify the timeouts for webhooks (#15141)
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/settings.py
Labels: skip changelog, main

#14820 [Test] Use external shipping methods in the checkout
  saleor/tests/e2e/apps/__init__.py
  saleor/tests/e2e/apps/utils/__init__.py
  saleor/tests/e2e/apps/utils/app_create.py
  saleor/tests/e2e/checkout/shipping/__init__.py
  saleor/tests/e2e/checkout/shipping/cassettes/test_use_external_shipping_methods_in_checkout/test_use_external_shipping_methods_in_checkout_core_1652.yaml
  saleor/tests/e2e/checkout/shipping/test_use_external_shipping_methods_in_checkout.py
  saleor/tests/e2e/checkout/utils/checkout_complete.py
  saleor/tests/e2e/checkout/utils/checkout_create.py
  saleor/tests/e2e/test_utils.py
  saleor/tests/e2e/utils.py
  saleor/tests/e2e/webhooks/__init__.py
  saleor/tests/e2e/webhooks/utils.py
Labels: skip changelog

#15161 [TEST] Tests for voucher usage in draft orders TC_0913 & TC_0922
  saleor/tests/e2e/checkout/discounts/vouchers/test_checkout_voucher_is_still_active_when_checkout_fails.py
  saleor/tests/e2e/checkout/discounts/vouchers/test_checkout_voucher_is_still_active_when_payment_fails.py
  saleor/tests/e2e/orders/discounts/test_order_voucher_is_released_when_draft_order_is_deleted.py
  saleor/tests/e2e/orders/discounts/test_order_voucher_usage_includes_draft_orders.py
  saleor/tests/e2e/orders/utils/draft_order_complete.py
  saleor/tests/e2e/orders/utils/draft_order_create.py
  saleor/tests/e2e/orders/utils/draft_order_update.py
  saleor/tests/e2e/vouchers/utils/query_voucher.py
Labels: voucher, skip changelog

#15165 Fix return value type in `send_webhook_using_aws_sqs`
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
Labels: 3.16

#15164 Fix return value type in `send_webhook_using_aws_sqs`
  saleor/webhook/transport/tests/__init__.py
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: 3.17

#15163 Fix return value type in `send_webhook_using_aws_sqs`
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: 3.18

#15171 Adjust batch size of removed apps in task
  saleor/app/tasks.py
Labels: 3.18

#15170 Adjust batch size of removed apps in task
  saleor/app/tasks.py
Labels: 3.17

#15169 Adjust batch size of removed apps in task
  saleor/app/tasks.py
Labels: 3.16

#15167 Adjust batch size of removed apps in task
  saleor/app/tasks.py
Labels: 3.15

#15166 Adjust batch size of removed apps in task
  saleor/app/tasks.py
Labels: 3.14

#15172 Adjust batch size of removed apps in task
  saleor/app/tasks.py
Labels: skip changelog, main

#15054 Allow defining `checkoutAndOrderPredicate` in promotion mutations
  saleor/discount/__init__.py
  saleor/discount/error_codes.py
  saleor/discount/migrations/0074_promotionrule_checkout_and_order_predicate.py
  saleor/discount/models.py
  saleor/graphql/discount/enums.py
  saleor/graphql/discount/inputs.py
  saleor/graphql/discount/mutations/promotion/promotion_create.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_create.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_update.py
  saleor/graphql/discount/mutations/promotion/validators.py
  saleor/graphql/discount/tests/mutations/test_promotion_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_update.py
  saleor/graphql/discount/tests/queries/test_promotion.py
  saleor/graphql/discount/tests/test_validators.py
  saleor/graphql/discount/types/promotions.py
  saleor/graphql/discount/utils.py
  saleor/graphql/schema.graphql
  saleor/product/tests/test_fetch_variants_for_promotion_rules.py
  saleor/tests/fixtures.py
Labels: promotions

#15193 Fix INSUFFICIENT_STOCK error not returning order lines ids
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/utils.py
  saleor/warehouse/availability.py
Labels: bug, skip changelog, 3.15

#15197 Fix INSUFFICIENT_STOCK error not returning order lines ids
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/utils.py
  saleor/warehouse/availability.py
Labels: bug, skip changelog, 3.16

#15196 Fix INSUFFICIENT_STOCK error not returning order lines ids
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/utils.py
  saleor/warehouse/availability.py
Labels: bug, skip changelog, 3.17

#15194 Fix INSUFFICIENT_STOCK error not returning order lines ids
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/utils.py
  saleor/warehouse/availability.py
Labels: bug, skip changelog, main

#15195 Fix INSUFFICIENT_STOCK error not returning order lines ids
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/utils.py
  saleor/warehouse/availability.py
Labels: bug, skip changelog, 3.18

#15175 Recalculate variant prices only when PromotionRule has reward_value set
  saleor/product/tasks.py
  saleor/product/tests/test_tasks.py
Labels: test deployment, skip changelog, promotions, 3.17

#15198 [TEST] Calculate simple taxes for checkout with click and collect CORE_2012
  saleor/tests/e2e/checkout/taxes/test_checkout_with_click_and_collect_calculate_simple_taxes_based_on_shipping_address.py
Labels: taxes, skip changelog

#15202 Recalculate variant prices only when PromotionRule has reward_value set
  saleor/product/tasks.py
  saleor/product/tests/test_tasks.py
Labels: skip changelog, 3.18

#15203 Recalculate variant prices only when PromotionRule has reward_value set
  saleor/product/tasks.py
  saleor/product/tests/test_tasks.py
Labels: skip changelog, main

#14652 Add voucherCodeCreated and voucherCodeDeleted webhooks
  CHANGELOG.md
  saleor/graphql/discount/mutations/voucher/voucher_code_bulk_delete.py
  saleor/graphql/discount/mutations/voucher/voucher_create.py
  saleor/graphql/discount/mutations/voucher/voucher_delete.py
  saleor/graphql/discount/mutations/voucher/voucher_update.py
  saleor/graphql/discount/tests/deprecated/test_voucher_create.py
  saleor/graphql/discount/tests/deprecated/test_voucher_update.py
  saleor/graphql/discount/tests/mutations/test_voucher_code_bulk_delete.py
  saleor/graphql/discount/tests/mutations/test_voucher_create.py
  saleor/graphql/discount/tests/mutations/test_voucher_delete.py
  saleor/graphql/discount/tests/mutations/test_voucher_update.py
  saleor/graphql/schema.graphql
  saleor/graphql/tests/queries/fragments.py
  saleor/graphql/webhook/mutations/webhook_dry_run.py
  saleor/graphql/webhook/mutations/webhook_trigger.py
  saleor/graphql/webhook/subscription_types.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/payloads.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_subscription.py
  saleor/tests/fixtures.py
  saleor/webhook/event_types.py
Labels: test deployment, voucher, 3.19

#15210 [TEST] Unable to create promotion rule with mixed predicates CORE_2125
  saleor/tests/e2e/promotions/test_promotions_query_with_different_parameters.py
  saleor/tests/e2e/promotions/test_unable_to_have_promotion_rule_with_mixed_predicates.py
  saleor/tests/e2e/promotions/utils/__init__.py
  saleor/tests/e2e/promotions/utils/promotion_create.py
  saleor/tests/e2e/promotions/utils/promotion_rule_update.py
Labels: skip changelog, promotions

#15176 Improve creation of PromotionRule-ProductVariant relation
  saleor/discount/tests/test_utils/test_update_rule_variant_relation.py
  saleor/discount/utils.py
  saleor/graphql/discount/mutations/utils.py
  saleor/graphql/discount/utils.py
  saleor/product/tests/test_fetch_variants_for_promotion_rules.py
  saleor/product/utils/variants.py
Labels: test deployment, skip changelog, promotions

#15189 Adjust voucher assignement
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/discount/utils.py
  saleor/graphql/checkout/mutations/checkout_remove_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
Labels: promotions

#15207 Rename checkoutAndOrder discount to order discount
  saleor/checkout/base_calculations.py
  saleor/checkout/tests/test_base_calculations.py
  saleor/checkout/tests/test_calculations.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/discount/__init__.py
  saleor/discount/migrations/0074_promotionrule_order_predicate.py
  saleor/discount/migrations/0075_checkout_discount.py
  saleor/discount/migrations/0076_update_base_discount_type.py
  saleor/discount/models.py
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_checkout.py
  saleor/discount/tests/test_utils/test_fetch_promotion_rules_for_checkout.py
  saleor/discount/utils.py
  saleor/graphql/channel/tests/mutations/test_channel_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/discount/inputs.py
  saleor/graphql/discount/mutations/promotion/promotion_create.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_update.py
  saleor/graphql/discount/mutations/promotion/validators.py
  saleor/graphql/discount/tests/mutations/test_promotion_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_update.py
  saleor/graphql/discount/tests/test_validators.py
  saleor/graphql/discount/types/promotions.py
  saleor/graphql/discount/utils.py
  saleor/graphql/schema.graphql
  saleor/payment/tests/test_utils.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_line_total_with_order_promotion[20.33-25.00-True].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_line_total_with_order_promotion[25.00-30.75-False].yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_line_unit_price_order_promotion_charge_taxes.yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_checkout_total_with_order_promotion.yaml
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/tax/tests/test_checkout_calculations.py
  saleor/tests/e2e/promotions/test_unable_to_have_promotion_rule_with_mixed_predicates.py
  saleor/tests/e2e/promotions/utils/promotion_create.py
  saleor/tests/fixtures.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
  saleor/webhook/tests/test_webhook_serializers.py
Labels: promotions

#15219 Improve creation of `PromotionRule`-`ProductVariant` relation.
  saleor/discount/tests/test_utils/test_update_rule_variant_relation.py
  saleor/discount/utils.py
  saleor/graphql/discount/mutations/utils.py
  saleor/graphql/discount/utils.py
  saleor/product/tests/test_fetch_variants_for_promotion_rules.py
  saleor/product/utils/variants.py
Labels: promotions, 3.18

#15218 Improve creation of `PromotionRule`-`ProductVariant` relation.
  saleor/discount/tests/test_utils/test_update_rule_variant_relation.py
  saleor/discount/utils.py
  saleor/graphql/discount/mutations/utils.py
  saleor/graphql/discount/utils.py
  saleor/product/tests/test_fetch_variants_for_promotion_rules.py
  saleor/product/utils/variants.py
Labels: promotions, 3.17

#15228 Remove demo from README
  README.md
Labels: skip changelog

#15220 Fix `promotionCreate` mutation to allow creating rules with no channels specified.
  saleor/graphql/discount/mutations/promotion/promotion_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_create.py
Labels: bug, test deployment, skip changelog, promotions

#15200 Add rules limit for checkout and order promotions.
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/discount/error_codes.py
  saleor/graphql/discount/mutations/promotion/promotion_create.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_create.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_update.py
  saleor/graphql/discount/mutations/promotion/validators.py
  saleor/graphql/discount/tests/mutations/test_promotion_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
  saleor/graphql/discount/tests/test_validators.py
  saleor/graphql/discount/utils.py
  saleor/graphql/schema.graphql
  saleor/settings.py
  saleor/tests/e2e/promotions/test_unable_to_have_promotion_rule_with_mixed_predicates.py
Labels: promotions, 3.19

#15232 Add order promotions when populating database with dummy data.
  saleor/core/management/commands/populatedb.py
  saleor/core/tests/test_core.py
  saleor/core/utils/random_data.py
Labels: promotions, 3.19

#15222 [TEST] Promotion applied on checkout with specified total/subtotal CORE_2132_2133_2134
  saleor/tests/e2e/checkout/discounts/promotions/test_checkout_products_on_fixed_promotion.py
  saleor/tests/e2e/checkout/discounts/promotions/test_checkout_products_on_percentage_promotion.py
  saleor/tests/e2e/checkout/discounts/promotions/test_checkout_with_fixed_promotion_should_not_result_in_negative_price.py
  saleor/tests/e2e/checkout/discounts/promotions/test_promotion_applied_on_checkout_with_specific_subtotal.py
  saleor/tests/e2e/checkout/discounts/promotions/test_promotion_discount_applied_on_checkout_with_specific_total_and_subtotal.py
  saleor/tests/e2e/checkout/discounts/test_checkout_with_promotion_and_voucher.py
  saleor/tests/e2e/checkout/utils/checkout_complete.py
  saleor/tests/e2e/checkout/utils/checkout_create.py
  saleor/tests/e2e/checkout/utils/checkout_lines_update.py
  saleor/tests/e2e/checkout/utils/query_checkout.py
  saleor/tests/e2e/orders/discounts/test_apply_better_promotion_to_product.py
  saleor/tests/e2e/orders/discounts/test_order_product_with_percentage_promotion.py
  saleor/tests/e2e/orders/discounts/test_order_products_from_the_same_category_on_fixed_promotion.py
  saleor/tests/e2e/orders/discounts/test_order_products_on_fixed_promotion.py
  saleor/tests/e2e/orders/discounts/test_order_products_on_promotion_and_manual_order_discount.py
  saleor/tests/e2e/orders/discounts/test_order_promotion_not_applied_when_not_within_time_range.py
  saleor/tests/e2e/orders/discounts/test_order_promotion_still_applied_to_the_order_when_promotion_is_removed.py
  saleor/tests/e2e/product/test_product_no_longer_on_promotion_when_promotion_is_removed.py
  saleor/tests/e2e/promotions/test_staff_can_change_catalog_predicate.py
  saleor/tests/e2e/promotions/test_staff_can_change_channel_in_promotion_rule.py
  saleor/tests/e2e/promotions/test_staff_can_change_reward_value_type_in_promotion_rule.py
  saleor/tests/e2e/promotions/test_staff_can_create_promotion_for_collections.py
  saleor/tests/e2e/promotions/test_staff_can_translate_promotions.py
  saleor/tests/e2e/promotions/utils/promotion_rule_create.py
  saleor/tests/e2e/promotions/utils/promotion_rule_update.py
Labels: skip changelog, promotions

#15229 Get rid of total discount
  saleor/checkout/tests/test_checkout.py
  saleor/discount/__init__.py
  saleor/discount/migrations/0074_promotionrule_order_predicate.py
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_checkout.py
  saleor/discount/utils.py
  saleor/graphql/schema.graphql
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/tests/fixtures.py
Labels: promotions

#15252 Collapse migrations introduced for order predicate
  saleor/discount/migrations/0074_auto_20240119_1029.py
  saleor/discount/migrations/0074_promotionrule_order_predicate.py
  saleor/discount/migrations/0076_update_base_discount_type.py
  saleor/discount/migrations/0077_alter_checkoutdiscount_unique_together.py
  saleor/discount/migrations/0078_promotionrule_predicate_type.py
Labels: promotions

#15251 Do not re-calculate the promotions when catalogue predicate is empty
  saleor/product/tasks.py
  saleor/product/tests/test_tasks.py
Labels: promotions

#15249 Fix `promotionCreate` mutation to allow creating rules with no channels specified.
  saleor/graphql/discount/mutations/promotion/promotion_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_create.py
Labels: promotions, 3.17

#15250 Fix `promotionCreate` mutation to allow creating rules with no channels specified.
  saleor/graphql/discount/mutations/promotion/promotion_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_create.py
Labels: promotions, 3.18

#15248 Fix `OrderDiscount.type` when converting checkout to order.
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
Labels: promotions

#15266 Fix missing Poetry cache in pytest workflow
  .github/workflows/pytest.yml
Labels: bug, skip changelog

#15261 [TEST] Promotion applied on checkout with specified lte/gte subtotal in order predicate
  saleor/tests/e2e/checkout/discounts/promotions/test_promotion_applied_on_checkout_with_subtotal_within_specified_range.py
Labels: skip changelog

#15260 Simplify `save_m2m` function in `promotionCreate` mutation.
  saleor/graphql/discount/mutations/promotion/promotion_create.py
Labels: skip changelog, promotions

#15276 Fix creating promotion rule without catalogue predicate
  saleor/graphql/discount/mutations/promotion/validators.py
  saleor/graphql/discount/tests/mutations/test_promotion_create.py
Labels: bug, skip changelog, promotions, 3.17

#15279 Checkout and order promotions adjustments
  saleor/checkout/utils.py
  saleor/graphql/discount/types/promotions.py
  saleor/graphql/schema.graphql
Labels: promotions

#15286 Fix creating promotion rule without catalogue predicate
  saleor/graphql/discount/mutations/promotion/validators.py
  saleor/graphql/discount/tests/mutations/test_promotion_create.py
Labels: bug, skip changelog, promotions, 3.18

#15287 Fix creating promotion rule without catalogue predicate
  saleor/graphql/discount/mutations/promotion/validators.py
  saleor/graphql/discount/tests/mutations/test_promotion_create.py
Labels: bug, skip changelog, promotions, main

#15275 Fix failing rounding on Weight
  saleor/graphql/core/types/common.py
  saleor/graphql/product/tests/queries/test_product_type_query.py
  saleor/graphql/schema.graphql
Labels: test deployment, skip changelog

#15288 Fix failing rounding on Weight
  saleor/graphql/core/types/common.py
  saleor/graphql/product/tests/queries/test_product_type_query.py
  saleor/graphql/schema.graphql
Labels: 3.18

#15262 Adding gh workflow for e2e tests
  .github/workflows/e2e.yml
Labels: skip changelog

#15289 Fix creating promotion rule with metadata
  saleor/graphql/core/filters.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
Labels: bug, skip changelog, promotions, main

#15277 GHA: publish container images using GITHUB_TOKEN
  .github/workflows/publish-containers.yml
Labels: skip changelog, ci

#15308 async webhooks: add extra data in failure logs
  saleor/webhook/transport/utils.py
Labels: skip changelog, observability

#15293 GHA: publish container images using GITHUB_TOKEN
  .github/workflows/publish-containers.yml
Labels: 3.18

#15294 GHA: publish container images using GITHUB_TOKEN
  .github/workflows/publish-containers.yml
Labels: 3.17

#15295 GHA: publish container images using GITHUB_TOKEN
  .github/workflows/publish-containers.yml
Labels: 3.16

#15296 GHA: publish container images using GITHUB_TOKEN
  .github/workflows/publish-containers.yml
Labels: 3.15

#15297 GHA: publish container images using GITHUB_TOKEN
  .github/workflows/publish-containers.yml
Labels: 3.14

#15298 GHA: publish container images using GITHUB_TOKEN
  .github/workflows/publish-containers.yml
Labels: 3.13

#15299 GHA: publish container images using GITHUB_TOKEN
  .github/workflows/publish-containers.yml
Labels: 3.12

#15300 deps: update pillow, cryptography, jinja2 to latest
  poetry.lock
  pyproject.toml
Labels: dependencies, 3.18

#15301 deps: update pillow, cryptography, jinja2 to latest
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.17

#15302 deps: update pillow, cryptography, jinja2 to latest
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.16

#15303 deps: update pillow, cryptography, jinja2 to latest
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.15

#15304 deps: update pillow, cryptography, jinja2 to latest
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.14

#15306 deps: update pillow, cryptography, jinja2 to latest
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.12

#15307 deps: update pillow, cryptography, jinja2 to latest
  poetry.lock
  pyproject.toml
Labels: dependencies, main

#15317 Removing duplicate of e2e tests from pytest workflow in favour of e2e workflow
  .github/workflows/pytest.yml
Labels: skip changelog

#15311 async webhooks: add extra data in failure logs
  saleor/webhook/transport/utils.py
Labels: 3.18, observability

#15312 async webhooks: add extra data in failure logs
  saleor/webhook/transport/utils.py
Labels: 3.17, observability

#15314 async webhooks: add extra data in failure logs
  saleor/plugins/webhook/tasks.py
Labels: 3.16, observability

#15315 async webhooks: add extra data in failure logs
  saleor/plugins/webhook/tasks.py
Labels: 3.15, observability

#15316 async webhooks: add extra data in failure logs
  saleor/plugins/webhook/tasks.py
Labels: 3.14, observability

#15320 security policy: remove v3.13, and v3.12 from supported versions
  SECURITY.md
Labels: skip changelog, docs

#15274 Gift promotions API.
  saleor/discount/error_codes.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
  saleor/graphql/discount/dataloaders.py
  saleor/graphql/discount/inputs.py
  saleor/graphql/discount/mutations/promotion/promotion_create.py
  saleor/graphql/discount/mutations/promotion/validators.py
  saleor/graphql/discount/tests/mutations/test_promotion_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_create.py
  saleor/graphql/discount/tests/mutations/test_promotion_rule_update.py
  saleor/graphql/discount/tests/queries/test_promotion.py
  saleor/graphql/discount/types/promotions.py
  saleor/graphql/order/tests/queries/test_order_line.py
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
Labels: promotions, 3.19

#15268 Provide default Sale.type when missing in PromotionRule
  saleor/graphql/discount/tests/queries/test_sale.py
  saleor/graphql/discount/types/sales.py
Labels: test deployment

#15290 Provide default Sale.type when missing in PromotionRule
  saleor/graphql/discount/tests/queries/test_sale.py
  saleor/graphql/discount/types/sales.py
Labels: 3.18

#15321 Workflow fixes for PR actions
  .github/workflows/e2e.yml
Labels: skip changelog

#15291 Provide default Sale.type when missing in PromotionRule
  saleor/graphql/discount/tests/queries/test_sale.py
  saleor/graphql/discount/types/sales.py
Labels: skip changelog

#15329 Removing doubled pytest command from the run
  .github/workflows/e2e.yml
Labels: skip changelog

#15269 Fix saving attribute values in order
  saleor/attribute/models/base.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
Labels: test deployment, 3.14

#15332 Fix filtering by order predicate
  saleor/checkout/tests/test_checkout.py
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/discount/tests/test_utils.py
  saleor/graphql/discount/utils.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/tests/e2e/checkout/discounts/promotions/test_promotion_applied_on_checkout_with_specific_subtotal.py
  saleor/tests/e2e/checkout/discounts/promotions/test_promotion_applied_on_checkout_with_subtotal_within_specified_range.py
  saleor/tests/e2e/checkout/discounts/promotions/test_promotion_discount_applied_on_checkout_with_specific_total_and_subtotal.py
  saleor/tests/fixtures.py
Labels: promotions
