Repository saleor/saleor, pull requests merged in 2024-09, with the labels that each got.

#16620 Fix test assertions
  saleor/checkout/tests/test_checkout_complete.py
  saleor/csv/tests/test_tasks.py
  saleor/graphql/account/tests/bulk_mutations/test_customer_bulk_update.py
  saleor/payment/tests/test_gateway.py
  saleor/plugins/user_email/tests/test_tasks.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/product/tests/test_tasks.py
Labels: bug, skip changelog

#16619 Split dataloaders in checkout and webhooks to avoid circular imports
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/checkout/dataloaders/__init__.py
  saleor/graphql/checkout/dataloaders/checkout_infos.py
  saleor/graphql/checkout/dataloaders/models.py
  saleor/graphql/checkout/dataloaders/problems.py
  saleor/graphql/checkout/dataloaders/promotion_rule_infos.py
  saleor/graphql/webhook/dataloaders/__init__.py
  saleor/graphql/webhook/dataloaders/models.py
  saleor/graphql/webhook/dataloaders/pregenerated_payload_for_checkout_tax.py
Labels: 3.20

#16622 Split dataloaders in checkout and webhooks to avoid circular imports
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/checkout/dataloaders/__init__.py
  saleor/graphql/checkout/dataloaders/checkout_infos.py
  saleor/graphql/checkout/dataloaders/models.py
  saleor/graphql/checkout/dataloaders/problems.py
  saleor/graphql/checkout/dataloaders/promotion_rule_infos.py
  saleor/graphql/webhook/dataloaders/__init__.py
  saleor/graphql/webhook/dataloaders/models.py
  saleor/graphql/webhook/dataloaders/pregenerated_payload_for_checkout_tax.py
Labels: 3.18

#16596 Fix failing email plugin when image data is not found
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: bug, 3.14, shopping

#16597 Fix failing email plugin when image data is not found
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: bug, 3.15, shopping

#16598 Fix failing email plugin when image data is not found
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: bug, 3.17, shopping

#16599 Fix failing email plugin when image data is not found
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: bug, 3.18, shopping

#16600 Fix failing email plugin when image data is not found
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: bug, 3.19, shopping

#16601 Fix failing email plugin when image data is not found
  saleor/plugins/email_common.py
  saleor/plugins/tests/test_email_common.py
Labels: bug, shopping, 3.20

#16629 Add missing line to Dockerfile
  Dockerfile
Labels: bug, skip changelog

#16602 New release workflows
  .github/workflows/create-tag-with-release-pr.yml
  .gitignore
  .release-it.json
Labels: 3.20

#16609 Reduce number of DB queries called for fulfillment logic
  saleor/account/notifications.py
  saleor/account/tests/test_notifications.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/core/notification/mutation_handler.py
  saleor/core/notify.py
  saleor/csv/notifications.py
  saleor/csv/tests/test_notifications.py
  saleor/giftcard/notifications.py
  saleor/giftcard/tests/test_notifications.py
  saleor/graphql/account/tests/mutations/account/test_account_register.py
  saleor/graphql/account/tests/mutations/account/test_account_request_deletion.py
  saleor/graphql/account/tests/mutations/account/test_request_email_change.py
  saleor/graphql/account/tests/mutations/account/test_send_confirmation_email.py
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
  saleor/graphql/account/tests/mutations/staff/test_customer_create.py
  saleor/graphql/account/tests/mutations/staff/test_staff_create.py
  saleor/graphql/invoice/tests/test_send_invoice_notification.py
  saleor/graphql/notifications/tests/test_external_notification_query.py
  saleor/graphql/order/mutations/order_fulfill.py
  saleor/graphql/order/tests/mutations/test_order_capture.py
  saleor/graphql/order/tests/mutations/test_order_confirm.py
  saleor/graphql/order/types.py
  saleor/graphql/product/dataloaders/products.py
  saleor/invoice/notifications.py
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/order/tests/test_order.py
  saleor/plugins/admin_email/notify_events.py
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/test_notify_events.py
  saleor/plugins/admin_email/tests/test_plugin.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/sendgrid/plugin.py
  saleor/plugins/sendgrid/tests/test_plugin.py
  saleor/plugins/user_email/notify_events.py
  saleor/plugins/user_email/plugin.py
  saleor/plugins/user_email/tests/test_notify_events.py
  saleor/plugins/user_email/tests/test_plugin.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: 3.19

#16610 Reduce number of DB queries called for fulfillment logic
  saleor/account/notifications.py
  saleor/account/tests/test_notifications.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/core/notification/mutation_handler.py
  saleor/core/notify.py
  saleor/csv/notifications.py
  saleor/csv/tests/test_notifications.py
  saleor/giftcard/notifications.py
  saleor/giftcard/tests/test_notifications.py
  saleor/graphql/account/tests/mutations/account/test_account_register.py
  saleor/graphql/account/tests/mutations/account/test_account_request_deletion.py
  saleor/graphql/account/tests/mutations/account/test_request_email_change.py
  saleor/graphql/account/tests/mutations/account/test_send_confirmation_email.py
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
  saleor/graphql/account/tests/mutations/staff/test_customer_create.py
  saleor/graphql/account/tests/mutations/staff/test_staff_create.py
  saleor/graphql/invoice/tests/test_send_invoice_notification.py
  saleor/graphql/notifications/tests/test_external_notification_query.py
  saleor/graphql/order/mutations/order_fulfill.py
  saleor/graphql/order/tests/mutations/test_order_capture.py
  saleor/graphql/order/tests/mutations/test_order_confirm.py
  saleor/graphql/order/types.py
  saleor/graphql/product/dataloaders/products.py
  saleor/invoice/notifications.py
  saleor/order/notifications.py
  saleor/order/tests/test_notifications.py
  saleor/order/tests/test_order.py
  saleor/plugins/admin_email/notify_events.py
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/test_notify_events.py
  saleor/plugins/admin_email/tests/test_plugin.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/sendgrid/plugin.py
  saleor/plugins/sendgrid/tests/test_plugin.py
  saleor/plugins/user_email/notify_events.py
  saleor/plugins/user_email/plugin.py
  saleor/plugins/user_email/tests/test_notify_events.py
  saleor/plugins/user_email/tests/test_plugin.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: 3.20

#16642 fix unhandled none cases with shipping method list and add tests
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/webhook/transport/shipping.py
Labels: 3.20

#16627 Fix failing static payload for variant-stock-updated
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: skip changelog

#16633 Fix failing static payload for variant-stock-updated
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: 3.20

#16634 Fix failing static payload for variant-stock-updated
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: 3.19

#16635 Fix failing static payload for variant-stock-updated
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: 3.18

#16636 Fix failing static payload for variant-stock-updated
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: 3.17

#16637 Fix failing static payload for variant-stock-updated
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: 3.16

#16638 Fix failing static payload for variant-stock-updated
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: 3.15

#16639 Fix failing static payload for variant-stock-updated
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
Labels: 3.14

#16630 Add `TaxableObjectDiscountType` to inform tax apps how to distribute discounts.
  CHANGELOG.md
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils/manual_discount.py
  saleor/graphql/core/types/taxes.py
  saleor/graphql/schema.graphql
  saleor/graphql/tax/enums.py
  saleor/tax/__init__.py
  saleor/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
Labels: test deployment, taxes, discount

#16643 Fix `ShippingMethodTranslation.name` API field to allow return nullable values
  saleor/graphql/schema.graphql
  saleor/graphql/translations/types.py
Labels: 3.16

#16644 Fix `ShippingMethodTranslation.name` API field to allow return nullable values
  saleor/graphql/schema.graphql
  saleor/graphql/translations/types.py
Labels: 3.17

#16645 Fix `ShippingMethodTranslation.name` API field to allow return nullable values
  saleor/graphql/schema.graphql
  saleor/graphql/translations/types.py
Labels: 3.18

#16650 Fix `ShippingMethodTranslation.name` API field to allow return nullable values
  saleor/graphql/schema.graphql
  saleor/graphql/translations/types.py
Labels: 3.20

#16651 Fix `ShippingMethodTranslation.name` API field to allow return nullable values
  saleor/graphql/schema.graphql
  saleor/graphql/translations/types.py
Labels: skip changelog, main, 3.21

#16659 Release 3.20.25
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16248 Use last-login threshold in external log-in mutations
  saleor/graphql/account/mutations/authentication/create_token.py
  saleor/graphql/account/mutations/authentication/external_obtain_access_tokens.py
  saleor/graphql/account/mutations/authentication/external_refresh.py
  saleor/graphql/account/mutations/authentication/refresh_token.py
  saleor/graphql/account/mutations/authentication/utils.py
  saleor/graphql/account/tests/mutations/authentication/test_external_obtain_access_tokens.py
  saleor/graphql/account/tests/mutations/authentication/test_external_refresh.py
  saleor/graphql/account/tests/mutations/authentication/test_token_create.py
  saleor/graphql/account/tests/mutations/authentication/test_token_refresh.py
Labels: skip changelog

#16249 Use last-login treshold in external mutations
  saleor/graphql/account/mutations/authentication/create_token.py
  saleor/graphql/account/mutations/authentication/external_obtain_access_tokens.py
  saleor/graphql/account/mutations/authentication/external_refresh.py
  saleor/graphql/account/mutations/authentication/refresh_token.py
  saleor/graphql/account/mutations/authentication/utils.py
  saleor/graphql/account/tests/mutations/authentication/test_external_obtain_access_tokens.py
  saleor/graphql/account/tests/mutations/authentication/test_external_refresh.py
  saleor/graphql/account/tests/mutations/authentication/test_token_create.py
  saleor/graphql/account/tests/mutations/authentication/test_token_refresh.py
Labels: 3.18

#16250 Use last-login threshold in external log-in mutations
  saleor/graphql/account/mutations/authentication/create_token.py
  saleor/graphql/account/mutations/authentication/external_obtain_access_tokens.py
  saleor/graphql/account/mutations/authentication/external_refresh.py
  saleor/graphql/account/mutations/authentication/refresh_token.py
  saleor/graphql/account/mutations/authentication/utils.py
  saleor/graphql/account/tests/mutations/authentication/test_external_obtain_access_tokens.py
  saleor/graphql/account/tests/mutations/authentication/test_external_refresh.py
  saleor/graphql/account/tests/mutations/authentication/test_token_create.py
  saleor/graphql/account/tests/mutations/authentication/test_token_refresh.py
Labels: 3.19

#16652 Use last-login threshold in external log-in mutations
  saleor/graphql/account/mutations/authentication/create_token.py
  saleor/graphql/account/mutations/authentication/external_obtain_access_tokens.py
  saleor/graphql/account/mutations/authentication/external_refresh.py
  saleor/graphql/account/mutations/authentication/refresh_token.py
  saleor/graphql/account/mutations/authentication/utils.py
  saleor/graphql/account/tests/mutations/authentication/test_external_obtain_access_tokens.py
  saleor/graphql/account/tests/mutations/authentication/test_external_refresh.py
  saleor/graphql/account/tests/mutations/authentication/test_token_create.py
  saleor/graphql/account/tests/mutations/authentication/test_token_refresh.py
Labels: 3.20

#16661 reliability: fix and prevent logging exceptions
  .semgrep/security/logging/exception-object-in-logger-extra.py
  .semgrep/security/logging/exception-object-in-logger-extra.yaml
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/openid_connect/utils.py
Labels: bug, skip changelog

#16662 semgrep: support all different types of try-except blocks
  .semgrep/security/logging/exception-object-in-logger-extra.py
  .semgrep/security/logging/exception-object-in-logger-extra.yaml
  saleor/payment/gateways/adyen/webhooks.py
Labels: skip changelog

#16624 Fix fetching available collection points
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/tests/fixtures.py
  saleor/warehouse/models.py
  saleor/warehouse/tests/test_warehouse.py
Labels: 3.20

#16656 Test `checkoutComplete` with overridden prices.
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_price_override.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
Labels: tests

#16657 Test `checkoutComplete` with overridden prices.
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_price_override.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
Labels: tests

#16654 Add `TaxableObjectDiscountType` to inform tax apps how to distribute discounts.
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils.py
  saleor/graphql/core/types/taxes.py
  saleor/graphql/schema.graphql
  saleor/graphql/tax/enums.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/tax/__init__.py
Labels: taxes, discount, 3.19

#16655 Add `TaxableObjectDiscountType` to inform tax apps how to distribute discounts.
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils/manual_discount.py
  saleor/graphql/core/types/taxes.py
  saleor/graphql/schema.graphql
  saleor/graphql/tax/enums.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/tax/__init__.py
Labels: taxes, discount, 3.20

#16665 Release 3.20.27
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16646 fix unhandled none cases with shipping method list and add tests (#16…
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/webhook/transport/shipping.py
Labels: skip changelog

#16669 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: skip changelog

#16670 Add resource names to common operations
  saleor/graphql/core/dataloaders.py
  saleor/graphql/core/tracing.py
  saleor/graphql/views.py
Labels: skip changelog

#16666 Fix release tool to trigger publishing containers
  .github/workflows/create-tag-with-release-pr.yml
  .github/workflows/publish-containers.yml
  .github/workflows/publish-main.yml
Labels: 3.20

#16672 Add resource names to common operations
  saleor/graphql/core/dataloaders.py
  saleor/graphql/core/tracing.py
  saleor/graphql/views.py
Labels: skip changelog, 3.20

#16673 Release 3.20.28
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16674 Trigger workflow staging build in new release flow
  .github/workflows/create-tag-with-release-pr.yml
Labels: 3.20

#16680 Revert "Fix fetching available collection points"
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/tests/fixtures.py
  saleor/warehouse/models.py
  saleor/warehouse/tests/test_warehouse.py
Labels: 3.20

#16681 Revert "Fix fetching available collection points"
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/tests/fixtures.py
  saleor/warehouse/models.py
  saleor/warehouse/tests/test_warehouse.py
Labels: skip changelog

#16678 Fix restoring voucher usage limit when the voucher is removed from draft order
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
Labels: 3.18

#16664 Fix restoring voucher usage limit when the voucher is removed from draft order
  saleor/graphql/discount/mutations/voucher/voucher_update.py
  saleor/graphql/discount/tests/mutations/test_voucher_update.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/tests/e2e/orders/discounts/test_order_voucher_usage_is_released_when_voucher_is_removed.py
  saleor/tests/e2e/orders/utils/draft_order_create.py
  saleor/tests/e2e/orders/utils/draft_order_update.py
Labels: 3.19

#16676 Fix restoring voucher usage limit when the voucher is removed from draft order
  saleor/graphql/discount/mutations/voucher/voucher_update.py
  saleor/graphql/discount/tests/mutations/test_voucher_update.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/tests/e2e/orders/discounts/test_order_voucher_usage_is_released_when_voucher_is_removed.py
  saleor/tests/e2e/orders/utils/draft_order_create.py
  saleor/tests/e2e/orders/utils/draft_order_update.py
Labels: 3.20

#16677 Fix restoring voucher usage limit when the voucher is removed from draft order
  saleor/graphql/discount/mutations/voucher/voucher_update.py
  saleor/graphql/discount/tests/mutations/test_voucher_update.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/tests/e2e/orders/discounts/test_order_voucher_usage_is_released_when_voucher_is_removed.py
  saleor/tests/e2e/orders/utils/draft_order_create.py
Labels: skip changelog, main

#16618 [Test] Should be able to complete draft order with both catalog promotion and order promotion subtotal applied
  saleor/tests/e2e/orders/discounts/test_order_products_on_catalog_promotion_and_order_promotion.py
  saleor/tests/e2e/orders/utils/__init__.py
  saleor/tests/e2e/orders/utils/draft_order_complete.py
  saleor/tests/e2e/orders/utils/order_line_update.py
Labels: skip changelog

#16685 Release 3.20.29
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16697 Fix workflow for publishing release with tag
  .github/workflows/create-tag-with-release-pr.yml
  .github/workflows/publish-containers.yml
Labels: bug, 3.20

#16686 Fix failing deprecated `send_webhook_request_async` task
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_deprecated_webhook_tasks.py
Labels: 3.17

#16679 Fix failing deprecated `send_webhook_request_async` task
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_deprecated_webhook_tasks.py
Labels: 3.18

#16687 Fix failing deprecated `send_webhook_request_async` task
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_deprecated_webhook_tasks.py
Labels: 3.19

#16698 Release 3.20.30
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16675 Only allow Int and Float literals to be passed to the Decimal scalar
  saleor/graphql/core/scalars.py
  saleor/graphql/core/tests/test_scalars.py
Labels: bug, skip changelog

#16699 Revert experimental release flow
  .github/workflows/create-tag-with-release-pr.yml
  .github/workflows/publish-containers.yml
  .github/workflows/publish-main.yml
  .gitignore
  .release-it.json
Labels: 3.20

#16616 [Test] Should be able to remove draft orders in bulk
  saleor/tests/e2e/orders/test_bulk_delete_draft_orders.py
  saleor/tests/e2e/orders/utils/__init__.py
  saleor/tests/e2e/orders/utils/draft_order_bulk_delete.py
Labels: skip changelog

#16704 Make `amount` optional in `transactionEventReport` for `REFUND_REVERSE`, `CHARGEBACK`, `INFO`, and all `*_FAILURE` events
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/schema.graphql
  saleor/payment/__init__.py
  saleor/payment/error_codes.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.17

#16703 Make `amount` optional in `transactionEventReport` for `REFUND_REVERSE`, `CHARGEBACK`, `INFO`, and all `*_FAILURE` events
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/schema.graphql
  saleor/payment/__init__.py
  saleor/payment/error_codes.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.18

#16702 Make `amount` optional in `transactionEventReport` for `REFUND_REVERSE`, `CHARGEBACK`, `INFO`, and all `*_FAILURE` events
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/schema.graphql
  saleor/payment/__init__.py
  saleor/payment/error_codes.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.19

#16688 Make `amount` optional in `transactionEventReport` for `REFUND_REVERSE`, `CHARGEBACK`, `INFO`, and all `*_FAILURE` events
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/schema.graphql
  saleor/payment/__init__.py
  saleor/payment/error_codes.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.20

#16705 Make `amount` optional in `transactionEventReport` for `REFUND_REVERSE`, `CHARGEBACK`, `INFO`, and all `*_FAILURE` events
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/schema.graphql
  saleor/payment/__init__.py
  saleor/payment/error_codes.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: skip changelog

#16692 Fix and prevent logging exceptions
  .semgrep/security/logging/exception-object-in-logger-extra.py
  .semgrep/security/logging/exception-object-in-logger-extra.yaml
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/openid_connect/utils.py
  saleor/webhook/observability/utils.py
Labels: 3.17

#16691 Fix and prevent logging exceptions
  .semgrep/security/logging/exception-object-in-logger-extra.py
  .semgrep/security/logging/exception-object-in-logger-extra.yaml
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/openid_connect/utils.py
  saleor/webhook/observability/utils.py
Labels: 3.18

#16690 Fix and prevent logging exceptions
  .semgrep/security/logging/exception-object-in-logger-extra.py
  .semgrep/security/logging/exception-object-in-logger-extra.yaml
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/openid_connect/utils.py
  saleor/webhook/observability/utils.py
Labels: 3.19

#16693 Fix and prevent logging exceptions
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/openid_connect/utils.py
  saleor/webhook/observability/utils.py
Labels: 3.16

#16694 Fix and prevent logging exceptions
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/openid_connect/utils.py
  saleor/webhook/observability/utils.py
Labels: 3.15

#16695 Fix and prevent logging exceptions
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/openid_connect/utils.py
  saleor/webhook/observability/utils.py
Labels: 3.14

#16716 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
Labels: :robot: bot, skip changelog

#16718 [TEST] Add tests for vouchers on draft orders
  saleor/tests/e2e/orders/discounts/test_order_voucher_entire_order.py
  saleor/tests/e2e/orders/discounts/test_order_voucher_entire_order_cheapest_product.py
  saleor/tests/e2e/orders/discounts/test_order_voucher_free_shipping.py
  saleor/tests/e2e/orders/discounts/test_order_voucher_specific_product_cheapest_product.py
  saleor/tests/e2e/product/utils/preparing_product.py
Labels: skip changelog

#16721 Fix `EventPayload` and `EventDelivery` creation
  saleor/core/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: 3.20

#16719 Add tests for order promotions on draft orders
  saleor/tests/e2e/orders/discounts/test_gift_promotion_applied_on_draft_order.py
  saleor/tests/e2e/orders/discounts/test_manual_total_discount_applied_on_draft_order.py
  saleor/tests/e2e/orders/discounts/test_promotion_applied_on_draft_order_with_specific_subtotal.py
  saleor/tests/e2e/orders/discounts/test_promotion_applied_on_draft_order_with_specific_total.py
  saleor/tests/e2e/orders/utils/draft_order_complete.py
  saleor/tests/e2e/orders/utils/order_discount_add.py
  saleor/tests/e2e/orders/utils/order_update_shipping.py
Labels: skip changelog

#16725 Fix `EventPayload` and `EventDelivery` creation (#16721)
  saleor/webhook/tests/test_webhook_protocols.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: skip changelog, main

#16723 Fix getting token in workflow
  .github/workflows/check-patches.yml
Labels: check patches

#16734 Log extra data when anomalies occur.
  saleor/checkout/calculations.py
  saleor/checkout/tests/test_calculations.py
  saleor/checkout/tests/test_utils.py
  saleor/checkout/utils.py
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils/shared.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/order/tests/test_order_utils.py
  saleor/order/utils.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/tax/tests/test_utils.py
  saleor/tax/utils.py
Labels: taxes

#16726 Add validation for tax data received from the Avatax plugin.
  saleor/checkout/calculations.py
  saleor/checkout/tests/test_calculations.py
  saleor/checkout/tests/test_utils.py
  saleor/checkout/utils.py
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils/shared.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/order/tests/test_order_utils.py
  saleor/order/utils.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/avatax/tests/test_avatax_caching.py
  saleor/tax/tests/test_utils.py
  saleor/tax/utils.py
  saleor/tests/fixtures.py
Labels: taxes

#16720 Add validation for tax data received from the tax app.
  CHANGELOG.md
  saleor/checkout/calculations.py
  saleor/checkout/tests/test_calculations.py
  saleor/checkout/tests/test_utils.py
  saleor/checkout/utils.py
  saleor/core/prices.py
  saleor/core/taxes.py
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils/shared.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/order/tests/test_order_utils.py
  saleor/order/utils.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/avatax/tests/test_avatax_caching.py
  saleor/tax/tests/test_utils.py
  saleor/tax/utils.py
  saleor/tests/fixtures.py
Labels: taxes

#16739 Bump `uvicorn`
  poetry.lock
  pyproject.toml
Labels: skip changelog

#16733 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
Labels: test deployment, :robot: bot, skip changelog

#16746 Fix migrations compability workflow
  .github/workflows/test-migrations-compatibility.yml
Labels: skip changelog

#16696 Fix order-level discounts handling when using tax app for tax calculation.
  CHANGELOG.md
  saleor/discount/utils/manual_discount.py
  saleor/discount/utils/voucher.py
  saleor/graphql/core/types/taxes.py
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/test_apply_order_discount.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/tests/e2e/orders/discounts/test_order_with_shipping_voucher_and_manual_order_discount.py
  saleor/tests/e2e/orders/utils/draft_order_complete.py
  saleor/tests/e2e/orders/utils/order_discount_add.py
  saleor/tests/e2e/orders/utils/order_lines_create.py
  saleor/tests/fixtures.py
  saleor/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
Labels: test deployment, taxes, discount

#16762 Log the warning when checkout and order are missing for provided payment in Stripe webhooks
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: 3.14

#16761 Log the warning when checkout and order are missing for provided payment in Stripe webhooks
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: 3.15

#16760 Log the warning when checkout and order are missing for provided payment in Stripe webhooks
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: 3.16

#16758 Log the warning when checkout and order are missing for provided payment in Stripe webhooks
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: 3.18

#16737 Log the warning when checkout and order are missing for provided payment in Stripe webhooks
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: 3.19

#16756 Log the warning when checkout and order are missing for provided payment in Stripe webhooks
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: 3.20

#16757 Log the warning when checkout and order are missing for provided payment in Stripe webhooks
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/payment/gateways/stripe/webhooks.py
Labels: skip changelog, main

#16744 Refactor webhook tests for checkout
  saleor/checkout/tests/test_actions.py
Labels: skip changelog

#16738 Do not stack manual line discounts with line-level vouchers.
  CHANGELOG.md
  saleor/discount/utils/promotion.py
  saleor/discount/utils/voucher.py
  saleor/graphql/order/mutations/order_line_discount_update.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/tests/e2e/orders/discounts/test_order_voucher_specific_product_and_manual_line_discount.py
  saleor/tests/e2e/orders/utils/draft_order_complete.py
  saleor/tests/e2e/orders/utils/draft_order_update.py
  saleor/tests/e2e/orders/utils/order_line_discount_update.py
Labels: bug, discount

#16749 Add validation for tax data received from the tax app.
  saleor/checkout/calculations.py
  saleor/checkout/tests/test_calculations.py
  saleor/checkout/tests/test_utils.py
  saleor/checkout/utils.py
  saleor/core/prices.py
  saleor/core/taxes.py
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils/shared.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/order/tests/test_order_utils.py
  saleor/order/utils.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/avatax/tests/test_avatax_caching.py
  saleor/tax/tests/test_utils.py
  saleor/tax/utils.py
  saleor/tests/fixtures.py
Labels: taxes, 3.20, check patches

#16748 Add validation for tax data received from the tax app.
  saleor/checkout/calculations.py
  saleor/checkout/tests/test_calculations.py
  saleor/checkout/tests/test_utils.py
  saleor/checkout/utils.py
  saleor/core/prices.py
  saleor/core/taxes.py
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/order/utils.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/avatax/tests/test_avatax_caching.py
  saleor/tax/tests/test_utils.py
  saleor/tax/utils.py
  saleor/tests/fixtures.py
Labels: taxes, 3.19

#16736 Allow providing `metadata` in `TransactionEventReport` mutation
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/schema.graphql
Labels: 3.17

#16752 Allow providing `metadata` in `TransactionEventReport` mutation
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/schema.graphql
Labels: 3.18

#16753 Allow providing `metadata` in `TransactionEventReport` mutation
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/schema.graphql
Labels: 3.19

#16754 Allow providing `metadata` in `TransactionEventReport` mutation
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/schema.graphql
Labels: 3.20, check patches

#16755 Allow providing `metadata` in `TransactionEventReport` mutation
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/schema.graphql
Labels: skip changelog, main

#16724 Fix fetching available collection points
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/tests/fixtures.py
  saleor/warehouse/migrations/0034_warehouse_click_and_collect_option_idx.py
  saleor/warehouse/models.py
  saleor/warehouse/tests/test_warehouse.py
Labels: 3.20, check patches

#16745 Fix fetching available collection points
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/tests/fixtures.py
  saleor/warehouse/migrations/0034_warehouse_click_and_collect_option_idx.py
  saleor/warehouse/models.py
  saleor/warehouse/tests/test_warehouse.py
Labels: skip changelog, main, skip migrations perf test

#16747 Refactor graphql mutations webhook tests
  saleor/graphql/meta/tests/mutations/test_checkout.py
  saleor/graphql/meta/tests/mutations/test_order.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/tests/mutations/test_order_capture.py
  saleor/graphql/order/tests/mutations/test_order_line_delete.py
  saleor/graphql/order/tests/mutations/test_order_line_update.py
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/graphql/order/tests/mutations/test_order_note_add.py
  saleor/graphql/order/tests/mutations/test_order_note_update.py
  saleor/graphql/order/tests/mutations/test_order_update.py
  saleor/graphql/order/tests/mutations/test_order_update_shipping.py
Labels: skip changelog

#16763 Fix order-level discounts handling when using tax app for tax calculation.
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils.py
  saleor/graphql/core/types/taxes.py
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/benchmark/test_fetch_order_prices.py
  saleor/order/tests/test_apply_order_discount.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/tax/calculations/order.py
  saleor/tests/e2e/orders/discounts/test_order_with_shipping_voucher_and_manual_order_discount.py
  saleor/tests/e2e/orders/utils/draft_order_complete.py
  saleor/tests/e2e/orders/utils/draft_order_update.py
  saleor/tests/e2e/orders/utils/order_discount_add.py
  saleor/tests/e2e/orders/utils/order_lines_create.py
  saleor/tests/fixtures.py
Labels: taxes, discount, 3.19

#16764 Fix order-level discounts handling when using tax app for tax calculation.
  saleor/discount/tests/test_discounts.py
  saleor/discount/utils/manual_discount.py
  saleor/discount/utils/voucher.py
  saleor/graphql/core/types/taxes.py
  saleor/graphql/order/types.py
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/benchmark/test_fetch_order_prices.py
  saleor/order/tests/test_apply_order_discount.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/tax/calculations/order.py
  saleor/tests/e2e/orders/discounts/test_order_with_shipping_voucher_and_manual_order_discount.py
  saleor/tests/e2e/orders/utils/draft_order_complete.py
  saleor/tests/e2e/orders/utils/draft_order_update.py
  saleor/tests/e2e/orders/utils/order_discount_add.py
  saleor/tests/e2e/orders/utils/order_lines_create.py
  saleor/tests/fixtures.py
Labels: taxes, discount, 3.20, check patches

#16768 Do not stack manual line discounts with line-level vouchers.
  saleor/discount/utils/promotion.py
  saleor/discount/utils/voucher.py
  saleor/graphql/order/mutations/order_line_discount_update.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/tests/e2e/orders/discounts/test_order_voucher_specific_product_and_manual_line_discount.py
  saleor/tests/e2e/orders/utils/__init__.py
  saleor/tests/e2e/orders/utils/draft_order_complete.py
  saleor/tests/e2e/orders/utils/draft_order_update.py
  saleor/tests/e2e/orders/utils/order_line_discount_update.py
  saleor/tests/e2e/orders/utils/order_update_shipping.py
  saleor/tests/e2e/product/utils/preparing_product.py
Labels: 3.20, check patches

#16769 Do not stack manual line discounts with line-level vouchers.
  saleor/discount/utils.py
  saleor/graphql/order/mutations/order_line_discount_update.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/tests/e2e/orders/discounts/test_order_voucher_specific_product_and_manual_line_discount.py
  saleor/tests/e2e/orders/utils/__init__.py
  saleor/tests/e2e/orders/utils/draft_order_complete.py
  saleor/tests/e2e/orders/utils/draft_order_update.py
  saleor/tests/e2e/orders/utils/order_line_discount_update.py
  saleor/tests/e2e/orders/utils/order_update_shipping.py
  saleor/tests/e2e/product/utils/preparing_product.py
Labels: 3.19

#16770 Fix typo in invalid IP address validation error
  saleor/account/throttling.py
Labels: skip changelog

#16771 Fix `test_split_manual_discount` to silent warnings
  saleor/discount/tests/test_discounts.py
Labels: skip changelog
