Repository saleor/saleor, pull requests merged in 2024-04, with the labels that each got.

#15729 Add allow_writer usages to delivery attempts and payments
  saleor/payment/utils.py
  saleor/webhook/payloads.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: skip changelog

#15730 Add allow_writer_in_context in resolvers
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/checkout/types.py
  saleor/graphql/order/types.py
  saleor/permission/enums.py
  saleor/shipping/utils.py
  saleor/tax/calculations/order.py
  saleor/warehouse/models.py
Labels: skip changelog

#15737 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
Labels: test deployment, :robot: bot, skip changelog

#15727 Fix inconsistent history
  saleor/product/migrations/0190_merge_20231221_1356.py
Labels: 3.18

#15726 Fix inconsistent history
  saleor/product/migrations/0190_merge_20231221_1356.py
Labels: 3.17

#15742 fix checkout shipping addresses which had reference to warehouse addresses
  saleor/checkout/migrations/0063_auto_20240402_1114.py
  saleor/checkout/migrations/tasks/saleor3_14.py
Labels: checkout, skip changelog, 3.15, shopping

#15743 fix checkout shipping addresses which had reference to warehouse addresses
  saleor/checkout/migrations/0063_auto_20240402_1114.py
  saleor/checkout/migrations/tasks/saleor3_14.py
Labels: checkout, skip changelog, 3.16, shopping

#15744 fix checkout shipping addresses which had reference to warehouse addresses
  saleor/checkout/migrations/0063_auto_20240402_1114.py
  saleor/checkout/migrations/tasks/saleor3_14.py
Labels: checkout, skip changelog, 3.17, shopping

#15745 fix checkout shipping addresses which had reference to warehouse addresses
  saleor/checkout/migrations/0063_auto_20240402_1114.py
  saleor/checkout/migrations/tasks/saleor3_14.py
Labels: skip changelog, channel, 3.18, shopping

#15746 fix checkout shipping addresses which had reference to warehouse addresses
  saleor/checkout/migrations/0063_auto_20240402_1114.py
  saleor/checkout/migrations/0066_merge_0063_auto_20240402_1114_0065_checkout_tax_error.py
  saleor/checkout/migrations/tasks/saleor3_14.py
Labels: checkout, skip changelog, 3.19, shopping

#15752 Bump requests-hardened
  poetry.lock
  pyproject.toml
Labels: dependencies, skip changelog

#15753 Bump requests-hardened
  poetry.lock
  pyproject.toml
Labels: dependencies, 3.19

#15754 Bump requests-hardened
  poetry.lock
  pyproject.toml
Labels: dependencies, 3.18

#15755 Bump requests-hardened
  poetry.lock
  pyproject.toml
Labels: dependencies, 3.17

#15748 Optimize validate_draft_order function to run less queries
  saleor/discount/utils.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/tests/test_draft_order_validate.py
  saleor/graphql/order/types.py
  saleor/graphql/order/utils.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
Labels: skip changelog

#15756 Bump requests-hardened
  poetry.lock
  pyproject.toml
  saleor/__init__.py
  saleor/core/http_client.py
  saleor/core/tests/test_http_client.py
Labels: dependencies, 3.16

#15757 Fix missing autodiscover task for checkout migrations
  saleor/celeryconf.py
  saleor/checkout/migrations/0063_auto_20240402_1114.py
  saleor/checkout/migrations/0067_auto_20240405_0756.py
Labels: bug, checkout, skip changelog, 3.19, shopping

#15765 Fix requirements files after bumping `requests-hardened`
  requirements.txt
  requirements_dev.txt
Labels: 3.16

#15774 Add `unique_type` to discount line models.
  CHANGELOG.md
  saleor/discount/migrations/0078_add_unique_type.py
  saleor/discount/migrations/0079_add_index_for_unique_type.py
  saleor/discount/migrations/0080_add_unique_type_constraint.py
  saleor/discount/models.py
Labels: migration, promotions, 3.19, merchant

#15775 Add `unique_type` to line discount models.
  CHANGELOG.md
  saleor/discount/migrations/0078_add_unique_type.py
  saleor/discount/migrations/0079_add_index_for_unique_type.py
  saleor/discount/migrations/0080_add_unique_type_constraint.py
  saleor/discount/models.py
Labels: migration, promotions, merchant

#15778 Remove unique constraint
  saleor/attribute/migrations/0040_clear_assignedattributes.py
Labels: 3.19

#15777 Fix checkout base prices when tax app is broken
  saleor/checkout/calculations.py
  saleor/checkout/tests/test_calculations.py
Labels: bug, 3.19

#15776 Remove celery task from order migration
  saleor/order/migrations/0172_update_order_cc_addresses.py
  saleor/order/migrations/tasks/__init__.py
  saleor/order/migrations/tasks/saleor3_19.py
Labels: bug, migrations perf test, order, skip changelog, main, shopping

#15783 Fix checkout base prices when tax app is broken
  saleor/checkout/calculations.py
  saleor/checkout/tests/test_calculations.py
Labels: bug, skip changelog, main

#15764 Fix migration nodes
  saleor/product/migrations/0187_merge_20231221_1030.py
  saleor/product/migrations/0188_merge_20231221_1119.py
  saleor/product/migrations/0189_merge_20240405_1121.py
  saleor/product/migrations/0191_merge_20240405_1125.py
  saleor/product/migrations/0192_merge_20240405_1154.py
Labels: skip changelog, main, skip migrations perf test

#15763 Fix migration nodes
  saleor/product/migrations/0187_merge_20231221_1030.py
  saleor/product/migrations/0188_merge_20231221_1119.py
  saleor/product/migrations/0189_merge_20240405_1121.py
  saleor/product/migrations/0191_merge_20240405_1125.py
  saleor/product/migrations/0192_merge_20240405_1154.py
Labels: 3.19

#15762 Fix migration nodes
  saleor/product/migrations/0187_merge_20231221_1030.py
  saleor/product/migrations/0188_merge_20231221_1119.py
  saleor/product/migrations/0189_merge_20240405_1121.py
  saleor/product/migrations/0191_merge_20240405_1125.py
Labels: 3.18

#15761 Fix migration nodes
  saleor/product/migrations/0187_merge_20231221_1030.py
  saleor/product/migrations/0188_merge_20231221_1119.py
  saleor/product/migrations/0189_merge_20240405_1121.py
  saleor/product/migrations/0191_merge_20240405_1125.py
Labels: 3.17

#15760 Fix migration nodes
  saleor/product/migrations/0187_merge_20231221_1030.py
  saleor/product/migrations/0189_merge_20240405_1121.py
Labels: 3.16

#15740 Add transaction items limit to TransactionSessionBase
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
Labels: 3.14

#15769 Optimize plugin manager initialization
  saleor/core/tests/test_dataloaders.py
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/tests/benchmark/test_permission_group.py
  saleor/graphql/account/tests/queries/test_me.py
  saleor/graphql/account/types.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
  saleor/graphql/discount/tests/benchmark/test_voucher_code_bulk_delete.py
  saleor/graphql/payment/mutations/stored_payment_methods/payment_gateway_initialize_tokenization.py
  saleor/graphql/payment/mutations/stored_payment_methods/payment_method_intialize_tokenization.py
  saleor/graphql/payment/mutations/stored_payment_methods/payment_method_process_tokenization.py
  saleor/graphql/payment/mutations/stored_payment_methods/payment_method_request_delete.py
  saleor/graphql/payment/mutations/stored_payment_methods/utils.py
  saleor/graphql/payment/tests/mutations/test_payment_gateway_initialize_tokenization.py
  saleor/graphql/payment/tests/mutations/test_payment_method_initialize_tokenization.py
  saleor/graphql/payment/tests/mutations/test_payment_method_process_tokenization.py
  saleor/graphql/payment/tests/mutations/test_stored_payment_method_request_delete.py
  saleor/graphql/plugins/resolvers.py
  saleor/graphql/product/mutations/utils.py
  saleor/graphql/product/tests/benchmark/test_collection.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/graphql/product/tests/deprecated/test_utils.py
  saleor/graphql/product/tests/mutations/test_product_create.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/types/products.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/payment/gateway.py
  saleor/payment/gateways/adyen/tests/conftest.py
  saleor/payment/gateways/authorize_net/tests/conftest.py
  saleor/payment/gateways/np_atobarai/tests/conftest.py
  saleor/payment/gateways/stripe/tests/conftest.py
  saleor/plugins/admin_email/tests/conftest.py
  saleor/plugins/admin_email/tests/test_plugin.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/deprecated/__init__.py
  saleor/plugins/avatax/tests/deprecated/test_tax_code_mutations.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/openid_connect/tests/conftest.py
  saleor/plugins/sendgrid/tests/conftest.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/tests/test_manager.py
  saleor/plugins/user_email/tests/conftest.py
  saleor/plugins/user_email/tests/test_plugin.py
  saleor/plugins/webhook/conftest.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/conftest.py
Labels: test deployment

#15459 Calculate order promotions in draft order
  CHANGELOG.md
  saleor/checkout/utils.py
  saleor/discount/interface.py
  saleor/discount/tests/test_utils/fixtures.py
  saleor/discount/tests/test_utils/test_copy_unit_discount_data_to_order_line.py
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_checkout.py
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_order.py
  saleor/discount/tests/test_utils/test_fetch_promotion_rules_for_checkout.py
  saleor/discount/utils.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/discount/utils.py
  saleor/graphql/order/filters.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/order_update.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/tests/mutations/test_order_discount.py
  saleor/graphql/order/tests/mutations/test_order_line_update.py
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/graphql/order/tests/queries/test_draft_order_with_filter.py
  saleor/graphql/order/types.py
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/fetch.py
  saleor/order/tests/benchmark/__init__.py
  saleor/order/tests/benchmark/test_fetch_order_prices.py
  saleor/order/tests/test_apply_order_discount.py
  saleor/order/tests/test_fetch.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/order/utils.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_order_total_gift_promotion.yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_order_total_order_promotion.yaml
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/tax/calculations/order.py
  saleor/tax/tests/test_checkout_calculations.py
  saleor/tax/tests/test_order_calculations.py
  saleor/tests/e2e/orders/discounts/test_order_product_with_percentage_promotion.py
  saleor/tests/e2e/orders/discounts/test_order_products_on_percentage_sale.py
  saleor/tests/e2e/orders/discounts/test_order_products_on_promotion_and_manual_order_discount.py
  saleor/tests/fixtures.py
  saleor/tests/utils.py
Labels: promotions, merchant

#15598 Update readme
  README.md
Labels: skip changelog

#15807 Optimize plugin manager initialization (#15769)
  saleor/core/tests/test_dataloaders.py
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/tests/benchmark/test_permission_group.py
  saleor/graphql/account/tests/queries/test_me.py
  saleor/graphql/account/types.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
  saleor/graphql/discount/tests/benchmark/test_promotion_create.py
  saleor/graphql/discount/tests/benchmark/test_promotion_delete.py
  saleor/graphql/discount/tests/benchmark/test_promotion_rule_create.py
  saleor/graphql/discount/tests/benchmark/test_voucher_code_bulk_delete.py
  saleor/graphql/payment/mutations/stored_payment_methods/payment_gateway_initialize_tokenization.py
  saleor/graphql/payment/mutations/stored_payment_methods/payment_method_intialize_tokenization.py
  saleor/graphql/payment/mutations/stored_payment_methods/payment_method_process_tokenization.py
  saleor/graphql/payment/mutations/stored_payment_methods/payment_method_request_delete.py
  saleor/graphql/payment/mutations/stored_payment_methods/utils.py
  saleor/graphql/payment/tests/mutations/test_payment_gateway_initialize_tokenization.py
  saleor/graphql/payment/tests/mutations/test_payment_method_initialize_tokenization.py
  saleor/graphql/payment/tests/mutations/test_payment_method_process_tokenization.py
  saleor/graphql/payment/tests/mutations/test_stored_payment_method_request_delete.py
  saleor/graphql/plugins/resolvers.py
  saleor/graphql/product/mutations/utils.py
  saleor/graphql/product/tests/benchmark/test_collection.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/graphql/product/tests/deprecated/test_utils.py
  saleor/graphql/product/tests/mutations/test_product_create.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/types/products.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/payment/gateway.py
  saleor/payment/gateways/adyen/tests/conftest.py
  saleor/payment/gateways/authorize_net/tests/conftest.py
  saleor/payment/gateways/np_atobarai/tests/conftest.py
  saleor/payment/gateways/stripe/tests/conftest.py
  saleor/plugins/admin_email/tests/conftest.py
  saleor/plugins/admin_email/tests/test_plugin.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/deprecated/__init__.py
  saleor/plugins/avatax/tests/deprecated/test_tax_code_mutations.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/openid_connect/tests/conftest.py
  saleor/plugins/sendgrid/tests/conftest.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/tests/test_manager.py
  saleor/plugins/user_email/tests/conftest.py
  saleor/plugins/user_email/tests/test_plugin.py
  saleor/plugins/webhook/conftest.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/conftest.py
Labels: skip changelog

#15809 Add deepcoopy when updating CONFIG_STRUCTURE for AdminEmailPlugin
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/test_plugin.py
Labels: bug, 3.14

#15800 Raise `ValidationError` for invalid `shippingMethod` in `DraftOrderInput`
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/shipping/utils.py
Labels: 3.15

#15799 Raise `ValidationError` for invalid `shippingMethod` in `DraftOrderInput`
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/shipping/utils.py
Labels: 3.16

#15798 Raise `ValidationErro`r for invalid `shippingMethod` in `DraftOrderInput`
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/shipping/utils.py
Labels: 3.17

#15797 Raise `ValidationError` for invalid `shippingMethod` in `DraftOrderInput`
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/shipping/utils.py
Labels: 3.18

#15796 Raise `ValidationError` for invalid `shippingMethod` in `DraftOrderInput`
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/shipping/utils.py
Labels: 3.19

#15779 Remove unique constraint
  saleor/attribute/migrations/0040_clear_assignedattributes.py
Labels: skip changelog, main, skip migrations perf test

#15817 Add deepcoopy when updating CONFIG_STRUCTURE for AdminEmailPlugin
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/test_plugin.py
Labels: bug, 3.16

#15816 Add deepcoopy when updating CONFIG_STRUCTURE for AdminEmailPlugin
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/test_plugin.py
Labels: bug, 3.15

#15815 Add deepcoopy when updating CONFIG_STRUCTURE for AdminEmailPlugin
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/test_plugin.py
Labels: bug, 3.18

#15814 Add deepcoopy when updating CONFIG_STRUCTURE for AdminEmailPlugin
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/test_plugin.py
Labels: bug, 3.17

#15813 Add deepcoopy when updating CONFIG_STRUCTURE for AdminEmailPlugin
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/test_plugin.py
Labels: bug, skip changelog, main

#15820 Bump gunicorn
  poetry.lock
  pyproject.toml
Labels: dependencies, 3.18

#15821 Bump gunicorn
  poetry.lock
  pyproject.toml
Labels: dependencies, 3.17

#15822 Bump gunicorn
  poetry.lock
  pyproject.toml
Labels: dependencies, 3.16

#15823 Bump gunicorn
  poetry.lock
  pyproject.toml
Labels: dependencies, 3.15

#15824 Bump gunicorn
  poetry.lock
  pyproject.toml
Labels: dependencies, 3.14

#15786 Raise a `ValidationError` for invalid `shippingMethod` in `DraftOrderInput`
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/shipping/utils.py
Labels: skip changelog

#15828 Bump gunicorn (update requirements files)
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.16

#15829 Bump gunicorn (update requirements files)
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.15

#15830 Bump gunicorn (update requirements files)
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.14

#15827 Bump gunicorn (update requirements files)
  requirements.txt
  requirements_dev.txt
Labels: dependencies, 3.17

#15787 ProductsQueryset manager execute duplicated channel queries
  saleor/graphql/attribute/filters.py
  saleor/graphql/order/utils.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/categories.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/product/models.py
  saleor/product/tests/test_product_availability.py
Labels: 3.14

#15842 Add transaction items limit to TransactionSessionBase
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_payment_gateway_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/schema.graphql
  saleor/settings.py
Labels: 3.14

#15794 Add transaction items limit to TransactionSessionBase
  saleor/graphql/payment/mutations/base.py
  saleor/graphql/payment/mutations/transaction/payment_gateway_initialize.py
  saleor/graphql/payment/mutations/transaction/transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_payment_gateway_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/schema.graphql
  saleor/settings.py
Labels: 3.19

#15793 Add transaction items limit to TransactionSessionBase
  saleor/graphql/payment/mutations/base.py
  saleor/graphql/payment/mutations/transaction/payment_gateway_initialize.py
  saleor/graphql/payment/mutations/transaction/transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_payment_gateway_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/schema.graphql
  saleor/settings.py
Labels: 3.18

#15792 Add transaction items limit to TransactionSessionBase
  saleor/graphql/payment/mutations/base.py
  saleor/graphql/payment/mutations/transaction/payment_gateway_initialize.py
  saleor/graphql/payment/mutations/transaction/transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_payment_gateway_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/schema.graphql
  saleor/settings.py
Labels: 3.17

#15843 Add transaction items limit to TransactionSessionBase
  saleor/graphql/payment/mutations/base.py
  saleor/graphql/payment/mutations/transaction/payment_gateway_initialize.py
  saleor/graphql/payment/mutations/transaction/transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_payment_gateway_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/schema.graphql
  saleor/settings.py
Labels: 3.16

#15790 Add transaction items limit to TransactionSessionBase
  saleor/graphql/payment/mutations/base.py
  saleor/graphql/payment/mutations/payment/payment_gateway_initialize.py
  saleor/graphql/payment/mutations/transaction/transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_payment_gateway_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/schema.graphql
  saleor/settings.py
Labels: 3.15

#15859 Change value type from float to str in test
  saleor/checkout/tests/test_calculations.py
Labels: skip changelog, main

#15844 Recalculate prices with celery beat - improvements and compatibility between 3.18-3.19-main
  saleor/discount/migrations/0072_promotionrule_variants_dirty.py
  saleor/discount/migrations/0076_promotionrule_variants_dirty.py
  saleor/discount/migrations/0081_merge_20240422_1207.py
  saleor/graphql/product/mutations/product/product_update.py
  saleor/product/tasks.py
Labels: skip changelog, skip migrations perf test

#15841 Recalculate prices with celery beat - improvements and compatibility between 3.18-3.19-main
  saleor/discount/migrations/0072_promotionrule_variants_dirty.py
  saleor/discount/migrations/0076_promotionrule_variants_dirty.py
  saleor/discount/migrations/0081_merge_20240422_1207.py
  saleor/graphql/product/mutations/product/product_update.py
  saleor/product/tasks.py
Labels: 3.19

#15840 Recalculate prices with celery beat - improvements and compatibility between 3.18-3.19-main
  saleor/discount/migrations/0072_promotionrule_variants_dirty.py
  saleor/graphql/product/mutations/product/product_update.py
  saleor/product/tasks.py
Labels: 3.18

#15848 ProductsQueryset manager execute duplicated channel queries
  saleor/graphql/attribute/filters.py
  saleor/graphql/order/utils.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/categories.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/product/managers.py
  saleor/product/tests/test_product_availability.py
Labels: 3.15

#15850 ProductsQueryset manager execute duplicated channel queries
  saleor/graphql/attribute/filters.py
  saleor/graphql/order/utils.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/categories.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/product/managers.py
  saleor/product/tests/test_product_availability.py
Labels: 3.16

#15851 ProductsQueryset manager execute duplicated channel queries
  saleor/graphql/attribute/filters.py
  saleor/graphql/order/utils.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/categories.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/product/managers.py
  saleor/product/tests/test_product_availability.py
Labels: 3.17

#15852 ProductsQueryset manager execute duplicated channel queries
  saleor/graphql/attribute/filters.py
  saleor/graphql/order/utils.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/categories.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/product/managers.py
  saleor/product/tests/test_product_availability.py
Labels: 3.18

#15854 ProductsQueryset manager execute duplicated channel queries
  saleor/graphql/attribute/filters.py
  saleor/graphql/order/utils.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/categories.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/product/managers.py
  saleor/product/tests/test_product_availability.py
Labels: 3.19

#15874 Fix flaky tests for page with attributes
  saleor/attribute/tests/model_helpers.py
Labels: skip changelog

#15863 Fix discounts resolver to work like in docs
  saleor/graphql/core/types/taxes.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
Labels: skip changelog, main

#15855 Fix race concurrency condition for completing checkout with the voucher that has a usage limit
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0064_checkout_is_voucher_usage_increased.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/utils.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/tests/fixtures.py
Labels: 3.14

#15856 Fix race concurrency condition for completing checkout with the voucher that has a usage limit
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0064_checkout_is_voucher_usage_increased.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/utils.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/tests/fixtures.py
Labels: 3.15

#15857 Fix voucher usage increasing race condition
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0064_checkout_is_voucher_usage_increased.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/utils.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/tests/fixtures.py
Labels: 3.16

#15860 Fix voucher usage increasing race condition
  saleor/checkout/complete_checkout.py
  saleor/checkout/fetch.py
  saleor/checkout/migrations/0064_checkout_is_voucher_usage_increased.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/utils.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/tests/fixtures.py
Labels: 3.17

#15861 Fix voucher usage increasing race condition
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0064_checkout_is_voucher_usage_increased.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/utils.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/tests/fixtures.py
Labels: 3.18

#15849 Fix race concurrency condition for completing checkout with the voucher that has a usage limit
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0064_checkout_is_voucher_usage_increased.py
  saleor/checkout/migrations/0068_merge_20240424_1209.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/utils.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/tests/fixtures.py
Labels: 3.19

#15875 Fix transactionUpdate/transactionCreate with empty metadata
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
Labels: skip changelog, main

#15862 Fix voucher usage increasing race condition
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0064_checkout_is_voucher_usage_increased.py
  saleor/checkout/migrations/0068_merge_20240424_1209.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/utils.py
  saleor/payment/gateways/stripe/tests/test_webhooks.py
  saleor/tests/fixtures.py
Labels: skip changelog, main, skip migrations perf test

#15865 Add index for ShippingZone.countries field
  saleor/shipping/migrations/0034_shippingzone_countries_idx.py
  saleor/shipping/models.py
Labels: 3.15

#15866 Add index for ShippingZone.countries field
  saleor/shipping/migrations/0034_shippingzone_countries_idx.py
  saleor/shipping/models.py
Labels: 3.16

#15867 Add index for ShippingZone.countries field
  saleor/shipping/migrations/0034_shippingzone_countries_idx.py
  saleor/shipping/models.py
Labels: 3.17

#15869 Add index for ShippingZone.countries field
  saleor/shipping/migrations/0034_shippingzone_countries_idx.py
  saleor/shipping/models.py
Labels: 3.19

#15870 Add index for ShippingZone.countries field
  saleor/shipping/migrations/0034_shippingzone_countries_idx.py
  saleor/shipping/models.py
Labels: skip changelog, skip migrations perf test

#15900 Added support for the `BrokerProperties` custom header to webhooks to support Azure Service Bus
  saleor/app/tests/test_installation_utils.py
  saleor/graphql/schema.graphql
  saleor/graphql/webhook/mutations/webhook_update.py
  saleor/graphql/webhook/tests/mutations/test_webhook_create.py
  saleor/graphql/webhook/tests/mutations/test_webhook_update.py
  saleor/webhook/tests/test_webhook_validators.py
  saleor/webhook/validators.py
Labels: 3.19

#15906 Add missing locks for price recalculation (#15901)
  saleor/discount/utils.py
  saleor/product/tasks.py
  saleor/product/utils/product.py
  saleor/product/utils/variant_prices.py
Labels: skip changelog

#15905 Add missing locks for price recalculation (#15901)
  saleor/discount/utils.py
  saleor/product/tasks.py
  saleor/product/utils/product.py
  saleor/product/utils/variant_prices.py
Labels: 3.19

#15858 ProductsQueryset manager execute duplicated channel queries
  saleor/graphql/attribute/filters.py
  saleor/graphql/order/utils.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/tests/benchmark/test_product.py
  saleor/graphql/product/tests/benchmark/test_variant.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/categories.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/product/managers.py
  saleor/product/tests/test_product_availability.py
Labels: skip changelog, main

#15885 Fix discounts resolver to work like in docs
  saleor/graphql/core/types/taxes.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
Labels: 3.19
