Repository saleor/saleor, pull requests merged in 2024-03, with the labels that each got.

#15505 Fix tax calculation for Click and Collect option.
  saleor/checkout/error_codes.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/mutations/checkout_shipping_address_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/schema.graphql
Labels: bug, checkout, skip changelog, main, shopping

#15337 Bulk create attribute value
  saleor/attribute/models/base.py
  saleor/attribute/utils.py
  saleor/graphql/attribute/enums.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/page/tests/mutations/test_page_update.py
  saleor/graphql/product/tests/benchmark/test_product_bulk_create.py
Labels: 3.15

#15336 Bulk create attribute value
  saleor/attribute/models/base.py
  saleor/attribute/utils.py
  saleor/graphql/attribute/enums.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/page/tests/mutations/test_page_update.py
  saleor/graphql/product/tests/benchmark/test_product_bulk_create.py
Labels: 3.16

#15343 Bulk create attribute value
  saleor/attribute/models/base.py
  saleor/attribute/utils.py
  saleor/graphql/attribute/enums.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/page/tests/mutations/test_page_update.py
  saleor/graphql/product/tests/benchmark/test_product_bulk_create.py
Labels: 3.17

#15508 Update user confirmation
  saleor/account/migrations/0081_update_user_is_confirmed.py
  saleor/account/migrations/0083_confirm_active_user.py
  saleor/account/migrations/0084_merge_20240229_1435.py
  saleor/account/migrations/tasks/saleor3_15.py
  saleor/celeryconf.py
  saleor/graphql/account/mutations/authentication/request_password_reset.py
  saleor/graphql/account/mutations/authentication/set_password.py
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
  saleor/graphql/account/tests/mutations/authentication/test_set_password.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.15

#15509 Update user confirmation
  saleor/account/migrations/0081_update_user_is_confirmed.py
  saleor/account/migrations/0083_confirm_active_user.py
  saleor/account/migrations/0084_merge_20240229_1435.py
  saleor/account/migrations/tasks/saleor3_16.py
  saleor/celeryconf.py
  saleor/graphql/account/mutations/authentication/request_password_reset.py
  saleor/graphql/account/mutations/authentication/set_password.py
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
  saleor/graphql/account/tests/mutations/authentication/test_set_password.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.16

#15510 Update user confirmation
  saleor/account/migrations/0081_update_user_is_confirmed.py
  saleor/account/migrations/0083_confirm_active_user.py
  saleor/account/migrations/0084_merge_20240229_1435.py
  saleor/account/migrations/tasks/saleor3_17.py
  saleor/celeryconf.py
  saleor/graphql/account/mutations/authentication/request_password_reset.py
  saleor/graphql/account/mutations/authentication/set_password.py
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
  saleor/graphql/account/tests/mutations/authentication/test_set_password.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.17

#15511 Update user confirmation
  saleor/account/migrations/0081_update_user_is_confirmed.py
  saleor/account/migrations/0083_confirm_active_user.py
  saleor/account/migrations/0084_merge_20240229_1435.py
  saleor/account/migrations/tasks/saleor3_18.py
  saleor/celeryconf.py
  saleor/graphql/account/mutations/authentication/request_password_reset.py
  saleor/graphql/account/mutations/authentication/set_password.py
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
  saleor/graphql/account/tests/mutations/authentication/test_set_password.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.18

#15512 Update user confirmation
  saleor/account/migrations/0081_update_user_is_confirmed.py
  saleor/account/migrations/0083_confirm_active_user.py
  saleor/account/migrations/0084_merge_20240229_1435.py
  saleor/account/migrations/tasks/saleor3_19.py
  saleor/celeryconf.py
  saleor/graphql/account/mutations/authentication/request_password_reset.py
  saleor/graphql/account/mutations/authentication/set_password.py
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
  saleor/graphql/account/tests/mutations/authentication/test_set_password.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.19

#15513 Update user confirmation
  saleor/account/migrations/0081_update_user_is_confirmed.py
  saleor/account/migrations/0083_confirm_active_user.py
  saleor/account/migrations/0084_merge_20240229_1435.py
  saleor/graphql/account/mutations/authentication/request_password_reset.py
  saleor/graphql/account/mutations/authentication/set_password.py
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
  saleor/graphql/account/tests/mutations/authentication/test_set_password.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: skip changelog, skip migrations perf test

#15506 fix `_get_the_cheapest_line` when there is no lines
  saleor/checkout/fetch.py
  saleor/graphql/checkout/tests/mutations/test_utils.py
Labels: bug, checkout, 3.19

#15515 Call user events in OIDC
  saleor/account/tests/test_utils.py
  saleor/account/utils.py
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.18

#15534 Call user events in OIDC
  saleor/account/tests/test_utils.py
  saleor/account/utils.py
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.19

#15535 Call user events in OIDC
  saleor/account/tests/test_utils.py
  saleor/account/utils.py
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: skip changelog, skip migrations perf test

#15536 Call user events in OIDC
  saleor/account/tests/test_utils.py
  saleor/account/utils.py
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.17

#15537 Call user events in OIDC
  saleor/account/tests/test_utils.py
  saleor/account/utils.py
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.16

#15538 Call user events in OIDC
  saleor/account/tests/test_utils.py
  saleor/account/utils.py
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.15

#15539 Call user events in OIDC
  saleor/account/tests/test_utils.py
  saleor/account/utils.py
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
  saleor/plugins/openid_connect/tests/test_utils.py
  saleor/plugins/openid_connect/utils.py
Labels: 3.14

#15540 Add more usages of replica
  saleor/graphql/account/schema.py
  saleor/graphql/app/schema.py
  saleor/graphql/attribute/schema.py
  saleor/graphql/attribute/types.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/core/connection.py
  saleor/graphql/csv/schema.py
  saleor/graphql/discount/schema.py
  saleor/graphql/giftcard/schema.py
  saleor/graphql/menu/schema.py
  saleor/graphql/order/schema.py
  saleor/graphql/page/resolvers.py
  saleor/graphql/page/schema.py
  saleor/graphql/page/types.py
  saleor/graphql/payment/schema.py
  saleor/graphql/product/filters.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/types/categories.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/schema.py
  saleor/graphql/tax/schema.py
  saleor/graphql/translations/types.py
  saleor/graphql/warehouse/schema.py
  saleor/graphql/webhook/resolvers.py
  saleor/graphql/webhook/types.py
  saleor/product/tests/test_product.py
Labels: skip changelog

#15541 fix _get_the_cheapest_line when there is no lines_info (#15506)
  saleor/checkout/fetch.py
  saleor/graphql/checkout/tests/mutations/test_utils.py
Labels: bug, main, shopping

#15542 Use replica to resolve default channel
  saleor/channel/utils.py
  saleor/graphql/account/mutations/account/account_register.py
  saleor/graphql/account/mutations/account/account_request_deletion.py
  saleor/graphql/account/mutations/account/confirm_email_change.py
  saleor/graphql/account/mutations/account/request_email_change.py
  saleor/graphql/account/mutations/account/send_confirmation_email.py
  saleor/graphql/account/mutations/authentication/request_password_reset.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/channel/utils.py
  saleor/graphql/checkout/mutations/checkout_create.py
  saleor/graphql/core/connection.py
  saleor/graphql/menu/schema.py
  saleor/graphql/order/resolvers.py
  saleor/graphql/product/schema.py
  saleor/graphql/product/types/categories.py
  saleor/graphql/product/types/products.py
  saleor/graphql/utils/sorting.py
Labels: skip changelog

#15532 Fix external shipping method calls on checkout lines add
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
Labels: bug, 3.18

#15543 Add using() method for filters and resolvers
  saleor/checkout/utils.py
  saleor/graphql/account/types.py
  saleor/graphql/attribute/filters.py
  saleor/graphql/attribute/tests/queries/test_attribute_filter.py
  saleor/graphql/checkout/filters.py
  saleor/graphql/csv/filters.py
  saleor/graphql/discount/filters.py
  saleor/graphql/giftcard/filters.py
  saleor/graphql/giftcard/types.py
  saleor/graphql/meta/permissions.py
  saleor/graphql/order/filters.py
  saleor/graphql/page/types.py
  saleor/graphql/plugins/filters.py
  saleor/graphql/plugins/resolvers.py
  saleor/graphql/plugins/schema.py
  saleor/graphql/shop/resolvers.py
  saleor/graphql/shop/utils.py
  saleor/graphql/tax/filters.py
  saleor/graphql/utils/__init__.py
  saleor/graphql/warehouse/filters.py
  saleor/payment/utils.py
Labels: skip changelog

#15552 Mark user as unconfirmed by default in `CustomerCreate`
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/mutations/staff/test_customer_create.py
  saleor/graphql/schema.graphql
Labels: 3.15

#15553 Mark user as unconfirmed by default in CustomerCreate
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/mutations/staff/test_customer_create.py
  saleor/graphql/schema.graphql
Labels: 3.16

#15557 Mark user as unconfirmed by default in `CustomerCreate`
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/mutations/staff/test_customer_create.py
  saleor/graphql/schema.graphql
Labels: 3.17

#15546 Change `discount_promotionrule_variants` `id` to `bigint`
  saleor/discount/migrations/0069_promotionrule_variants.py
  saleor/discount/migrations/0070_alter_promotionrule_variants_id.py
  saleor/discount/models.py
Labels: 3.17

#15560 Change `discount_promotionrule_variants` id to bigint
  saleor/discount/migrations/0069_promotionrule_variants.py
  saleor/discount/migrations/0070_alter_promotionrule_variants_id.py
  saleor/discount/migrations/0071_merge_20240307_1156.py
  saleor/discount/models.py
Labels: 3.18

#15561 Change `discount_promotionrule_variants` id to bigint
  saleor/discount/migrations/0069_promotionrule_variants.py
  saleor/discount/migrations/0070_alter_promotionrule_variants_id.py
  saleor/discount/migrations/0071_merge_20240307_1156.py
  saleor/discount/migrations/0077_merge_20240307_1217.py
  saleor/discount/models.py
Labels: 3.19

#15562 Change `discount_promotionrule_variants` id to bigint
  saleor/discount/migrations/0069_promotionrule_variants.py
  saleor/discount/migrations/0070_alter_promotionrule_variants_id.py
  saleor/discount/migrations/0071_merge_20240307_1156.py
  saleor/discount/migrations/0077_merge_20240307_1217.py
  saleor/discount/models.py
Labels: migrations perf test, skip changelog

#15549 Fix external shipping method calls on checkout lines add
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
Labels: bug, 3.19

#15550 Fix external shipping method calls on checkout lines add
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
Labels: bug, skip changelog, main

#15570 Trigger price relaculation when sale is deleted
  saleor/graphql/discount/mutations/sale/sale_channel_listing_update.py
  saleor/graphql/discount/mutations/sale/sale_delete.py
  saleor/graphql/discount/tests/mutations/test_sale_channel_listing_update.py
  saleor/graphql/product/tests/test_product_discounted_price.py
Labels: skip changelog

#15581 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  saleor/graphql/core/connection.py
  saleor/graphql/core/fields.py
  saleor/graphql/core/tests/test_graphql.py
  saleor/graphql/utils/__init__.py
Labels: test deployment, :robot: bot, skip changelog

#15585 add crit header to `JWTManager.jws_encode`
  saleor/core/jwt_manager.py
  saleor/core/tests/test_jwt_manager.py
Labels: 3.15, shopping

#15586 add crit header to `JWTManager.jws_encode`
  saleor/core/jwt_manager.py
  saleor/core/tests/test_jwt_manager.py
Labels: 3.16, shopping

#15587 add crit header to `JWTManager.jws_encode`
  saleor/core/jwt_manager.py
  saleor/core/tests/test_jwt_manager.py
Labels: 3.17, shopping

#15588 add crit header to `JWTManager.jws_encode`
  saleor/core/jwt_manager.py
  saleor/core/tests/test_jwt_manager.py
Labels: 3.18, shopping

#15589 add crit header to `JWTManager.jws_encode`
  saleor/core/jwt_manager.py
  saleor/core/tests/test_jwt_manager.py
Labels: 3.19, shopping

#15582 Fix failing migrate sales to promotions task
  saleor/discount/migrations/tasks/saleor3_16.py
Labels: 3.16

#15593 Fix failing migrate sales to promotions task
  saleor/discount/migrations/0047_migrate_sales_to_promotions.py
Labels: 3.18

#15594 Fix failing migrate sales to promotions task
  saleor/discount/migrations/0047_migrate_sales_to_promotions.py
Labels: 3.19

#15595 Fix failing migrate sales to promotions task
  saleor/discount/migrations/0047_migrate_sales_to_promotions.py
Labels: migrations perf test, skip changelog

#15602 Upgrade sentry-sdk to 1.40
  poetry.lock
  pyproject.toml
Labels: test deployment, 3.19

#15571 Add replica usages to checkout and order related queries
  saleor/checkout/calculations.py
  saleor/checkout/fetch.py
  saleor/checkout/models.py
  saleor/checkout/payment_utils.py
  saleor/checkout/utils.py
  saleor/discount/utils.py
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/types.py
  saleor/graphql/core/utils/__init__.py
  saleor/graphql/core/validators/__init__.py
  saleor/graphql/order/schema.py
  saleor/graphql/order/types.py
  saleor/graphql/order/utils.py
  saleor/graphql/shop/resolvers.py
  saleor/graphql/webhook/resolvers.py
  saleor/graphql/webhook/subscription_types.py
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/order/utils.py
  saleor/plugins/webhook/tests/test_tax_webhook.py
  saleor/product/managers.py
  saleor/product/utils/variant_prices.py
  saleor/shipping/models.py
  saleor/tax/calculations/checkout.py
  saleor/tax/calculations/order.py
  saleor/tax/utils.py
  saleor/warehouse/availability.py
  saleor/warehouse/reservations.py
Labels: skip changelog

#15605 Remove prefetched_for_webhook to legacy payload generators.
  saleor/graphql/product/bulk_mutations/collection_bulk_delete.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/mutations/collection/collection_add_products.py
  saleor/graphql/product/mutations/collection/collection_remove_products.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/graphql/product/mutations/product/product_media_delete.py
  saleor/graphql/product/mutations/product/product_media_reorder.py
  saleor/graphql/product/mutations/product/product_media_update.py
  saleor/graphql/product/mutations/product_variant/product_variant_preorder_deactivate.py
  saleor/graphql/product/mutations/product_variant/product_variant_reorder.py
  saleor/graphql/product/mutations/product_variant/product_variant_set_default.py
  saleor/graphql/product/mutations/product_variant/variant_media_assign.py
  saleor/graphql/product/mutations/product_variant/variant_media_unassign.py
  saleor/graphql/translations/mutations/product_variant_translate.py
  saleor/product/managers.py
  saleor/webhook/payloads.py
Labels: 3.19

#15607 Remove prefetched_for_webhook to legacy payload generators.
  saleor/graphql/product/bulk_mutations/collection_bulk_delete.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/mutations/collection/collection_add_products.py
  saleor/graphql/product/mutations/collection/collection_remove_products.py
  saleor/graphql/product/mutations/product/product_media_create.py
  saleor/graphql/product/mutations/product/product_media_delete.py
  saleor/graphql/product/mutations/product/product_media_reorder.py
  saleor/graphql/product/mutations/product/product_media_update.py
  saleor/graphql/product/mutations/product_variant/product_variant_preorder_deactivate.py
  saleor/graphql/product/mutations/product_variant/product_variant_reorder.py
  saleor/graphql/product/mutations/product_variant/product_variant_set_default.py
  saleor/graphql/product/mutations/product_variant/variant_media_assign.py
  saleor/graphql/product/mutations/product_variant/variant_media_unassign.py
  saleor/graphql/translations/mutations/product_variant_translate.py
  saleor/product/managers.py
  saleor/webhook/payloads.py
Labels: 3.18

#15606 Fix migrations with no reverse sql
  saleor/account/migrations/0078_add_group_channels_conf.py
  saleor/attribute/migrations/0035_assignedproductattributevalue_product_add_index.py
  saleor/discount/migrations/0055_drop_sales_from_db.py
  saleor/order/migrations/0129_alter_order_number.py
  saleor/product/migrations/0130_create_product_description_search_vector.py
  saleor/product/migrations/0131_update_ts_vector_existing_product_name.py
  saleor/product/migrations/0156_product_search_document.py
Labels: skip changelog, skip migrations perf test

#15616 Fix failing tasks in `migrate_sales_to_promotions_task`
  saleor/discount/migrations/tasks/saleor3_16.py
Labels: 3.16

#15611 Add test for cache builder for shipping methods for checkout
  saleor/webhook/transport/tests/test_utils.py
Labels: 3.18

#15619 Handle `AuthenticationError` in `OpenIDConnectPlugin`
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
Labels: 3.14

#15620 Handle `AuthenticationError` in `OpenIDConnectPlugin`
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
Labels: 3.15

#15621 Handle `AuthenticationError` in `OpenIDConnectPlugin`
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
Labels: 3.16

#15622 Handle AuthenticationErrors in OpenIDConnectPlugin
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
Labels: 3.18

#15623 Handle AuthenticationErrors in OpenIDConnectPlugin
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
Labels: 3.19

#15630 Add lock on PreorderAllocation on deactivation preorders on variant
  saleor/warehouse/management.py
Labels: 3.15

#15632 Add lock on PreorderAllocation on deactivation preorders on variant
  saleor/warehouse/management.py
Labels: 3.16

#15631 Add lock on PreorderAllocation on deactivation preorders on variant
  saleor/warehouse/management.py
Labels: 3.17

#15627 Add lock on `PreorderAllocation` on deactivation preorders on variant
  saleor/warehouse/management.py
Labels: skip changelog

#15604 Add replica usage to permissions related queries
  saleor/core/auth_backend.py
  saleor/core/jwt.py
  saleor/graphql/account/resolvers.py
  saleor/graphql/account/types.py
  saleor/graphql/account/utils.py
  saleor/graphql/app/resolvers.py
  saleor/graphql/shop/types.py
  saleor/permission/enums.py
  saleor/site/patch_sites.py
Labels: skip changelog

#15615 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
Labels: test deployment, :robot: bot, skip changelog

#15625 Fix cache for shipping methods main
  saleor/checkout/tests/test_calculations.py
  saleor/plugins/webhook/plugin.py
  saleor/tests/fixtures.py
  saleor/webhook/transport/shipping.py
  saleor/webhook/transport/tests/test_utils.py
Labels: skip changelog, main

#15626 Fix cache for shipping methods
  saleor/checkout/tests/test_calculations.py
  saleor/plugins/webhook/plugin.py
  saleor/tests/fixtures.py
  saleor/webhook/transport/shipping.py
  saleor/webhook/transport/tests/test_utils.py
Labels: 3.19

#15636 Add decorator prevent_sync_event_circular_query to checkout.deliveryMethod
  saleor/graphql/checkout/types.py
Labels: bug, 3.18

#15641 Add decorator prevent_sync_event_circular_query to checkout.deliveryMethod
  saleor/graphql/checkout/types.py
Labels: bug, 3.19

#15610 add `taxConfiguration` to `Channel` for tax app calculation precision.
  CHANGELOG.md
  saleor/graphql/channel/tests/queries/test_channel.py
  saleor/graphql/channel/types.py
  saleor/graphql/schema.graphql
Labels: test deployment, channel, main, shopping

#15660 Revert "Add decorator prevent_sync_event_circular_query to checkout.deliveryMethod"
  saleor/graphql/checkout/types.py
Labels: 3.18

#15659 Revert "Add decorator prevent_sync_event_circular_query to checkout.deliveryMethod"
  saleor/graphql/checkout/types.py
Labels: 3.19

#15657 add `taxConfiguration` to `Channel` for Avalara tax calculation
  saleor/graphql/channel/tests/queries/test_channel.py
  saleor/graphql/channel/types.py
  saleor/graphql/schema.graphql
Labels: channel, 3.18, shopping

#15658 add `taxConfiguration` to `Channel` for Avalara tax calculation
  saleor/graphql/channel/tests/queries/test_channel.py
  saleor/graphql/channel/types.py
  saleor/graphql/schema.graphql
Labels: channel, 3.19, shopping

#15662 Save discounted_price for ProductVariantBulkUpdate
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
Labels: 3.19

#15647 Raise 404 when the image for thumbnail creation cannot be open
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/views.py
Labels: 3.14

#15646 Raise 404 when the image for thumbnail creation cannot be open
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/views.py
Labels: 3.15

#15645 Raise 404 when the image for thumbnail creation cannot be open
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/views.py
Labels: 3.16

#15648 Raise 404 when the image for thumbnail creation cannot be open
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/views.py
Labels: 3.17

#15649 Raise 404 when the image for thumbnail creation cannot be open
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/views.py
Labels: 3.18

#15634 Raise 404 when the image for thumbnail creation cannot be open
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/views.py
Labels: 3.19

#15644 Raise 404 when the image for thumbnail creation cannot be open
  saleor/thumbnail/tests/test_views.py
  saleor/thumbnail/views.py
Labels: skip changelog

#15661 Fix attribute value assotiation for multiple attributes
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/tests/fixtures.py
Labels: 3.19

#15663 Fix attribute value assotiation for multiple attributes
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/tests/fixtures.py
Labels: skip changelog

#15664 Fix attribute value assotiation for multiple attributes
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/tests/fixtures.py
Labels: 3.18

#15665 Fix attribute value assotiation for multiple attributes
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/tests/fixtures.py
Labels: 3.17

#15667 Fix attribute value assotiation for multiple attributes
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/tests/fixtures.py
Labels: 3.16

#15668 Fix attribute value assotiation for multiple attributes
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
  saleor/tests/fixtures.py
Labels: 3.15

#15643 Handle errors in `authenticate_user` for `OpenIDConnectPlugin`
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
Labels: 3.19

#15674 Handle errors in authenticate_user for OpenIDConnectPlugin
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
Labels: 3.14

#15673 Handle errors in authenticate_user for OpenIDConnectPlugin
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
Labels: 3.15

#15672 Handle errors in authenticate_user for OpenIDConnectPlugin
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
Labels: 3.16

#15675 Handle errors in authenticate_user for OpenIDConnectPlugin
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
Labels: 3.17

#15676 Handle errors in authenticate_user for OpenIDConnectPlugin
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
Labels: 3.18

#15671 Handle errors in authenticate_user for OpenIDConnectPlugin
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/openid_connect/tests/test_plugin.py
Labels: skip changelog

#15666 Fix typos
  saleor/graphql/account/types.py
  saleor/graphql/app/types.py
  saleor/graphql/attribute/descriptions.py
  saleor/graphql/channel/mutations/channel_create.py
  saleor/graphql/channel/types.py
  saleor/graphql/core/types/common.py
  saleor/graphql/notifications/mutations/external_notification_trigger.py
  saleor/graphql/schema.graphql
  saleor/graphql/shop/types.py
Labels: skip changelog

#15683 Use more readable version of "sleep forever"
  .devcontainer/docker-compose.yml
Labels: skip changelog, skip migrations perf test

#15651 Add allow_writer context manager
  saleor/checkout/calculations.py
  saleor/checkout/payment_utils.py
  saleor/checkout/utils.py
  saleor/core/db/connection.py
  saleor/core/db/tests/__init__.py
  saleor/core/db/tests/test_connection.py
  saleor/discount/utils.py
  saleor/graphql/account/mutations/authentication/set_password.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/core/connection.py
  saleor/graphql/core/dataloaders.py
  saleor/graphql/core/mutations.py
  saleor/graphql/meta/mutations/base.py
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/mutations/digital_contents.py
  saleor/order/calculations.py
  saleor/settings.py
Labels: skip changelog

#15682 Fix relation between order and click and collect address
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/order/migrations/0172_update_order_cc_addresses.py
  saleor/order/migrations/tasks/saleor3_14.py
Labels: 3.14

#15688 Fix incorrect assigment of the shipping address for c&c
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: 3.14

#15689 Fix incorrect assigment of the shipping address
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: 3.15

#15690 Fix incorrect assigment of the shipping address
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: 3.16

#15692 Fix incorrect assigment of the shipping address
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: 3.18

#15693 Fix incorrect assigment of the shipping address
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: 3.19

#15694 Fix incorrect assigment of the shipping address
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: skip changelog, main

#15669 Save discounted_price for ProduvtVariantBulkUpdate
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
Labels: skip changelog

#15652 Add `translatable_content` to translation types.
  CHANGELOG.md
  saleor/graphql/schema.graphql
  saleor/graphql/translations/tests/test_translations.py
  saleor/graphql/translations/types.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_translation_subscription.py
Labels: 3.14, translations, merchant

#15700 Add `translatable_content` to translation types.
  saleor/graphql/schema.graphql
  saleor/graphql/translations/tests/test_translations.py
  saleor/graphql/translations/types.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_translation_subscription.py
Labels: 3.19

#15701 Add `translatable_content` to translation types.
  saleor/graphql/schema.graphql
  saleor/graphql/translations/tests/test_translations.py
  saleor/graphql/translations/types.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_translation_subscription.py
Labels: 3.18

#15702 Add `translatable_content` to translation types.
  saleor/graphql/schema.graphql
  saleor/graphql/translations/tests/test_translations.py
  saleor/graphql/translations/types.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_translation_subscription.py
Labels: 3.17

#15703 Add `translatable_content` to translation types.
  saleor/graphql/discount/dataloaders.py
  saleor/graphql/schema.graphql
  saleor/graphql/translations/tests/test_translations.py
  saleor/graphql/translations/types.py
  saleor/plugins/webhook/tests/subscription_webhooks/fixtures.py
  saleor/plugins/webhook/tests/subscription_webhooks/subscription_queries.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_translation_subscription.py
Labels: 3.16

#15685 Fix relation between order and click and collect address
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/order/migrations/0172_update_order_cc_addresses.py
  saleor/order/migrations/0176_merge_20240325_1315.py
  saleor/order/migrations/tasks/saleor3_15.py
Labels: 3.15

#15686 Fix relation between order and click and collect address
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/order/migrations/0172_update_order_cc_addresses.py
  saleor/order/migrations/0176_merge_20240325_1315.py
  saleor/order/migrations/0177_merge_20240325_1329.py
  saleor/order/migrations/tasks/saleor3_16.py
Labels: 3.16

#15687 Fix relation between order and click and collect address
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/order/migrations/0172_update_order_cc_addresses.py
  saleor/order/migrations/0176_merge_20240325_1315.py
  saleor/order/migrations/0177_merge_20240325_1329.py
  saleor/order/migrations/0180_merge_20240325_1333.py
  saleor/order/migrations/tasks/saleor3_17.py
Labels: 3.17

#15695 Fix relation between order and click and collect address
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/utils/__init__.py
  saleor/graphql/utils/sorting.py
  saleor/order/migrations/0172_update_order_cc_addresses.py
  saleor/order/migrations/0176_merge_20240325_1315.py
  saleor/order/migrations/0177_merge_20240325_1329.py
  saleor/order/migrations/0180_merge_20240325_1333.py
  saleor/order/migrations/0182_merge_20240325_1338.py
  saleor/order/migrations/tasks/saleor3_18.py
Labels: 3.18

#15696 Fix relation between order and click and collect address
  saleor/celeryconf.py
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/order/migrations/0172_update_order_cc_addresses.py
  saleor/order/migrations/0176_merge_20240325_1315.py
  saleor/order/migrations/0177_merge_20240325_1329.py
  saleor/order/migrations/0180_merge_20240325_1333.py
  saleor/order/migrations/0182_merge_20240325_1338.py
  saleor/order/migrations/0184_merge_0182_merge_20240325_1338_0183_order_tax_error.py
  saleor/order/migrations/tasks/saleor3_19.py
Labels: 3.19

#15711 Fix failing exif data validation for images
  saleor/thumbnail/tests/test_utils.py
  saleor/thumbnail/utils.py
Labels: 3.15

#15710 Fix failing exif data validation for images
  saleor/thumbnail/tests/test_utils.py
  saleor/thumbnail/utils.py
Labels: 3.16

#15709 Fix failing exif data validation for images
  saleor/thumbnail/tests/test_utils.py
  saleor/thumbnail/utils.py
Labels: 3.17

#15707 Fix failing exif data validation for images
  saleor/thumbnail/tests/test_utils.py
  saleor/thumbnail/utils.py
Labels: 3.19

#15681 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
Labels: test deployment, :robot: bot, skip changelog

#15713 Use dataloaders for default account addresses
  saleor/graphql/account/types.py
Labels: skip changelog

#15697 Fix relation between order and click and collect address
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/order/migrations/0172_update_order_cc_addresses.py
  saleor/order/migrations/0176_merge_20240325_1315.py
  saleor/order/migrations/0177_merge_20240325_1329.py
  saleor/order/migrations/0180_merge_20240325_1333.py
  saleor/order/migrations/0182_merge_20240325_1338.py
  saleor/order/migrations/0184_merge_0182_merge_20240325_1338_0183_order_tax_error.py
  saleor/order/migrations/tasks/saleor3_19.py
Labels: migrations perf test, skip changelog

#15714 Refactor line weight calculation to reuse DB queries
  saleor/checkout/complete_checkout.py
  saleor/checkout/fetch.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_cart.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/order/models.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
  saleor/plugins/manager.py
  saleor/shipping/models.py
Labels: skip changelog

#15718 Turn off Jaeger during tests.
  saleor/settings.py
  saleor/tests/settings.py
Labels: skip changelog

#15684 Fix failing exif data validation for images
  saleor/thumbnail/tests/test_utils.py
  saleor/thumbnail/utils.py
Labels: skip changelog

#15717 Fix filter to check if checkout exist with associated checkout line
  saleor/discount/migrations/tasks/saleor3_16.py
Labels: 3.16

#15724 Turn off Jaeger during tests.
  saleor/settings.py
  saleor/tests/settings.py
Labels: 3.14

#15723 Turn off Jaeger during tests.
  saleor/settings.py
  saleor/tests/settings.py
Labels: 3.15

#15722 Turn off Jaeger during tests.
  saleor/settings.py
  saleor/tests/settings.py
Labels: 3.16

#15721 Turn off Jaeger during tests.
  saleor/settings.py
  saleor/tests/settings.py
Labels: 3.17

#15720 Turn off Jaeger during tests.
  saleor/settings.py
  saleor/tests/settings.py
Labels: 3.18

#15719 Turn off Jaeger during tests.
  saleor/settings.py
  saleor/tests/settings.py
Labels: 3.19
