Repository saleor/saleor, pull requests merged in 2024-05, with the labels that each got.

#15912 Fix passing args to list_stored_payment_methods
  saleor/graphql/account/tests/queries/test_me.py
  saleor/graphql/account/types.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
Labels: 3.19

#15911 Fix passing args to list_stored_payment_methods
  saleor/graphql/account/tests/queries/test_me.py
  saleor/graphql/account/types.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
Labels: skip changelog

#15847 Optimize memory collection for plugin manager
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/checkout/mutations/checkout_add_promo_code.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/deprecated/test_checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_method_update.py
  saleor/graphql/checkout/types.py
  saleor/graphql/context.py
  saleor/graphql/core/dataloaders.py
  saleor/graphql/core/tests/test_view.py
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/graphql/tests/test_context.py
  saleor/graphql/views.py
  saleor/graphql/webhook/resolvers.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_get_checkout_line_tax_rate_for_product_with_charge_taxes_set_to_false.yaml
  saleor/plugins/avatax/tests/conftest.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/tests/e2e/apps/__init__.py
  saleor/tests/e2e/apps/utils/__init__.py
  saleor/tests/e2e/apps/utils/app_create.py
  saleor/tests/e2e/checkout/shipping/__init__.py
  saleor/tests/e2e/checkout/shipping/cassettes/test_use_external_shipping_methods_in_checkout/test_use_external_shipping_methods_in_checkout_core_1652.yaml
  saleor/tests/e2e/checkout/shipping/test_checkout_invalidate_price_based_shipping_on_voucher_add.py
  saleor/tests/e2e/checkout/shipping/test_use_external_shipping_methods_in_checkout.py
  saleor/tests/e2e/checkout/test_checkout_with_shipping_method_with_min_order_value.py
  saleor/tests/e2e/checkout/utils/checkout_add_promo_code.py
  saleor/tests/e2e/checkout/utils/checkout_complete.py
  saleor/tests/e2e/checkout/utils/checkout_create.py
  saleor/tests/e2e/shipping_zone/utils/shipping_method_channel_listing.py
  saleor/tests/e2e/test_utils.py
  saleor/tests/e2e/utils.py
  saleor/tests/e2e/webhooks/__init__.py
  saleor/tests/e2e/webhooks/utils.py
  saleor/tests/fixtures.py
Labels: test deployment, 3.18

#15909 Optimize memory collection for plugin manager
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/checkout/mutations/checkout_add_promo_code.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/deprecated/test_checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_method_update.py
  saleor/graphql/checkout/types.py
  saleor/graphql/context.py
  saleor/graphql/core/dataloaders.py
  saleor/graphql/core/tests/test_view.py
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/graphql/tests/test_context.py
  saleor/graphql/views.py
  saleor/graphql/webhook/resolvers.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_get_checkout_line_tax_rate_for_product_with_charge_taxes_set_to_false.yaml
  saleor/plugins/avatax/tests/conftest.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/tests/e2e/checkout/shipping/test_checkout_invalidate_price_based_shipping_on_voucher_add.py
  saleor/tests/e2e/checkout/utils/checkout_add_promo_code.py
  saleor/tests/fixtures.py
Labels: 3.19

#15910 Optimize memory collection for plugin manager
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/checkout/mutations/checkout_add_promo_code.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/deprecated/test_checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_method_update.py
  saleor/graphql/checkout/types.py
  saleor/graphql/context.py
  saleor/graphql/core/dataloaders.py
  saleor/graphql/core/tests/test_view.py
  saleor/graphql/plugins/tests/test_mutation_plugin_update.py
  saleor/graphql/tests/test_context.py
  saleor/graphql/views.py
  saleor/graphql/webhook/resolvers.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_get_checkout_line_tax_rate_for_product_with_charge_taxes_set_to_false.yaml
  saleor/plugins/avatax/tests/conftest.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/tests/e2e/checkout/shipping/test_checkout_invalidate_price_based_shipping_on_voucher_add.py
  saleor/tests/e2e/checkout/utils/checkout_add_promo_code.py
  saleor/tests/fixtures.py
Labels: skip changelog

#15908 Save Atobarai gateway response in transaction object
  saleor/payment/gateways/np_atobarai/api.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/payment/gateways/np_atobarai/api_types.py
  saleor/payment/gateways/np_atobarai/tests/test_api.py
Labels: 3.14

#15913 Bump unsupported GitHub action versions
  .github/workflows/pytest.yml
  .github/workflows/test-migrations-compatibility.yml
Labels: technical debt, skip changelog

#15929 Add colon to valid custom header value.
  saleor/graphql/schema.graphql
  saleor/graphql/webhook/mutations/webhook_create.py
  saleor/webhook/tests/test_webhook_validators.py
  saleor/webhook/validators.py
Labels: bug, webhooks, skip changelog, merchant

#15918 Fix `CheckoutInfoByCheckoutTokenLoader` for checkout with voucher that does not exist
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/checkout/tests/test_checkout.py
Labels: 3.18

#15766 Optimise `ProductVariant.stocks` query.
  saleor/graphql/product/bulk_mutations/product_variant_stocks_create.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/dataloaders.py
  saleor/graphql/warehouse/dataloaders.py
Labels: performance, 3.14, merchant

#15893 Optimise `productVariant.stocks` query.
  saleor/graphql/product/bulk_mutations/product_variant_stocks_create.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/dataloaders.py
  saleor/graphql/warehouse/dataloaders.py
Labels: performance, skip changelog, main, merchant

#15895 Optimise `productVariant.stocks` query.
  saleor/graphql/product/bulk_mutations/product_variant_stocks_create.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/dataloaders.py
  saleor/graphql/warehouse/dataloaders.py
Labels: performance, 3.18, merchant

#15896 Optimise `productVariant.stocks` query.
  saleor/graphql/product/bulk_mutations/product_variant_stocks_create.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/dataloaders.py
  saleor/graphql/warehouse/dataloaders.py
Labels: performance, 3.17, merchant

#15897 Optimise `productVariant.stocks` query.
  saleor/graphql/product/bulk_mutations/product_variant_stocks_create.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/dataloaders.py
  saleor/graphql/warehouse/dataloaders.py
Labels: performance, 3.16, merchant

#15898 Optimise `productVariant.stocks` query.
  saleor/graphql/product/bulk_mutations/product_variant_stocks_create.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_delete.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/queries/test_product_variant_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/dataloaders.py
  saleor/graphql/warehouse/dataloaders.py
Labels: performance, 3.15, merchant

#15930 Add colon to valid custom header value.
  saleor/graphql/schema.graphql
  saleor/graphql/webhook/mutations/webhook_create.py
  saleor/webhook/tests/test_webhook_validators.py
  saleor/webhook/validators.py
Labels: bug, webhooks, 3.19

#15937 Remove dataloader finalizer
  saleor/graphql/core/dataloaders.py
Labels: 3.18

#15939 Remove dataloader finalizer
  saleor/graphql/core/dataloaders.py
Labels: skip changelog

#15923 Save Atobarai gateway response in transaction object
  saleor/payment/gateways/np_atobarai/api.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/payment/gateways/np_atobarai/api_types.py
  saleor/payment/gateways/np_atobarai/tests/test_api.py
Labels: 3.15

#15925 Save Atobarai gateway response in transaction object
  saleor/payment/gateways/np_atobarai/api.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/payment/gateways/np_atobarai/api_types.py
  saleor/payment/gateways/np_atobarai/tests/test_api.py
Labels: 3.16

#15924 Save Atobarai gateway response in transaction object
  saleor/payment/gateways/np_atobarai/api.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/payment/gateways/np_atobarai/api_types.py
  saleor/payment/gateways/np_atobarai/tests/test_api.py
Labels: 3.17

#15926 Save Atobarai gateway response in transaction object
  saleor/payment/gateways/np_atobarai/api.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/payment/gateways/np_atobarai/api_types.py
  saleor/payment/gateways/np_atobarai/tests/test_api.py
Labels: 3.18

#15928 Save Atobarai gateway response in transaction object
  saleor/payment/gateways/np_atobarai/api.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/payment/gateways/np_atobarai/api_types.py
  saleor/payment/gateways/np_atobarai/tests/test_api.py
Labels: 3.19

#15927 Save Atobarai gateway response in transaction object
  saleor/payment/gateways/np_atobarai/api.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/payment/gateways/np_atobarai/api_types.py
  saleor/payment/gateways/np_atobarai/tests/test_api.py
Labels: skip changelog

#15934 Fix CheckoutInfoByCheckoutTokenLoader for checkout with voucher that does not exist
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/checkout/tests/test_checkout.py
Labels: 3.17

#15933 Fix CheckoutInfoByCheckoutTokenLoader for checkout with voucher that does not exist
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/checkout/tests/test_checkout.py
Labels: skip changelog

#15886 Fix transactionUpdate/transactionCreate with empty metadata
  saleor/graphql/payment/mutations.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
Labels: 3.14

#15888 Fix transactionUpdate/transactionCreate with empty metadata
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
Labels: 3.16

#15889 Fix transactionUpdate/transactionCreate with empty metadata
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
Labels: 3.17

#15890 Fix transactionUpdate/transactionCreate with empty metadata
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
Labels: 3.18

#15891 Fix transactionUpdate/transactionCreate with empty metadata
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
Labels: 3.19

#15877 Valid address items extension.
  CHANGELOG.md
  saleor/account/i18n.py
  saleor/account/i18n_valid_address_extension.py
  saleor/account/tests/test_account.py
  saleor/graphql/warehouse/tests/mutations/test_warehouse_create.py
Labels: address, merchant

#15943 add missing filtering for active plugins on manager
  saleor/plugins/manager.py
  saleor/plugins/tests/test_manager.py
Labels: bug, 3.18, shopping

#15945 add missing filtering for active plugins on manager
  saleor/plugins/manager.py
  saleor/plugins/tests/test_manager.py
Labels: bug, 3.15, shopping

#15946 add missing filtering for active plugins on manager
  saleor/plugins/manager.py
  saleor/plugins/tests/test_manager.py
Labels: bug, 3.16, shopping

#15947 add missing filtering for active plugins on manager
  saleor/plugins/manager.py
  saleor/plugins/tests/test_manager.py
Labels: bug, 3.17, shopping

#15948 add missing filtering for active plugins on manager
  saleor/plugins/manager.py
  saleor/plugins/tests/test_manager.py
Labels: bug, 3.19, shopping

#15949 add missing filtering for active plugins on manager
  saleor/plugins/manager.py
  saleor/plugins/tests/test_manager.py
Labels: bug, skip changelog, main, shopping

#15880 Fix discounts resolver to work like in docs
  saleor/graphql/core/types/taxes.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.14

#15881 Fix discounts resolver to work like in docs
  saleor/graphql/core/types/taxes.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.15

#15882 Fix discounts resolver to work like in docs
  saleor/graphql/core/types/taxes.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.16

#15883 Fix discounts resolver to work like in docs
  saleor/graphql/core/types/taxes.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.17

#15884 Fix discounts resolver to work like in docs
  saleor/graphql/core/types/taxes.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.18

#15960 Fix discounts resolver to work like in docs
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.19

#15959 Fix discounts resolver to work like in docs
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: skip changelog, main

#15950 Handle zero subtotal case when propagating order discount to lines.
  saleor/order/base_calculations.py
  saleor/order/tests/test_apply_order_discount.py
Labels: bug, skip changelog, promotions, merchant

#15957 Handle zero subtotal case when propagating order discount to lines.
  saleor/order/base_calculations.py
  saleor/order/tests/test_discount_calculations.py
Labels: bug, promotions, 3.19, merchant

#15967 Allow deleting and updating order lines without allocation
  saleor/graphql/order/mutations/order_line_delete.py
  saleor/graphql/order/mutations/order_line_update.py
  saleor/graphql/order/tests/mutations/test_order_line_delete.py
  saleor/graphql/order/tests/mutations/test_order_line_update.py
Labels: skip changelog

#15952 Add `unique_type` to discount line models - migration compatibility
  saleor/discount/migrations/0073_add_unique_type.py
  saleor/discount/migrations/0074_add_index_for_unique_type.py
  saleor/discount/migrations/0075_add_unique_type_constraint.py
  saleor/discount/models.py
Labels: migration, 3.18, discount

#15951 Add `unique_type` to discount line models - migration compatibility
  saleor/discount/migrations/0073_add_unique_type.py
  saleor/discount/migrations/0074_add_index_for_unique_type.py
  saleor/discount/migrations/0075_add_unique_type_constraint.py
  saleor/discount/migrations/0078_add_unique_type.py
  saleor/discount/migrations/0079_add_index_for_unique_type.py
  saleor/discount/migrations/0080_add_unique_type_constraint.py
  saleor/discount/migrations/0082_merge_20240509_1550.py
  saleor/discount/migrations/0083_auto_20240510_0838.py
Labels: migration, skip changelog, discount

#15958 Fix mixing up attibute values because of the same slug value
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
Labels: bug, 3.15

#15977 Add product name to gift line.
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_order.py
  saleor/discount/utils.py
Labels: bug, test deployment, promotions, 3.19

#15980 Fix subtotal discount propagation.
  saleor/order/base_calculations.py
  saleor/order/tests/test_apply_order_discount.py
Labels: bug, promotions, 3.19

#15942 Calculate order promotions in draft order
  saleor/checkout/utils.py
  saleor/discount/interface.py
  saleor/discount/migrations/0073_add_unique_type.py
  saleor/discount/migrations/0074_add_index_for_unique_type.py
  saleor/discount/migrations/0075_add_unique_type_constraint.py
  saleor/discount/migrations/0078_add_unique_type.py
  saleor/discount/migrations/0079_add_index_for_unique_type.py
  saleor/discount/migrations/0080_add_unique_type_constraint.py
  saleor/discount/migrations/0082_merge_20240509_1550.py
  saleor/discount/migrations/0083_auto_20240510_0838.py
  saleor/discount/tests/test_utils/fixtures.py
  saleor/discount/tests/test_utils/test_copy_unit_discount_data_to_order_line.py
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_checkout.py
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_order.py
  saleor/discount/tests/test_utils/test_fetch_promotion_rules_for_checkout.py
  saleor/discount/utils.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/discount/utils.py
  saleor/graphql/order/filters.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/order_update.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/tests/mutations/test_order_discount.py
  saleor/graphql/order/tests/mutations/test_order_line_update.py
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/graphql/order/tests/queries/test_draft_order_with_filter.py
  saleor/graphql/order/types.py
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/fetch.py
  saleor/order/tests/benchmark/__init__.py
  saleor/order/tests/benchmark/test_fetch_order_prices.py
  saleor/order/tests/test_apply_order_discount.py
  saleor/order/tests/test_fetch.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/order/utils.py
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_order_total_gift_promotion.yaml
  saleor/plugins/avatax/tests/cassettes/test_avatax/test_calculate_order_total_order_promotion.yaml
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/tax/calculations/order.py
  saleor/tax/tests/test_checkout_calculations.py
  saleor/tax/tests/test_order_calculations.py
  saleor/tests/e2e/orders/discounts/test_order_product_with_percentage_promotion.py
  saleor/tests/e2e/orders/discounts/test_order_products_on_percentage_sale.py
  saleor/tests/e2e/orders/discounts/test_order_products_on_promotion_and_manual_order_discount.py
  saleor/tests/fixtures.py
  saleor/tests/utils.py
Labels: test deployment, promotions, 3.19, merchant

#15976 Order line operations without allocation
  saleor/graphql/order/mutations/order_line_delete.py
  saleor/graphql/order/mutations/order_line_update.py
  saleor/graphql/order/tests/mutations/test_order_line_delete.py
  saleor/graphql/order/tests/mutations/test_order_line_update.py
Labels: skip changelog, 3.19

#15984 Fix mixing up attribute values because of the same slug value
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/utils.py
Labels: bug, skip changelog, main

#15983 Fix mixing up attibute values because of the same slug value
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/utils.py
Labels: bug, 3.19

#15982 Fix mixing up attibute values because of the same slug value
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
  saleor/graphql/attribute/tests/test_utils.py
  saleor/graphql/attribute/utils.py
Labels: bug, 3.18

#15979 Fix mixing up attibute values because of the same slug value
  saleor/attribute/tests/test_utils.py
  saleor/attribute/utils.py
Labels: bug, 3.16

#15936 Use read replica in tests
  conftest.py
  saleor/checkout/fetch.py
  saleor/checkout/utils.py
  saleor/discount/utils.py
  saleor/graphql/checkout/dataloaders.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
  saleor/graphql/order/types.py
  saleor/order/base_calculations.py
  saleor/order/calculations.py
  saleor/order/fetch.py
  saleor/plugins/views.py
  saleor/settings.py
  saleor/shipping/utils.py
  saleor/tests/settings.py
  saleor/tests/test_db_connections.py
  saleor/tests/utils.py
Labels: skip changelog

#15973 Optimize category-related resolvers.
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_category.py
  saleor/graphql/product/types/categories.py
  saleor/product/migrations/0187_productvariantchannellisting_product_pro_price_a_fb6bd3_gin.py
  saleor/product/models.py
Labels: 3.14

#15974 Optimize category-related resolvers.
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_category.py
  saleor/graphql/product/types/categories.py
  saleor/product/migrations/0187_productvariantchannellisting_product_pro_price_a_fb6bd3_gin.py
  saleor/product/migrations/0188_merge_20240513_1023.py
  saleor/product/models.py
Labels: 3.15

#15961 Optimize category-related resolvers.
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_category.py
  saleor/graphql/product/types/categories.py
  saleor/product/migrations/0187_productvariantchannellisting_product_pro_price_a_fb6bd3_gin.py
  saleor/product/migrations/0188_merge_20240513_1023.py
  saleor/product/migrations/0190_merge_20240513_1042.py
  saleor/product/models.py
Labels: 3.16

#15963 Optimize category-related resolvers.
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_category.py
  saleor/graphql/product/types/categories.py
  saleor/product/migrations/0187_productvariantchannellisting_product_pro_price_a_fb6bd3_gin.py
  saleor/product/migrations/0188_merge_20240513_1023.py
  saleor/product/migrations/0190_merge_20240513_1042.py
  saleor/product/migrations/0192_merge_20240513_1055.py
  saleor/product/models.py
Labels: 3.17

#15725 Optimize category-related resolvers.
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_category.py
  saleor/graphql/product/types/categories.py
  saleor/product/migrations/0187_productvariantchannellisting_product_pro_price_a_fb6bd3_gin.py
  saleor/product/migrations/0188_merge_20240513_1023.py
  saleor/product/migrations/0190_merge_20240513_1042.py
  saleor/product/migrations/0192_merge_20240513_1055.py
  saleor/product/migrations/0193_merge_20240513_1105.py
  saleor/product/models.py
Labels: 3.18

#15964 Optimize category-related resolvers.
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_category.py
  saleor/graphql/product/types/categories.py
  saleor/product/migrations/0187_productvariantchannellisting_product_pro_price_a_fb6bd3_gin.py
  saleor/product/migrations/0188_merge_20240513_1023.py
  saleor/product/migrations/0190_merge_20240513_1042.py
  saleor/product/migrations/0192_merge_20240513_1055.py
  saleor/product/migrations/0193_merge_20240513_1105.py
  saleor/product/models.py
Labels: 3.19

#15965 Optimize category-related resolvers.
  saleor/graphql/product/dataloaders/products.py
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/benchmark/test_category.py
  saleor/graphql/product/types/categories.py
  saleor/product/migrations/0187_productvariantchannellisting_product_pro_price_a_fb6bd3_gin.py
  saleor/product/migrations/0188_merge_20240513_1023.py
  saleor/product/migrations/0190_merge_20240513_1042.py
  saleor/product/migrations/0192_merge_20240513_1055.py
  saleor/product/migrations/0193_merge_20240513_1105.py
  saleor/product/models.py
Labels: skip changelog, main, skip migrations perf test

#15999 Fix TypeError when availableActions null is provided to transactionCreate
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
Labels: bug, skip changelog, main

#15988 Handle concurrency `checkoutPaymentCreate` and `checkoutComplete`
  saleor/celeryconf.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0065_checkout_completing_started_at.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/payment/mutations/payment/checkout_payment_create.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/graphql/schema.graphql
  saleor/payment/error_codes.py
  saleor/payment/migrations/0056_fix_invalid_atobarai_payments.py
  saleor/payment/migrations/0057_merge_20240514_0825.py
  saleor/payment/migrations/tasks/__init__.py
  saleor/payment/migrations/tasks/saleor3_15.py
  saleor/settings.py
Labels: 3.15

#15990 Handle concurrency `checkoutPaymentCreate` and `checkoutComplete`
  saleor/celeryconf.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0065_checkout_completing_started_at.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/payment/mutations/payment/checkout_payment_create.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/graphql/schema.graphql
  saleor/payment/error_codes.py
  saleor/payment/migrations/0056_fix_invalid_atobarai_payments.py
  saleor/payment/migrations/0057_merge_20240514_0825.py
  saleor/payment/migrations/tasks/__init__.py
  saleor/payment/migrations/tasks/saleor3_16.py
  saleor/settings.py
Labels: 3.16

#15991 Handle concurrency `checkoutPaymentCreate` and `checkoutComplete`
  saleor/celeryconf.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0065_checkout_completing_started_at.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/payment/mutations/payment/checkout_payment_create.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/graphql/schema.graphql
  saleor/payment/error_codes.py
  saleor/payment/migrations/0056_fix_invalid_atobarai_payments.py
  saleor/payment/migrations/0057_merge_20240514_0825.py
  saleor/payment/migrations/tasks/__init__.py
  saleor/payment/migrations/tasks/saleor3_17.py
  saleor/settings.py
Labels: 3.17

#15992 Handle concurrency `checkoutPaymentCreate` and `checkoutComplete`
  saleor/celeryconf.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0065_checkout_completing_started_at.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/payment/mutations/payment/checkout_payment_create.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/graphql/schema.graphql
  saleor/payment/error_codes.py
  saleor/payment/migrations/0056_fix_invalid_atobarai_payments.py
  saleor/payment/migrations/0057_merge_20240514_0825.py
  saleor/payment/migrations/tasks/__init__.py
  saleor/payment/migrations/tasks/saleor3_18.py
  saleor/settings.py
Labels: 3.18

#15993 Handle concurrency `checkoutPaymentCreate` and `checkoutComplete`
  saleor/celeryconf.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0065_checkout_completing_started_at.py
  saleor/checkout/migrations/0069_merge_20240514_1008.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/payment/mutations/payment/checkout_payment_create.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/graphql/schema.graphql
  saleor/payment/error_codes.py
  saleor/payment/migrations/0056_fix_invalid_atobarai_payments.py
  saleor/payment/migrations/0057_merge_20240514_0825.py
  saleor/payment/migrations/tasks/__init__.py
  saleor/payment/migrations/tasks/saleor3_19.py
  saleor/settings.py
Labels: 3.19

#15987 Add product name to gift line.
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_order.py
  saleor/discount/utils.py
Labels: bug, skip changelog, promotions

#15989 Fix subtotal discount propagation.
  saleor/order/base_calculations.py
  saleor/order/tests/test_apply_order_discount.py
Labels: bug, skip changelog, promotions

#16007 Unassign shipping address on CheckoutDeliveryMethodUpdate from C&C
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: bug, 3.15

#16006 Unassign shipping address on CheckoutDeliveryMethodUpdate from C&C
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: bug, 3.16

#16005 Unassign shipping address on CheckoutDeliveryMethodUpdate from C&C
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: bug, 3.17

#16004 Unassign shipping address on CheckoutDeliveryMethodUpdate from C&C
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: bug, 3.18

#16002 Unassign shipping address on CheckoutDeliveryMethodUpdate from C&C
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: bug, skip changelog, main

#15997 Fix order from draft confirmation
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/order/actions.py
  saleor/order/tests/test_actions.py
Labels: bug, 3.19

#15998 Fix order from draft confirmation
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/order/actions.py
  saleor/order/tests/test_actions.py
Labels: bug, skip changelog, main

#16016 Fix order status depending on flag
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
Labels: 3.19

#16021 Fix order status depending on flag
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
Labels: skip changelog, main

#16001 Allow query checkout for all users.
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/queries/test_checkout.py
  saleor/graphql/meta/tests/test_meta_queries.py
  saleor/graphql/schema.graphql
Labels: checkout, 3.18, shopping

#16009 Allow query checkout for all users.
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/queries/test_checkout.py
  saleor/graphql/meta/tests/test_meta_queries.py
  saleor/graphql/schema.graphql
Labels: checkout, 3.19, shopping

#16010 Allow query checkout for all users.
  CHANGELOG.md
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/queries/test_checkout.py
  saleor/graphql/meta/tests/test_meta_queries.py
  saleor/graphql/schema.graphql
Labels: checkout, main, skip migrations perf test, shopping

#16011 Allow query checkout for all users.
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/queries/test_checkout.py
  saleor/graphql/meta/tests/test_meta_queries.py
  saleor/graphql/schema.graphql
Labels: checkout, 3.17, shopping

#16012 Allow query checkout for all users.
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/queries/test_checkout.py
  saleor/graphql/schema.graphql
Labels: checkout, 3.16, shopping

#16013 Allow query checkout for all users.
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/queries/test_checkout.py
  saleor/graphql/schema.graphql
Labels: checkout, 3.15, shopping

#16014 Allow query checkout for all users.
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/meta/tests/test_meta_queries.py
  saleor/graphql/schema.graphql
Labels: checkout, 3.14, shopping

#16015 Disallow to update checkout shipping method with mismatching currency
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: bug, skip changelog, main

#16024 Disallow to update checkout shipping method with mismatching currency
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: skip changelog, 3.18

#16023 Disallow to update checkout shipping method with mismatching currency
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: skip changelog, 3.19

#16025 Disallow to update checkout shipping method with mismatching currency
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: skip changelog, 3.17

#16008 Skip address validation.
  CHANGELOG.md
  saleor/account/migrations/0085_address_validation_skipped.py
  saleor/account/models.py
  saleor/account/tests/test_account.py
  saleor/graphql/account/bulk_mutations/customer_bulk_update.py
  saleor/graphql/account/i18n.py
  saleor/graphql/account/mutations/account/account_address_create.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/mutations/staff/address_create.py
  saleor/graphql/account/tests/bulk_mutations/test_customer_bulk_update.py
  saleor/graphql/account/tests/mutations/account/test_account_address_create.py
  saleor/graphql/account/tests/mutations/account/test_account_address_update.py
  saleor/graphql/account/tests/mutations/account/test_account_update.py
  saleor/graphql/account/tests/mutations/staff/test_address_create.py
  saleor/graphql/account/tests/mutations/staff/test_address_update.py
  saleor/graphql/account/tests/mutations/staff/test_customer_create.py
  saleor/graphql/account/tests/mutations/staff/test_customer_update.py
  saleor/graphql/account/tests/test_i18n.py
  saleor/graphql/account/types.py
  saleor/graphql/checkout/mutations/checkout_complete.py
  saleor/graphql/checkout/mutations/checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_billing_address_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/core/mutations.py
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/tests/mutations/test_order_bulk_create.py
  saleor/graphql/order/tests/mutations/test_order_confirm.py
  saleor/graphql/order/tests/mutations/test_order_update.py
  saleor/graphql/schema.graphql
  saleor/graphql/shop/resolvers.py
  saleor/graphql/shop/tests/mutations/test_shop_address_update.py
  saleor/graphql/warehouse/mutations/base.py
  saleor/graphql/warehouse/mutations/warehouse_create.py
  saleor/graphql/warehouse/mutations/warehouse_update.py
  saleor/graphql/warehouse/tests/mutations/test_warehouse_create.py
  saleor/graphql/warehouse/tests/mutations/test_warehouse_update.py
  saleor/payment/interface.py
  saleor/tests/fixtures.py
Labels: test deployment, address, 3.19

#16032 Add logs for 0 line total price
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_calculations.py
  saleor/checkout/tests/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/tax/calculations/checkout.py
Labels: 3.14

#16036 Fix introspection query validator
  saleor/graphql/tests/test_utils.py
  saleor/graphql/utils/validators.py
Labels: bug, skip changelog

#16028 Disallow to update checkout shipping method with mismatching currency
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: skip changelog, 3.14

#16027 Disallow to update checkout shipping method with mismatching currency
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: skip changelog, 3.15

#16026 Disallow to update checkout shipping method with mismatching currency
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
Labels: skip changelog, 3.16

#16045 Add validation when VoucherCode is used in Voucher input
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
Labels: skip changelog

#16044 Fix error when discount_amount is 0 for taxes webhook payload
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: skip changelog

#16043 Transaction id validation in `getTransaction`
  saleor/graphql/payment/schema.py
  saleor/graphql/payment/tests/queries/test_transaction.py
Labels: skip changelog, main, translations

#16042 Transaction id validation in `getTransaction`
  saleor/graphql/payment/schema.py
  saleor/graphql/payment/tests/queries/test_transaction.py
Labels: 3.19

#16038 Optimize writer/replica usages in Celery tasks
  saleor/attribute/tasks.py
  saleor/core/db/connection.py
  saleor/core/tasks.py
  saleor/csv/utils/export.py
  saleor/csv/utils/product_headers.py
  saleor/giftcard/tasks.py
  saleor/graphql/discount/utils.py
  saleor/order/tasks.py
  saleor/payment/tasks.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_tasks.py
  saleor/product/tasks.py
  saleor/product/utils/variants.py
Labels: skip changelog

#16031 Read replica in tests - add docstrings
  saleor/tests/utils.py
Labels: skip changelog, docs

#16053 Fix config of observability tasks
  saleor/settings.py
  saleor/webhook/transport/asynchronous/transport.py
Labels: skip changelog

#16049 Fix error when discount_amount is 0 for taxes webhook payload
  saleor/webhook/payloads.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: skip changelog, 3.19

#15995 Handle a celery task error when the job_id for an AppInstall is missing in the db
  saleor/app/tasks.py
  saleor/app/tests/test_app_tasks.py
Labels: skip changelog

#16037 #14475: Improve description for customers query
  saleor/graphql/account/schema.py
  saleor/graphql/schema.graphql
Labels: skip changelog, main, community

#16051 Allow account mutations to be run by app.
  saleor/graphql/account/i18n.py
  saleor/graphql/account/mixins.py
  saleor/graphql/account/mutations/account/account_address_create.py
  saleor/graphql/account/mutations/account/account_update.py
  saleor/graphql/account/tests/mutations/account/test_account_address_create.py
  saleor/graphql/account/tests/mutations/account/test_account_address_update.py
  saleor/graphql/account/tests/mutations/account/test_account_update.py
  saleor/graphql/schema.graphql
Labels: address, 3.19

#16058 Check required fields when skipping address validation.
  saleor/graphql/account/i18n.py
  saleor/graphql/account/tests/mutations/staff/test_address_create.py
  saleor/graphql/account/tests/test_i18n.py
Labels: address

#16055 Use PostgreSQL 15
  .devcontainer/docker-compose.yml
Labels: technical debt, skip changelog
