Repository saleor/saleor, pull requests merged in 2024-11, with the labels that each got.

#16951 Optimize database calls for webhooks in bulk mutations
  saleor/graphql/attribute/mutations/attribute_bulk_create.py
  saleor/graphql/page/bulk_mutations.py
  saleor/graphql/page/tests/mutations/test_page_types_bulk_delete.py
  saleor/graphql/translations/mutations/utils.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
Labels: 3.20

#16947 Optimize database calls for webhooks in bulk mutations
  saleor/graphql/attribute/mutations/attribute_bulk_create.py
  saleor/graphql/page/bulk_mutations.py
  saleor/graphql/page/tests/mutations/test_page_types_bulk_delete.py
  saleor/graphql/translations/mutations/utils.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
Labels: skip changelog, main, 3.21

#16960 Release 3.20.43
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16942 Fix crash on checkout resolver when variant listing is not present
  saleor/checkout/base_calculations.py
  saleor/checkout/calculations.py
  saleor/checkout/fetch.py
  saleor/checkout/migrations/0070_checkoutline_undiscounted_unit_price_amount.py
  saleor/checkout/migrations/0071_propagate_line_unidscounted_unit_price.py
  saleor/checkout/migrations/0072_alter_checkoutline_undiscounted_unit_price_amount.py
  saleor/checkout/models.py
  saleor/checkout/tests/fixtures/checkout.py
  saleor/checkout/tests/fixtures/checkout_line.py
  saleor/checkout/tests/fixtures/checkout_with_discount.py
  saleor/checkout/tests/test_fetch.py
  saleor/checkout/tests/test_tasks.py
  saleor/checkout/utils.py
  saleor/core/pricing/interface.py
  saleor/discount/interface.py
  saleor/discount/utils/promotion.py
  saleor/discount/utils/voucher.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_billing_address_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create_from_order.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_attach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_detach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_note_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_email_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_language_code_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_line_delete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_delete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/tests/mutations/test_product_channel_listing_update.py
  saleor/order/fetch.py
  saleor/order/tests/test_fetch.py
  saleor/order/utils.py
  saleor/warehouse/tests/test_preorder_reservations_management.py
  saleor/warehouse/tests/test_stock_reservations_management.py
  saleor/webhook/serializers.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: test deployment, skip changelog

#16952 Improve the performance of StockBulkUpdate mutation
  saleor/core/models.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/graphql/warehouse/tests/bulk_mutations/test_stock_bulk_update.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/tests/subscription_webhooks/test_webhook.py
  saleor/webhook/transport/asynchronous/tests/test_create_deliveries_for_subscriptions.py
  saleor/webhook/transport/asynchronous/transport.py
Labels: skip changelog

#16965 Add missing database connection to the shipping resolver inside webhooks
  saleor/graphql/webhook/resolvers.py
Labels: skip changelog

#16966 Add missing database connection to the shipping resolver inside webhooks
  saleor/graphql/webhook/resolvers.py
Labels: 3.20

#16948 Fix crash on checkout resolver when variant listing is not present
  saleor/celeryconf.py
  saleor/checkout/base_calculations.py
  saleor/checkout/calculations.py
  saleor/checkout/fetch.py
  saleor/checkout/migrations/0070_checkoutline_undiscounted_unit_price_amount.py
  saleor/checkout/migrations/0071_propagate_line_unidscounted_unit_price.py
  saleor/checkout/migrations/tasks/saleor3_20.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_fetch.py
  saleor/checkout/tests/test_tasks.py
  saleor/checkout/utils.py
  saleor/core/pricing/interface.py
  saleor/discount/interface.py
  saleor/discount/utils/promotion.py
  saleor/discount/utils/voucher.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/conftest.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_billing_address_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create_from_order.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_attach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_detach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_email_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_language_code_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_line_delete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_delete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/tests/mutations/test_product_channel_listing_update.py
  saleor/order/fetch.py
  saleor/order/tests/test_fetch.py
  saleor/order/utils.py
  saleor/tests/fixtures.py
  saleor/warehouse/tests/test_preorder_reservations_management.py
  saleor/warehouse/tests/test_stock_reservations_management.py
  saleor/webhook/serializers.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.20

#16949 Fix crash on checkout resolver when variant listing is not present
  saleor/celeryconf.py
  saleor/checkout/base_calculations.py
  saleor/checkout/calculations.py
  saleor/checkout/fetch.py
  saleor/checkout/migrations/0070_checkoutline_undiscounted_unit_price_amount.py
  saleor/checkout/migrations/0071_propagate_line_unidscounted_unit_price.py
  saleor/checkout/migrations/tasks/saleor3_19.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_fetch.py
  saleor/checkout/tests/test_tasks.py
  saleor/checkout/utils.py
  saleor/core/pricing/interface.py
  saleor/discount/interface.py
  saleor/discount/utils.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/conftest.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_billing_address_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create_from_order.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_attach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_detach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_email_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_language_code_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_line_delete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_delete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/tests/mutations/test_product_channel_listing_update.py
  saleor/order/fetch.py
  saleor/order/tests/test_fetch.py
  saleor/order/utils.py
  saleor/tests/fixtures.py
  saleor/warehouse/tests/test_preorder_reservations_management.py
  saleor/warehouse/tests/test_stock_reservations_management.py
  saleor/webhook/serializers.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: 3.19

#16961 Improve the performance of StockBulkUpdate mutation
  saleor/core/models.py
  saleor/graphql/product/bulk_mutations/product_variant_stocks_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_stocks_update.py
  saleor/graphql/warehouse/bulk_mutations/stock_bulk_update.py
  saleor/graphql/warehouse/tests/benchmark/test_stock_bulk_update.py
  saleor/graphql/warehouse/tests/bulk_mutations/test_stock_bulk_update.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/tests/test_manager.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/subscription_webhooks/test_webhook.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/transport/asynchronous/tests/test_create_deliveries_for_subscriptions.py
  saleor/webhook/transport/asynchronous/transport.py
Labels: 3.20

#16968 Release 3.20.44
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16976 Fix potential deadlock in celery task triggered by checkout.0071 migration
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0072_propagate_line_undiscounted_unit_price.py
  saleor/checkout/migrations/0073_merge_20241107_1646.py
  saleor/checkout/tasks.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
Labels: skip changelog

#16974 Fix potential deadlock in celery task triggered by checkout.0071 migration
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0071_propagate_line_unidscounted_unit_price.py
  saleor/checkout/migrations/0072_propagate_line_undiscounted_unit_price.py
  saleor/checkout/migrations/tasks/saleor3_20.py
  saleor/checkout/tasks.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
Labels: 3.20

#16975 Fix potential deadlock in celery task triggered by checkout.0071 migration
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0071_propagate_line_unidscounted_unit_price.py
  saleor/checkout/migrations/0072_propagate_line_undiscounted_unit_price.py
  saleor/checkout/migrations/tasks/saleor3_19.py
  saleor/checkout/tasks.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
Labels: 3.19

#16977 Release 3.20.45
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16971 Change error to warning when logging invalid data provided by customer in the payment integration
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.20

#16972 Use denormalized quantity allocated in stock resolver
  saleor/graphql/warehouse/tests/queries/test_stock.py
  saleor/graphql/warehouse/types.py
  saleor/tests/fixtures.py
Labels: 3.20

#16978 Change error to warning when logging invalid data provided by customer in the payment integration
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: skip changelog

#16980 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip changelog

#16808 Async payload generation
  saleor/core/utils/events.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_method_update.py
  saleor/graphql/core/types/taxes.py
  saleor/graphql/webhook/mutations/webhook_trigger.py
  saleor/graphql/webhook/tests/mutations/test_webhook_trigger.py
  saleor/tests/fixtures.py
  saleor/webhook/event_types.py
  saleor/webhook/transport/asynchronous/tests/test_deferred_payload.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: load test, check patches

#16987 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  saleor/core/languages.py
  saleor/settings.py
Labels: test deployment, :robot: bot, skip changelog

#16988 Release 3.20.47
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16991 Release 3.20.48
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16986 Recalculate prices even when tax app returns empty data.
  saleor/order/calculations.py
  saleor/order/tests/test_fetch_order_prices_tax_app.py
Labels: bug, skip changelog, discount

#16994 Recalculate prices even when tax app returns empty data.
  saleor/order/calculations.py
  saleor/order/tests/test_fetch_order_prices_tax_app.py
Labels: bug, discount, 3.19

#16993 Recalculate prices even when tax app returns empty data.
  saleor/order/calculations.py
  saleor/order/tests/test_fetch_order_prices_tax_app.py
Labels: bug, discount, 3.20

#16996 Remove custom config for CodeQL
  .github/workflows/codeql-analysis.yml
Labels: technical debt, skip changelog

#16911 split account module fixtures
  conftest.py
  saleor/account/tests/fixtures/__init__.py
  saleor/account/tests/fixtures/user.py
  saleor/graphql/account/tests/fixtures/__init__.py
  saleor/graphql/account/tests/fixtures/benchmark.py
  saleor/graphql/account/tests/fixtures/utils.py
  saleor/tests/fixtures.py
Labels: skip changelog

#16985 Skip request event in calculation, when the `pspReference` is missing in the response from payment app
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.20

#16995 Release 3.20.49
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16982 Use denormalized quantity allocated in stock resolver
  saleor/graphql/warehouse/tests/queries/test_stock.py
  saleor/graphql/warehouse/types.py
  saleor/order/tests/fixtures/order.py
Labels: skip changelog, main

#16897 Make sure we never log URL credentials
  saleor/core/utils/tests/test_url.py
  saleor/core/utils/url.py
  saleor/webhook/observability/obfuscation.py
  saleor/webhook/observability/payloads.py
  saleor/webhook/observability/tests/test_obfuscation.py
  saleor/webhook/observability/tests/test_payloads.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: security, skip changelog

#16999 Async payload generation
  saleor/core/utils/events.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_method_update.py
  saleor/graphql/core/types/taxes.py
  saleor/graphql/webhook/mutations/webhook_trigger.py
  saleor/graphql/webhook/tests/mutations/test_webhook_trigger.py
  saleor/webhook/event_types.py
  saleor/webhook/tests/fixtures/webhook.py
  saleor/webhook/transport/asynchronous/tests/test_deferred_payload.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: skip changelog

#17002 Skip request event in calculation, when the pspReference is missing in the response from payment app
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: skip changelog

#17014 Exclude graphql playground from being indexed by search engines
  templates/graphql/playground.html
Labels: skip changelog

#17015 Exclude graphql playground from being indexed by search engines
  templates/graphql/playground.html
Labels: 3.20

#17016 Exclude graphql playground from being indexed by search engines
  templates/graphql/playground.html
Labels: 3.14

#17017 Exclude graphql playground from being indexed by search engines
  templates/graphql/playground.html
Labels: 3.15

#17018 Exclude graphql playground from being indexed by search engines
  templates/graphql/playground.html
Labels: 3.16

#17019 Exclude graphql playground from being indexed by search engines
  templates/graphql/playground.html
Labels: 3.17

#17020 Exclude graphql playground from being indexed by search engines
  templates/graphql/playground.html
Labels: 3.18

#17021 Exclude graphql playground from being indexed by search engines
  templates/graphql/playground.html
Labels: 3.19

#17022 Release 3.20.50
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17013 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
Labels: test deployment, :robot: bot, skip changelog

#16981 Optimize ProductVariantUpdate mutation
  saleor/graphql/core/mutations.py
  saleor/graphql/product/mutations/product_variant/product_variant_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/product/models.py
Labels: 3.20

#17004 Fix rounding issue when propagating order/checkout level discount on lines
  saleor/checkout/base_calculations.py
  saleor/checkout/calculations.py
  saleor/order/base_calculations.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/plugins/manager.py
  saleor/tax/calculations/checkout.py
  saleor/tax/tests/test_checkout_calculations.py
  saleor/tax/tests/test_order_calculations.py
  saleor/tests/fixtures.py
Labels: 3.20

#17024 Fix rounding issue when propagating order/checkout level discount on lines
  saleor/checkout/base_calculations.py
  saleor/checkout/calculations.py
  saleor/order/base_calculations.py
  saleor/order/tests/fixtures/order.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/plugins/manager.py
  saleor/tax/calculations/checkout.py
  saleor/tax/tests/test_checkout_calculations.py
  saleor/tax/tests/test_order_calculations.py
  saleor/tests/e2e/orders/discounts/test_order_products_on_catalog_promotion_and_voucher_entire.py
  saleor/tests/e2e/orders/utils/draft_order_update.py
Labels: skip changelog

#17031 Release 3.20.51
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16997 Fix risk of updating the already deleted checkout line
  saleor/checkout/utils.py
  saleor/core/exceptions.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/checkout_lines_update.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
Labels: skip changelog

#17026 Fix risk of updating the already deleted checkout line
  saleor/checkout/utils.py
  saleor/core/exceptions.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/checkout_lines_update.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
Labels: 3.19

#17025 Fix risk of updating the already deleted checkout line
  saleor/checkout/utils.py
  saleor/core/exceptions.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/checkout_lines_update.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
Labels: 3.20

#17035 Add payload size to the webhook spans
  saleor/core/models.py
  saleor/core/tracing.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: skip changelog

#16998 Add paginated `productVariants` to `Product` type
  CHANGELOG.md
  saleor/graphql/product/resolvers.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/types/products.py
  saleor/graphql/query_cost_map.py
  saleor/graphql/schema.graphql
Labels: main, 3.21

#17037 Add payload size to the webhook spans
  saleor/core/models.py
  saleor/core/tracing.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: 3.20

#17028 Fix decreasing voucher code usage after changing `includeDraftOrderInVoucherUsage` to false.
  CHANGELOG.md
  saleor/discount/tasks.py
  saleor/discount/tests/test_tasks.py
  saleor/graphql/channel/tests/mutations/test_channel_update.py
Labels: bug, voucher

#17050 Release 3.20.52
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17044 Truncate lenghty responses in `EventDeliveryAttempt` objects
  CHANGELOG.md
  saleor/settings.py
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: main

#17039 Update test for automatic checkout completion to not overcharge the order
  saleor/checkout/tests/test_tasks.py
Labels: 3.20

#17034 Handle long message when reporting transaction event
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/graphql/schema.graphql
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.20

#17045 Do not update EventAttempt for success event delivery
  saleor/plugins/webhook/tests/test_deprecated_webhook_tasks.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: 3.19

#17043 Do not update EventAttempt for success event delivery
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: 3.20

#17038 Do not update EventAttempt for success event delivery
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: skip changelog

#17040 Do not delete checkout lines when product-channel-listing is removed
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_fetch.py
  saleor/checkout/tests/test_tasks.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_billing_address_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create_from_order.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_attach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_detach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_note_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_email_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_language_code_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_line_delete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_delete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/tests/mutations/test_product_channel_listing_update.py
Labels: 3.20

#17027 Do not delete checkout lines when product-channel-listing is removed
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_fetch.py
  saleor/checkout/tests/test_tasks.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_billing_address_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create_from_order.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_attach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_detach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_note_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_email_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_language_code_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_line_delete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_delete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/tests/mutations/test_product_channel_listing_update.py
Labels: test deployment, skip changelog

#17041 Do not delete checkout lines when product-channel-listing is removed
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_fetch.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_billing_address_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create_from_order.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_attach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_detach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_note_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_email_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_language_code_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_line_delete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_delete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/product/mutations/channels.py
  saleor/graphql/product/tests/mutations/test_product_channel_listing_update.py
Labels: 3.19

#17046 Fix decreasing voucher code usage after changing `includeDraftOrderInVoucherUsage` to false.
  saleor/discount/tasks.py
  saleor/discount/tests/test_tasks.py
  saleor/graphql/channel/tests/mutations/test_channel_update.py
Labels: bug, voucher, 3.19, check patches

#17047 Fix decreasing voucher code usage after changing `includeDraftOrderInVoucherUsage` to false.
  saleor/discount/tasks.py
  saleor/discount/tests/test_tasks.py
  saleor/graphql/channel/tests/mutations/test_channel_update.py
Labels: bug, voucher, 3.20, check patches

#17042 Optimize ProductVariantUpdate mutation
  saleor/graphql/core/mutations.py
  saleor/graphql/product/mutations/product_variant/product_variant_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/product/models.py
Labels: performance, skip changelog, main

#17067 Prevent attempts to truncate objects that are not strings
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: skip changelog

#17053 Truncate lenghty responses in EventDeliveryAttempt objects
  saleor/settings.py
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: 3.18

#17054 Truncate lenghty responses in EventDeliveryAttempt objects
  saleor/settings.py
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: 3.17

#17051 Truncate lenghty responses in EventDeliveryAttempt objects
  saleor/settings.py
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: 3.20

#17080 Release 3.20.54
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17077 Fix `EventPayload` and `EventDelivery` creation
  saleor/core/tasks.py
  saleor/plugins/webhook/tasks.py
Labels: 3.15

#17078 Fix `EventPayload` and `EventDelivery` creation
  saleor/core/tasks.py
  saleor/plugins/webhook/tasks.py
Labels: 3.16

#17079 Fix `EventPayload` and `EventDelivery` creation
  saleor/core/tasks.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: 3.17

#17081 Fix `EventPayload` and `EventDelivery` creation
  saleor/core/tasks.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: 3.18

#17082 Fix `EventPayload` and `EventDelivery` creation
  saleor/core/tasks.py
  saleor/plugins/webhook/tests/test_webhook_protocols.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: 3.19

#17069 Call webhooks after transaction in `BaseCustomerCreate`
  saleor/graphql/account/mutations/base.py
Labels: 3.14

#17070 Call webhooks after transaction in `BaseCustomerCreate`
  saleor/graphql/account/mutations/base.py
Labels: 3.15

#17071 Call webhooks after transaction in `BaseCustomerCreate`
  saleor/graphql/account/mutations/base.py
Labels: 3.16

#17072 Call webhooks after transaction in `BaseCustomerCreate`
  saleor/graphql/account/mutations/base.py
Labels: 3.17

#17073 Call webhooks after transaction in `BaseCustomerCreate`
  saleor/graphql/account/mutations/base.py
Labels: 3.18

#17074 Call webhooks after transaction in `BaseCustomerCreate`
  saleor/graphql/account/mutations/base.py
Labels: 3.19

#17075 Call webhooks after transaction in `BaseCustomerCreate`
  saleor/graphql/account/mutations/base.py
Labels: 3.20

#17076 Call webhooks after transaction in `BaseCustomerCreate`
  saleor/graphql/account/mutations/base.py
Labels: skip changelog, main

#17084 Prevent attempts to truncate objects that are not strings
  saleor/plugins/webhook/utils.py
Labels: 3.14

#17036 Improve performance of bulk translate mutations
  saleor/graphql/translations/mutations/product_translate.py
  saleor/graphql/translations/mutations/product_variant_translate.py
  saleor/graphql/translations/mutations/promotion_rule_translate.py
  saleor/graphql/translations/mutations/promotion_translate.py
  saleor/graphql/translations/mutations/sale_translate.py
  saleor/graphql/translations/mutations/shop_settings_translate.py
  saleor/graphql/translations/mutations/utils.py
  saleor/graphql/translations/tests/mutations/test_attribute_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_attribute_value_bulk_transalte.py
  saleor/graphql/translations/tests/mutations/test_product_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_product_variant_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_promotion_rule_translate.py
  saleor/graphql/translations/tests/mutations/test_promotion_translate.py
  saleor/graphql/translations/tests/mutations/test_sale_translate.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/webhook/plugin.py
Labels: skip changelog

#17085 Improve performance of bulk translate mutations
  saleor/graphql/translations/mutations/product_translate.py
  saleor/graphql/translations/mutations/product_variant_translate.py
  saleor/graphql/translations/mutations/promotion_rule_translate.py
  saleor/graphql/translations/mutations/promotion_translate.py
  saleor/graphql/translations/mutations/sale_translate.py
  saleor/graphql/translations/mutations/shop_settings_translate.py
  saleor/graphql/translations/mutations/utils.py
  saleor/graphql/translations/tests/mutations/test_attribute_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_attribute_value_bulk_transalte.py
  saleor/graphql/translations/tests/mutations/test_product_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_product_variant_bulk_translate.py
  saleor/graphql/translations/tests/mutations/test_promotion_rule_translate.py
  saleor/graphql/translations/tests/mutations/test_promotion_translate.py
  saleor/graphql/translations/tests/mutations/test_sale_translate.py
  saleor/graphql/translations/tests/test_translations.py
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
  saleor/plugins/tests/sample_plugins.py
  saleor/plugins/tests/test_manager.py
  saleor/plugins/webhook/plugin.py
Labels: 3.20

#17083 Use poetry 1.8.x
  .devcontainer/Dockerfile
  .github/workflows/e2e.yml
  .github/workflows/pytest.yml
  .github/workflows/test-migrations-compatibility.yml
  Dockerfile
  pyproject.toml
Labels: technical debt, skip changelog

#17086 Retry webhook request in case `EventDelivery` cannot be found
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/plugins/webhook/utils.py
Labels: 3.14

#17087 Retry webhook request in case `EventDelivery` cannot be found
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/plugins/webhook/utils.py
Labels: 3.15

#17088 Retry webhook request in case EventDelivery cannot be found
  saleor/plugins/webhook/tasks.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/plugins/webhook/utils.py
Labels: 3.16

#17089 Retry webhook request in case `EventDelivery` cannot be found
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: 3.17

#17090 Retry webhook request in case EventDelivery cannot be found
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: 3.18

#17091 Retry webhook request in case EventDelivery cannot be found
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: 3.19

#17092 Prevent raising an error for `AUTHORIZATION_SUCESS` in case parallel actions on transaction are performed
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/payment/utils.py
Labels: skip changelog, main

#17094 Retry webhook request in case EventDelivery cannot be found
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: skip changelog, main

#17093 Retry webhook request in case EventDelivery cannot be found
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/tests/test_utils.py
  saleor/webhook/transport/utils.py
Labels: 3.20

#17061 Fix for transaction message truncate
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.20

#17099 Fix ProductVariantUpdate preorder fields
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/product/models.py
Labels: bug, 3.20

#17100 Fix ProductVariantUpdate preorder fields
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/product/models.py
Labels: bug, skip changelog, main

#17102 Release 3.20.56
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17101 Fix for transaction message truncate
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: skip changelog, main

#17106 Set the garbage collection baseline immediately after preloading the ASGI app
  saleor/asgi/__init__.py
Labels: performance, technical debt, skip changelog

#17107 Set the garbage collection baseline immediately after preloading the ASGI app
  saleor/asgi/__init__.py
Labels: performance, technical debt, skip changelog, 3.20
