Repository saleor/saleor, pull requests merged in 2025-06, with the labels that each got.

#17769 Release 3.21.2
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17764 Get rid of `payment_status` filter from order where
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/queries/test_order_with_where.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#17761 Refactor `webhook.transport.utils.py` file
  saleor/core/tests/test_taxes.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_payment_webhook.py
  saleor/plugins/webhook/tests/test_tax_webhook.py
  saleor/webhook/tests/test_payment_webhook_utils.py
  saleor/webhook/tests/test_sync_webhooks_for_removed_app.py
  saleor/webhook/tests/test_tax_webhook_tasks.py
  saleor/webhook/tests/test_tax_webhook_utils.py
  saleor/webhook/transport/payment.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/taxes.py
  saleor/webhook/transport/utils.py
Labels: skip changelog

#17767 Fix flaky test for exclude sm pregenerated webhook paylaod
  saleor/graphql/webhook/tests/pregenerated_subscription/test_exclude_shipping_methods_pregenerated_payloads.py
Labels: skip changelog

#17766 Prefer input email over account email for checkout/order
  saleor/checkout/complete_checkout.py
  saleor/checkout/fetch.py
  saleor/checkout/models.py
  saleor/discount/tests/test_utils/test_get_customer_email_for_voucher_usage.py
  saleor/discount/utils/voucher.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_attach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_email_update.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/types.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/order/models.py
  saleor/order/tasks.py
  saleor/order/tests/test_order_utils.py
Labels: 3.21

#17762 Telemetry - port trace context propagation
  saleor/core/telemetry/__init__.py
  saleor/core/telemetry/metric.py
  saleor/core/telemetry/tests/__init__.py
  saleor/core/telemetry/tests/test_metric.py
  saleor/core/telemetry/tests/test_trace.py
  saleor/core/telemetry/trace.py
  saleor/graphql/tests/test_tracing.py
  saleor/graphql/views.py
  saleor/tests/fixtures.py
  saleor/tests/settings.py
  saleor/webhook/transport/utils.py
Labels: skip changelog

#17784 Release 3.20.90
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17775 Allow filtering orders by voucher code
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/queries/test_order_with_where.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#17768 SCL-941 - reconfigure saleor workflows to use IAM roles instead of IAM users for CICD
  .github/workflows/migrations-perf-test.yml
  .github/workflows/test-env-cleanup.yml
  .github/workflows/test-env-deploy.yml
Labels: skip changelog

#17789 Fix race condition with checkout complete process and TransactionEventReport mutation.
  saleor/checkout/actions.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
Labels: skip changelog, main

#17780 Support NEW_TAB for extension target & add new mounting points
  CHANGELOG.md
  saleor/app/manifest_validations.py
  saleor/app/migrations/0031_alter_appextension_mount_alter_appextension_target.py
  saleor/app/tests/test_validators.py
  saleor/app/types.py
  saleor/graphql/app/tests/mutations/test_app_fetch_manifest.py
  saleor/graphql/schema.graphql
Labels: test deployment

#17792 Drop unused `CHECKOUT_BATCH_FOR_RELEASING_FUNDS` variable from settings
  saleor/settings.py
Labels: skip changelog

#17782 Revert additional .quantitze in `normalize_tax_rate_for_db`
  saleor/checkout/tests/test_calculations.py
  saleor/tax/tests/test_checkout_calculations.py
  saleor/tax/tests/test_order_calculations.py
  saleor/tax/utils.py
Labels: 3.21

#17787 Extend `Order` model with `lines_count`
  saleor/account/tests/test_account.py
  saleor/checkout/complete_checkout.py
  saleor/core/utils/random_data.py
  saleor/graphql/account/tests/fixtures/benchmark.py
  saleor/graphql/account/tests/queries/test_customers.py
  saleor/graphql/account/tests/queries/test_customers_filtering.py
  saleor/graphql/account/tests/queries/test_customers_sorting.py
  saleor/graphql/account/tests/queries/test_staff_users_sorting.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/core/tests/test_scalars.py
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/order_line_delete.py
  saleor/graphql/order/mutations/order_lines_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_fulfillment_return_products.py
  saleor/graphql/order/tests/mutations/test_order_bulk_create.py
  saleor/graphql/order/tests/mutations/test_order_line_delete.py
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/graphql/order/tests/queries/test_draft_order_with_filter.py
  saleor/graphql/order/tests/queries/test_draft_order_with_sort.py
  saleor/graphql/order/tests/queries/test_order_by_token.py
  saleor/graphql/order/tests/queries/test_order_with_filter.py
  saleor/graphql/order/tests/queries/test_order_with_sort.py
  saleor/graphql/order/tests/queries/test_orders.py
  saleor/graphql/order/tests/queries/test_pagination.py
  saleor/graphql/order/tests/test_filters.py
  saleor/order/actions.py
  saleor/order/migrations/0203_order_lines_count.py
  saleor/order/migrations/0204_merge_0203_merge_20250527_1210_0203_order_lines_count.py
  saleor/order/migrations/0204_set_order_lines_count.py
  saleor/order/migrations/0205_merge_20250603_1125.py
  saleor/order/migrations/0206_alter_order_lines_count.py
  saleor/order/models.py
  saleor/order/tests/fixtures/benchmark.py
  saleor/order/tests/fixtures/order.py
  saleor/order/tests/fixtures/order_line.py
  saleor/order/tests/test_order.py
  saleor/order/tests/test_order_actions_create_fulfillments_for_returned_products.py
  saleor/order/tests/test_order_utils.py
  saleor/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
  saleor/webhook/tests/test_webhook_payloads.py
Labels: migrations perf test, skip changelog

#17743 Add env var support for read-replica database URL
  saleor/settings.py
Labels: skip changelog

#17814 Separate parse logic for transaction item webhooks
  saleor/payment/interface.py
  saleor/payment/tests/test_utils/__init__.py
  saleor/payment/tests/test_utils/test_parse_transaction_action_data_for_action_webhook.py
  saleor/payment/tests/test_utils/test_parse_transaction_action_data_for_session_webhook.py
  saleor/payment/tests/test_utils/test_utils.py
  saleor/payment/utils.py
Labels: skip changelog

#17736 Improve time execution of AppByTokenLoader
  saleor/graphql/app/dataloaders/app.py
  saleor/graphql/app/tests/test_app_by_token_loader_use_cache.py
Labels: 3.20

#17818 Move tests for create_transaction_event_for_transaction_session to separate file
  saleor/payment/tests/test_utils/test_create_transaction_event_for_transaction_session.py
  saleor/payment/tests/test_utils/test_utils.py
Labels: skip changelog

#17820 Release 3.20.91
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17821 Release 3.21.5
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17827 Additional test for resolving extension options
  saleor/graphql/app/tests/queries/test_app_extension.py
Labels: skip changelog

#17826 Allow filtering orders by `productTypeId`
  CHANGELOG.md
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/queries/test_order_with_where.py
  saleor/graphql/schema.graphql
  saleor/order/migrations/0212_orderline_product_type_id_btree_idx.py
  saleor/order/models.py
Labels: migrations perf test

#17849 Resolve migration conflict in order module
  saleor/order/migrations/0215_merge_20250623_0624.py
Labels: skip changelog

#17855 Revert "Bump dependencies (#17852)"
  .pre-commit-config.yaml
Labels: skip changelog

#17841 Improve app extension validators
  saleor/app/manifest_validations.py
  saleor/app/tests/test_installation_utils.py
  saleor/app/tests/test_validators.py
  saleor/graphql/app/tests/mutations/test_app_fetch_manifest.py
Labels: skip changelog

#17859 Denormalized number of orders placed by the user
  saleor/account/lock_objects.py
  saleor/account/migrations/0090_user_number_of_orders.py
  saleor/account/migrations/0091_populate_user_number_of_orders.py
  saleor/account/migrations/tasks/__init__.py
  saleor/account/migrations/tasks/saleor3_22.py
  saleor/account/models.py
  saleor/account/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/order/bulk_mutations/order_bulk_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_order_bulk_create.py
  saleor/order/actions.py
  saleor/order/tasks.py
  saleor/order/tests/test_order_actions.py
  saleor/order/tests/test_tasks.py
Labels: skip changelog

#17867 Allow filtering orders by shipping and billing address data
  CHANGELOG.md
  saleor/account/migrations/0092_address_address_country_idx.py
  saleor/account/models.py
  saleor/graphql/account/filters.py
  saleor/graphql/account/tests/queries/test_customers_where_filtering.py
  saleor/graphql/core/filters/where_input.py
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/queries/test_order_with_where.py
  saleor/graphql/schema.graphql
  saleor/graphql/utils/filters.py
Labels: skip migrations perf test

#17871 Refactor the lock-related tests for TransactionEventReport mutation
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
Labels: skip changelog, main

#17873 Fix attributes filter returning single product
  saleor/graphql/product/filters.py
  saleor/graphql/product/tests/queries/test_products_query_with_where.py
Labels: skip changelog

#17877 Drop `isPreorder` from where order filters
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/queries/test_order_with_where.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#17882 Fix account migration
  saleor/account/migrations/0091_populate_user_number_of_orders.py
  saleor/account/migrations/0094_repopulate_user_number_of_orders.py
  saleor/account/migrations/0095_repopulate_user_number_of_orders.py
  saleor/account/migrations/tasks/saleor3_22.py
Labels: skip changelog, skip migrations perf test
