Repository saleor/saleor, pull requests merged in 2025-03, with the labels that each got.

#17443 Fix circuit breaker wrapper for trigger_webhook_sync
  saleor/webhook/circuit_breaker/breaker_board.py
  saleor/webhook/tests/circuit_breaker/test_breaker_board_decorator.py
Labels: bug, skip changelog

#17446 Extend the max size for checkout.external_shipping_method_id field
  saleor/checkout/migrations/0074_alter_checkout_external_shipping_method_id.py
  saleor/checkout/models.py
Labels: 3.20

#17447 Extend the max size for checkout.external_shipping_method_id field
  saleor/checkout/migrations/0074_alter_checkout_external_shipping_method_id.py
  saleor/checkout/migrations/0077_merge_20250303_0958.py
  saleor/checkout/models.py
Labels: skip changelog, skip migrations perf test

#17441 Add Discord badge & remove GH Discussions mention
  README.md
Labels: skip changelog

#17449 Announce releases with a full changelog
  .github/workflows/github-releases-to-discord.yml
Labels: skip changelog, 3.20

#17451 Fix trailing-whitespace in README
  README.md
Labels: skip changelog

#17440 Separate lint & test jobs
  .github/workflows/tests-and-linters.yml
Labels: skip changelog

#17457 Add client-side PII scrubbing for Sentry
  saleor/settings.py
Labels: security, skip changelog

#17454 Add a way for concurrent safe json updates in `updateMetadata` and `updatePrivateMetadata` mutations
  saleor/core/db/expressions.py
  saleor/core/db/tests/test_postgres_json_concatenate.py
  saleor/graphql/meta/mutations/update_metadata.py
  saleor/graphql/meta/mutations/update_private_metadata.py
  saleor/graphql/meta/mutations/utils.py
  saleor/graphql/meta/tests/mutations/test_update_metadata.py
  saleor/graphql/meta/tests/mutations/test_update_private_metadata.py
Labels: 3.20

#17375 Add a way for concurrent safe json updates in `updateMetadata` and `updatePrivateMetadata` mutations
  saleor/core/db/expressions.py
  saleor/core/db/tests/test_postgres_json_concatenate.py
  saleor/graphql/meta/mutations/update_metadata.py
  saleor/graphql/meta/mutations/update_private_metadata.py
  saleor/graphql/meta/mutations/utils.py
  saleor/graphql/meta/tests/mutations/test_update_metadata.py
  saleor/graphql/meta/tests/mutations/test_update_private_metadata.py
Labels: skip changelog, main, 3.21

#17459 Update setuptools package
  poetry.lock
  requirements.txt
  requirements_dev.txt
Labels: 3.17

#17460 Release 3.20.75
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17450 Add description to bulk order and checkout queries about skipping external calls
  saleor/graphql/account/types.py
  saleor/graphql/checkout/schema.py
  saleor/graphql/order/schema.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#17464 Add flag to create draft release
  .github/workflows/create-tag-with-release-pr.yml
Labels: skip changelog

#17474 Use sys.monitoring for coverage tracking
  .github/workflows/pytest.yml
  setup.cfg
Labels: 3.20

#17476 Use logical instead of physical cores to detect pytest workers
  .github/workflows/pytest.yml
Labels: 3.20

#17477 Separate lint & test jobs
  .github/workflows/tests-and-linters.yml
Labels: 3.20

#17472 The City field should not be cleared during address validation for Japan.
  saleor/account/i18n_rules_override.py
  saleor/account/tests/test_account.py
  saleor/settings.py
Labels: 3.20

#17479 Add good-first-issues-to-discord workflow
  .github/workflows/good-first-issues-to-discord.yml
Labels: skip changelog

#17483 Release 3.20.76
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: 3.20, release

#17484 Remove body from Discord GFI message
  .github/workflows/good-first-issues-to-discord.yml
Labels: skip changelog

#17482 The City field should not be cleared during address validation for Japan.
  saleor/account/i18n_rules_override.py
  saleor/account/tests/test_account.py
  saleor/settings.py
Labels: skip changelog

#17489 Change job name from E2E tests
  .github/workflows/e2e.yml
Labels: skip changelog, main

#17490 Bump dependencies
  .devcontainer/Dockerfile
  .github/workflows/e2e.yml
  .github/workflows/test-migrations-compatibility.yml
  .github/workflows/tests-and-linters.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Dockerfile
  poetry.lock
  pyproject.toml
  saleor/graphql/discount/mutations/promotion/promotion_rule_create.py
  saleor/graphql/discount/mutations/promotion/promotion_rule_update.py
  saleor/graphql/discount/mutations/sale/sale_base_catalogue.py
  saleor/graphql/discount/mutations/sale/sale_delete.py
  saleor/graphql/discount/mutations/sale/sale_update.py
  saleor/product/tasks.py
Labels: test deployment, :robot: bot, skip changelog

#17465 Update order mutations - explicitly save changed fields in `OrderUpdate` and `DraftOrderComplete`
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/order_update.py
  saleor/graphql/order/mutations/utils.py
Labels: 3.20

#17492 Pin Discord-related GH action versions
  .github/workflows/github-releases-to-discord.yml
  .github/workflows/good-first-issues-to-discord.yml
Labels: skip changelog

#17485 Update CONTRIBUTING.md and feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: skip changelog

#17518 Fix metadata_manager test instances
  saleor/core/tests/test_metadata_manager.py
Labels: skip changelog

#17519 Fix product media create with an image URL containing query params
  saleor/thumbnail/tests/test_utils.py
  saleor/thumbnail/utils.py
Labels: bug, core, 3.20

#17529 Release 3.20.77
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17531 Fix calling draft_order_updated webhook even nothing has changed
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
Labels: 3.20

#17524 Fix incorrectly deprecated `OrderAddNoteInput.message`
  saleor/graphql/order/mutations/order_note_add.py
  saleor/graphql/schema.graphql
Labels: bug, skip changelog

#17504 Prevent removing translation from OrderLine when translatedName = name
  CHANGELOG.md
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
Labels: skip changelog

#17499 Harden admin email plugin config
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/conftest.py
  saleor/plugins/admin_email/tests/test_plugin.py
  saleor/plugins/email_common.py
Labels: skip changelog

#17527 Harden admin email plugin config
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/conftest.py
  saleor/plugins/admin_email/tests/test_plugin.py
  saleor/plugins/email_common.py
Labels: 3.19

#17528 Harden admin email plugin config
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/conftest.py
  saleor/plugins/admin_email/tests/test_plugin.py
  saleor/plugins/email_common.py
Labels: 3.20

#17535 Release 3.20.79
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17501 Call `DRAFT_ORDER_CREATED` webhhok in `FulfillmentReturnProducts` in case the replace order is created
  saleor/graphql/order/tests/mutations/test_fulfillment_return_products.py
  saleor/order/actions.py
  saleor/order/tests/test_order_actions_create_fulfillments_for_returned_products.py
Labels: 3.20

#17525 Allow setting shipping address in case CC was changed to standard delivery method
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_add_promo_code.py
  saleor/graphql/checkout/mutations/checkout_line_delete.py
  saleor/graphql/checkout/mutations/checkout_lines_add.py
  saleor/graphql/checkout/mutations/checkout_lines_delete.py
  saleor/graphql/checkout/mutations/checkout_shipping_address_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_address_update.py
  saleor/graphql/checkout/tests/test_checkout_price_expiration.py
  saleor/tests/e2e/__init__.py
  saleor/tests/e2e/checkout/test_checkout_switch_from_cc_to_standard_delivery_method.py
  saleor/tests/e2e/checkout/utils/checkout_delivery_method_update.py
  saleor/tests/e2e/warehouse/utils/create_warehouse.py
Labels: skip changelog, main

#17539 Remove the deprecated "Stripe (deprecated)" payment plugin
  CHANGELOG.md
  saleor/payment/gateways/stripe/deprecated/__init__.py
  saleor/payment/gateways/stripe/deprecated/plugin.py
  saleor/payment/gateways/stripe/deprecated/tests/__init__.py
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_authorize.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_authorize_3d_secure.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_authorize_and_save_customer_id.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_authorize_error_response.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_authorize_with_customer_id.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_authorize_without_capture.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_capture.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_capture_3d_secure.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_capture_error_response.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_confirm__intent.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_confirm_error_response.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_list_customer_sources.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_refund.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_refund_error_response.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_void.yaml
  saleor/payment/gateways/stripe/deprecated/tests/cassettes/test_stripe/test_void_error_response.yaml
  saleor/payment/gateways/stripe/deprecated/tests/test_stripe.py
  saleor/payment/gateways/stripe/deprecated/tests/test_utils.py
  saleor/payment/gateways/stripe/deprecated/utils.py
  saleor/settings.py
Labels: technical debt

#17536 Fix typo
  saleor/graphql/schema_printer.py
Labels: skip changelog

#17522 Fix product media create with an image URL containing query params
  saleor/thumbnail/tests/test_utils.py
  saleor/thumbnail/utils.py
Labels: bug, skip changelog, main, core

#17521 Fix product media create with an image URL containing query params
  saleor/thumbnail/tests/test_utils.py
  saleor/thumbnail/utils.py
Labels: bug, 3.19, core

#17537 `OrderUpdate` saving improvements
  saleor/graphql/order/mutations/order_update.py
  saleor/graphql/order/tests/mutations/test_order_update.py
Labels: 3.20

#17538 Call `DRAFT_ORDER_CREATED` webhhok in `FulfillmentReturnProducts` in case the replace order is created
  saleor/graphql/order/tests/mutations/test_fulfillment_return_products.py
  saleor/order/actions.py
  saleor/order/tests/test_order_actions_create_fulfillments_for_returned_products.py
Labels: skip changelog, main

#17507 Update order mutations - explicitly save changed fields in `OrderUpdate` and `DraftOrderComplete`
  CHANGELOG.md
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/order_update.py
  saleor/graphql/order/mutations/utils.py
  saleor/graphql/order/tests/mutations/test_order_update.py
  saleor/order/models.py
Labels: skip changelog

#17542 Fix flaky test in export
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/products_data/utils.py
Labels: 3.20

#17543 Remove information about specific version of removing WebhookPlugin
  saleor/plugins/base_plugin.py
  saleor/plugins/manager.py
Labels: skip changelog

#17547 Bump Authlib to fix reference cycle
  poetry.lock
  pyproject.toml
  saleor/graphql/core/tests/garbage_collection/__init__.py
  saleor/graphql/core/tests/garbage_collection/test_oauth2.py
  saleor/graphql/core/tests/garbage_collection/utils.py
Labels: skip changelog

#17532 Update order mutations - explicitly save changed fields in DraftOrderUpdate, do not call `DRAFT_ORDER_UPDATED` event when nothing changed
  CHANGELOG.md
  saleor/graphql/order/mutations/draft_order_cleaner.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/order_update_shipping.py
  saleor/graphql/order/mutations/utils.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/tests/test_utils.py
  saleor/order/models.py
Labels: skip changelog, main

#17544 Fix flaky test in export
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/products_data/utils.py
Labels: skip changelog
