Repository saleor/saleor, pull requests merged in 2025-08, with the labels that each got.

#18014 Move product attribute related logic to product module
  saleor/graphql/product/filters/product_attributes.py
Labels: skip changelog

#18015 Move page attribute related logic to page module
  saleor/graphql/attribute/shared_filters.py
  saleor/graphql/page/filters.py
Labels: skip changelog

#18025 Fill voucher code when calling `orderCreateFromCheckout` mutation.
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
Labels: 3.20

#18029 Use referenced object name for attribute-value name
  saleor/graphql/attribute/tests/queries/test_selected_attribute.py
  saleor/graphql/attribute/types.py
  saleor/graphql/page/tests/mutations/test_page_update.py
Labels: skip changelog

#18033 Update invitation and password email subjects
  saleor/plugins/admin_email/constants.py
Labels: skip changelog

#18048 Release 3.21.11
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#18005 INFRA-732 - add cron-based testenv cleanup workflow
  .github/workflows/test-env-cleanup-cron.yml
  .github/workflows/test-env-cleanup.yml
Labels: skip changelog, main, skip migrations perf test

#18061 Release 3.21.12
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#18062 Make sure string truncation does not exceed the database field limits
  CHANGELOG.md
  saleor/attribute/tests/fixtures/attribute.py
  saleor/core/utils/tests/test_text.py
  saleor/core/utils/text.py
  saleor/graphql/attribute/utils/type_handlers.py
  saleor/graphql/translations/mutations/attribute_value_bulk_translate.py
  saleor/graphql/translations/mutations/attribute_value_translate.py
  saleor/payment/utils.py
  saleor/plugins/webhook/plugin.py
Labels: bug

#18072 Remove old invoicing templates
  templates/invoices/inter.ttf
  templates/invoices/invoice.html
  templates/invoices/invoice_products_table.html
  templates/invoices/invoice_summary_table.html
Labels: skip changelog

#18082 Release 3.21.13
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#18083 Improve description of SelectedAttribute type
  saleor/graphql/attribute/types.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#18088 INFRA-762 - prepare testenvs workflows for switch to using dev account resources
  .github/workflows/migrations-perf-test.yml
  .github/workflows/test-env-cleanup-cron.yml
  .github/workflows/test-env-cleanup.yml
  .github/workflows/test-env-deploy.yml
Labels: skip changelog

#18080 Replace poetry with uv
  .devcontainer/Dockerfile
  .github/workflows/bump-dependencies.yml
  .github/workflows/check-licenses.yaml
  .github/workflows/e2e.yml
  .github/workflows/test-migrations-compatibility.yml
  .github/workflows/tests-and-linters.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Dockerfile
  poetry.lock
  pyproject.toml
  saleor/app/tasks.py
  saleor/core/management/commands/clearorders.py
  uv.lock
Labels: skip changelog

#18092 Pin GitHub Action versions for uv
  .github/dependabot.yml
  .github/workflows/bump-dependencies.yml
  .github/workflows/e2e.yml
  .github/workflows/test-migrations-compatibility.yml
  .github/workflows/tests-and-linters.yml
Labels: skip changelog

#18112 gha: build images natively on ARM64
  .github/workflows/publish-containers.yml
Labels: performance, skip changelog
