Repository saleor/saleor, pull requests merged in 2025-04, with the labels that each got.

#17548 Fix deferred payload issued_at field
  saleor/graphql/webhook/mutations/webhook_trigger.py
  saleor/graphql/webhook/tests/mutations/test_webhook_trigger.py
  saleor/webhook/tests/fixtures/webhook.py
  saleor/webhook/transport/asynchronous/tests/test_deferred_payload.py
Labels: skip changelog, main

#17546 Make sure that adding manual order discount always use correct prices
  saleor/checkout/utils.py
  saleor/discount/utils/promotion.py
  saleor/graphql/order/mutations/order_discount_add.py
  saleor/graphql/order/tests/mutations/test_order_discount.py
  saleor/order/utils.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
Labels: skip changelog

#17556 Release 3.20.80
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17553 Allow to set languageCode on Orders
  CHANGELOG.md
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/order_update.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/tests/mutations/test_order_update.py
  saleor/graphql/schema.graphql
  saleor/order/models.py
Labels: test deployment

#17541 Introduce static typing for shipping sync webhook responses
  poetry.lock
  pyproject.toml
  saleor/checkout/fetch.py
  saleor/core/utils/metadata_manager.py
  saleor/core/utils/tests/test_metadata_manager.py
  saleor/graphql/checkout/tests/benchmark/test_homepage.py
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/webhook/response_schemas/__init__.py
  saleor/webhook/response_schemas/annotations.py
  saleor/webhook/response_schemas/shipping.py
  saleor/webhook/tests/response_schemas/__init__.py
  saleor/webhook/tests/response_schemas/test_shipping.py
  saleor/webhook/transport/shipping.py
  saleor/webhook/transport/shipping_helpers.py
  saleor/webhook/transport/tests/test_shipping_helpers.py
Labels: skip changelog, main

#17559 Fix call of webhook trigger mutation to use context request time
  saleor/graphql/webhook/mutations/webhook_trigger.py
Labels: skip changelog

#17554 Fix deferred payload issued_at field
  saleor/graphql/webhook/mutations/webhook_trigger.py
  saleor/graphql/webhook/tests/mutations/test_webhook_trigger.py
  saleor/tests/fixtures.py
  saleor/webhook/transport/asynchronous/tests/test_deferred_payload.py
Labels: 3.20

#17557 Add otel tests
  saleor/asgi/tests/test_telemetry.py
  saleor/core/telemetry/metric.py
  saleor/core/telemetry/tests/__init__.py
  saleor/core/telemetry/tests/test_metric.py
  saleor/core/telemetry/tests/test_trace.py
  saleor/core/telemetry/tests/test_utils.py
  saleor/graphql/tests/test_metrics.py
Labels: skip changelog

#17552 Improve checkout lines metadata overwriting conditions
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_add.py
  saleor/graphql/checkout/tests/mutations/test_checkout_lines_update.py
Labels: skip changelog

#17555 Improve the way of handling tax-class
  saleor/graphql/product/tests/test_product_channel_listings_queries.py
  saleor/graphql/product/tests/test_variant_pricing.py
  saleor/graphql/product/types/channels.py
  saleor/graphql/product/types/products.py
  saleor/graphql/tax/dataloaders.py
  saleor/order/tests/benchmark/test_fetch_order_prices.py
  saleor/tax/calculations/checkout.py
  saleor/tax/calculations/order.py
  saleor/tax/tests/test_order_calculations.py
  saleor/tax/utils.py
Labels: skip changelog

#17534 Refactor: BaseCustomerCreate inheritance
  saleor/graphql/account/mutations/account/account_update.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/mutations/staff/customer_create.py
  saleor/graphql/account/mutations/staff/customer_update.py
Labels: skip changelog

#17563 Allow to change Admin email plugin custom templates back to default
  CHANGELOG.md
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/test_plugin.py
Labels: main

#17569 Allow to change custom templates back to default (#17563)
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/test_plugin.py
Labels: 3.19

#17570 Allow to change custom templates back to default (#17563)
  saleor/plugins/admin_email/plugin.py
  saleor/plugins/admin_email/tests/test_plugin.py
Labels: 3.20

#17571 Release 3.20.81
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17567 Drop `django-prices`
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  saleor/checkout/models.py
  saleor/checkout/tests/test_checkout.py
  saleor/core/db/fields.py
  saleor/discount/models.py
  saleor/giftcard/models.py
  saleor/graphql/core/types/money.py
  saleor/graphql/core/validators/__init__.py
  saleor/order/models.py
  saleor/payment/models.py
  saleor/plugins/email_common.py
  saleor/product/models.py
  saleor/settings.py
  saleor/shipping/models.py
Labels: technical debt, skip changelog

#17565 Rewrite checking sensitive content in payload to use visit_using_rules
  saleor/webhook/observability/obfuscation.py
Labels: skip changelog

#17578 Release 3.20.82
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17577 Fix `product.productVariants` resolver - do not require providing channel anymore
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/queries/test_product_query.py
  saleor/graphql/product/types/products.py
Labels: skip changelog, main

#17562 Introduce static typing for tax sync webhook responses
  saleor/checkout/calculations.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_calculations.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/core/taxes.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/order/calculations.py
  saleor/order/models.py
  saleor/order/tests/test_calculations.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
  saleor/plugins/manager.py
  saleor/plugins/tests/test_manager.py
  saleor/plugins/tests/test_manager_get_taxes.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_tax_webhook.py
  saleor/tax/tests/test_utils.py
  saleor/tax/utils.py
  saleor/tests/fixtures.py
  saleor/webhook/response_schemas/annotations.py
  saleor/webhook/response_schemas/shipping.py
  saleor/webhook/response_schemas/taxes.py
  saleor/webhook/tests/response_schemas/test_shipping.py
  saleor/webhook/tests/response_schemas/test_taxes.py
  saleor/webhook/tests/test_sync_webhooks_for_removed_app.py
  saleor/webhook/tests/test_tax_webhook_tasks.py
  saleor/webhook/tests/test_tax_webhook_utils.py
  saleor/webhook/transport/synchronous/__init__.py
  saleor/webhook/transport/synchronous/transport.py
  saleor/webhook/transport/utils.py
Labels: skip changelog

#17585 Drop the log indicating the mismatch of code usage
  saleor/order/tasks.py
  saleor/order/tests/test_tasks.py
Labels: skip changelog, main

#17584 Fix `PromotionRule.giftIds` resolver
  saleor/graphql/discount/tests/queries/test_promotion.py
  saleor/graphql/discount/types/promotions.py
Labels: skip changelog

#17588 Remove reference cycle in Saleor context
  saleor/graphql/context.py
  saleor/graphql/core/tests/garbage_collection/test_saleor_context.py
  saleor/graphql/core/tests/test_graphql.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_create.py
  saleor/graphql/order/mutations/order_confirm.py
Labels: skip changelog, main

#17564 Remove reference cycles in Promise
  saleor/graphql/core/tests/garbage_collection/test_promise.py
  saleor/graphql/promise.py
  saleor/settings.py
Labels: skip changelog, main

#17589 Remove reference cycle in Gzip
  saleor/asgi/gzip_compression.py
  saleor/graphql/core/tests/garbage_collection/test_gzip.py
  saleor/patch_gzip.py
  saleor/settings.py
Labels: skip changelog, main

#17592 Remove reference cycle in Django DB
  saleor/core/db/patch.py
  saleor/graphql/core/tests/garbage_collection/test_django.py
  saleor/settings.py
Labels: skip changelog, main

#17594 Remove reference cycle in Asgiref Local
  saleor/graphql/core/tests/garbage_collection/test_asgiref.py
  saleor/patch_local.py
  saleor/settings.py
Labels: skip changelog, main

#17586 Return shipping app id in ShippingMethodSchema.id
  saleor/webhook/response_schemas/shipping.py
  saleor/webhook/tests/response_schemas/test_shipping.py
  saleor/webhook/transport/shipping.py
Labels: skip changelog

#17593 Fix PositiveDecimal scalar
  saleor/graphql/core/scalars.py
  saleor/graphql/core/tests/test_scalars.py
  saleor/graphql/core/tests/test_scalars_decimals.py
Labels: skip changelog

#17573 Change Discord Workflow from "good first issue" to "help wanted"
  .github/workflows/help-wanted-issues-to-discord.yml
Labels: skip changelog

#17598 Fix incorrect call of PluginsManager.get_tax_code_from_object_meta
  saleor/graphql/product/tests/queries/test_product_type_query.py
  saleor/graphql/product/types/products.py
Labels: skip changelog

#17597 fix flaky tests: Do not relay on order of returned shipping methods in tests
  saleor/graphql/webhook/tests/pregenerated_subscription/test_checkout_resolvers.py
Labels: skip changelog

#17590 Add migration for orders with `awaiting_for_approval` fulfillment
  saleor/order/migrations/0200_order_with_waiting_for_approval_fulfillments.py
  saleor/order/migrations/tasks/saleor3_21.py
Labels: migrations perf test, skip changelog, 3.21

#17582 Prevent race condition when creating customers
  saleor/graphql/account/mutations/account/account_update.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/mutations/staff/customer_create.py
  saleor/graphql/account/mutations/staff/customer_update.py
  saleor/graphql/account/tests/mutations/staff/test_customer_create.py
  saleor/tests/race_condition.py
Labels: skip changelog

#17606 Drop unused SEO functions
  saleor/seo/schema/__init__.py
  saleor/seo/schema/email.py
  saleor/seo/tests/__init__.py
  saleor/seo/tests/test_seo_schema.py
Labels: skip changelog

#17621 Use latest ubuntu build in publish-load-test job
  .github/workflows/publish-load-test.yml
Labels: skip changelog

#17628 fix: invalid cache action usage for pre-commit
  .github/workflows/tests-and-linters.yml
Labels: bug, skip changelog

#17612 Update denormalized discounts when adding a new line discount
  saleor/discount/interface.py
  saleor/discount/tests/test_utils/test_copy_unit_discount_data_to_order_line.py
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_order.py
  saleor/discount/tests/test_utils/test_create_voucher_discount_object_for_order.py
  saleor/discount/tests/test_utils/test_update_voucher_discount_object_for_order.py
  saleor/discount/utils/order.py
  saleor/discount/utils/promotion.py
  saleor/discount/utils/voucher.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/order/tests/deprecated/test_order.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_order_discount.py
  saleor/graphql/order/tests/mutations/test_order_line_update.py
  saleor/order/calculations.py
  saleor/order/tests/fixtures/order.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/order/tests/test_fetch_order_prices_line_price_expiration.py
  saleor/order/tests/test_fetch_order_prices_tax_app.py
  saleor/order/tests/test_refresh_order_base_prices_and_discounts.py
  saleor/order/utils.py
Labels: skip changelog

#17631 Fix `PromotionRule.giftIds` resolver
  saleor/graphql/discount/tests/queries/test_promotion.py
  saleor/graphql/discount/types/promotions.py
Labels: 3.20

#17632 Fixes an issue where totalRefund was incorrect for fully refunded payments.
  saleor/graphql/order/tests/queries/test_order_amounts.py
  saleor/graphql/order/types.py
Labels: skip changelog

#17633 Fixes an issue where totalRefund was incorrect for fully refunded payments.
  saleor/graphql/order/tests/queries/test_order_amounts.py
  saleor/graphql/order/types.py
Labels: 3.20

#17622 Use use_legacy_line_voucher_propagation_for_order to control entire-order propagation
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/tests/e2e/checkout/discounts/test_checkout_calculate_correct_discount_for_sale_and_voucher.py
  saleor/tests/e2e/checkout/discounts/test_checkout_with_promotion_and_voucher.py
  saleor/tests/e2e/shop/utils/preparing_shop.py
Labels: skip changelog

#17644 Upgrade `pillow-avif-plugin`
  poetry.lock
  pyproject.toml
  saleor/graphql/core/tests/test_file_validation.py
Labels: skip changelog

#17637 Rename flag to useLegacyLineDiscountPropagation
  saleor/channel/migrations/0021_rename_use_legacy_line_voucher_propagation_for_order_channel_use_legacy_line_discount_propagation_fo.py
  saleor/channel/models.py
  saleor/checkout/complete_checkout.py
  saleor/graphql/channel/mutations/channel_create.py
  saleor/graphql/channel/mutations/utils.py
  saleor/graphql/channel/tests/mutations/test_channel_create.py
  saleor/graphql/channel/tests/mutations/test_channel_update.py
  saleor/graphql/channel/tests/queries/test_channel.py
  saleor/graphql/channel/types.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/tests/queries/test_order_line.py
  saleor/graphql/order/types.py
  saleor/graphql/schema.graphql
  saleor/tests/e2e/checkout/discounts/test_checkout_calculate_correct_discount_for_sale_and_voucher.py
  saleor/tests/e2e/checkout/discounts/test_checkout_with_promotion_and_voucher.py
Labels: migrations perf test, skip changelog

#17540 Remove channel to be required from request password reset mutation
  CHANGELOG.md
  saleor/account/tasks.py
  saleor/graphql/account/mutations/authentication/request_password_reset.py
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#17641 Fix a potential race condition when creating a new user instance via the AccountRegister mutation
  saleor/graphql/account/mutations/account/account_register.py
  saleor/graphql/account/tests/mutations/account/test_account_register.py
  saleor/graphql/account/tests/mutations/staff/test_customer_create.py
Labels: skip changelog

#17659 Drop deprecated runner
  .github/workflows/publish-release-tag.yml
Labels: skip changelog

#17658 Make sure to set default value for legacy-discount-propagation flag
  saleor/graphql/channel/mutations/channel_create.py
  saleor/graphql/channel/tests/mutations/test_channel_create.py
  saleor/graphql/channel/tests/mutations/test_channel_update.py
Labels: skip changelog

#17661 Add benchmark test for `draftOrderUpdate` mutation
  saleor/graphql/order/tests/benchmark/test_draft_order_update.py
Labels: skip changelog, tests

#17639 Add GraphQL metrics
  saleor/core/telemetry/__init__.py
  saleor/core/telemetry/metric.py
  saleor/graphql/metrics.py
  saleor/graphql/query_cost_map.py
  saleor/graphql/tests/test_metrics.py
  saleor/graphql/utils/__init__.py
  saleor/graphql/views.py
Labels: skip changelog
