Repository saleor/saleor, pull requests merged in 2025-05, with the labels that each got.

#17666 Release 3.20.83
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17669 Release 3.20.84
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17660 Use correct env for GS_MEDIA_PRIVATE_BUCKET_NAME
  saleor/settings.py
Labels: skip changelog

#17670 Update ubuntu version on workflows
  .github/workflows/publish-containers.yml
  .github/workflows/publish-load-test.yml
Labels: 3.20

#17663 Add HTTP metrics
  saleor/core/telemetry/utils.py
  saleor/graphql/metrics.py
  saleor/graphql/tests/test_metrics.py
  saleor/graphql/views.py
Labels: skip changelog

#17673 Release 3.20.85
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17646 Telemetry - Fix `TelemetryTaskContext` serialization
  saleor/core/telemetry/tests/test_utils.py
  saleor/core/telemetry/utils.py
Labels: skip changelog

#17671 changelogs: add missing breaking change for GCP private storage
  CHANGELOG.md
Labels: skip changelog, docs

#17679 Properly return CANCEL fulfilments in order resolver for app [3.20]
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/types.py
Labels: 3.20

#17677 Properly return CANCEL fulfilments in order resolver for app
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/types.py
Labels: skip changelog

#17682 Revert adding `createdAutomatically` to `TransactionEvent` type
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/graphql/payment/types.py
  saleor/graphql/schema.graphql
Labels: 3.20

#17672 Telemetry - Bump OTEL dependencies
  poetry.lock
  pyproject.toml
  saleor/core/telemetry/metric.py
  saleor/core/telemetry/tests/test_metric.py
  saleor/tests/settings.py
  saleor/tests/utils.py
  saleor/webhook/transport/asynchronous/tests/test_transport.py
  saleor/webhook/transport/synchronous/tests/test_transport.py
Labels: skip changelog

#17678 Change `DEFAULT_MAX_DIGITS` to 20
  saleor/checkout/migrations/0075_alter_checkout_base_subtotal_amount_and_more.py
  saleor/discount/migrations/0085_alter_checkoutdiscount_amount_value_and_more.py
  saleor/giftcard/migrations/0021_alter_giftcard_current_balance_amount_and_more.py
  saleor/order/migrations/0196_alter_fulfillment_shipping_refund_amount_and_more.py
  saleor/order/tests/test_calculations.py
  saleor/payment/migrations/0060_alter_payment_captured_amount_alter_payment_total_and_more.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/product/migrations/0195_alter_productchannellisting_discounted_price_amount_and_more.py
  saleor/settings.py
  saleor/shipping/migrations/0035_alter_shippingmethodchannellisting_maximum_order_price_amount_and_more.py
  saleor/tax/migrations/0009_alter_taxclasscountryrate_rate.py
  saleor/tax/tests/test_utils.py
Labels: 3.20

#17684 Release 3.20.86
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17655 Add static typing for transaction events
  saleor/graphql/payment/mutations/transaction/payment_gateway_initialize.py
  saleor/graphql/payment/tests/mutations/test_payment_gateway_initialize.py
  saleor/payment/interface.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_payment_gateway_initialize_session_webhook.py
  saleor/webhook/response_schemas/annotations.py
  saleor/webhook/response_schemas/transaction.py
  saleor/webhook/tests/response_schemas/test_transaction.py
Labels: skip changelog

#17680 Change `DEFAULT_MAX_DIGITS` to 20
  saleor/checkout/migrations/0075_alter_checkout_base_subtotal_amount_and_more.py
  saleor/checkout/migrations/0078_merge_20250507_0613.py
  saleor/discount/migrations/0085_alter_checkoutdiscount_amount_value_and_more.py
  saleor/giftcard/migrations/0021_alter_giftcard_current_balance_amount_and_more.py
  saleor/order/migrations/0196_alter_fulfillment_shipping_refund_amount_and_more.py
  saleor/order/migrations/0201_merge_20250507_0613.py
  saleor/order/tests/test_calculations.py
  saleor/payment/migrations/0060_alter_payment_captured_amount_alter_payment_total_and_more.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/product/migrations/0195_alter_productchannellisting_discounted_price_amount_and_more.py
  saleor/product/migrations/0198_merge_20250507_0613.py
  saleor/settings.py
  saleor/shipping/migrations/0035_alter_shippingmethodchannellisting_maximum_order_price_amount_and_more.py
  saleor/tax/migrations/0009_alter_taxclasscountryrate_rate.py
Labels: skip changelog, main

#17668 Introduce static typing for `LIST_STORED_PAYMENT_METHODS` webhook
  saleor/payment/interface.py
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/webhook/response_schemas/annotations.py
  saleor/webhook/response_schemas/payment.py
  saleor/webhook/response_schemas/shipping.py
  saleor/webhook/response_schemas/validators.py
  saleor/webhook/tests/response_schemas/test_payment.py
  saleor/webhook/tests/response_schemas/test_shipping.py
  saleor/webhook/tests/response_schemas/test_validators.py
  saleor/webhook/tests/test_utils.py
  saleor/webhook/transport/list_stored_payment_methods.py
  saleor/webhook/transport/shipping.py
Labels: skip changelog, 3.20

#17681 Enhance `TransactionEvent` handling
  saleor/graphql/payment/tests/queries/test_transaction.py
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: skip changelog, main

#17686 Migrate pre-commit
  .pre-commit-config.yaml
Labels: 3.20

#17685 Implementation of resource limits.
  saleor/core/rlimit.py
  saleor/core/tests/test_rlimit.py
  saleor/settings.py
Labels: 3.20

#17691 Format validation error for `TransactionEvent` and tax webhooks
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
  saleor/plugins/webhook/plugin.py
  saleor/plugins/webhook/tests/test_shipping_webhook.py
  saleor/webhook/response_schemas/payment.py
  saleor/webhook/response_schemas/shipping.py
  saleor/webhook/response_schemas/transaction.py
  saleor/webhook/response_schemas/utils/__init__.py
  saleor/webhook/response_schemas/utils/annotations.py
  saleor/webhook/response_schemas/utils/helpers.py
  saleor/webhook/response_schemas/utils/validators.py
  saleor/webhook/tests/response_schemas/test_helpers.py
  saleor/webhook/tests/response_schemas/test_payment.py
  saleor/webhook/tests/response_schemas/test_shipping.py
  saleor/webhook/tests/response_schemas/test_transaction.py
  saleor/webhook/tests/response_schemas/test_validators.py
  saleor/webhook/tests/test_utils.py
Labels: skip changelog, main

#17692 Implementation of resource limits.
  saleor/core/rlimit.py
  saleor/core/tests/test_rlimit.py
  saleor/settings.py
Labels: skip changelog, main

#17693 Ensure that transaction event time is properly transformed to UTC
  saleor/webhook/response_schemas/utils/annotations.py
  saleor/webhook/tests/response_schemas/test_transaction.py
Labels: skip changelog, main

#17701 Make token generator class configurable
  CHANGELOG.md
  saleor/account/notifications.py
  saleor/account/tasks.py
  saleor/account/tests/test_notifications.py
  saleor/core/tokens.py
  saleor/graphql/account/mutations/account/confirm_account.py
  saleor/graphql/account/mutations/account/send_confirmation_email.py
  saleor/graphql/account/mutations/authentication/set_password.py
  saleor/graphql/account/mutations/staff/customer_create.py
  saleor/graphql/account/mutations/staff/staff_create.py
  saleor/graphql/account/tests/mutations/account/test_account_register.py
  saleor/graphql/account/tests/mutations/account/test_confirm_account.py
  saleor/graphql/account/tests/mutations/account/test_send_confirmation_email.py
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
  saleor/graphql/account/tests/mutations/authentication/test_set_password.py
  saleor/graphql/account/tests/mutations/staff/test_customer_create.py
  saleor/graphql/account/tests/mutations/staff/test_staff_create.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/settings.py
Labels: main, do not merge

#17704 Telemetry - Drop setting span attributes with IPs
  saleor/graphql/views.py
Labels: skip changelog

#17702 Add Semgrep rule to prevent using Django's default token generator
  .semgrep/Makefile
  .semgrep/correctness/django/django-no-default-token-generator.py
  .semgrep/correctness/django/django-no-default-token-generator.yaml
Labels: skip changelog

#17703 actions: update Semgrep to latest supported version
  .github/workflows/test-semgrep-rules.yml
  poetry.lock
  pyproject.toml
Labels: technical debt, skip changelog

#17706 Make token generator class configurable
  saleor/account/notifications.py
  saleor/account/tests/test_notifications.py
  saleor/core/tokens.py
  saleor/graphql/account/mutations/account/account_register.py
  saleor/graphql/account/mutations/account/account_request_deletion.py
  saleor/graphql/account/mutations/account/confirm_account.py
  saleor/graphql/account/mutations/account/send_confirmation_email.py
  saleor/graphql/account/mutations/authentication/request_password_reset.py
  saleor/graphql/account/mutations/authentication/set_password.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/mutations/staff/staff_create.py
  saleor/graphql/account/tests/mutations/account/test_account_register.py
  saleor/graphql/account/tests/mutations/account/test_confirm_account.py
  saleor/graphql/account/tests/mutations/account/test_send_confirmation_email.py
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
  saleor/graphql/account/tests/mutations/authentication/test_set_password.py
  saleor/graphql/account/tests/mutations/staff/test_customer_create.py
  saleor/graphql/account/tests/mutations/staff/test_staff_create.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/settings.py
Labels: 3.19

#17707 deps: upgrade urllib3 from v1.x to v2.x
  .github/workflows/test-semgrep-rules.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  saleor/payment/gateways/braintree/tests/test_braintree.py
  saleor/plugins/openid_connect/tests/test_utils.py
Labels: dependencies

#17688 Add static typing for `STORED_PAYMENT_METHOD_DELETE_REQUESTED` webhook
  saleor/plugins/webhook/tests/test_stored_payment_method_request_delete.py
  saleor/webhook/response_schemas/annotations.py
  saleor/webhook/response_schemas/payment.py
  saleor/webhook/response_schemas/utils/annotations.py
  saleor/webhook/tests/conftest.py
  saleor/webhook/tests/response_schemas/test_payment.py
  saleor/webhook/tests/test_utils.py
  saleor/webhook/transport/list_stored_payment_methods.py
  saleor/webhook/transport/tests/test_list_stored_payment_methods.py
Labels: skip changelog, main

#17695 Refactor `productVariantUpdate` mutations
  saleor/graphql/attribute/utils.py
  saleor/graphql/product/mutations/product_variant/product_variant_cleaner.py
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/graphql/product/mutations/product_variant/product_variant_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
Labels: skip changelog

#17694 Refactor `draftOrderUpdate` mutation
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
Labels: skip changelog

#17705 Add static typing for `PAYMENT_GATEWAY_INITIALIZE_TOKENIZATION_SESSION`
  saleor/payment/interface.py
  saleor/webhook/response_schemas/payment.py
  saleor/webhook/tests/response_schemas/test_payment.py
  saleor/webhook/transport/list_stored_payment_methods.py
  saleor/webhook/transport/tests/test_list_stored_payment_methods.py
Labels: skip changelog, main

#17708 Add static typing for paymenr method tokenization
  saleor/plugins/webhook/tests/test_payment_method_initialize_tokenization.py
  saleor/plugins/webhook/tests/test_payment_method_process_tokenization.py
  saleor/plugins/webhook/tests/test_stored_payment_method_request_delete.py
  saleor/webhook/response_schemas/payment.py
  saleor/webhook/response_schemas/utils/helpers.py
  saleor/webhook/tests/response_schemas/test_helpers.py
  saleor/webhook/tests/response_schemas/test_payment.py
  saleor/webhook/transport/list_stored_payment_methods.py
  saleor/webhook/transport/tests/test_list_stored_payment_methods.py
Labels: skip changelog, main

#17700 Make token generator class configurable
  .semgrep/Makefile
  .semgrep/correctness/django/django-no-default-token-generator.py
  .semgrep/correctness/django/django-no-default-token-generator.yaml
  saleor/account/notifications.py
  saleor/account/tests/test_notifications.py
  saleor/core/tokens.py
  saleor/graphql/account/mutations/account/account_register.py
  saleor/graphql/account/mutations/account/account_request_deletion.py
  saleor/graphql/account/mutations/account/confirm_account.py
  saleor/graphql/account/mutations/account/send_confirmation_email.py
  saleor/graphql/account/mutations/authentication/request_password_reset.py
  saleor/graphql/account/mutations/authentication/set_password.py
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/mutations/staff/staff_create.py
  saleor/graphql/account/tests/mutations/account/test_account_register.py
  saleor/graphql/account/tests/mutations/account/test_confirm_account.py
  saleor/graphql/account/tests/mutations/account/test_send_confirmation_email.py
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
  saleor/graphql/account/tests/mutations/authentication/test_set_password.py
  saleor/graphql/account/tests/mutations/staff/test_customer_create.py
  saleor/graphql/account/tests/mutations/staff/test_staff_create.py
  saleor/plugins/webhook/tests/test_webhook.py
  saleor/settings.py
Labels: 3.20

#17718 Bump runner
  .github/workflows/publish-containers.yml
Labels: 3.19

#17717 Release 3.20.88
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17713 Drop graphql.operation.name attribute from metrics
  saleor/graphql/metrics.py
  saleor/graphql/tests/test_metrics.py
  saleor/graphql/views.py
Labels: skip changelog

#17656 Apply `InstanceTracker` to `DraftOrderUpdate` mutation
  saleor/core/utils/tests/test_update_mutation_manager.py
  saleor/core/utils/update_mutation_manager.py
  saleor/graphql/account/mutations/account/utils.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/mutations/utils.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
Labels: skip changelog

#17710 Update required pydantic version
  poetry.lock
  pyproject.toml
Labels: skip changelog

#17640 Apply `InstanceTracker` to `ProductVariantUpdate` mutation
  saleor/graphql/product/mutations/product_variant/product_variant_create.py
  saleor/graphql/product/mutations/product_variant/product_variant_update.py
  saleor/graphql/product/mutations/utils.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/product/models.py
Labels: performance, skip changelog

#17733 Release 3.21.0
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17461 Rewrite order 199 migration from celery task to standard migration
  saleor/order/migrations/0199_set_draft_base_price_expire_at.py
  saleor/order/migrations/tasks/saleor3_21.py
Labels: migration, migrations perf test, skip changelog, 3.22

#17742 Lock order during order amounts recalculation in TransactionEventReport mutation
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/order/utils.py
Labels: 3.20

#17747 Release 3.20.89
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17732 Fix IntegrityError when providing tracking as null to orderFulfill mutation
  saleor/graphql/order/mutations/order_fulfill.py
  saleor/graphql/order/tests/mutations/test_order_fulfill.py
Labels: skip changelog

#17738 Fix error when providing tracking as null to orderFulfill
  saleor/graphql/order/mutations/order_fulfill.py
  saleor/graphql/order/tests/mutations/test_order_fulfill.py
Labels: 3.21

#17752 Improve transaction json schema
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
  saleor/webhook/response_schemas/transaction.py
  saleor/webhook/tests/response_schemas/test_transaction.py
Labels: skip changelog

#17591 Rewrite order 0200 migration to standard migration
  saleor/order/migrations/0200_order_with_waiting_for_approval_fulfillments.py
  saleor/order/migrations/tasks/saleor3_21.py
Labels: migrations perf test, skip changelog, 3.22

#17749 Lock order during order amounts recalculation in TransactionEventReport mutation
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/order/utils.py
Labels: 3.21

#17756 Release 3.21.1
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17759 Telemetry - Add explicit histogram bucket boundaries for metrics
  saleor/core/telemetry/__init__.py
  saleor/core/telemetry/metric.py
  saleor/graphql/metrics.py
  saleor/webhook/transport/metrics.py
Labels: skip changelog

#17758 Use calculation module for building PaymentData object instead of direct plugin calls
  saleor/payment/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.21

#17757 Use dataloader in checkout resolver
  saleor/graphql/checkout/resolvers.py
  saleor/graphql/checkout/tests/benchmark/test_checkout.py
Labels: 3.21

#17753 Use checkout/order email instead of user.email
  saleor/checkout/complete_checkout.py
  saleor/checkout/fetch.py
  saleor/checkout/models.py
  saleor/discount/tests/test_utils/test_get_customer_email_for_voucher_usage.py
  saleor/discount/utils/voucher.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_checkout_create.py
  saleor/graphql/checkout/tests/mutations/test_checkout_customer_attach.py
  saleor/graphql/checkout/tests/mutations/test_checkout_email_update.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/draft_order_update.py
  saleor/graphql/order/tests/queries/test_order.py
  saleor/graphql/order/types.py
  saleor/graphql/payment/tests/mutations/test_checkout_payment_create.py
  saleor/order/models.py
  saleor/order/tasks.py
  saleor/order/tests/test_order_utils.py
Labels: skip changelog

#17730 Add possibility to use weighted shipping tax rate
  saleor/checkout/calculations.py
  saleor/checkout/tests/test_calculations.py
  saleor/graphql/schema.graphql
  saleor/graphql/tax/mutations/tax_configuration_update.py
  saleor/graphql/tax/tests/fragments.py
  saleor/graphql/tax/tests/mutations/test_tax_configuration_update.py
  saleor/graphql/tax/tests/queries/test_tax_configuration.py
  saleor/graphql/tax/types.py
  saleor/graphql/webhook/dataloaders/pregenerated_payload_for_checkout_tax.py
  saleor/order/tests/benchmark/test_fetch_order_prices.py
  saleor/order/tests/test_calculations.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/plugin.py
  saleor/tax/calculations/checkout.py
  saleor/tax/calculations/order.py
  saleor/tax/migrations/0010_taxconfiguration_use_weighted_tax_for_shipping_and_more.py
  saleor/tax/models.py
  saleor/tax/tests/test_checkout_calculations.py
  saleor/tax/tests/test_order_calculations.py
  saleor/tax/tests/test_utils.py
  saleor/tax/utils.py
  saleor/webhook/serializers.py
Labels: 3.21
