Repository saleor/saleor, pull requests merged in 2025-02, with the labels that each got.

#17309 Remove reference cycle in Saleor context
  saleor/graphql/context.py
  saleor/graphql/core/tests/test_graphql.py
  saleor/graphql/giftcard/bulk_mutations/gift_card_bulk_create.py
  saleor/graphql/order/mutations/order_confirm.py
Labels: 3.20

#17315 Move source-service-name from HTTP to GraphQL span
  saleor/graphql/views.py
Labels: skip changelog, main

#17317 Revert `sync` back to `install`
  Dockerfile
Labels: skip changelog

#17313 Remove reference cycle in Django DB
  saleor/core/db/patch.py
  saleor/settings.py
Labels: 3.20

#17300 Adjust order fulfillment
  saleor/giftcard/tests/test_utils.py
  saleor/giftcard/utils.py
  saleor/graphql/checkout/tests/deprecated/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/order/mutations/order_confirm.py
  saleor/graphql/order/mutations/order_fulfill.py
  saleor/graphql/order/tests/deprecated/test_order.py
  saleor/graphql/order/tests/mutations/test_fulfillment_approve.py
  saleor/graphql/order/tests/mutations/test_order_fulfill.py
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/order/actions.py
  saleor/order/events.py
  saleor/order/tests/test_fulfillments_actions.py
  saleor/order/tests/test_order.py
  saleor/order/tests/test_order_actions.py
  saleor/order/utils.py
Labels: 3.20

#17318 Remove reference cycle in gzip
  saleor/asgi/gzip_compression.py
  saleor/patch_gzip.py
  saleor/settings.py
Labels: 3.20

#17060 Update test_create_transaction_event_message_limit_exceeded
  saleor/payment/tests/test_utils.py
Labels: 3.20

#17322 Release 3.20.69
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17324 Fix csv exporter for products
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/test_export.py
  saleor/csv/utils/__init__.py
  saleor/csv/utils/export.py
  saleor/csv/utils/product_headers.py
  saleor/csv/utils/products_data.py
Labels: 3.20

#17321 Fix csv exporter for products
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/test_export.py
  saleor/csv/utils/__init__.py
  saleor/csv/utils/export.py
  saleor/csv/utils/product_headers.py
  saleor/csv/utils/products_data.py
Labels: skip changelog

#17325 Ensure the status is refreshed in `CheckoutComplete` and `OrderCreateFromCheckout`
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/order/mutations/order_confirm.py
  saleor/order/actions.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
Labels: 3.20

#17336 Release 3.20.70
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17335 Port GitHub workflow updates
  .github/CODEOWNERS
  .github/workflows/pytest.yml
  .github/workflows/test-migrations-compatibility.yml
Labels: 3.17

#17343 Bring back removed link to roadmap
  README.md
Labels: skip changelog

#17332 Fix checkout order line creation in case of empty `ProductTranslation`
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
  saleor/product/models.py
Labels: 3.19

#17333 Fix checkout order line creation in case of empty `ProductTranslation`
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
  saleor/product/models.py
Labels: 3.17

#17330 Fix checkout order line creation in case of empty `ProductTranslation`
  saleor/checkout/complete_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/order/tests/test_order.py
  saleor/order/utils.py
  saleor/product/models.py
Labels: skip changelog, main

#17301 Adjust order fulfillment
  saleor/checkout/tests/test_checkout_complete.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/giftcard/tests/test_utils.py
  saleor/giftcard/utils.py
  saleor/graphql/checkout/tests/deprecated/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/order/mutations/order_confirm.py
  saleor/graphql/order/mutations/order_fulfill.py
  saleor/graphql/order/tests/deprecated/test_order.py
  saleor/graphql/order/tests/mutations/test_fulfillment_approve.py
  saleor/graphql/order/tests/mutations/test_order_fulfill.py
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/order/actions.py
  saleor/order/events.py
  saleor/order/tests/test_fulfillments_actions.py
  saleor/order/tests/test_order.py
  saleor/order/tests/test_order_actions.py
  saleor/order/utils.py
Labels: skip changelog, main

#17347 Update contributing guide with changes from saleor-docs
  CONTRIBUTING.md
  README.md
Labels: skip changelog

#17342 Fix productVariantBulkUpdate not saved fields to DB
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
Labels: skip changelog

#17357 Fix productVariantBulkUpdate not saved fields to DB (3.20)
  saleor/graphql/product/bulk_mutations/product_variant_bulk_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_bulk_update.py
Labels: 3.20

#17361 Fix test warning message
  setup.cfg
Labels: skip changelog

#17368 Regenerate poetry.lock file
  poetry.lock
Labels: skip changelog

#17370 Fix devcontainer setup by install poetry via pipx
  .devcontainer/Dockerfile
Labels: skip changelog

#17344 Remove c&c when assigning shipping method with CheckoutShippingMethodUpdate
  saleor/graphql/checkout/mutations/checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_method_update.py
Labels: 3.20

#17367 Improve pre commit config
  .pre-commit-config.yaml
Labels: skip changelog

#17360 Add ipdb
  .devcontainer/common.env
  .gitignore
  CONTRIBUTING.md
  poetry.lock
  pyproject.toml
  setup.cfg
Labels: skip changelog

#17356 Add common tasks via PoeThePoet
  .env.example
  .gitignore
  CONTRIBUTING.md
  package.json
  poetry.lock
  pyproject.toml
Labels: skip changelog

#17383 Remove reference cycle when query returns error.
  saleor/graphql/core/tests/garbage_collection/__init__.py
  saleor/graphql/core/tests/garbage_collection/test_errors.py
  saleor/graphql/core/tests/garbage_collection/utils.py
  saleor/graphql/error.py
  saleor/graphql/executor.py
  saleor/graphql/graphql_core.py
  saleor/graphql/views.py
  saleor/settings.py
  setup.cfg
Labels: 3.20

#17391 Release 3.20.71
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: 3.20, release

#17369 Add poetry lock check to pre commit
  .pre-commit-config.yaml
Labels: skip changelog

#17353 Improve setup for local development
  .devcontainer/docker-compose.yml
  CONTRIBUTING.md
Labels: skip changelog

#17380 Prevent race conditions on customerCreate and accountUpdate [3.20]
  saleor/graphql/account/mutations/base.py
  saleor/graphql/account/tests/mutations/staff/test_customer_create.py
Labels: 3.20

#17390 Cancel stale jobs after new push
  .github/workflows/pytest.yml
Labels: skip changelog

#17284 Use denormalized prices during order update for vouchers
  saleor/discount/tests/test_discounts.py
  saleor/discount/tests/test_utils/test_copy_unit_discount_data_to_order_line.py
  saleor/discount/tests/test_utils/test_create_voucher_discount_object_for_order.py
  saleor/discount/tests/test_utils/test_update_voucher_discount_object_for_order.py
  saleor/discount/utils/order.py
  saleor/discount/utils/promotion.py
  saleor/discount/utils/voucher.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/order_line_update.py
  saleor/graphql/order/mutations/order_update_shipping.py
  saleor/graphql/order/mutations/utils.py
  saleor/graphql/order/tests/deprecated/test_discount_order.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/graphql/order/tests/mutations/test_order_discount.py
  saleor/graphql/order/tests/mutations/test_order_line_update.py
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/graphql/order/tests/mutations/test_order_update_shipping.py
  saleor/order/fetch.py
  saleor/order/tests/benchmark/test_fetch_order_prices.py
  saleor/order/tests/fixtures/order.py
  saleor/order/tests/test_fetch.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/order/tests/test_fetch_order_prices_tax_app.py
  saleor/order/tests/test_order.py
  saleor/order/tests/test_order_utils.py
  saleor/order/utils.py
  saleor/product/tests/fixtures/variant.py
  saleor/tests/e2e/orders/discounts/test_manual_order_discount_and_voucher.py
  saleor/webhook/tests/subscription_webhooks/test_create_deliveries_for_taxes.py
Labels: order, voucher, pricing

#17388 Add test cmd to poe
  CONTRIBUTING.md
  pyproject.toml
Labels: skip changelog

#17392 Turn off pre-generated checkout paylaods for bulk checkouts queries
  saleor/graphql/checkout/types.py
  saleor/graphql/webhook/tests/pregenerated_subscription/test_checkout_resolvers.py
Labels: skip changelog

#17381 Denormalize assigned shipping method to checkout
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/migrations/0073_checkout_external_shipping_method_id_and_more.py
  saleor/checkout/migrations/0075_merge_20250210_1203.py
  saleor/checkout/models.py
  saleor/checkout/tests/fixtures/checkout.py
  saleor/checkout/tests/test_calculations.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/tests/test_delivery_assignent_to_checkout.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/mutations/checkout_shipping_method_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/benchmark/test_homepage.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_method_update.py
  saleor/graphql/checkout/tests/mutations/test_utils.py
  saleor/graphql/checkout/tests/test_checkout_price_expiration.py
Labels: skip changelog

#17339 Add fields to checkout to store external shipping method
  saleor/checkout/calculations.py
  saleor/checkout/migrations/0073_checkout_external_shipping_method_id_and_more.py
  saleor/checkout/models.py
  saleor/checkout/tests/test_calculations.py
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
  saleor/graphql/checkout/mutations/checkout_delivery_method_update.py
  saleor/graphql/checkout/mutations/checkout_shipping_method_update.py
  saleor/graphql/checkout/mutations/utils.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/checkout/tests/benchmark/test_homepage.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_payment.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete_with_transactions.py
  saleor/graphql/checkout/tests/mutations/test_checkout_delivery_method_update.py
  saleor/graphql/checkout/tests/mutations/test_checkout_shipping_method_update.py
Labels: 3.20

#17403 Release 3.20.72
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17404 Use sys.monitoring for coverage tracking
  .github/workflows/pytest.yml
  setup.cfg
Labels: skip changelog

#17413 Use logical instead of physical cores to detect pytest workers
  .github/workflows/pytest.yml
Labels: skip changelog

#17401 Skip pre-generate payload for exclude shipping when webhooks are blocked
  saleor/graphql/checkout/dataloaders/checkout_infos.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
  saleor/graphql/core/types/taxes.py
  saleor/graphql/webhook/tests/pregenerated_subscription/test_checkout_resolvers.py
Labels: skip changelog

#17407 Make sure that clear_delivery_method handles external shipping
  saleor/checkout/tests/test_checkout.py
  saleor/checkout/utils.py
Labels: 3.20

#17416 Add missing tests for garbage collecting
  saleor/graphql/core/tests/garbage_collection/test_asgiref.py
  saleor/graphql/core/tests/garbage_collection/test_django.py
  saleor/graphql/core/tests/garbage_collection/test_gzip.py
  saleor/graphql/core/tests/garbage_collection/test_oauth2.py
  saleor/graphql/core/tests/garbage_collection/test_promise.py
  saleor/graphql/core/tests/garbage_collection/test_saleor_context.py
  saleor/graphql/core/tests/garbage_collection/utils.py
Labels: 3.20

#17433 Fix discord invite link
  README.md
Labels: skip changelog

#17426 Fix missing prefetch on update_discounted_prices_for_promotion task
  saleor/product/utils/variant_prices.py
Labels: skip changelog

#16658 Circuit breakers for sync webhooks
  CHANGELOG.md
  conftest.py
  saleor/graphql/app/enums.py
  saleor/graphql/app/mutations/__init__.py
  saleor/graphql/app/mutations/app_reenable_sync_webhooks.py
  saleor/graphql/app/schema.py
  saleor/graphql/app/tests/mutations/test_reenable_sync_webhooks.py
  saleor/graphql/app/tests/queries/test_app.py
  saleor/graphql/app/types.py
  saleor/graphql/schema.graphql
  saleor/settings.py
  saleor/tests/settings.py
  saleor/webhook/circuit_breaker/breaker_board.py
  saleor/webhook/circuit_breaker/storage.py
  saleor/webhook/tests/circuit_breaker/__init__.py
  saleor/webhook/tests/circuit_breaker/fixtures.py
  saleor/webhook/tests/circuit_breaker/test_breaker_board.py
  saleor/webhook/tests/circuit_breaker/test_breaker_board_decorator.py
  saleor/webhook/tests/circuit_breaker/test_redis_storage.py
  saleor/webhook/tests/circuit_breaker/utils.py
  saleor/webhook/transport/synchronous/transport.py
Labels: main

#17434 Release 3.20.73
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17435 Update README with permanent Discord link and new logo
  README.md
Labels: skip changelog

#17437 Merge account and users e2e directories
  saleor/tests/e2e/account/account/__init__.py
  saleor/tests/e2e/account/account/test_login_throttling.py
  saleor/tests/e2e/account/account/test_should_create_account_without_email_confirmation.py
  saleor/tests/e2e/account/account/test_should_login_before_email_confirmation.py
  saleor/tests/e2e/account/account/test_should_not_be_able_to_create_account_with_existing_email.py
  saleor/tests/e2e/account/account/test_should_not_be_able_to_login_with_invalid_credentials.py
  saleor/tests/e2e/account/staff/__init__.py
  saleor/tests/e2e/account/staff/test_create_and_update_customer_with_metadata.py
  saleor/tests/e2e/account/staff/test_create_and_update_staff_with_metadata.py
  saleor/tests/e2e/account/staff/test_should_bulk_update_customers_metadata.py
  saleor/tests/e2e/account/utils/__init__.py
  saleor/tests/e2e/account/utils/create_customer.py
  saleor/tests/e2e/account/utils/customer_bulk_update.py
  saleor/tests/e2e/account/utils/customer_update.py
  saleor/tests/e2e/account/utils/staff_create.py
  saleor/tests/e2e/account/utils/staff_update.py
  saleor/tests/e2e/account/utils/user.py
  saleor/tests/e2e/checkout/test_guest_checkout_should_be_assigned_to_user_after_creating_the_account.py
  saleor/tests/e2e/checkout/test_guest_checkout_should_be_associated_with_user_account.py
  saleor/tests/e2e/orders/test_complete_draft_order_for_existing_customer.py
  saleor/tests/e2e/users/utils/__init__.py
Labels: skip changelog

#17439 Fix failing CI for readme
  README.md
Labels: skip changelog
