Repository saleor/saleor, pull requests merged in 2025-10, with the labels that each got.

#18246 Fix missing mime types the Docker image.
  .devcontainer/Dockerfile
  Dockerfile
  saleor/graphql/core/tests/test_file_validation.py
Labels: 3.21

#18250 Fix missing mime types the Docker image.
  .devcontainer/Dockerfile
  Dockerfile
  saleor/graphql/core/tests/test_file_validation.py
Labels: skip changelog, main

#18251 Fix missing mime types the Docker image.
  .devcontainer/Dockerfile
  Dockerfile
  saleor/graphql/core/tests/test_file_validation.py
Labels: 3.20

#18259 Adjust retry backoffs policy
  saleor/app/installation_utils.py
  saleor/app/tests/test_installation_utils.py
  saleor/plugins/avatax/tasks.py
  saleor/plugins/sendgrid/tasks.py
Labels: 3.20

#18264 Fix version bumping for uv.lock file (#18258)
  .release-it.json
Labels: skip changelog, main

#18282 Release 3.22.0-a.4
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
  uv.lock
Labels: release

#18261 Fix test envs.
  .github/workflows/migrations-perf-test.yml
  .github/workflows/test-env-cleanup.yml
  .github/workflows/test-env-deploy.yml
  .github/workflows/test-semgrep-rules.yml
Labels: 3.21

#18280 Rebuild search index when new invoice object has been created
  saleor/graphql/invoice/mutations/invoice_request.py
  saleor/graphql/invoice/tests/test_invoice_request.py
Labels: skip changelog
