Repository saleor/saleor, pull requests merged in 2025-01, with the labels that each got.

#17212 Fix failing CORE_2118 e2e
  saleor/tests/e2e/promotions/test_promotions_query_with_different_parameters.py
Labels: skip changelog

#17213 Fix failing CORE_2118 e2e
  saleor/tests/e2e/promotions/test_promotions_query_with_different_parameters.py
Labels: 3.20

#17214 Fix failing CORE_2118 e2e
  saleor/tests/e2e/promotions/test_promotions_query_with_different_parameters.py
Labels: 3.19

#17196 Add tests when app do not return taxes
  saleor/tests/e2e/checkout/taxes/test_checkout_complete_return_tax_error.py
  saleor/tests/e2e/checkout/taxes/test_order_create_from_checkout_return_tax_error.py
  saleor/tests/e2e/orders/taxes/test_draft_order_complete_return_tax_error.py
  saleor/tests/e2e/orders/utils/__init__.py
  saleor/tests/e2e/orders/utils/order_create_from_checkout.py
  saleor/tests/e2e/taxes/utils/query_tax_configurations.py
  saleor/tests/e2e/taxes/utils/tax_configuration_update.py
Labels: skip changelog

#17215 Fix failing CORE_2118 e2e
  saleor/tests/e2e/promotions/test_promotions_query_with_different_parameters.py
Labels: 3.18

#17216 Fix failing CORE_2118 e2e
  saleor/core/logging.py
  saleor/tests/e2e/promotions/test_promotions_query_with_different_parameters.py
Labels: 3.17

#17220 Fix checkout `line.undiscountedTotalPrice` and `line.undiscountedUnitPrice` calculations
  saleor/checkout/calculations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
Labels: 3.20

#17218 Bump dependencies
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: test deployment, :robot: bot, skip changelog

#17221 Fix checkout `line.undiscountedTotalPrice` and `line.undiscountedUnitPrice` calculations
  saleor/checkout/calculations.py
  saleor/graphql/checkout/tests/test_checkout.py
  saleor/graphql/checkout/types.py
Labels: 3.19

#17223 Require `MANAGE_ORDERS` for updating order and order line metadata
  CHANGELOG.md
  saleor/graphql/meta/permissions.py
  saleor/graphql/meta/tests/mutations/test_order.py
  saleor/graphql/order/tests/queries/test_order.py
Labels: 3.21

#17229 Allow clearing the voucher code in case the voucher or voucher code is missing or inactive
  saleor/checkout/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
Labels: 3.16

#17228 Allow clearing the voucher code in case the voucher or voucher code is missing or inactive
  saleor/checkout/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
Labels: 3.17

#17227 Allow clearing the voucher code in case the voucher or voucher code is missing or inactive
  saleor/checkout/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
Labels: 3.18

#17219 Allow clearing the voucher code in case the voucher or voucher code is missing or inactive
  saleor/checkout/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
Labels: 3.19

#17225 Allow clearing the voucher code in case the voucher or voucher code is missing or inactive
  saleor/checkout/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
Labels: 3.20

#17226 Allow clearing the voucher code in case the voucher or voucher code is missing or inactive
  saleor/checkout/utils.py
  saleor/graphql/checkout/tests/mutations/test_checkout_remove_promo_code.py
Labels: skip changelog, main

#17198 Fix checkout funds releasing task
  CHANGELOG.md
  saleor/payment/models.py
  saleor/payment/tasks.py
  saleor/payment/tests/test_tasks.py
  saleor/tests/e2e/promotions/test_promotions_query_with_different_parameters.py
Labels: main

#17222 Fix incorrect cursor returned when making a query with search input
  saleor/graphql/core/connection.py
  saleor/graphql/order/tests/queries/test_pagination.py
  saleor/graphql/product/tests/queries/test_products_query.py
  saleor/graphql/product/utils.py
Labels: skip changelog

#17230 Fix incorrect cursor returned when making a query with search input
  saleor/graphql/core/connection.py
  saleor/graphql/order/tests/queries/test_pagination.py
  saleor/graphql/product/tests/queries/test_products_query.py
  saleor/graphql/product/utils.py
Labels: 3.20

#17232 Fix incorrect cursor returned when making a query with search input
  saleor/graphql/core/connection.py
  saleor/graphql/order/tests/queries/test_pagination.py
  saleor/graphql/product/tests/queries/test_products_query.py
  saleor/graphql/product/utils.py
Labels: 3.19

#17224 Fix product sorting over collection order
  saleor/graphql/product/sorters.py
  saleor/graphql/product/tests/test_product_sorting.py
Labels: 3.20

#17247 Release 3.20.66
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17238 Fix incorrect tax rate returned by Avatax plugin
  saleor/order/calculations.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/conftest.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/manager.py
Labels: skip changelog

#17251 Fix incorrect tax rate returned by Avatax plugin
  saleor/order/calculations.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/conftest.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/manager.py
Labels: 3.19

#17252 Fix incorrect tax rate returned by Avatax plugin
  saleor/order/calculations.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tests/conftest.py
  saleor/plugins/avatax/tests/test_avatax.py
  saleor/plugins/manager.py
Labels: 3.20

#17248 fix: health check middleware not forwarding non-HTTP requests
  CHANGELOG.md
  saleor/asgi/health_check.py
  saleor/asgi/tests/asgi_test_utils.py
  saleor/asgi/tests/test_healthcheck.py
Labels: bug

#17233 Fix checkout funds releasing task
  saleor/payment/models.py
  saleor/payment/tasks.py
  saleor/payment/tests/test_tasks.py
Labels: 3.20

#17234 Fix checkout funds releasing task
  saleor/payment/models.py
  saleor/payment/tasks.py
  saleor/payment/tests/test_tasks.py
Labels: 3.19

#17235 Fix checkout funds releasing task
  saleor/payment/models.py
  saleor/payment/tasks.py
  saleor/payment/tests/test_tasks.py
Labels: 3.18

#17236 Fix checkout funds releasing task
  saleor/payment/models.py
  saleor/payment/tasks.py
  saleor/payment/tests/test_tasks.py
Labels: 3.17

#17237 Fix checkout funds releasing task
  saleor/payment/models.py
  saleor/payment/tasks.py
  saleor/payment/tests/test_tasks.py
Labels: 3.16

#17266 Fix duplicated checkout tests
  saleor/checkout/tests/fixtures/checkout_with_discount.py
  saleor/checkout/tests/test_base_calculations.py
  saleor/checkout/tests/test_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
  saleor/graphql/checkout/tests/test_checkout.py
Labels: skip changelog, main

#17270 Fix test http client
  saleor/core/tests/cassettes/test_http_client/test_http_client_disallows_private_ip_ranges[http].yaml
  saleor/core/tests/cassettes/test_http_client/test_http_client_disallows_private_ip_ranges[https].yaml
  saleor/core/tests/test_http_client.py
Labels: 3.20

#17253 Fix undiscounted price taxation inside an order calculations when the Avatax plugin is used
  CHANGELOG.md
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/tests/fixtures.py
Labels: taxes

#17059 Fix missing currency in voucher discount objects
  saleor/discount/migrations/0084_set_missing_currency.py
  saleor/discount/utils/voucher.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/order/tests/test_fetch_order_prices.py
Labels: bug, migration, migrations perf test, voucher, skip changelog, discount

#17264 Fix missing currency in voucher discount objects
  saleor/celeryconf.py
  saleor/discount/migrations/0084_set_missing_currency.py
  saleor/discount/migrations/tasks/saleor3_20.py
  saleor/discount/utils/voucher.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/order/tests/test_fetch_order_prices.py
Labels: bug, migration, voucher, discount, 3.20

#17265 Fix missing currency in voucher discount objects
  saleor/celeryconf.py
  saleor/discount/migrations/0084_set_missing_currency.py
  saleor/discount/migrations/tasks/saleor3_19.py
  saleor/discount/utils.py
  saleor/discount/utils/voucher.py
  saleor/graphql/order/tests/mutations/test_draft_order_update.py
  saleor/order/tests/test_fetch_order_prices.py
Labels: bug, migration, voucher, discount, 3.19

#17272 Fix undiscounted price taxation inside an order calculations when the Avatax plugin is used
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/tests/fixtures.py
Labels: bug, taxes, 3.20

#17271 Fix undiscounted price taxation inside an order calculations when the Avatax plugin is used
  saleor/order/calculations.py
  saleor/order/tests/test_calculations.py
  saleor/tests/fixtures.py
Labels: bug, taxes, 3.19

#17260 Block `orderCreateFromCheckout` mutation when tax error occur
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/graphql/checkout/mutations/order_create_from_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/order/actions.py
  saleor/order/tests/test_actions.py
  saleor/tests/e2e/checkout/taxes/test_order_create_from_checkout_return_tax_error.py
  saleor/tests/e2e/orders/utils/__init__.py
  saleor/tests/e2e/orders/utils/order_create_from_checkout.py
  saleor/tests/e2e/taxes/utils/tax_configuration_update.py
Labels: taxes, 3.20

#17259 Block `orderCreateFromCheckout` mutation when tax error occur
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/graphql/checkout/mutations/order_create_from_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/order/actions.py
  saleor/order/tests/test_actions.py
  saleor/tests/e2e/checkout/taxes/test_order_create_from_checkout_return_tax_error.py
  saleor/tests/e2e/orders/utils/__init__.py
  saleor/tests/e2e/orders/utils/order_create_from_checkout.py
  saleor/tests/e2e/taxes/utils/tax_configuration_update.py
Labels: taxes, 3.19

#17258 Block `orderCreateFromCheckout` mutation when tax error occur
  saleor/checkout/calculations.py
  saleor/checkout/complete_checkout.py
  saleor/checkout/tests/test_order_from_checkout.py
  saleor/graphql/checkout/mutations/order_create_from_checkout.py
  saleor/graphql/checkout/tests/mutations/test_checkout_complete.py
  saleor/graphql/checkout/tests/mutations/test_order_create_from_checkout.py
  saleor/graphql/order/mutations/draft_order_complete.py
  saleor/graphql/order/tests/mutations/test_draft_order_complete.py
  saleor/order/actions.py
  saleor/order/tests/test_actions.py
  saleor/tests/e2e/checkout/taxes/test_checkout_complete_return_tax_error.py
  saleor/tests/e2e/checkout/taxes/test_order_create_from_checkout_return_tax_error.py
  saleor/tests/e2e/orders/taxes/test_draft_order_complete_return_tax_error.py
Labels: taxes, skip changelog

#17278 Release 3.20.67
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17250 Add source.service.name span tag
  saleor/graphql/tests/test_tracing.py
  saleor/graphql/tests/test_utils.py
  saleor/graphql/utils/__init__.py
  saleor/graphql/views.py
Labels: skip changelog

#17279 Add source.service.name span tag
  saleor/graphql/tests/test_tracing.py
  saleor/graphql/tests/test_utils.py
  saleor/graphql/utils/__init__.py
  saleor/graphql/views.py
Labels: 3.20

#17285 Add Source-Service-Name to the CORS handler
  saleor/asgi/cors_handler.py
  saleor/asgi/tests/test_cors.py
Labels: skip changelog

#17291 Remove reference cycles in Promise
  saleor/graphql/promise.py
  saleor/settings.py
Labels: 3.20

#17292 Remove reference cycles in Authlib
  saleor/plugins/openid_connect/patch.py
  saleor/settings.py
Labels: 3.20

#17293 Remove reference cycle in Asgiref Local
  saleor/patch_local.py
  saleor/settings.py
Labels: 3.20

#17297 Remove remaining traces of WSGI
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/gateways/stripe/plugin.py
  saleor/payment/gateways/stripe/webhooks.py
  saleor/plugins/base_plugin.py
  saleor/plugins/openid_connect/plugin.py
  saleor/plugins/tests/sample_plugins.py
  saleor/settings.py
  saleor/wsgi/__init__.py
  saleor/wsgi/health_check.py
  saleor/wsgi/uwsgi.ini
Labels: technical debt, skip changelog

#17125 Use denormalized prices during order update for catalogue discounts
  saleor/checkout/fetch.py
  saleor/core/pricing/interface.py
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_checkout.py
  saleor/discount/tests/test_utils/test_create_or_update_discount_objects_from_promotion_for_order.py
  saleor/discount/utils/checkout.py
  saleor/discount/utils/order.py
  saleor/discount/utils/promotion.py
  saleor/discount/utils/voucher.py
  saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py
  saleor/graphql/order/mutations/draft_order_create.py
  saleor/graphql/order/mutations/order_lines_create.py
  saleor/graphql/order/mutations/utils.py
  saleor/graphql/order/tests/mutations/test_draft_order_create.py
  saleor/graphql/order/tests/mutations/test_order_discount.py
  saleor/graphql/order/tests/mutations/test_order_line_update.py
  saleor/graphql/order/tests/mutations/test_order_lines_create.py
  saleor/order/fetch.py
  saleor/order/tests/benchmark/test_fetch_order_prices.py
  saleor/order/tests/fixtures/draft_order.py
  saleor/order/tests/fixtures/order.py
  saleor/order/tests/fixtures/order_line.py
  saleor/order/tests/test_fetch.py
  saleor/order/tests/test_fetch_order_prices.py
  saleor/order/tests/test_order_utils.py
  saleor/order/utils.py
  saleor/product/tasks.py
  saleor/product/utils/variants.py
  saleor/tests/e2e/orders/test_draft_order_update_uses_denormalized_prices.py
  saleor/tests/e2e/orders/utils/draft_order_create.py
  saleor/tests/e2e/orders/utils/draft_order_update.py
  saleor/tests/e2e/orders/utils/order_line_delete.py
  saleor/tests/e2e/orders/utils/order_lines_create.py
Labels: order, promotions, pricing

#17298 Remove gunicorn from the Docker image
  Dockerfile
  poetry.lock
  pyproject.toml
  saleor/asgi/gunicorn_worker.py
Labels: technical debt, skip changelog

#17304 Release 3.20.68
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#16352 Replace `OpenTracing` with `OpenTelemetry`
  poetry.lock
  pyproject.toml
  saleor/core/otel/__init__.py
  saleor/core/tracing.py
  saleor/graphql/core/dataloaders.py
  saleor/graphql/core/tracing.py
  saleor/graphql/tests/test_tracing.py
  saleor/graphql/views.py
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/utils/common.py
  saleor/payment/gateways/braintree/__init__.py
  saleor/payment/gateways/np_atobarai/api_helpers.py
  saleor/payment/gateways/np_atobarai/plugin.py
  saleor/payment/gateways/np_atobarai/utils.py
  saleor/payment/gateways/razorpay/__init__.py
  saleor/payment/gateways/stripe/deprecated/__init__.py
  saleor/payment/gateways/stripe/stripe_api.py
  saleor/plugins/avatax/__init__.py
  saleor/plugins/avatax/plugin.py
  saleor/plugins/avatax/tasks.py
  saleor/plugins/manager.py
  saleor/settings.py
  saleor/webhook/__init__.py
  saleor/webhook/observability/__init__.py
  saleor/webhook/observability/tracing.py
  saleor/webhook/observability/utils.py
  saleor/webhook/transport/asynchronous/transport.py
  saleor/webhook/transport/synchronous/transport.py
Labels: skip changelog

#17308 Fix the Codecov badge
  README.md
Labels: skip changelog

#17307 Use Poetry 2.x
  .devcontainer/Dockerfile
  .github/workflows/e2e.yml
  .github/workflows/pytest.yml
  .github/workflows/test-migrations-compatibility.yml
  CONTRIBUTING.md
  Dockerfile
Labels: technical debt, skip changelog

#17283 Fix incorrect order for reordering collection products when sort_order is null
  saleor/graphql/core/utils/reordering.py
  saleor/graphql/product/mutations/collection/collection_reorder_products.py
  saleor/graphql/product/tests/test_product_sorting.py
Labels: 3.20
