Repository saleor/saleor, pull requests merged in 2025-07, with the labels that each got.

#17898 Add support for Kosovo country
  saleor/account/tests/test_account.py
  saleor/discount/migrations/0086_alter_voucher_countries.py
  saleor/discount/migrations/0087_merge_20250630_1332.py
  saleor/graphql/schema.graphql
  saleor/settings.py
  saleor/shipping/migrations/0036_alter_shippingzone_countries.py
  saleor/shipping/migrations/0037_merge_20250630_1332.py
Labels: migrations perf test, skip changelog

#17645 chore: add Codecov test analytics
  .github/workflows/tests-and-linters.yml
Labels: skip changelog

#17902 Split `test_collection` file into smaller test files
  saleor/graphql/product/tests/mutations/test_collection_add_products.py
  saleor/graphql/product/tests/mutations/test_collection_create.py
  saleor/graphql/product/tests/mutations/test_collection_delete.py
  saleor/graphql/product/tests/mutations/test_collection_remove_products.py
  saleor/graphql/product/tests/mutations/test_collection_update.py
  saleor/graphql/product/tests/queries/test_collection_query.py
  saleor/graphql/product/tests/queries/test_collections_query.py
  saleor/graphql/product/tests/queries/test_collections_query_with_filter_and_sort.py
  saleor/graphql/product/tests/test_collection.py
  saleor/graphql/product/tests/test_collection_filtering_and_sorting_with_channels.py
Labels: skip changelog

#17904 Release 3.20.92
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17905 Release 3.21.6
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17893 Fix race condition in TransactionCreate mutation when updating checkout/order prices
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/mutations/transaction/transaction_update.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/order/utils.py
Labels: 3.20

#17903 Allow assigning category and collection as reference
  CHANGELOG.md
  saleor/attribute/__init__.py
  saleor/attribute/migrations/0049_attributevalue_references_attr_entity_type.py
  saleor/attribute/models/base.py
  saleor/attribute/tests/fixtures/attribute.py
  saleor/csv/tests/export/products_data/test_get_products_data.py
  saleor/csv/tests/export/products_data/test_handle_relations_data.py
  saleor/csv/tests/export/products_data/test_prepare_headers.py
  saleor/csv/utils/__init__.py
  saleor/csv/utils/products_data.py
  saleor/graphql/attribute/utils.py
  saleor/graphql/page/tests/deprecated/test_page_update.py
  saleor/graphql/page/tests/mutations/test_page_create.py
  saleor/graphql/page/tests/mutations/test_page_update.py
  saleor/graphql/product/tests/mutations/test_category_delete.py
  saleor/graphql/product/tests/mutations/test_category_update.py
  saleor/graphql/product/tests/mutations/test_collection_add_products.py
  saleor/graphql/product/tests/mutations/test_collection_create.py
  saleor/graphql/product/tests/mutations/test_collection_delete.py
  saleor/graphql/product/tests/mutations/test_collection_remove_products.py
  saleor/graphql/product/tests/mutations/test_collection_update.py
  saleor/graphql/product/tests/mutations/test_product_create.py
  saleor/graphql/product/tests/mutations/test_product_update.py
  saleor/graphql/product/tests/mutations/test_product_variant_create.py
  saleor/graphql/product/tests/mutations/test_product_variant_update.py
  saleor/graphql/product/tests/queries/test_categories_query_with_filter.py
  saleor/graphql/product/tests/queries/test_collections_query_with_filter_and_sort.py
  saleor/graphql/schema.graphql
Labels: skip migrations perf test

#17911 Move ChannelContextType to core module
  saleor/graphql/channel/types.py
  saleor/graphql/core/types/context.py
  saleor/graphql/discount/types/sales.py
  saleor/graphql/discount/types/vouchers.py
  saleor/graphql/menu/types.py
  saleor/graphql/product/types/collections.py
  saleor/graphql/product/types/products.py
  saleor/graphql/shipping/mutations/shipping_price_create.py
  saleor/graphql/shipping/mutations/shipping_price_delete.py
  saleor/graphql/shipping/mutations/shipping_price_exclude_products.py
  saleor/graphql/shipping/mutations/shipping_price_remove_product_from_exclude.py
  saleor/graphql/shipping/mutations/shipping_price_update.py
  saleor/graphql/shipping/mutations/shipping_zone_create.py
  saleor/graphql/shipping/mutations/shipping_zone_delete.py
  saleor/graphql/shipping/mutations/shipping_zone_update.py
  saleor/graphql/shipping/schema.py
  saleor/graphql/shipping/types.py
Labels: skip changelog

#17913 Fix race condition in TransactionCreate mutation when updating checkout/order prices
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/mutations/transaction/transaction_update.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/order/utils.py
Labels: skip changelog, main

#17921 Remove unnecessary tasks
  saleor/checkout/migrations/tasks/saleor3_14.py
  saleor/payment/migrations/tasks/saleor3_19.py
Labels: skip changelog, main, skip migrations perf test

#17925 Add ChannelContext to Page type
  saleor/graphql/attribute/types.py
  saleor/graphql/menu/types.py
  saleor/graphql/meta/mutations/base.py
  saleor/graphql/page/mutations/page_create.py
  saleor/graphql/page/mutations/page_delete.py
  saleor/graphql/page/mutations/page_reorder_attribute_values.py
  saleor/graphql/page/mutations/page_update.py
  saleor/graphql/page/schema.py
  saleor/graphql/page/types.py
  saleor/graphql/translations/types.py
  saleor/graphql/webhook/subscription_types.py
Labels: skip changelog

#17909 Fix logic for subtracting gift cards value from checkout total
  saleor/checkout/calculations.py
  saleor/order/migrations/0197_fix_negative_total_net_for_orders_using_gift_cards.py
  saleor/order/migrations/tasks/saleor3_20.py
  saleor/order/tests/test_tasks.py
  saleor/tax/tests/test_checkout_calculations.py
  saleor/tests/fixtures.py
Labels: do not merge, 3.20

#17920 Fix logic for subtracting gift cards value from checkout total
  saleor/checkout/calculations.py
  saleor/order/migrations/0197_fix_negative_total_net_for_orders_using_gift_cards.py
  saleor/order/migrations/0205_merge_20250703_1438.py
  saleor/order/migrations/tasks/saleor3_21.py
  saleor/order/tests/fixtures/order.py
  saleor/order/tests/test_tasks.py
  saleor/tax/tests/test_checkout_calculations.py
Labels: 3.21, do not merge

#17930 Release 3.21.7
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17926 Fix logic for subtracting gift cards value from checkout total
  saleor/checkout/calculations.py
  saleor/order/migrations/0197_fix_negative_total_net_for_orders_using_gift_cards.py
  saleor/order/migrations/0205_merge_20250703_1438.py
  saleor/order/migrations/0216_merge_20250704_1033.py
  saleor/order/tests/fixtures/order.py
  saleor/tax/tests/test_checkout_calculations.py
Labels: skip changelog, main, skip migrations perf test

#17933 Change bump-dependencies workflow to run monthly
  .github/workflows/bump-dependencies.yml
Labels: skip changelog

#17915 Fix race condition in TransactionUpdate mutation when updating checkout/order prices
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/mutations/transaction/transaction_update.py
  saleor/graphql/payment/mutations/transaction/utils.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
Labels: 3.20

#17938 Add dedicated fields for Adyen plugin
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/test_plugin.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/interface.py
  saleor/payment/migrations/0064_transaction_legacy_adyen_plugin_payment_method_and_more.py
  saleor/payment/models.py
  saleor/payment/utils.py
Labels: migrations perf test, skip changelog

#17940 Move ability to control checkout funds release to channel api
  saleor/celeryconf.py
  saleor/channel/migrations/0019_auto_20250625_1048.py
  saleor/channel/migrations/0020_migrate_checkout_ttl_release_funds.py
  saleor/channel/migrations/0022_merge_20250708_1220.py
  saleor/channel/migrations/tasks/saleor3_21.py
  saleor/channel/models.py
  saleor/channel/tests/fixtures/channel.py
  saleor/graphql/channel/mutations/channel_create.py
  saleor/graphql/channel/mutations/utils.py
  saleor/graphql/channel/tests/mutations/test_channel_create.py
  saleor/graphql/channel/tests/mutations/test_channel_update.py
  saleor/graphql/channel/types.py
  saleor/graphql/core/scalars.py
  saleor/graphql/schema.graphql
  saleor/payment/tasks.py
  saleor/payment/tests/fixtures/transaction_item.py
  saleor/payment/tests/test_tasks.py
Labels: 3.21

#17945 Release 3.20.94
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17946 Release 3.21.8
  package-lock.json
  package.json
  pyproject.toml
  saleor/__init__.py
Labels: release

#17948 Revert "Add dedicated fields for Adyen plugin"
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/test_plugin.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/interface.py
  saleor/payment/migrations/0064_transaction_legacy_adyen_plugin_payment_method_and_more.py
  saleor/payment/models.py
  saleor/payment/utils.py
Labels: skip changelog, skip migrations perf test

#17953 Fix race condition in TransactionInitialize mutation when updating checkout/order prices
  saleor/graphql/order/tests/benchmark/test_fulfillment_refund_and_return_products.py
  saleor/graphql/order/tests/deprecated/test_order.py
  saleor/graphql/order/tests/mutations/test_fulfillment_refund_products.py
  saleor/graphql/order/tests/mutations/test_fulfillment_return_products.py
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/mutations/transaction/transaction_update.py
  saleor/graphql/payment/mutations/transaction/utils.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/order/actions.py
  saleor/order/tests/test_order_actions_create_fulfillments_for_returned_products.py
  saleor/order/tests/test_order_actions_refund_products.py
  saleor/payment/gateways/np_atobarai/tests/conftest.py
  saleor/payment/gateways/np_atobarai/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.20

#17964 Fix deprecation warning in the test.
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
Labels: 3.21

#17963 Fix deprecation warning in the test.
  saleor/graphql/account/tests/mutations/authentication/test_request_password_reset.py
Labels: skip changelog, main

#17961 Fix race condition in TransactionInitialize mutation when updating checkout/order prices
  saleor/graphql/order/tests/benchmark/test_fulfillment_refund_and_return_products.py
  saleor/graphql/order/tests/deprecated/test_order.py
  saleor/graphql/order/tests/mutations/test_fulfillment_refund_products.py
  saleor/graphql/order/tests/mutations/test_fulfillment_return_products.py
  saleor/graphql/payment/mutations/transaction/transaction_create.py
  saleor/graphql/payment/mutations/transaction/transaction_event_report.py
  saleor/graphql/payment/mutations/transaction/transaction_update.py
  saleor/graphql/payment/mutations/transaction/utils.py
  saleor/graphql/payment/tests/mutations/test_transaction_create.py
  saleor/graphql/payment/tests/mutations/test_transaction_event_report.py
  saleor/graphql/payment/tests/mutations/test_transaction_initialize.py
  saleor/graphql/payment/tests/mutations/test_transaction_update.py
  saleor/order/actions.py
  saleor/order/tests/test_order_actions_create_fulfillments_for_returned_products.py
  saleor/order/tests/test_order_actions_refund_products.py
  saleor/payment/gateways/np_atobarai/tests/conftest.py
  saleor/payment/gateways/np_atobarai/tests/test_utils.py
  saleor/payment/utils.py
Labels: 3.21

#17967 Extend `AttributePageWhereInput` to allow filtering by assigned references
  saleor/graphql/attribute/filters.py
  saleor/graphql/core/filters/where_input.py
  saleor/graphql/page/filters.py
  saleor/graphql/page/tests/queries/test_pages.py
  saleor/graphql/page/tests/queries/test_pages_with_where.py
  saleor/graphql/schema.graphql
  saleor/page/tests/fixtures/page.py
Labels: skip changelog

#17979 Fix checkout.discount amount when override is set
  saleor/checkout/fetch.py
  saleor/checkout/tests/test_fetch.py
  saleor/graphql/checkout/tests/mutations/test_checkout_add_promo_code.py
Labels: skip changelog

#17978 Fix typing in reference handler
  saleor/graphql/attribute/tests/type_handlers/test_reference_handler.py
  saleor/graphql/attribute/utils/shared.py
  saleor/graphql/attribute/utils/type_handlers.py
Labels: skip changelog

#17949 [3.20] Add dedicated fields for Adyen plugin
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/test_plugin.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/interface.py
  saleor/payment/migrations/0061_transaction_legacy_adyen_plugin_payment_method_and_more.py
  saleor/payment/models.py
  saleor/payment/utils.py
Labels: 3.20

#17951 [3.21] Add dedicated fields for Adyen plugin
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/test_plugin.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/interface.py
  saleor/payment/migrations/0061_transaction_legacy_adyen_plugin_payment_method_and_more.py
  saleor/payment/models.py
  saleor/payment/utils.py
Labels: 3.21

#17952 Add dedicated fields for Adyen plugin
  saleor/payment/gateways/adyen/plugin.py
  saleor/payment/gateways/adyen/tests/test_plugin.py
  saleor/payment/gateways/adyen/webhooks.py
  saleor/payment/interface.py
  saleor/payment/migrations/0061_transaction_legacy_adyen_plugin_payment_method_and_more.py
  saleor/payment/migrations/0064_merge_20250716_0709.py
  saleor/payment/models.py
  saleor/payment/utils.py
Labels: migrations perf test, skip changelog

#17970 Add race condition tests for TransactionProcess mutation
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
Labels: 3.21

#17971 Add race condition tests for TransactionProcess mutation
  saleor/graphql/payment/tests/mutations/test_transaction_process.py
Labels: skip changelog, main

#17975 Allow filtering nested objects by passing a list
  saleor/graphql/order/filters.py
  saleor/graphql/order/tests/queries/test_draft_order_with_where.py
  saleor/graphql/order/tests/queries/test_order_with_where.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#17983 Update descriptions in order filters
  saleor/graphql/order/filters.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#17988 Update supported versions in the security policy
  SECURITY.md
Labels: skip changelog, docs

#17995 Optional slug attribute for use in Page.where filter
  saleor/graphql/page/filters.py
  saleor/graphql/page/tests/queries/test_pages_with_where.py
  saleor/graphql/schema.graphql
Labels: skip changelog

#17997 Split tests for page where functionality
  saleor/graphql/page/tests/queries/pages_with_where/__init__.py
  saleor/graphql/page/tests/queries/pages_with_where/shared.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_attributes.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_attributes_boolean.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_attributes_date.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_attributes_datetime.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_attributes_numeric.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_ids.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_metadata.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_multiple_arguments.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_page_type.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_references_pages.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_references_products.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_references_variants.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_slug.py
  saleor/graphql/page/tests/queries/pages_with_where/test_with_where_validation.py
  saleor/graphql/page/tests/queries/test_pages_with_where.py
Labels: skip changelog

#18010 Improve product filter error msg
  saleor/graphql/product/filters/product_attributes.py
Labels: skip changelog
